### ISSUE TITLE
Variables page gets more laggy the further down you go

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1000]
#### Describe the bug
The more variables you have in the variables menu, and the further you go down, the slower the calculator gets

#### Screenshots
Lag can't be screenshot

#### To Reproduce
1. Add many variables (for example, 10)
2. Open the variables menu (VAR)
3. Try to get to the tenth variable

#### Expected behavior
It should be as fast all the way through

#### Environment
 - Epsilon version 10.0.1.
 - Happening on the calculator

**Comment by Moddingear** [comment]
Seeing as this is still not fixed, here it is in action : https://youtu.be/27htsx1WweM
1 minute to get to the 50th variable is quite too long imo.

**Comment by artaxxx** [comment]
It's fixed
