### ISSUE TITLE
differentiation notation

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1012]
#### Problem you'd like to fix
The notation for differentiation is not used.

#### Screenshots
Left: actual / Right: desired usual notation
![diff](https://user-images.githubusercontent.com/28948599/59511366-5901e800-8eb6-11e9-8c34-4f4501ac765d.jpg)

#### Describe the solution you'd like
Either use the d/dx notation directly from the input box (as for integrate, sum and product) or at least for displaying the result

#### Describe alternatives you've considered
None actually available, as far as I know

**Comment by artaxxx** [comment]
Fixed in version 16
