### ISSUE TITLE
Wrong implementation of exponential regression

### ISSUE THREAD

**Issue by rkfritzsch** [numworks/epsilon#1021]
#### Describe the bug
In an attempt to resolve issues #969 and #983, in the latest beta firmware the exponential regression is simply done like exp(linear regression of ln(y)). This is not the expected behaviour, since it does NOT give the best result in the sense of least squares.

#### Screenshots
![Clipboard01](https://user-images.githubusercontent.com/50665635/59765131-a6f36300-929d-11e9-8170-f80d3d136dbc.jpg)

#### To Reproduce
Enter the data already mentioned in my comment to issue #969:
X1={0, 10, 20, 30, 40, 50, 60}

Y1={2938,7354,11900,17000,47200,79100,119600}

The result is
y=3346.754*exp(0.06160023*x)
(with a r^2=0.9859198)

#### Expected behavior
The result in the sense of least squares should rather be
y=5081.101*exp(0.05311736*x)
(with a  better r^2=0.9865023)

#### Environment
 - Epsilon version 11.0.0
 - The platform(s) on which the problem happens: online simulator

**Comment by artaxxx** [comment]
Thanks @rkfritzsch !

Actually, we chose to compute it this way because the least squares method wasn't the best design in some cases and didn't work on several data sets. 

The method with the logarithm is used on other (almost all) calculators and softwares, see Geogebra : 
<img width="513" alt="Capture d’écran 2019-06-19 à 15 20 13" src="https://user-images.githubusercontent.com/20040032/59771560-3e5eb300-92aa-11e9-95c9-d7451d9013d4.png">

That's why we wanted to implement it! It allows us to be more consistent with other platforms.

**Comment by rkfritzsch** [comment]
I see! You are right; just cross-checked with a vintage TI-92 Plus:
![Clipboard02](https://user-images.githubusercontent.com/50665635/59774704-36097680-92b0-11e9-9d48-cedff3418911.jpg)

What a pity, I rather had loved to see the better least squares result:
![Clipboard03](https://user-images.githubusercontent.com/50665635/59774869-78cb4e80-92b0-11e9-8ee9-1a265abffcc8.jpg)

But I accept the way chosen.

**Comment by IoIxD** [comment]
> the least squares method wasn't the best design in some cases

Which is unfortunate when you don't have control over what you're comparing against.
My university uses a custom, in house software for homework, and questions regarding exponential regression seem to use the least squares method. It would at least be nice to toggle on this method, even if it doesn't work for some datasets.

**Comment by IoIxD** [comment]
Ok so three months later and no response, I modified somebody else's Desmos program to remove the notes and functions that don't apply, [you can use that here.](https://www.desmos.com/calculator/0oelmftb7q) Desmos seems to use the least squares method which gives the answer that my college's online math is looking for.
