### ISSUE TITLE
Python: Toolbox submenu for Lists

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1022]
#### Problem you'd like to fix
When working with lists in the Python app, not every Python functions and methods are available in the Catalog submenu of the Toolbox

#### Screenshots
Example: `count` does not appear in the Catalog submenu, even if the Python app is able to handle it
![ekrano-kopio 2019-06-20 à 14 10 37](https://user-images.githubusercontent.com/28948599/59848349-3283f700-9365-11e9-97ad-b2fe3a9013c4.jpg)

#### Describe the solution you'd like
Create a Toolbox “List” submenu with (at least!):

**a.** these functions, already in the Catalog:
· len(list)
· max(list)
· min(list)
· sorted(list)
· sum(list)

**b.** _and_ these methods, not in the Catalog:
· append(object)
· count(object)
· index(object)
· insert(index, object)
· remove(object)
· reverse()

#### Describe alternatives you've considered
For now, the user has to type in every of these functions and methods not available in the Catalog.

#### Additional context
Where to add the List menu:
![ekrano-kopio 2019-06-20 à 14 12 38](https://user-images.githubusercontent.com/28948599/59848472-88f13580-9365-11e9-92d7-28d0e121da3f.jpg)

**Comment by RedGl0w** [comment]
This issue can be closed since https://github.com/numworks/epsilon/commit/76304604249f980546e5f45969e5a32566342dee

**Comment by XanderLeaDaren** [comment]
> This issue can be closed since [7630460](https://github.com/numworks/epsilon/commit/76304604249f980546e5f45969e5a32566342dee)

Well, the issue is only partially resolved: the functions and methods are indeed in the Catalog, however a dedicated menu for lists is not yet present.
I express the wish for such a menu again, because lists are a required part of the French math curriculum from this year on, to give one reason.

**Comment by artaxxx** [comment]
We do not plan to add a "Lists" submenu in the toolbox for now. So I'm going to close this issue. However, we plan to work on an easier way to access python functions in the toolbox :)
