### ISSUE TITLE
Python script list display: more scripts and size

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1023]
#### Problem you'd like to fix
The actual display (list) of Python scripts lacks the size of these scripts and can only display three scripts at a time.

#### Screenshots
Left: actual / Right: mock-up proposal
![python-scripts-list](https://user-images.githubusercontent.com/28948599/59851522-23a14280-936d-11e9-849e-c8e06d7b0d36.jpg)

#### Describe the solution you'd like
1. Height of every line: 50 px instead of actual 100 px
2. End of line: show every script size, in octets

#### Describe alternatives you've considered
No alternative for now

**Comment by 0b101** [comment]
The 50px line heights look a little squished. A 75px line height might look a little better while still allowing more scripts to be displayed.

**Comment by boricj** [comment]
You also need to display the available/total storage capacity, otherwise the script sizes by themselves are not really a useful information for the end-user.

**Comment by XanderLeaDaren** [comment]
Both of your ideas are good!

Capacity seems related to #623 “No size or memory limit mentioned”

**Comment by RemyDCF** [comment]
The height is currently defined by Metric::StoreRowHeight, which is currently system-wide, so if we want to change the cell's height, we can either change the Metric::StoreRowHeight, or we can create a new variable.
And, in my opinion, setting Metric::StoreRowHeight to 37 is quite a good fit.

<img width="506" alt="Capture d’écran 2019-06-20 à 16 25 41" src="https://user-images.githubusercontent.com/11600393/59856995-4b49d800-9378-11e9-9cd2-55d8e3ab0f25.png">

**Comment by 0b101** [comment]
> The height is currently defined by Metric::StoreRowHeight, which is currently system-wide

Does this change anything other than the Python script list?

**Comment by RemyDCF** [comment]
> > The height is currently defined by Metric::StoreRowHeight, which is currently system-wide
> 
> Does this change anything other than the Python script list?

Functions, equations and sequences list, at least. But the height is adapted if the cell need a bigger height (for fractions, square roots, ...)

**Comment by XanderLeaDaren** [comment]
With these new settings, I remark the bottom buttons are not consistent in height: “Solve the system“ and “Python shell” appear with a bigger font. For the latter, using the smaller font (as for “Plot graph” and “Display values”) is another way of getting one more script to appear in the list. What do you think?

**Comment by artaxxx** [comment]
Let me close this issue since we decided not to display script size in the app.

**Comment by artaxxx** [comment]
Please, feel free to open a new issue with the reduced height of cells.
