### ISSUE TITLE
Fractions product in natural writing

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1028]
#### Describe the bug and screenshots to reproduce it
When wanting to type in ![bildo](https://user-images.githubusercontent.com/28948599/60004163-66646280-966c-11e9-8f04-636234e4b4fe.png) in natural writing format, ![ekrano-kopio 2019-06-24 à 10 46 48](https://user-images.githubusercontent.com/28948599/60004715-66b12d80-966d-11e9-9d5c-630a784cdc09.jpg) gives
![bildo](https://user-images.githubusercontent.com/28948599/60004332-b2afa280-966c-11e9-8e61-292de46a17ce.png)

#### Expected behavior
Typing the last `÷` should compose the last fraction and not put everything already typed in on top of a new fraction.

#### Additional researchs
**1. In linear writing format:**
![bildo](https://user-images.githubusercontent.com/28948599/60004232-8136d700-966c-11e9-94b0-12a99760a78d.png) gives 
![bildo](https://user-images.githubusercontent.com/28948599/60004269-914eb680-966c-11e9-8dd0-b64a942bcc98.png)
and that’s perfect.

**2. How to get past this strange behaviour**
For a pupil wanting to have the desired product in “natural writing”, you have to add un-needed brackets in order to compose it… Very counter-intuitive!
![bildo](https://user-images.githubusercontent.com/28948599/60004553-25b91900-966d-11e9-979a-5de6df7e2678.png)

**3. I believe this is related to the new behaviour from #524 onward**
Because ![bildo](https://user-images.githubusercontent.com/28948599/60004617-42555100-966d-11e9-8b19-5369ca149bbf.png) is perfectly rendered

#### Environment
 - Epsilon version 10.1.0
 - online simulator and actual device

**Comment by LeaNumworks** [comment]
Hello,
Thanks for reporting this problem! It is indeed more user-friendly to be able to write the fractions "intuitively".
This should be fixed by #1032

**Comment by rkfritzsch** [comment]
What a pity the fix wasn't included in 11.2.0!
