### ISSUE TITLE
Statistics App - Sort List

### ISSUE THREAD

**Issue by gunther3613** [numworks/epsilon#1035]
#### Problem you'd like to fix
Be able to sort the lists in the Statistics App. I am frustrated that when I am given unsorted list to work with and need to sort it figure out the frequencies manually I have to rely on an external tool to do it.

#### Describe the solution you'd like
I would like an option to sort the lists in the Statistics App when I click ok on the list name like to clear it or fill it with a formula.

#### Describe alternatives you've considered
Writing a Python script to do the sorting.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
