### ISSUE TITLE
[iOS] touch position is shifted after an application switch

### ISSUE THREAD

**Issue by LudovicRousseau** [numworks/epsilon#1042]
#### Describe the bug
After I switch to another application (or just using the home button) and come back to Numworks the position on the touch screen is shifted up. For example I click on the button "5" and I get "cos()" instead.
The same problem occurs with all the buttons on the interface.

#### To Reproduce
Steps to reproduce the behaviour:
1. Start to the Numworks app
2. Select "Calculs"
3. click on the button "5" to get 5
4. Press the iPhone home button
5. Select the Numworks app again
6. click on the button "5" and you get "cos()" instead of "5"

#### Expected behaviour
I expect to get "5" when I click on "5" button.

#### Environment
 - Epsilon version (Settings > About > Software version).
10.0.5
 - The platform(s) on which the problem happens: online simulator, actual device, etc...
iOS version 12.3.2 on a iPhone 8 Plus.

**Comment by 0b101** [comment]
> The platform(s) on which the problem happens: online simulator, actual device, etc...

This happens on the simulator and the app? I cannot replicate the problem on my iPhone XR.

Can you press the volume up, then the volume down, and finally hold the power button until you see the Apple logo? This should reboot your device ensure that it's the app and not your phone.

**Comment by LudovicRousseau** [comment]
I have the problem on my iPhone 8 Plus (real device).
I rebooted the phone and I can still reproduce the problem.

I can try to reproduce on the iPhone simulator but I have no idea how to install the Numworks app on the simulator.

**Comment by PiGuy2** [comment]
I can’t reproduce it on my iPhone 7 either.

**Comment by DSchndr** [comment]
I also can't reproduce this bug on an IPhone 5s. (IOS 12.1.4)

**Comment by LudovicRousseau** [comment]
I upgraded the NumWorks application to version 12.2.0 on iOS 13.2.2 and I can’t reproduce the problem any more.
Closing.
