### ISSUE TITLE
Make the cursor blink

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1045]
#### Problem you'd like to fix
There is no way of easily knowing if the calculator is "busy"/frozen or not. (type 25^100 to see a short freeze while the answer is being calculated)

#### Describe the solution you'd like
Make the cursor blink when the calculator isn't frozen/busy (like computers & other calculators).

#### Describe alternatives you've considered
Add text/an icon that appears the user when the calculator is calculating/busy (like the Ti-89).

**Comment by MixedMatched** [comment]
I think a symbol that periodically blinks in the topbar would be better, because it would work in all the apps, not just calculation.

**Comment by Lesquivemeau** [comment]
> 
> 
> I think a symbol that periodically blinks in the topbar would be better, because it would work in all the apps, not just calculation.

it seems a bit counter-intuituve, i would understand such a thing as a "busy" inducator, like on ti calculators

**Comment by Ryder17z** [comment]
> > I think a symbol that periodically blinks in the topbar would be better, because it would work in all the apps, not just calculation.
> 
> it seems a bit counter-intuituve, i would understand such a thing as a "busy" inducator, like on ti calculators

it depends on the location: high up is usually busy while down low is usually the opposite (think of using DOS or other console/terminal blinking marker)

**Comment by RedGl0w** [comment]
> > I think a symbol that periodically blinks in the topbar would be better, because it would work in all the apps, not just calculation.
> 
> it seems a bit counter-intuituve, i would understand such a thing as a "busy" inducator, like on ti calculators

that's the solution chosen for epsilon 16
