### ISSUE TITLE
Add support for more than two series

### ISSUE THREAD

**Issue by Cocosushi6** [numworks/epsilon#1046]
#### Problem you'd like to fix
I think it would be a great idea if we could add series the same way we add functions : having the ability to give them a custom name, and being able to add more than two series, as we are currently restricted to two series only : u<sub>n</sub> and v<sub>n</sub>.

#### Screenshots 
Here's a screenshot of the current screen : 
![screenshot](https://user-images.githubusercontent.com/15072840/61550608-66286e80-aa42-11e9-9a33-93a7053ea70a.png)

As you can see, there is currently no way to add a new serie after having added two.

#### Describe alternatives you've considered
Another idea would be to add the ability to customize series names, as it's also possible for functions.

**Comment by Ecco** [comment]
We've added a third series in master.
