### ISSUE TITLE
Support split view on iPad

### ISSUE THREAD

**Issue by ghost** [numworks/epsilon#1049]
#### Problem you'd like to fix
The calculator doesn't show in split view on iPad.

#### Screenshots
![IMG_0001](https://user-images.githubusercontent.com/17487559/62000094-41587a80-b084-11e9-88dd-3239cc6407aa.PNG)

#### Describe the solution you'd like
It would be great if there was support for split view on iPad! I could have my math book on one side and the calculator on the other.

**Comment by Ecco** [comment]
Unfortunately we're hit by a bug in SDL. We've reported it on [their bugtracker](https://bugzilla.libsdl.org/show_bug.cgi?id=4586)

**Comment by Ecco** [comment]
This has been solved by #1154
