### ISSUE TITLE
Allow firmware upgrade for Linux end user

### ISSUE THREAD

**Issue by titimoby** [numworks/epsilon#105]
Today, it is not possible to upgrade the firmware in the same simple way it's done under Windows or MacOS.
The only solution is to have all the build and compile tools and be careful with the version you build.

Is there any technical issue?

**Comment by artaxxx** [comment]
Thanks titimoby, this is definitely something we have to do!

**Comment by yeKcim** [comment]
I'm writing an article about Epsilon for the paper magazine "Linux Pratique". If the feature is added before mid-November, the sooner the better (the article is released in December) the paper will be a much better advertisement for Numworks.

**Comment by debrouxl** [comment]
When the operational aspects of workshop.numworks.com have stabilized, publishing the source code of the Windows and MacOS X application(s) would probably help :)

**Comment by madhatter0** [comment]
In case it helps in the interim, I've added a brief guide to flashing the NumWorks under Linux on the reddit thread, at https://www.reddit.com/r/numworks/comments/710dfm/how_to_update_on_linux/

**Comment by Ecco** [comment]
We eventually found the right technology stack to solve this issue. From now on, you can flash your device from your web browser on linux at https://workshop.numworks.com :)
