### ISSUE TITLE
[build] Improve N0110 build/flash mechanism

### ISSUE THREAD

**Issue by boricj** [numworks/epsilon#1052]
#### Describe the bug
There is no obvious and easy way to build and flash the firmware with just basic tooling (i.e. dfu-util and a USB cable, not a ST-Link).

#### To Reproduce
This is what I had to type to flash a custom firmware for the N0110 through NumWorks's DFU:
```
make EPSILON_DEVICE_BENCH=0 EPSILON_USB_DFU_XIP=0 EPSILON_ONBOARDING_APP=1 EPSILON_BOOT_PROMPT=update build/device/n0110/epsilon_two_binaries -j
sudo dfu-util -D build/device/n0110/epsilon.internal.bin -s 0x08000000
sudo dfu-util -D build/device/n0110/epsilon.external.bin -s 0x90000000
```

#### Expected behavior
- [ ] Flashing a new firmware for the N0110 through dfu-util should be a short one-liner.
- [ ] Official documentation should be updated (https://www.numworks.com/resources/engineering/software/sdk/).

#### While I'm here
I haven't looked too deeply into that yet, but I'm not sure there is a way to reflash from scratch (STM's DFU) both internal and external Flash with unmodified sources and dfu-util. The stock dfu-util utility refuses to flash at a location that is not described in the DFU string descriptor, so it won't let me download/upload the recovery to RAM on both STM's DFU and NumWorks's DFU.

**Comment by EmilieNumworks** [comment]
Hi @boricj,
I developed something to fix flashing from USB, I will merge this soon.
Thank you!

**Comment by Ecco** [comment]
I'm going to close this one since it's been mostly addressed:

* Documentation is now editable (#1077 )
* We don't use dfu-util anymore in favor of embedded Python scripts
