### ISSUE TITLE
Common accesible memory storage for all apps

### ISSUE THREAD

**Issue by ericflores** [numworks/epsilon#1053]
#### Problem you'd like to fix
When I analyze data (mostly vectors) I prefer to avoid repeating myself. Currently I must enter 5-20 values in the Regression App to visualize the them as a scatter plot and see basic statistics. If I want to see what values are outliers, I must type everything again in the statistics app. If I need to perform some simple computation on the data I need type again in the Calculator app. Then if I need to perform a major transformation, I need to type it again, in my micropython program.

#### Describe the solution you'd like
A common serialized storage memory so that all applications work like different UIs to a single Computing Engine:

- A micropython module to access (read/write) variables stored in the Calculator app. This should be able to read numerals, strings, booleans, lists and if possible, vectors/matrices (not sure if micropython supports them). In this way I can save variables with given names, run my program and get the computation performed in batch mode. Being able to read and evaluate Function variables in mycropython would be awesome too. As a stretch goal, this or another module could to read **ans** (for input) and write back to the calculator stack as output.
- Define reserved variable names to be loaded by the apps if they exists. For example if, a variable  _DATA exists and the content is compatible with the Statistics or Regression apps, then use the content instead of asking the user to type it , again. When a user types input in any of these apps, save it in _DATA, so that it can be used in the Calculator, micropython, etc, The same applies for Functions stored in variables. Define reserved names. If they exists when loading the Functions or Equations apps, then they could be loaded. If you create functions in any of the apps, expose them as variables using their reserved names, so that I can use the  outside of the app. 
This can become a single computing engine instead of separated apps that share input buttons and a display.

#### Describe alternatives you've considered
Tried Copy / Paste mechanism, but it doesn't work either. Created a vector in the calculator, copied it and tried pasting in the Statistics module, but all values are pasted in a single cell. I tried both with vertical and horizontal vectors.
The copy/paste mechanism enhancement would work as a workaround the silos between apps. However, when debugging a python app when you have to edit the app, run, type input values, see output, cycle.....Really, you need your data stored to skip the input step.

#### Additional context

This enhancement doesn't require more memory in the calculator. But in terms of usability would raise the calculator at the level of some of the bests. It would also prepare the software to compete head to head with the best in the market once a better hardware (more storage and RAM) is released for the more profitable college market.

**Comment by boricj** [comment]
The lack of integration between apps has been mentioned before (#690, #640, #201...). While it's not as bad as it used to be thanks to shared functions/constants, this is still an area where the TI-83/TI-84 series of calculators handle this far better.

**Comment by RedGl0w** [comment]
I've already started working on a new Ion module's function for accessing to the globals expressuon

**Comment by RedGl0w** [comment]
I've already started working on a new Ion module's function for accessing to the globals expressuon

**Comment by RedGl0w** [comment]
I've already started working on a new Ion module's function for accessing to the globals expressuon

**Comment by RedGl0w** [comment]
Cf. #1388

**Comment by artaxxx** [comment]
Fixed in version 19
