### ISSUE TITLE
Bricked after flash

### ISSUE THREAD

**Issue by ManshionProd** [numworks/epsilon#1055]
#### Describe the bug
The upload of the flash look good, but the calculator is bricked 
#### Screenshots
![image](https://user-images.githubusercontent.com/26840567/63521009-f0f30200-c4f5-11e9-8c9c-7780fde57b99.png)

#### Environment
 - Epsilon version: last master
 - The platform(s) on which the problem happens: msys2 on window10 64bits

**Comment by Ecco** [comment]
The NumWorks calculators cannot be bricked. A faulty flash can always be recovered by following the rescue procedure on the [NumWorks Workshop](https://workshop.numworks.com).

**Comment by ManshionProd** [comment]
i know but it's always do the same error. so i cannot flash modified rom

**Comment by RemyDCF** [comment]
Are you sure your binary file is not corrupted ? If so, you should be able to recover your calculator from the official build on the workshop (as advised by @Ecco), or try cleaning the builded files and recompiling the project.

**Comment by ManshionProd** [comment]
i actually retried the build a lot of time,and i also retried after recloned the git. 
but thinking about it, is it because I don't put all the apps (with EPSILON_APP , otherwise I have an error that the argument list is too long when building epsilon.elf)
