### ISSUE TITLE
Flashing device failed

### ISSUE THREAD

**Issue by tomdet** [numworks/epsilon#1057]
I cannot seem to flash my device. I am working on Ubuntu 16.04.
And I keep having this error. I can't go further.

OBJCOPY epsilon.bin
Padding epsilon.bin
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
DFU     epsilon_flash
dfu-util 0.8

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2014 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to dfu-util@lists.gnumonks.org

dfu-util: File size is too big: Success
scripts/targets.device.mak:42: recipe for target 'epsilon_flash' failed
make: *** [epsilon_flash] Error 74
rm epsilon.bin

**Comment by boricj** [comment]
From the looks of it, it seems you are trying to flash a N0110 model with a N0100 build. Make sure you have an up-to-date source tree (N0110 support was published about 20 days ago), the latest source code builds for a N0110 model by default.

**Comment by madhatter0** [comment]
Is it possible you mean "trying to flash an N0100 model with an N0110 build"?  I definitely have an N0100, and get this error when trying to flash recent builds.

> the latest source code builds for a N0110 model by default.

Could we get some instructions on how to build recent epsilon releases for N0100?

**Comment by boricj** [comment]
@madhatter0 It's possible that it's the other way around too. Use `MODEL=n0100 make` to build for the old model.

**Comment by madhatter0** [comment]
Thanks, but I'm not sure that's helping:

```
[madhatta@risby epsilon]$ MODEL=n0100 make
I18N    apps/i18n.cpp
QSTRDAT python/port/genhdr/qstrdefs.generated.h
CXX     apps/main.o
[...]
[madhatta@risby epsilon]$ MODEL=n0100 make epsilon_flash
OBJCOPY epsilon.bin
Padding epsilon.bin
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
DFU     epsilon_flash
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: File size is too big: Success
make: *** [scripts/targets.device.mak:47: epsilon_flash] Error 74
rm epsilon.bin

```

**Comment by Ecco** [comment]
This has been fixed on master 😄
