### ISSUE TITLE
Error in the graph of a function.

### ISSUE THREAD

**Issue by DavidNumworks** [numworks/epsilon#1059]
#### Describe the bug
Error in the graph of a function. The function should be smoothly decreasing to 0, but it oscillates like a Runge's phenomenon.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/53866078/64028732-79e7ea00-cb43-11e9-9b67-f79367e5a424.png)

#### To Reproduce
1. Go to the 'Function.' app
2. Type `binomial(20,8)*(x^8)*(1-x)^12`
3. Go to Graph

#### Expected behavior
<img width="1011" alt="Screenshot 2019-08-30 at 16 29 12" src="https://user-images.githubusercontent.com/53866078/64029191-6426f480-cb44-11e9-923a-cf9a13a60d60.png">

#### Environment
 - Epsilon version 11.2.0
 - Simulator, Android app and actual device

**Comment by Ecco** [comment]
For the record, here's what happened:

* `binomial(20,8)*(x^8)*(1-x)^12` got simplified to `125970*(x^20-12x^19+....+x^8)`
* This last form, while in theory identical to the first one, creates a lot more rounding errors.

A simple fix is to prevent expansion of `(1-x)^12`.
