### ISSUE TITLE
Kandinsky and Turtle are able to draw in the up bar

### ISSUE THREAD

**Issue by LopsemPyier** [numworks/epsilon#1061]
Hi,
In python when you open the sandbox with a `fill_rect` function then you wait for an `input` and you enter in _alpha_ mode or _shift_ mode, the next `fill_rect` or `draw_string` or whatever (I didn't test every thing) while draw considering the area where _alpha_ was writen as the area to display.

code for test:
```Python
from kandinsky import *
fill_rect(0, 0, 1, 1, (0, 0, 0))
input()
draw_string("test", 0, 0)
```

And the result:

![screenshot(1)](https://user-images.githubusercontent.com/32937655/64448170-5c83c480-d0dd-11e9-97bc-d4ffe0df64e8.png)

Also when you enter _locked alpha_ mode, it's the lock icon area that is the area were it display:
![screenshot(2)](https://user-images.githubusercontent.com/32937655/64448314-b6848a00-d0dd-11e9-841d-bb01716969c6.png)

Hope you can fix it.

**Comment by RedGl0w** [comment]
This issue seems to be patched since that `input()` stops the sandbox display (I can't find the exact commit).

**Comment by EmilieNumworks** [comment]
This was indeed fixed!
