### ISSUE TITLE
[Calculus] Extact result for matrix operations

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1063]
#### Problem you'd like to fix
Only approximate values are returned when inverting even very basic 2x2 matrixes
More generally, matrix content is always returned as approximate and not exact values.

#### Screenshots
![SmartSelect_20190907-234340_Chrome](https://user-images.githubusercontent.com/55035114/64480537-ea3cde00-d1c9-11e9-8df3-997124a395ed.jpg)
![SmartSelect_20190907-234618_Chrome](https://user-images.githubusercontent.com/55035114/64480542-f7f26380-d1c9-11e9-85df-77a2bfc0904c.jpg)

#### Describe the solution you'd like
Could you just run the calculus the same way they're run when not dealing with matrixes? Why such a difference? Or at least display the results as in any other operations?

Thx

**Comment by suazhero** [comment]
Hi guys. No feedback? I think implementing this one is quite important since competition (both Casio and ti) has it working for ages on same calculator range (graph 35+ etc...) @ecco

**Comment by Ecco** [comment]
We released the patch that adds this feature this morning 😄 Just build the master branch and you'll be all set 😄

**Comment by suazhero** [comment]
Wow great didn't notice it. Thx! :)

**Comment by suazhero** [comment]
@leanumworks @emilienumworks comit id?

**Comment by Ecco** [comment]
Quite a bunch 😄
