### ISSUE TITLE
Device flashing never starts

### ISSUE THREAD

**Issue by raccoondude** [numworks/epsilon#1065]
I made a custom test SDK for my calculator. Everything works up to make epsilon_flash

It doesn't detect my calculator, so all I get is this,

```
paul@Laptop:~/Documents/Cal/epsilon$ make epsilon_flash
OBJCOPY epsilon.bin
Padding epsilon.bin
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
```

When I restart my device, it won't turn back on unless I unplug the device and restart again.

What am I doing wrong?

**Comment by boricj** [comment]
I assume you have a N0100. Resetting a N0100 (whether by crash, reset button or complete power loss) while it is plugged in will start ST's DFU recovery mode, which cannot turn on the display or blink a LED to indicate what's going on to the end-user. The N0110 will not enter ST's recovery unless the button `6` is pressed upon reset.

I believe you need to be `root` to flash a firmware with `dfu-util` on Linux. Try again with `root` privileges.

**Comment by Ecco** [comment]
This is most likely not relevant given we don't use dfu-util anymore. Please try again with the latest master 😄
