### ISSUE TITLE
[Graphing] trigonometric functions look very weried

### ISSUE THREAD

**Issue by TheWanderingCoel** [numworks/epsilon#1066]
#### Describe the bug
A clear and concise description of what the bug is. Please describe a **single** bug per issue. Feel free to create multiple issues though!

When graphing trigonometric functions, the x-axis is very big(200). When I manually set it to [-10,10] by [-10,10]. It shows me like a linear function.

#### Screenshots
Please provide at least one screenshot of the issue happening. This is by far the best way to quickly show any issue! To attach a screenshot, just go to our [online simulator]
(https://www.numworks.com/simulator), navigate to reproduce your issue, and click the "screenshot" button. Then drag'n'drop the file here!

![screenshot](https://user-images.githubusercontent.com/39617891/64851149-63fd1d80-d649-11e9-950b-0003b44c06d1.png)
![screenshot-2](https://user-images.githubusercontent.com/39617891/64851227-8b53ea80-d649-11e9-99f8-96ee474564a7.png)
![screenshot-3](https://user-images.githubusercontent.com/39617891/64851232-8c851780-d649-11e9-8a05-b9d8d8a613f6.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type 'sin(x)'
3. Go to 'Graph'

#### Expected behavior

It should be like this below in the other calculators e.g(T1-84 Plus)

![IMG_0504_2](https://user-images.githubusercontent.com/39617891/64851696-804d8a00-d64a-11e9-9d96-8d664bec7833.jpg)

#### Environment
 - Epsilon version (Settings > About > Software version).
 - The platform(s) on which the problem happens: online simulator, actual device, etc...

Eplision version: 11.2.0
Platform: online simulator

**Comment by EmilieNumworks** [comment]
Hi, to get what you expect, you first need to change the angle unit to Radian (go to Settings > Angle measure > Radians). The default angle unit is degree.

**Comment by TheWanderingCoel** [comment]
Thank you very much about that!
