### ISSUE TITLE
Epsilon is a pain to set up, especially when trying to upload it to the calculator.

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1069]
Most of it is due to a lack of documentation :

- #922 The ARM toolchain isn't even mentionned on the website : https://www.numworks.com/resources/engineering/software/sdk/
Installation procedure is tricky to execute and badly documented on the internet.
- #932 doesn't have any answers on how to actually get past that issue, and the toolchain doesn't even work
- When running in the simulator, Epsilon.exe should be launched instead of Epsilon.elf

I know that from your point of view, someone that isn't able to set up a mingw project isn't of any help, but that's wrong since not all devs know ARM, but most know C. And even then, it can be used for testing before release.

I'd like you to rewrite fully your documentation on that part, so that it makes the software accessible to more people. Make the tutorial from a fresh install of Windows and step-by-step.

**Comment by adriweb** [comment]
> * #922 The ARM toolchain isn't even mentionned on the website : [numworks.com/resources/engineering/software/sdk](https://www.numworks.com/resources/engineering/software/sdk/)
>   Installation procedure is tricky to execute and badly documented on the internet.
> * #932 doesn't have any answers on how to actually get past that issue, and the toolchain doesn't even work

Looks like you haven't been on the pages linked by the SDK page. Particularly "Other": https://www.numworks.com/resources/engineering/software/sdk/other/ where the toolchain is mentioned, the dependencies are listed, and an example apt command is shown.

Sure, it could be better (some things have to be fixed manually with the recent stuff), but it's not very bad either.

**Comment by Moddingear** [comment]
> > * #922 The ARM toolchain isn't even mentionned on the website : [numworks.com/resources/engineering/software/sdk](https://www.numworks.com/resources/engineering/software/sdk/)
> >   Installation procedure is tricky to execute and badly documented on the internet.
> > * #932 doesn't have any answers on how to actually get past that issue, and the toolchain doesn't even work
> 
> Looks like you haven't been on the pages linked by the SDK page. Particularly "Other": https://www.numworks.com/resources/engineering/software/sdk/other/ where the toolchain is mentioned, the dependencies are listed, and an example apt command is shown.
> 
> Sure, it could be better (some things have to be fixed manually with the recent stuff), but it's not very bad either.

I have seen that page, but actually getting the ARM toolchain at the correct place and working took me about 2 hours to figure out.

**Comment by adriweb** [comment]
Well, maybe on Windows. I have no idea about that there. But on Linux and macOS, that part at least is rather trivial.
Maybe "everything" works fine with WSL / WSL2 now though?

**Comment by Moddingear** [comment]
I don't know what that is and how it would help.

**Comment by adriweb** [comment]
It's basically a way to run Linux natively on Windows. Take a look here: https://docs.microsoft.com/en-us/windows/wsl/install-win10#windows-10-fall-creators-update-and-later-install-from-the-microsoft-store
For instance if you download the latest Debian from the Windows store, then you might just be able to follow the linux/debian instructions in the Debian console, even though you're technically on Windows.
Apparently it works, from what I read on some posts here and there.

**Comment by Moddingear** [comment]
> It's basically a way to run Linux natively on Windows. Take a look here: https://docs.microsoft.com/en-us/windows/wsl/install-win10#windows-10-fall-creators-update-and-later-install-from-the-microsoft-store
> For instance if you download the latest Debian from the Windows store, then you might just be able to follow the linux/debian instructions in the Debian console, even though you're technically on Windows.
> Apparently it works, from what I read on some posts here and there.

I'll try that, but that's far from ideal

**Comment by adriweb** [comment]
I'd argue it's much better than having to deal with Windows that's often a pain for non-windows-oriented development... As you witnessed, actually.
Even with better docs, it's more complex than just having to run a native single command line to install deps. Some environment and tools (what's mentioned in the docs) make it simpler, but yeah it's still a "workaround". You can also look at how the windows CI is done with appveyor (using msys2/MINGW64): https://github.com/numworks/epsilon/blob/master/.appveyor.yml

**Comment by Ecco** [comment]
For what it's worth, once #1077 will be merged, anyone will be able to submit PRs to improve the docs 😄

**Comment by Ecco** [comment]
We've fixed most of those issues, so I'm going to close this "umbrella" bug. Feel free to reopen individual issues.
