### ISSUE TITLE
File size is too big: Undefined error: 0

### ISSUE THREAD

**Issue by TheWanderingCoel** [numworks/epsilon#1070]
#### Describe the bug

I'm currently flashing my calculator, I use `make MODELS=n0100` and ``make MODELS=n0100 epsilon_flash``. However it gives me this error and the calculator is black screen now.

#### Expected behavior

I expected to flash successfully. By the way, I set the mode to n0100 but the device folder is still n0110

#### Environment
 - Epsilon version (Settings > About > Software version).
 - The platform(s) on which the problem happens: online simulator, actual device, etc...
  
I'm currently using Mac Os Catalina 15.0 Beta 19A558d  
The calculator is n0100

**Comment by Ecco** [comment]
You made a typo. Use `MODEL=n0100`, not `MODELS=n0100`.

**Comment by TheWanderingCoel** [comment]
Oh. I see! Thank you very much.

**Comment by Ecco** [comment]
You're welcome 😄
