### ISSUE TITLE
fractions and natural writing

### ISSUE THREAD

**Issue by ranousse** [numworks/epsilon#1072]
I have great difficulties writing expressions involving fractions when natural writing is on.

Suppose you want to write

(1 + 2) / 3

In natural mode you don't need parenthesis. But if I don't write the parenthesis, I can't make the calculator understand what I want. In a way, we loose the advantages of the natural mode.

Now suppose I want to write 

1/2 * 3/5

The only way I found was to write  (1/2) * (3/5) which is really cumbersome
(more difficult than in linear mode : 1/2 * 3/5)

And it is worse with more complicated expressions which sometimes are just impossible to write.

Is there somewhere a key or command to make an empty fraction appear on the screen?

**Comment by Ecco** [comment]
You're right! This is something we've significantly improved in the upcoming version 12 which we'll publish a beta version of very soon.

Keep in mind that this kind of compromise is to be expected though, but in the case of `1/2*3/4` we definitely didn't pick the best choice by default 😄

**Comment by Ecco** [comment]
This is fixed on the master branch 😄
