### ISSUE TITLE
Incorrect graph on square

### ISSUE THREAD

**Issue by wow0000** [numworks/epsilon#1074]
#### Describe the bug
The graphic made with the function: root(x)² is incorrect while the Calculator app get the good result with a negative x

#### Screenshots

![](https://i.imgur.com/pgyyF8r.png)
![](https://i.imgur.com/gJIMkQO.png)
![](https://i.imgur.com/Z894jeu.png)

#### Expected behavior
The curve should stop at 0

#### Environment
 - 11.2.0
 - Online, Real device (N0100)

**Comment by EmilieNumworks** [comment]
Hi @wow0000, thank you for reporting this! It should be fixed once #1090 is merged.
