### ISSUE TITLE
Unable to flash to device

### ISSUE THREAD

**Issue by taokann** [numworks/epsilon#1078]
I cloned the repo, installed dependencies, built with ``make clean && make`` but I can't flash it : ``make epsilon_flash`` returns 

```make: *** no rules to make « epsilon_flash » target.```

It may be a bit different of the regular error message because it is translated from french.
I'm running Ubuntu 19.04 and my calculator is model N0110.

**Comment by Ecco** [comment]
You're completely right! #1079 fixes this 😄
