### ISSUE TITLE
bug when the result of a formula is stored in a variable used in the formula

### ISSUE THREAD

**Issue by bernouilli** [numworks/epsilon#108]
1->A returns 1 which is OK
2*A+3->A -> returns 3 instead of 5 and 3 is stored in A
This behavior is as if the variable we store something in is zeroed before the expression is calculated

This bus is in 1.1.0, 1.1.1 and 1.1.2
I don't know if it's already present in 1.0.3

**Comment by Nemhome** [comment]
But A+2->A is working fine.
It's the * action (same for ^). e^M -> M works fine.

**Comment by bernouilli** [comment]
No, A+2->A returns 2 and stores 2 in A, whatever the value of A is in the first place. 
Same for e^M->M returns 1  whatever M contains. 
Tested it right now in the simulator which is in 1.1.2

**Comment by Nemhome** [comment]
Yep sorry, I've just seen the return value, not the stored value.

**Comment by bernouilli** [comment]
The returned value is also wrong : 
A+2->A returns always 2 whatever is stored in A
