### ISSUE TITLE
Add a switch for symbolic computation/simplification

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#1099]
#### Problem you'd like to fix
I completely understand removing symbolic computation and simplification to comply with UK test standards, but it's awful for trying to do math that isn't for a UK test. 

#### Describe the solution you'd like
To satisfy both the test requirements and the want for symbolic computation, you should add a switch in settings to enable and disable it, that locks in exam mode.

#### Screenshots
Symbolic calculation:
![symbolicCalcOff](https://user-images.githubusercontent.com/30960626/65380061-2def1780-dca1-11e9-998b-f123cbd116ba.png)
Vs.
![symbolicCalcOn](https://user-images.githubusercontent.com/30960626/65380062-321b3500-dca1-11e9-83bf-42354ff58787.png)

The settings menu:
![on](https://user-images.githubusercontent.com/30960626/65380026-98538800-dca0-11e9-8a83-a24b66f20d4c.png)
![off](https://user-images.githubusercontent.com/30960626/65380027-9984b500-dca0-11e9-8fbe-4f7e0f4b5d05.png)
![exam](https://user-images.githubusercontent.com/30960626/65380030-9ee1ff80-dca0-11e9-8821-8d2d6406be99.png)

**Comment by Thauxeeb** [comment]
I agree, one of the main reasons to buy NumWorks was this feature and now it's gone.
For example, in Hungary, you can not use NumWorks in tests anyways legally, so it wouldn't matter for me.

**Comment by boricj** [comment]
Remember that symbolic computation was removed in order to sell calculators to markets that prohibit CAS calculators during exams, _even_ if they offer an exam mode that deactivates it (#949).

**Comment by MixedMatched** [comment]
The way I interpreted the guidelines was that it cannot be facilitated within the confines of the test. If it really is the case that it cannot be designed at all with symbolic manipulation, I guess two branches could be maintained, one with and one without, where the workshop flasher asks if symbolics are allowed in their country. Then, the symbolic-less branch would ship by default.

**Comment by nsajko** [comment]
Numworks wants to sell calculators to high-schoolers; I get that - totally reasonable.

But why burn bridges towards other possible customers with no such restrictions like the high-schoolers have? Also, I think even some (most?) high-schoolers may use symbolic computation enabled calculators during exams; so providing a version of epsilon (probably just another app) with more advanced features to users seems like a must.

**Comment by artaxxx** [comment]
Unfortunately this idea doesn't solve the problem. If the CAS is prohibited at the exam, a switch won't be allowed... So we can't develop this enhancement.
We are trying to find another solution!

**Comment by MixedMatched** [comment]
Hi @artaxxx,
In the time between writing this issue and now, I now believe the only solutions would be to maintain multiple branches or have computer-algebra/non-computer-algebra build options. The second one is preferable, as it's easier for third-party development and is easier to maintain. The user side of this is obviously more simple, probably just a switch in the installation site.

In terms of exam moderation, the best solution I could think of is the CAS version having a different LED color, no Dutch mode, and displaying "CAS" or "sym" next to the degree text in the header bar. The non-CAS version would keep the current color, the Dutch mode, and probably wouldn't have anything additional in the header.

**Comment by lesves** [comment]
What about having an external switch? Could we have a switch to turn on the CAS in the web interface (workshop.numworks.com)? I have no idea about the exam regulations so this is just a random idea.

**Comment by RedGl0w** [comment]
> What about having an external switch? Could we have a switch to turn on the CAS in the web interface (workshop.numworks.com)? I have no idea about the exam regulations so this is just a random idea. (But I would like to use the feature)

The issue is that NumWorks can't deal a firmware with CAS. A switch in the compilation or on the workshop wouldn't neither fit.
