### ISSUE TITLE
Cannot compile for device on windows

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1104]
#### Describe the bug

Current master cannot be compiled for device on Windows due to a linker error.

#### Screenshots

```
d:/arm/bin/../lib/gcc/arm-none-eabi/7.2.1/thumb/v7e-m/fpv4-sp/hard\libgcc.a(_udivmoddi4.o):(.ARM.exidx+0x0): relocation truncated to fit: R_ARM_PREL31 against `.text'

collect2.exe: error: ld returned 1 exit status

make: *** [Makefile:206: output/device/release/n0110/epsilon.elf] Error 1
```

#### Environment

On Windows, using `gcc-arm-none-eabi-8-2019-q3-update-win32.exe`. For some reason, the exact same toolchain works well on macOS and Linux.

**Comment by Ecco** [comment]
The error becomes ``lib/gcc/arm-none-eabi/8.3.1/thumb/v7e-m+fp/hard\libgcc.a(_udivmoddi4.o):(.ARM.exidx+0x0): relocation truncated to fit: R_ARM_PREL31 against `.text'`` using the latest toolchain.

**Comment by Ecco** [comment]
A possible fix is to add this to the linker script:
```
  /DISCARD/ : {
    *(.ARM.exidx*)
  }
```

**Comment by toml12953** [comment]
> A possible fix is to add this to the linker script:
> 
> ```
>   /DISCARD/ : {
>     *(.ARM.exidx*)
>   }
> ```

Has anyone tried this fix? If it works, exactly which file do I add it to and where in the file? I don't see any file called linker and I'm a total Linux noob. I just know enough to compile the Numworks files if everything goes perfectly. If there's a problem, fuggedaboudit.

**Comment by boricj** [comment]
@toml12953 The file you are looking for is `ion/src/device/{n0100,n0110}/flash.ld`, depending on which model you are building for. Add the snippet at the end and it should link the firmware (haven't tested, not affected).

**Comment by toml12953** [comment]
> A possible fix is to add this to the linker script:
> 
> ```
>   /DISCARD/ : {
>     *(.ARM.exidx*)
>   }
> ```

I copied and pasted the lines above into flash.ld and now I get this:

d:/arm/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe:ion/src/device/n0110/flash.ld:200: syntax error
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:206: output/device/release/n0110/epsilon.elf] Error 1

**Comment by Ecco** [comment]
Fixed by 4d02d33375

**Comment by toml12953** [comment]
After Ecco's fix 4d02d33, I get this:

lto-wrapper.exe: fatal error: CreateProcess: No such file or directory
compilation terminated.
d:/arm/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: error: lto-wrapper failed
collect2.exe: error: ld returned 1 exit status
make: *** [build/rules.mk:32: output/release/device/n0110/epsilon.elf] Error 1

**Comment by Ecco** [comment]
That's weird. You could try to `make clean` then `make LTO=0`

**Comment by toml12953** [comment]
> That's weird. Would you mind trying to do `make clean` then `make LTO=0`?

d:/arm/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: output/release/device/n0110/ion/src/device/shared/usb/dfu.elf section `.rodata' will not fit in region `RAM_BUFFER'
d:/arm/bin/../lib/gcc/arm-none-eabi/8.3.1/../../../../arm-none-eabi/bin/ld.exe: region `RAM_BUFFER' overflowed by 172 bytes
collect2.exe: error: ld returned 1 exit status
make: *** [build/rules.mk:32: output/release/device/n0110/ion/src/device/shared/usb/dfu.elf] Error 1
