### ISSUE TITLE
Rounding inconsistency in cartesian plots

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1105]
#### Describe the bug

Rounding can result in some inconsistencies in the Graph app.

#### Screenshots

![screenshot (12)](https://user-images.githubusercontent.com/55989/65410485-c80ea700-ddea-11e9-86c6-3319f0bad6bc.png)

#### To Reproduce
1. Go to the Functions app
2. Type `f(x)=x-1`
3. Plot
4. Select "Preadjustment > Orthonormal"
5. Scroll to x=1

#### Expected behavior
It should display `f(x)=0` and `x=1`

#### Environment
Epsilon version 11.2.0 on the web simulator

**Comment by Ecco** [comment]
The problem arises because we do it this way:

1. Figure out an `x` value according to the screen's resolution and cursor position. Now sometimes this value can be tricky, such as `1.00000000001`. Let's assume it's the case.
2. We compute `f(x)`, which is `0.00000000001`, and we try to display it on 5 characters. Easy, it's "1E-9", that fits!
3. We try to display `x` using 5 characters. It doesn't fit entirely so we round it to `1`.

Suggested solution: do the rounding first, then evaluate f(x) using the rounded value.

**Comment by nsajko** [comment]
Newbie question: why is the 'x' value displayed as being exactly '1' (so presumably it is rounded), while 'f(x)' is not rounded?

Also, why does the function value in the "Functions" app not respect the "Result format" "Significant figures" setting?

**Comment by artaxxx** [comment]
For the first question, @Ecco replied in the comment just before yours :)
For the second, please feel free to open a new issue!
I close this one because the initial problem is now fixed
