### ISSUE TITLE
log with base , not lg that called "log"

### ISSUE THREAD

**Issue by alexeyneu** [numworks/epsilon#1109]
lg( x ) / lg( base) is bad . some major brands models support this

**Comment by Ecco** [comment]
I really don't understand what you meant. Please follow our issue template. Thanks.

**Comment by alexeyneu** [comment]
@Ecco dude do you know what `lg` means in math? not sure it's your subject to understand

**Comment by adriweb** [comment]
Doesn't matter, you need to follow the issue template just like anyone.

**Comment by alexeyneu** [comment]
https://www.youtube.com/watch?v=rbGbKpCGN6c  
good luck

**Comment by Ecco** [comment]
I fail to see any mention of `lg` in the video you linked. We already do custom-base logs, just use `log(x,a)` in the toolbox.

![screenshot (13)](https://user-images.githubusercontent.com/55989/65436165-01aed480-de22-11e9-84ac-c422b1f15250.png)


Last but not least, note that the `lg` [name is ambiguous](http://mathworld.wolfram.com/Lg.html).

**Comment by alexeyneu** [comment]
see "also" section in your link. Thats told about lg . Your governament accepts russian-deutsch convention and recommends you to do so (before it's too late haha).
