### ISSUE TITLE
[Suggestion] Shift Alpha Lock changes

### ISSUE THREAD

**Issue by ian-abbott** [numworks/epsilon#111]
Currently, the following ShiftAlphaStatus values are supported:
 * `Default` - no modifiers in effect.
 * `Shift` - next key invokes shifted function - title bar shows `shift`.
 * `Alpha` - next key produces lower case character - title bar shows `alpha`.
* `ShiftAlpha` - next key produces upper case character - title bar shows `ALPHA`.
* `AlphaLock` - locked in lower case alpha mode - title bar shows padlock icon + `alpha`.
* `AlphaLockShift` - locked in lower case alpha mode, but next key produces upper case character - title bar shows padlock icon + `alpha`.
* `ShiftAlphaLock` - locked in upper case alpha mode - title bar shows padlock icon + `ALPHA`.

There are some issues with the above:

1. There is no visual distinction between the `AlphaLock` and `AlphaLockShift` states.
2. There is no way to enter a lower case character in the `ShiftAlphaLock` state other than by pressing the 'alpha' key to return to the `Default` state and proceeding from there.
3. Pressing the 'alpha' key in the `AlphaLockShift` state goes back to the `Shift` state. Although reasonably logical, it may be unexpected as there is no visual indication that 'shift' has previously been pressed.

I came up with a couple of possible solutions. One of them involved adding an additional `ShiftAlphaLockShift` state to allow a lower case character to be entered when locked in upper case alpha mode, and to add a couple of new title bar strings `Alpha` and `aLPHA` to distinguish all the current states. However, I think this would make the interface too complicated and confusing.

The simpler solution I came up with is to eliminate the `AlphaLockShift` state altogether and allow the 'shift' key to toggle between the `AlphaLock` and `ShiftAlphaLock` states, so the title bar will keep displaying the padlock icon, but toggle between showing `alpha` and `ALPHA`. This is consistent with the existing use of the 'shift' key to toggle between the `Alpha` and `ShiftAlpha` states.

**Comment by artaxxx** [comment]
Fixed by #141 

Thanks @ian-abbott !
