### ISSUE TITLE
Status bar does not indicate engineering notation mode

### ISSUE THREAD

**Issue by boricj** [numworks/epsilon#1112]
#### Describe the bug
Unlike scientific mode, engineering mode is not flagged as such in the status bar.

#### Screenshots
![image](https://user-images.githubusercontent.com/9872969/65452512-aee51500-de41-11e9-8263-31784dc380e2.png)

![image](https://user-images.githubusercontent.com/9872969/65452595-d4721e80-de41-11e9-87c1-96a689d8e519.png)

#### To Reproduce
1. Go to the 'Settings' app
2. Put the calculator in engineering mode
4. See missing flag

#### Expected behavior
Both scientific and engineering mode having flags in the status bar, unlike decimal mode.

#### Environment
 - Epsilon master (version 79a70f5b6ef657e6916403c70dc4f3e1a79db6ac).

**Comment by LeaNumworks** [comment]
Hello,
Thanks for spotting this!
This was fixed by 2686b0d51ded8f95c6ce08449757ef2a33103ba7.
