### ISSUE TITLE
simulator eye-breaking quality in full-screen 

### ISSUE THREAD

**Issue by alexeyneu** [numworks/epsilon#1113]
reallyy low-graded full screen picture in simulator.  
it doesnt look like 300x300 but like picture is downscaled and then upscaled again  
if it's the case then stop to do so.  
if it's just upscaled then you use wrong method. Use glsl (or webgl if we're talkin about online stuff) .i mean multisampling/mipmapping or anisotropic stuff there. My bet that it will work.  opencv zoom will work fo' sho' also . So simulator would be used as stand-alone tool along with demo and testing.

**Comment by Ecco** [comment]
That's by design. We want the simulator to look as much as the real device as possible, hence the nearest-neighbor interpolation.

**Comment by alexeyneu** [comment]
and why then you have added full-screen feature?  
and there's no ips on typical monitor And you not gonna sit so close to it.  
what i offer would be like optically zoomed calc display.
