### ISSUE TITLE
Make Epsilon IB compliant

### ISSUE THREAD

**Issue by ghost** [numworks/epsilon#1129]
International Baccalaureate Diploma Programme is a high-school curriculum similar to AP. They have a bunch of [recommended calculators](https://www.ibo.org/contentassets/e3e2d5a7b79e48f7a47f8973e7873a10/use-of-calculators-in-examinations-2019_en.pdf) such as the TI-84 or FX 9860G

The [recommended calculator](https://www.ibo.org/contentassets/e3e2d5a7b79e48f7a47f8973e7873a10/use-of-calculators-in-examinations-2019_en.pdf) list has a list of things that the calculator must have and must not have. Though some of them are very vague.

We should try to get the epsilon OS approved for IB Use.

**Comment by MixedMatched** [comment]
Epsilon already seems to cover the requirements, up to and including Mathematics HL.

**Comment by boricj** [comment]
I would exercise caution before reaching that conclusion. The function `isPrime` is blocked in their custom exam mode for the TI-Nspire and epsilon has a nearly-equivalent `factor` function. Similarly, advanced graphing is blocked on the HP Prime and the upcoming release has new graphing functionalities that may or may not be considered advanced.

**Comment by Will-of-R-Learn** [comment]
One of the things missing is the finance option that the ti-84 has. Other than that I guess the calculator should be fine. One more addition I would like to make about this would be that IB has very vague requirements. Look at the Casio FX-CG50 which has a lot more functionality in the exam mode than the ti-84, still both calculators are recommended by IB.

**Comment by Will-of-R-Learn** [comment]
> Epsilon already seems to cover the requirements, up to and including Mathematics HL.

Also, compliant and covering requirements is not exactly same. If there are any extra features that IB does not allow, then they must not be allowed in the exam mode also. (maybe make a separate IB exam mode)

**Comment by Will-of-R-Learn** [comment]
#1148

**Comment by Will-of-R-Learn** [comment]
@Ecco Could you guys make this part of your next milestone? IB students still have to suffer with the crappy Ti-84

**Comment by Will-of-R-Learn** [comment]
+1

**Comment by artaxxx** [comment]
Done!
