### ISSUE TITLE
linux simulator crashes

### ISSUE THREAD

**Issue by gnah33** [numworks/epsilon#1132]
### Compiling : OK
`make -j5 PLATFORM=simulator`
Everything was fine

### Running it
`./output/release/simulator/linux/epsilon.bin`
Then the window shows up less than a sec. and disappears with an error message : 
`epsilon.bin:ion/src/simulator/shared/display.cpp :65 : void Ion::SDL::Display::draw(SDL_Renderer*, SDL_Rect*):  l'assertion « pitch == 2*Ion::Display::Width » a échoué.`

gcc version 8.30
glibc 2.29-r2
libsdl and libsdl2 installed.

I've been trying with diffrent command lines, same result.
It used to work when using fltk's libraries.
What did I do wrong ?

**Comment by boricj** [comment]
The SDL simulator tries to create a hardware-accelerated renderer and fails. Try the fixes in #1128 to fallback on a ugly but functional software renderer.
