### ISSUE TITLE
Add Chi-squared test

### ISSUE THREAD

**Issue by Will-of-R-Learn** [numworks/epsilon#1148]
Addition of Chi-squared test to the operating system

https://en.wikipedia.org/wiki/Chi-squared_test

**Comment by Will-of-R-Learn** [comment]
This feature now has a small bounty also: https://www.bountysource.com/issues/81383701-add-chi-squared-test

**Comment by RubenNumworks** [comment]
Related to #958

**Comment by artaxxx** [comment]
Duplicate #958
