### ISSUE TITLE
Cannot flash from Windows

### ISSUE THREAD

**Issue by Gegenter** [numworks/epsilon#1149]
this is the error i get when i want to flash my code on the calculator. Please help. 

  File "build/device/dfu.py", line 575, in main
    list_dfu_devices(__Identifiers)
  File "build/device/dfu.py", line 472, in list_dfu_devices
    devices = get_dfu_devices_with_vid_pids(__Identifiers)
  File "build/device/dfu.py", line 100, in get_dfu_devices_with_vid_pids
    devices = [get_dfu_devices(idVendor=vid_pid["VID"],idProduct=vid_pid["PID"]) for vid_pid in vid_pids]
  File "build/device/dfu.py", line 100, in <listcomp>
    devices = [get_dfu_devices(idVendor=vid_pid["VID"],idProduct=vid_pid["PID"]) for vid_pid in vid_pids]
  File "build/device/dfu.py", line 432, in get_dfu_devices
    custom_match=FilterDFU(), **kwargs))
  File "C:\msys64\home\Gegenter\epsilon\build\device\usb\core.py", line 1265, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available

**Comment by Ecco** [comment]
Indeed, that's not something that's either part of our in-house development process nor part of our CI. There's no reason it couldn't be made to work though. Here are the steps that would be required:

1. Install libusb for Windows and make sure pyusb can find it
2. Install the NumWorks driver for windows by doing an update from the [Workshop](https://workshop.numworks.com)

**Comment by Gegenter** [comment]
Oh wow libusb is really a pain in the ass, but I got it to work so thanks! Im closing the issue now.

**Comment by Ecco** [comment]
Great news 😄 Would you mind sharing what steps you had to do to get it to work? That might be helpful for other people 😄

**Comment by Gegenter** [comment]
Well I did download libusb which was already a trouble since the new version that is on their site does not seem to work or atleast i couldnot seem to get it to work so i downloaded libusb from some other weird website and then i did all the steps that were proposed in a tutorial, basically i had to enable windows to allow non original driver installs, then i had to update the drivers on the calculator and then i got it to work! But for some reason if you update the driver for the calculator, the numworks page will not detect it (on that computer) so i had to use a vm when i wanted to send files on it and etc. Basically it was a mess but now im happy i got it to work.

**Comment by Ecco** [comment]
Thanks for taking the time to share this!
