### ISSUE TITLE
Infra issue with doc

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1159]
#### Describe the bug
Image doesn't appear in the doc

#### Screenshots
https://github.com/numworks/epsilon/blob/master/docs/poincare/index.md
![image](https://user-images.githubusercontent.com/43498612/66703602-ac752d00-ed14-11e9-9db7-efb84d594033.png)

**Comment by Ecco** [comment]
Yes. The doc is published online at https://www.numworks.com/resources/engineering/software/

**Comment by adriweb** [comment]
> Yes. The doc is published online at [numworks.com/resources/engineering/software](https://www.numworks.com/resources/engineering/software/)

Speaking of which, I just noticed Latex isn't rendered ([here for instance](https://www.numworks.com/resources/engineering/software/poincare/#additions-are-reduced-by-common-applying-mathematics-rules)) - is MathJax, or equivalent, missing?
