### ISSUE TITLE
How to debug on a real device?

### ISSUE THREAD

**Issue by oakes** [numworks/epsilon#1169]
Can anyone explain their process for debugging epsilon? Right now I can't even do print debugging...is there a debug console I can access?

Apologies for making an issue...I don't know where else to ask this.

**Comment by boricj** [comment]
You can debug the simulator like any other program, which is the preferred way to investigate platform-independent bugs.

On the calculator, you have two options:
- Connect to the UART (Rx/Tx pads) and collect logs,
- Connect to the Cortex Debug pads and use a SWD probe like a ST-Link V2.

The second option gives you a GDB remote target with OpenOCD, where you can debug the firmware almost like any other program. Unfortunately, this requires modding your calculator: the NumWorks team has modified calculators with the Cortex Debug connector soldered on and a hole in the back of the calculator shell. Personally, I have modded my own N0100 myself with pin headers (https://tiplanet.org/forum/viewtopic.php?f=102&t=21010&start=10#p226761), but that is extremely non-conspicuous.

Now that I think about it, @zardam redirected the UART on the USB data pins for a rover project a while ago. Maybe it's possible to do the same with SWD, which would only require a hacked USB cable.

**Comment by Ecco** [comment]
You will need to open your calculator to debug on a real device. Note that this will void your warranty though.

Anyway, we put a standard Cortex Debug footprint on production units. Here's what you'll need to do to debug on a real device:

1. Open your device (there's a Torx screw beneath each pad)
2. Solder a standard [Cortex Debug](https://img1.daumcdn.net/thumb/R720x0.q80/?scode=mtistory2&fname=http%3A%2F%2Fcfile24.uf.tistory.com%2Fimage%2F140CEE1E4CE1F5BA320197) connector at the bottom of the PCB. The part number is `FTSH-105-01-L-DV-K`.
3. Attach an SWD probe such as an ST-Link v2.
4. Install openocd on your computer, and type "make openocd" in a terminal.
5. In another terminal, type "make epsilon_run". That will rebuild Epsilon

**Comment by oakes** [comment]
Makes sense, thank you.
