### ISSUE TITLE
[toolbox] Chemistry and other scientific constants in Toolbox

### ISSUE THREAD

**Issue by tjhorner** [numworks/epsilon#117]
As per suggestion of @adriweb (thanks!), I'm opening an issue on this.

I'm sure many high school students, such as myself, would find that scientific constants in the Toolbox prove helpful during chemistry or physics work, for example.

I've already implemented [chemistry constants](https://twitter.com/tjhorner/status/906790966924734464) in my [personal fork](https://github.com/tjhorner/kaleculator-os), and they've been proven to be helpful already!

Adding these in the toolbox is _perfect_, since it's [non-intrusive](https://core.telegram.org/tsi/feature_philosophy#3-complexity) for those who don't need it, but still easily accessible for those who do.

The question that remains is: what constants should be placed in the Toolbox? Right now on my fork, I only have Avogadro's number and the molar mass of the elements.

**Comment by adriweb** [comment]
It is a good idea indeed, many other calcs have this feature (including when in exam mode).
I'd also like to insist a lot on displaying the unit of the constant too, as it is quite important.

Regarding what to have, here's a list of physics constants: http://hyperphysics.phy-astr.gsu.edu/hbase/Tables/funcon.html 
and one for chemistry constants: https://en.wikibooks.org/wiki/General_Chemistry/Constants (that said, both could be merged)
There are also useful stuff here that could be used for conversions: https://chem.libretexts.org/Reference/Units_and_Conversions/Physical_Constants

**Comment by tjhorner** [comment]
Yes, displaying the proper unit for the constant would be important. The only reason I didn't on my fork was because I was too lazy to include two localisation strings: one for the value with units (displayed), and one for the value without the units (inserted into text field).

But yes, in science units are super important. As my chemistry teacher says, "no naked numbers!" :)

**Comment by Zezombye** [comment]
I don't think the toolbox is the right place for this - a better way would be to add a new physics app, with constants and periodic table.

**Comment by adriweb** [comment]
A new app, dedicated to physics/chemistry, possibly a periodic table, is yet another thing on its own, this isn't the right github issue for it (even though I agree it needs to happen at some point, definitely).
I do think there needs to be some kind of "global toolbox" available across apps or something, that said a good first step would be to have those constants available at least in the calc app. It's mostly there that it'd be used.

**Comment by tjhorner** [comment]
@zezombye I'd have to disagree. Adding yet another app might cause more confusion since it's adding more complexity. If we were to add more dedicated scientific functions, then I would agree. But this is about simply adding numerical values for use in equations (like in the Calculation app)

**Comment by adriweb** [comment]
Yeah, a periodic table app is a must anyway but shouldn't be the only place where such constants are available - it'd be quite a waste of time having to constantly switch between apps to go grab a value!
At least with the toolbox, it's available right there :)

**Comment by Zezombye** [comment]
Indeed. Also why not allow apps to add categories to the toolbox?

As for the constants to add, you could look at the physics app from Casio. Here's the list of the included constants: http://www.planet-casio.com/files/programs/1779-3-physium.pdf#page=12&zoom=130,-252,586

**Comment by adriweb** [comment]
> Also why not allow apps to add categories to the toolbox?

I think that's a good idea. Apps could call an API to dynamically extend the (global/shared) toolbox's content to add their things, so that the user can access the app's data (constants or otherwise?) from anywhere.

**Comment by utybo** [comment]
Anything new on this?

**Comment by artaxxx** [comment]
It's now in version 17
