### ISSUE TITLE
[Bug] Segmentation error in the python shell (public code)

### ISSUE THREAD

**Issue by AntoninLoubiere** [numworks/epsilon#1176]
### Version used
I use the last version available on github, compile with Linux (*NB: I don't use the last version available on numworks.com which is the version of the 25 of October of 2019)*).
### Description
When I go to the python shell; I do some stuff, and I try to get some historic which is **hide** (= I go up, out of the screen). On my local simulator I got a segmentation error, and on my calculator, the led become red and it reset.

*NB: This doesn't happened on the last release available on numworks.com *

**Comment by adriweb** [comment]
I submitted PR #1177 to fix this.

**Comment by EmilieNumworks** [comment]
Hi @AntoninLoubiere, good catch! Thank you for reporting this, I am merging @adriweb PR which indeed fixes the crash.
