### ISSUE TITLE
Improve Equations solving (chemistry CPGE)

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#1182]
**Update: added another (much worse) exemple that occurred during an oral exam.**

#### Problem you'd like to fix
Chemistry exercices sometimes require the student to use a calculator to solve the equation of reaction.

<details>
<summary>Exemple 1: Cannot find value when frame too tight</summary>

This one really shocks: try to solve
`(0.0301-x)*(0.902-3x)^3*45.8*(8.314*400/(2*10^-3))^2=(2x)^2`

With very carefully chosen values [0,0.5]
![5467DF48-9246-494A-91B9-DFCFCB702961](https://user-images.githubusercontent.com/10530980/69356212-5daba300-0c83-11ea-80e8-4d9f3e1058c4.jpeg)
![C98C724D-6A24-48F0-A5EE-FD691B6AAF40](https://user-images.githubusercontent.com/10530980/69355780-af076280-0c82-11ea-8221-fc07352dbcf3.jpeg)

But with crazy values:
![C06282D9-0F3F-4CAC-A97A-C081A79FBCEA](https://user-images.githubusercontent.com/10530980/69355811-bd557e80-0c82-11ea-9ff1-ce5e6865cb2c.jpeg)
![B67C6DCA-50F7-4624-BA3B-5D916D79AE16](https://user-images.githubusercontent.com/10530980/69355813-bdee1500-0c82-11ea-864d-65af8ac59324.jpeg)
Where clearly the value was in the first interval
</details>

<details>
<summary>Exemple 2: Cannot find value when frame too large</summary>

A typical example would be
![59E78EF5-48FC-4CF0-98B7-7276BF15C7CD](https://user-images.githubusercontent.com/10530980/68244120-6a3dc380-0014-11ea-8a47-d0659d1cac3a.jpeg)

> A classic exercise : get the pH of, in this case, `H2C2O4 + H2O = HC2O4- + H3O+` with a `PKa=1.2`, initial concentration of `c_H2C2O4=0.1mol.L-1`

In this format, NumWorks will prompt a selector which by default (-10,10) would give an impossible result
![42890F81-7770-4645-9E6E-88570D4B34A6](https://user-images.githubusercontent.com/10530980/68244357-f8b24500-0014-11ea-8a2b-9ede32f8e314.jpeg)

It is possible by setting a tighter frame
![DC55025B-1FEB-4EEF-B0A0-50AC00F3E931](https://user-images.githubusercontent.com/10530980/68244334-e89a6580-0014-11ea-8ff0-dc610ebe4df1.jpeg)
To get the proper result
![A5C41A7E-3E22-4356-8E76-FEB927F12427](https://user-images.githubusercontent.com/10530980/68244536-4fb81a00-0015-11ea-9679-5d62af6a76f2.jpeg)
But that remains counter intuitive, and blur to a student panicking on his test.

Another workaround is to reverse the fraction
![A45983C7-CA5E-46F3-906A-D96643284282](https://user-images.githubusercontent.com/10530980/68244619-7d04c800-0015-11ea-9bc8-77890fadf16e.jpeg)
Which will give some unreadable results, but that are correct
![D046E928-257E-4B83-8E25-192AA3E03BE6](https://user-images.githubusercontent.com/10530980/68244650-8e4dd480-0015-11ea-93b0-b68ae0bc5132.jpeg)

</details>

I am not aware of a mean to improve / fix the behavior of the solver in this case, and apparently so does the TI-83PremiumCE, but this apparently works on some Casio (among other) models, without requiring trickery or further thinking like this. It would be very helpful to improve this.

**Comment by artaxxx** [comment]
Fixed in version 16
