### ISSUE TITLE
Datetime module for numworks

### ISSUE THREAD

**Issue by Cozax** [numworks/epsilon#1184]
### FEATURE 

A datetime module for numworks would be very useful, for example to get the time and day in some python scripts.
For example, to make a clock or something like that

**Comment by boricj** [comment]
While the DateTime module does not technically require a RTC for most of its functionalities, keep in mind that the lack of a RTC on NumWorks calculators will prevent things like `datetime.now()` from properly working.

**Comment by Cozax** [comment]
Thanks for reply
