### ISSUE TITLE
Matrix product is aproximated 

### ISSUE THREAD

**Issue by Flirno** [numworks/epsilon#1185]
Hi,
I know that on Texas instrument when you do this simple matrix product : 
[image1](https://i.imgur.com/MTh9liv.png)

You get the exact result, which is 1/3. 

Even for the inverse of a matrix, what it returns on Numworks is an approximation : 
[image2](https://i.imgur.com/BFfuAQB.png)

And I can't get the exact result :/

I would really really appreciate that this get fixed as quickly as it can be ;)

I think you could take inspiration from the method proposed in this topic #919  which seems to consume few resources

Still active on the latest version 11.2.0

**Comment by Ecco** [comment]
This is already fixed in master 😄The fix will be distributed as part of version 12.

**Comment by Flirno** [comment]
Thanks ^^
