### ISSUE TITLE
LCM & GCD should take a set of numbers

### ISSUE THREAD

**Issue by Ryder17z** [numworks/epsilon#1187]
#### Screenshots

http://www.alcula.com/calculators/math/gcd/
![opera_2019-11-11_01-17-50](https://user-images.githubusercontent.com/2000703/68553419-32be8500-0421-11ea-82d4-478c23e4c75f.png)

#### 
![opera_2019-11-11_01-21-22](https://user-images.githubusercontent.com/2000703/68553454-9b0d6680-0421-11ea-8fd2-4abcc9535444.png)

**Comment by RedGl0w** [comment]
LCM should too :)

**Comment by Ryder17z** [comment]
> LCM should too :)

I wasn't sure so i omitted that. i've seen arguments for why and why not and i'm not sure where i stand on LCM

**Comment by artaxxx** [comment]
Fixed in 15.0.0
