### ISSUE TITLE
Polar and parametric functions crash the functions app

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#1188]
#### Describe the bug
When a parametric or polar function is the first entered into the functions app as the first function, the app will crash on the "table" tab.

Crash message:
`linux git:(master) ./epsilon.bin 
epsilon.bin: apps/graph/values/values_controller.cpp:243: Shared::ContinuousFunction::PlotType Graph::ValuesController::plotTypeAtColumn(int*) const: Assertion 'plotTypeIndex < ContinuousFunction::k_numberOfPlotTypes' failed.
[1]    23270 abort      ./epsilon.bin`

Full back trace:
`#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6728801 in __GI_abort () at abort.c:79
#2  0x00007ffff671839a in __assert_fail_base (fmt=0x7ffff689f7d8 "%s%s%s:%u: %s%sAssertion %s' failed.\n%n", assertion=assertion@entry=0x5555557ed0f6 "plotTypeIndex < ContinuousFunction::k_numberOfPlotTypes", 
    file=file@entry=0x5555557ed032 "apps/graph/values/values_controller.cpp", line=line@entry=243, 
    function=function@entry=0x5555557ed640 <Graph::ValuesController::plotTypeAtColumn(int*) const::__PRETTY_FUNCTION__> "Shared::ContinuousFunction::PlotType Graph::ValuesController::plotTypeAtColumn(int*) const") at assert.c:92
#3  0x00007ffff6718412 in __GI___assert_fail (assertion=0x5555557ed0f6 "plotTypeIndex < ContinuousFunction::k_numberOfPlotTypes", file=0x5555557ed032 "apps/graph/values/values_controller.cpp", line=243, 
    function=0x5555557ed640 <Graph::ValuesController::plotTypeAtColumn(int*) const::__PRETTY_FUNCTION__> "Shared::ContinuousFunction::PlotType Graph::ValuesController::plotTypeAtColumn(int*) const") at assert.c:101
#4  0x0000555555774881 in Graph::ValuesController::plotTypeAtColumn(int*) const ()
#5  0x0000555555774a23 in Graph::ValuesController::intervalAtColumn(int) ()
#6  0x0000555555760539 in Shared::ValuesController::numberOfElementsInColumn(int) const ()
#7  0x0000555555760c7f in Shared::ValuesController::memoizedBufferForCell(int, int) ()
#8  0x0000555555760ddd in Shared::ValuesController::willDisplayCellAtLocation(HighlightCell*, int, int) ()
#9  0x00005555557751fa in Graph::ValuesController::willDisplayCellAtLocation(HighlightCell*, int, int) ()
#10 0x00005555555dae54 in TableView::ContentView::layoutSubviews() ()
#11 0x00005555555dae88 in TableView::layoutSubviews() ()
#12 0x00005555555de6f1 in View::setFrame(KDRect) ()
#13 0x00005555555de6f1 in View::setFrame(KDRect) ()
#14 0x00005555555d1733 in ButtonRowController::ContentView::layoutSubviews() ()
#15 0x00005555555de6f1 in View::setFrame(KDRect) ()
#16 0x00005555555d9368 in StackViewController::ControllerView::setContentView(View*) ()
#17 0x00005555555d94ad in StackViewController::viewWillAppear() ()
#18 0x00005555555da20e in TabViewController::setActiveTab(signed char) ()
#19 0x000055555575892a in Shared::FunctionListController::FunctionListController(Responder*, ButtonRowController*, ButtonRowController*, I18n::Message)::{lambda(void*, void*)#2}::_FUN(void*, void*) ()
#20 0x00005555555d13b1 in Button::handleEvent(Ion::Events::Event) ()
#21 0x00005555555d0c9a in App::processEvent(Ion::Events::Event) ()
#22 0x00005555555d21ad in Container::dispatchEvent(Ion::Events::Event) ()
#23 0x000055555579d0a6 in AppsContainer::dispatchEvent(Ion::Events::Event) ()
#24 0x00005555555d73f6 in RunLoop::step() ()
#25 0x00005555555d7434 in RunLoop::runWhile(bool (*)(void*), void*) ()
#26 0x000055555579d22d in AppsContainer::run() ()
#27 0x00005555555cf0ed in main ()`

#### To Reproduce
1. Go to the 'functions' app
2. Type a polar or parametric function
3. Go to the table tab

#### Environment
 - Commit 0736a3f
 - Happens on the simulator, n0100, and n0110

**Comment by Ecco** [comment]
Hi @MixedMatched ! Thanks for reporting this!
