### ISSUE TITLE
Multiplication elision is inconsistent

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1192]
#### Describe the bug
`2*x` is displayed as `2x` but `2*θ` is displayed as `2•θ`.

#### Screenshots
![screenshot (18)](https://user-images.githubusercontent.com/55989/68691271-c607cf80-0573-11ea-9370-49bca9fae662.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type `f(x)=2x`
3. Scroll and type `g(θ)=2θ`

**Comment by EmilieNumworks** [comment]
Good one ! This is fixed by #1195.
