### ISSUE TITLE
Integration of convergent infinite series

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#1198]
Integration appears to get very wrong very quickly when when it comes to convergent infinite series.

The following is a derivative of https://fr.wikipedia.org/wiki/Int%C3%A9grale_de_Dirichlet when applied to x^2

![](https://user-images.githubusercontent.com/10530980/68813073-f6836280-0674-11ea-96ae-f34310d47b8d.jpeg)

We get a result somewhat coherent for n=100
![A756310D-B762-4C29-B54F-C06B601240D4](https://user-images.githubusercontent.com/10530980/68813162-46fac000-0675-11ea-9aef-dba53b9eddd3.jpeg)
But it gets blatantly wrong afterwards
![9E91672E-50D8-4C8E-822F-73BD65196DA5](https://user-images.githubusercontent.com/10530980/68813187-5b3ebd00-0675-11ea-815e-09a95ca7ed91.jpeg)

I know that this serie especially is very hard to compute.

**Comment by nsajko** [comment]
There is a big regression here, even with n=100 a bogus result is obtained using current master.

**Comment by RubenNumworks** [comment]
> There is a big regression here, even with n=100 a bogus result is obtained using current master.

Could you give more details? Is your calculator set in radians?

**Comment by gpotter2** [comment]
This is pretty true. Here's 12.3.0
![365013B2-E205-4ACC-B69B-2FDD52DBB7D4](https://user-images.githubusercontent.com/10530980/75686611-d5cf2f00-5c9c-11ea-85ac-967558ea09cf.jpeg)
It's much worse than the above (which i can't recall the version of, but it matches the date of this issue).

**Comment by RubenNumworks** [comment]
Is your calculator set in radians? The value of the integral depends on the angle unit setting.

**Comment by gpotter2** [comment]
"deg" in the upper corner actually means... degrees 😄

**Comment by RubenNumworks** [comment]
Is the result better if you switch to radians?

**Comment by gpotter2** [comment]
Dirichlet's integral makes little sense in radians. :/
I can't check if the output means anything

**Comment by RubenNumworks** [comment]
The variable of the `sinc` function is in radians. I concede it does not appear explicitly on the [French](https://fr.wikipedia.org/wiki/Sinus_cardinal) or [English](https://en.wikipedia.org/wiki/Sinc_function) Wikipedia articles, but it appears implicitly if you read through.

Note that if `α` is the value in degrees corresponding to a value `θ` in radians (that is `α = θ * 180 / π`) then the numerical values of `sin(θ) / θ` and `sin(α) / α` are not equal.

**Comment by gpotter2** [comment]
My bad, the original post is correct.
So nothing has changed since the original post.
![94C3874D-F1F4-436A-A44F-EDCC2DC5F0FE](https://user-images.githubusercontent.com/10530980/75693991-1da78380-5ca8-11ea-889b-091bc7592130.jpeg)
