### ISSUE TITLE
Probleme when copy - pasting between different apps

### ISSUE THREAD

**Issue by MDLC01** [numworks/epsilon#1206]
#### Describe the bug
When copy - pasting a calculation from 'Calculation' app to 'Python' app, some carracteres are not modified.

#### Screenshots
Copied text:
![copied_text](https://user-images.githubusercontent.com/57839069/69234754-3a53fb80-0b90-11ea-8f3c-27b615190e64.png)
Pasted in Python editor:
![pasted_text](https://user-images.githubusercontent.com/57839069/69234755-3aec9200-0b90-11ea-8266-0347071ad653.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type 'something × something'
3. Copy it (shift + copy)
4. Paste it into the Python editor
OR
1. Go to the 'Settings' app
2. Set 'Result format' to 'Scientific' or 'Engineering'
3. Go to the 'Calculation' app
4. Type 'something ×10^ something'
5. Copy the result (should be something like 'something E something')
6. Paste it into the Python editor

#### Expected behavior
'×' should be replaced by '*'
'E' should be replaced by '\*10**'
![python](https://user-images.githubusercontent.com/57839069/69235740-65d7e580-0b92-11ea-8b20-0a37269f7eee.png)

#### Environment
 - Epsilon version: 12.2.0
 - Happens everywhere

**Comment by RedGl0w** [comment]
For the E, I think we shouldn't make too much change, or when you'll copy and paste, all your E will be replaced.
For the ×, I'm going to open a PR to correct it.

**Comment by Ecco** [comment]
> For the E, I think we shouldn't make too much change, or when you'll copy and paste, all your E will be replaced.

Actually, the <small>E</small> character used to mean 1E10 is a currently a different one. We might want to use a standard E though, or at least also accept a standard one when parsing.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
