### ISSUE TITLE
sigma equation Why not to solve

### ISSUE THREAD

**Issue by alexeyneu** [numworks/epsilon#1211]
![2](https://user-images.githubusercontent.com/31589671/69419839-673e1500-0d2e-11ea-9223-7a13f1ffbf84.png)
  
and there's hp  
![1](https://user-images.githubusercontent.com/31589671/69420123-209cea80-0d2f-11ea-8b4a-62ecfcb03fe5.png)
![3](https://user-images.githubusercontent.com/31589671/69421368-e1bc6400-0d31-11ea-909e-db4695acf0ca.png)

**Comment by artaxxx** [comment]
This kind of equations is now handled in the solver
