### ISSUE TITLE
Strange reactions with graph function list

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1213]
#### Describe the bug
When you create a parametric function with x=0; y=1 like coordonates, you rename it a(t), and you create a new function, it copy/paste the function, but with other names, it doesn't

#### Screenshots

![image](https://user-images.githubusercontent.com/43498612/69454705-0e3ea300-0d67-11ea-857c-2e628b61fd21.png)
![screenshot](https://user-images.githubusercontent.com/43498612/69454683-01ba4a80-0d67-11ea-952c-82cfd8b98f87.png)

#### Expected behavior
To have a new function, with an empty expression

#### Environment
 - Epsilon version : 12.2.0
 - The platform(s) on which the problem happens: online simulator, actual device

**Comment by Ecco** [comment]
Would you mind listing the required steps to reproduce this issue?

**Comment by RedGl0w** [comment]
you neee to go to graph, add a function, change its type to parametric, put in the matrix 1 in the top of the first column, and 0 in the second line of the first column. Then rename the function to a(t), and add a new function. 
It's notre the worst bug, but with other names it doesn't react like that....

**Comment by Ecco** [comment]
Indeed, good catch. Not a very severe bug though, but definitely not a normal behavior. Thanks for reporting this!
