### ISSUE TITLE
Simplify nested radicals

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1215]
#### Problem you'd like to fix
Turn `sqrt(3+sqrt(8))` into `1+sqrt(2)`.

#### Screenshots

Here's an example with `sqrt(3)+sqrt(2)` that doesn't get detected as such.

![nested radicals 1](https://user-images.githubusercontent.com/55989/69535139-81b8fe00-0f7b-11ea-8898-28e695a326f6.png)

And an example in the Equations app
![nested radicals 2](https://user-images.githubusercontent.com/55989/69535154-8978a280-0f7b-11ea-9f06-3322b045c4fe.png)
![nested radicals 3](https://user-images.githubusercontent.com/55989/69535157-8b426600-0f7b-11ea-9332-cb1a96199de7.png)

**Comment by artaxxx** [comment]
Fixed in version 16
