### ISSUE TITLE
[Python] using fill_rect in a loop renders the calculator unusable

### ISSUE THREAD

**Issue by carl-vbn** [numworks/epsilon#1219]
#### Describe the bug
I noticed that when using the new `fill_rect` function from the kandinsky module in a loop to fill a large amount of pixels, the calculator freezes and can't be used or turned off anymore without pressing the reset button on the back.

The bug happens on my calculator with epsilon 12.2.0 ( 0090271 ) and on the online numworks simulator. The code used is shown below.

#### Screenshots
The screenshot looks normal, but none of the buttons work anymore, including the power button and the home button.

![image](https://user-images.githubusercontent.com/50620101/69562441-797ab600-0faf-11ea-92fc-32cfc827ce77.png)

#### To Reproduce (Backup your scripts first!)
1. Go to the 'Python' app
2. Create a new script
3. Type the following code:

```
from math import *
from kandinsky import *

while 1:
  fill_rect(0,0,222,222,color(0,0,0))
```

4. Execute the script (at your own risk)
5. Congratulations! Your calculator is now unusable (until you press the reset button on the back but you will lose all your scripts)

#### Expected behavior
The user should be able to terminate the script by pressing Back or Home on the calculator.

#### Environment
 - Epsilon version: 12.2.0 ( 0090271 )
 - The platform(s) on which the problem happens: online simulator, actual device

**Comment by Ecco** [comment]
That's odd. Shouldn't `micropython_port_vm_hook_loop` be called regularly in this script?

**Comment by carl-vbn** [comment]
Sorry for the late reply.
I haven't completely understood MicroPython yet, so I'm therefore not able to answer your request. 
But anyways, I noticed that this issue doesn't happen with `set_pixel`, so it has to be specific to the `fill_rect` function implementation. 
Maybe something to do with memory management? (I honestly don't have much of a clue)

**Comment by EmilieNumworks** [comment]
`micropython_port_vm_hook_loop` is indeed "regularly" called in `mp_execute_bytecode`. But when calling our module function (`fill_rect` here), we jump inside our kandinsky module and `micropython_port_vm_hook_loop` is not called until we jump back in `mp_execute_bytecode `. This is usually not an issue as modules codes are generally quick to execute. But not always! In the given script, most of the execution time is spent inside `fillRect` function (of Kandinsky module). The script is interruptible but you have to press the `back`button quite a long time... The PR #1229  resolves this case by adding calls to `micropython_port_interrupt_if_needed ` in module functions that are likely to be long to execute.
