### ISSUE TITLE
[Functions][Sequences] Performances scrolling down in table view

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1221]
Whether on the physical or Android calculator, performances are very poor when it comes to scroll down the table displaying the values of a function or a sequence. 
Occurs quite easily as soon as you put an exponential. But even with basic polynomial function of order 2.

Un = n² - 8n + 12 would lead to that for example

**Comment by suazhero** [comment]
In addition, pressing the back button when having just scrolled down with a lag gives you the same lag back to upper tabs selection....

**Comment by suazhero** [comment]
Hi guys, is this taken into account somewhere? Could you acknoledge? This is a real drawback when using the calculator on a daily basis :( especially in senior high option ES in France where quite a number of solutions have to be taken from tables @Ecco @LeaNumworks

**Comment by EmilieNumworks** [comment]
Hi @suazhero, I believe the issue has already been taken care of but the fix was not included in the last stable version 12.4.0. If you compile the firmware from the branch 'master', the problem has disappeared.

**Comment by suazhero** [comment]
Ok thank you. Well i usually wait for the official release but i will probably jump into having the whole environment running. Is having the compiled 'master' branch available an option you would consider in the future? To allow updating the device without having to have the full environment installed?

**Comment by Ecco** [comment]
It's already the case @suazhero ! Just go to the [actions](https://github.com/numworks/epsilon/actions) tab, select the "Continuous Integration" action of whichever commit you'd like to install, then select "Artifacts" in the top-right corner, and download the proper `.dfu` file. Then you can install it using `dfu-util -D file.dfu`.

**Comment by suazhero** [comment]
Oh thx :)
