### ISSUE TITLE
[Bug] Failed to graph second derivative of 3x/2e^x+e^-x

### ISSUE THREAD

**Issue by TheWanderingCoel** [numworks/epsilon#1222]
#### Describe the bug
A clear and concise description of what the bug is. Please describe a **single** bug per issue. Feel free to create multiple issues though!

I used my TI-83 and it's no problem.  
When I use numworks calculator, It stucked at ``plot graph`` button clicked. And after a few minutes, a strange graph was produced.

#### Screenshots

![WX20191127-135149](https://user-images.githubusercontent.com/39617891/69697320-160e9680-111d-11ea-8300-997f52902e59.png)

![WX20191127-135405](https://user-images.githubusercontent.com/39617891/69697435-6c7bd500-111d-11ea-8b46-46996b87c78a.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type '3x/2e^x+e^-x'
3. Click 'plot graph'

#### Expected behavior

Graph correctly

![WX20191127-135618](https://user-images.githubusercontent.com/39617891/69697556-bbc20580-111d-11ea-894c-25547a3a2057.png)

#### Environment
 - Epsilon version (Settings > About > Software version).
 - The platform(s) on which the problem happens: online simulator, actual device, etc...

Both on online and actual device

**Comment by nsajko** [comment]
I tried this on my device (which is on 984d1ff), and this turns out to be not just an issue of the graph being bad, I had to reset my Numworks because it was frozen, neither the back button nor the power button worked while the graph was being "drawn".

**Comment by TheWanderingCoel** [comment]
> I tried this on my device (which is on [984d1ff](https://github.com/numworks/epsilon/commit/984d1ff924e85e111439d1220ed7da4ed192d6ed)), and this turns out to be not just an issue of the graph being bad, I had to reset my Numworks because it was frozen, neither the back button nor the power button worked while the graph was being "drawn".

Same here, you had to reset your calculator otherwise you need wait a long time...

**Comment by suazhero** [comment]
Also occurs with (x^3)/6. Supposed to plot y=x when derivated twice. But plots the following instead
But is it supposed to be supported at all? 

![image](https://user-images.githubusercontent.com/55035114/70997056-6ea9d180-20d4-11ea-9416-82a34ac97eb3.png)

**Comment by TheWanderingCoel** [comment]
It should be supported. But I don't if there was a bug causing graph failure.

**Comment by suazhero** [comment]
There's clearly something weird as soon as function is defined from two times derivatives.
But my point was to understand whether this was still being supported given formal calculus was removed a couple of versions ago.

**Comment by TheWanderingCoel** [comment]
Maybe checkout an old version and compile it for sure?

**Comment by RedGl0w** [comment]
Seems to be fixed with epsilon 15

**Comment by HugoNumworks** [comment]
Indeed, this issue has been resolved by @GabrielNumworks with V-15, probably in [this commit](https://github.com/numworks/epsilon/commit/648cdbaa29222cda1f9fb672bfa95fa8d8a65211).
