### ISSUE TITLE
Exam mode should be reset-proof

### ISSUE THREAD

**Issue by parisseb** [numworks/epsilon#1223]
A quick and dirty fix is to set the calculator in exam mode after reset. After all, reset clears all user data.

At the end of apps/main.cpp, add before `AppsContainer::sharedAppsContainer()->run(); `
 
`
GlobalPreferences::sharedGlobalPreferences()->setExamMode(GlobalPreferences::ExamMode::Activate);
    Ion::LED::setColor(KDColorRed);
    Ion::LED::setBlinking(1000, 0.1f);
`

**Comment by boricj** [comment]
So upgrading the calculator will put it in exam mode? That would be rather silly.

To make the exam mode reset-proof, the proper way would be to store its boolean flag in the RTC backup registers.

**Comment by parisseb** [comment]
Le 27/11/2019 à 21:48, Jean-Baptiste Boric a écrit :
>
> So upgrading the calculator will put it in exam mode? That would be 
> rather silly.
>
Yes, but it's not a real nuisance, since you can reconnect the calc and 
leave exam mode if you upgrade (and I would say that most people do not 
upgrade their calc more than once a year if they even upgrade it...).
>
> To make the exam mode reset-proof, the proper way would be to store 
> its boolean flag in the RTC backup registers.
>

Since I don't know how to do that, I choosed the simplest way to keep 
the calc in exam mode after reset. As I said it's a quick and dirty fix, 
feel free to implement a better fix.

**Comment by carl-vbn** [comment]
So that would mean the calculator would constantly be in exam mode? (starting from the first reset)

**Comment by parisseb** [comment]
No! Plug it, then leave exam mode.

Le 02/12/2019 à 11:31, carl-vbn a écrit :

**Comment by carl-vbn** [comment]
Oh right I forgot you could exit it that way, but since the Led flashes during exam mode, the teacher would notice if it was turned off.
I think it would be a good idea to make the LED blink green when the calculator resets, so anyone attempting to turn it off would get caught pretty easily

**Comment by adriweb** [comment]
You're not supposed to be able to plug the calc to anything during an exam so I'm not sure if there's really an issue?

**Comment by carl-vbn** [comment]
Yeah but you can reset the calculator by inserting a sharp pen into the hole on the back, which disables exam mode

**Comment by parisseb** [comment]
Le 02/12/2019 à 12:43, carl-vbn a écrit :
>
> Yeah but you can reset the calculator by inserting a sharp pen into 
> the hole on the back, which disables exam mode
>
>
That's precisely why I have modified the firmware. If a student press 
reset because a computation takes too long, or if the system resets 
because of a bug, he should not have to restart exam mode (otherwise the 
teacher could suspect a fraud because exam mode is not on).

**Comment by adriweb** [comment]
This issue can be closed since #1239 was merged

**Comment by Ecco** [comment]
Indeed 😄
