### ISSUE TITLE
Notepad

### ISSUE THREAD

**Issue by PierreSC2** [numworks/epsilon#1226]
A thing that might be useful is a simple notepad application, integrated to the calculator, and being able to stock txt files.
Hope it might help
Best regards
Pierre

**Comment by boricj** [comment]
You can already do that with the Python app by deactivating the auto-import script toggle on a script.

**Comment by PierreSC2** [comment]
Ok. Haven't thought about that. Thanks !

**Comment by carl-vbn** [comment]
I don't see any purpose for this if it ain't for cheating to be honest
