### ISSUE TITLE
Error in build documentation for Linux: ./epsilon.elf doesn't exist after build

### ISSUE THREAD

**Issue by mobluse** [numworks/epsilon#1231]
#### Describe the bug
There is an error in the documentation at https://github.com/numworks/epsilon/blob/master/docs/build/index.md
```
$ ./epsilon.elf
bash: ./epsilon.elf: No such file or directory
```
However this works and starts the NUMWORKS simulator:
`$ ./output/release/simulator/linux/epsilon.bin
`

#### Screenshots
N/A

#### To Reproduce
See description above.

#### Expected behavior
The NUMWORKS simulator should start.

#### Environment
 - Epsilon version (Settings > About > Software version): 12.0.0 (I cloned GitHub today so it's strange that this version number is lower than the version for Android that was released earlier: 12.3.0. Is the GitHub source not the latest source?)
 - The platform(s) on which the problem happens: online simulator, actual device, etc...
NumWorks simulator in Raspbian Buster Linux running on Raspberry Pi 4 B.

**Comment by Ecco** [comment]
Indeed. I think we could use a specific target. Maybe `make epsilon_run`?

**Comment by HollMax** [comment]
Just encountered this issue myself. I'd start by updating the documentation to reflect what's happening rather than adding a new target.

**Comment by RedGl0w** [comment]
> Just encountered this issue myself. I'd start by updating the documentation to reflect what's happening rather than adding a new target.

Not a good idea : on macos, it's not in the same location...
It would be more complicated...

**Comment by RedGl0w** [comment]
Closed with https://github.com/numworks/epsilon/commit/80f3af389fc1247c65b124e3f2d7ff83eb6a1e9e#diff-44575cf5b28512d75644bf54a517dcef304ff809fd511747621b4d64f19aac66

**Comment by RedGl0w** [comment]
> Indeed, thanks for the bug report! I think we could use a specific target. Maybe `make epsilon_run`?

This is what was added with epsilon 15 :p

**Comment by LeaNumworks** [comment]
This issue is indeed outdated. Thanks!
