### ISSUE TITLE
Installation instructions soft-brick N0100

### ISSUE THREAD

**Issue by HollMax** [numworks/epsilon#1240]
#### Describe the bug
[Installation instructions](https://www.numworks.com/resources/engineering/software/build/) build and flash an image for the newest model (n0110), with no information about a different image for the older model (n0100).

#### To Reproduce
1. Go to [](https://www.numworks.com/resources/engineering/software/build/)
2. Follow instructions (I used Linux, but it should not be important)
3. Scroll down to '4. Run Epsilon on your calculator'
4. `make epsilon_flash` with an n0100 model connected
5. You now have a bricked n0100

#### Expected behavior
A mention of the `model` make option.

**Comment by Ecco** [comment]
`You now have a bricked n0100` Neither N0100 nor N0110 can be bricked 😄

**Comment by HollMax** [comment]
IDK, I couldn't get it to turn on using the power or reset button, and I wasn't able to flash it again using `make MODEL=n0100 epsilon_flash`, as it wasn't being detected anymore. I was able to flash it using webdfu, which is why I call it only a soft-brick.
