### ISSUE TITLE
Windows 10 SDK latest version 12.4.0 failed

### ISSUE THREAD

**Issue by Flirno** [numworks/epsilon#1246]
Hey,
I recently tried to flash the newest version of epsilon (12.4.0) into my numworks version N0100 but I'm stuck at that step ;

![stuck step flash](https://user-images.githubusercontent.com/34623058/70829166-42006c00-1ded-11ea-9d88-32034d68d8d6.jpg)
I'm doing the RESET manipulation but it seems like Msys2 do not recognize my calculator 

HOWEVER with an older version of epsilon (1.7.0) it worked 

![1 7 0 worked](https://user-images.githubusercontent.com/34623058/70831113-f9977d00-1df1-11ea-9ef5-6ce9e8c39022.jpg)
_(there is some errors but it worked)_

 With this older version, it told me just to press the RESET button, but with the 12.4.0 apparently I should press the 6 key also. Is this because this new version is exclusively flashable on the N0110? I don't know..

So I wonder why this is doing this????
Please help me here :)

I'm on windows 10 64 bits.

**Comment by boricj** [comment]
You've compiled and flashed a firmware for the newer N0110 model. Set the environment variable `MODEL=n0100` when invoking `make` to target the original model.

Pressing the 6 key upon reset will do nothing special with the N0100. It is only required by the N0110 to enter DFU mode upon reset.

**Comment by Flirno** [comment]
Thank you very much for your reply, setting the environment variable MODEL=n0100 indeed seems to have worked **but partly** :/
now I get the correct message that just tells me to press the REST button but after doing that nothing happens again...

![MODEL=n0100](https://user-images.githubusercontent.com/34623058/70847015-b8d64d00-1e5f-11ea-9d3e-22f9a5a37f55.jpg)

I also followed the indication of someone on [Reddit](https://www.reddit.com/r/numworks/comments/ea6gut/windows_sdk_stuck_at_press_at_the_same_time_the_6/) that told me to call the MODEL=0100 apart but this give me this message _"Nothing to be done for 'default'."_ as you can see

any others ideas please?

**Comment by RedGl0w** [comment]
I've got always this issue
The solution I found is to rescue the calculator from the workshop, and then to flash again with `MODEL=n0100`

**Comment by Flirno** [comment]
Hey, do you stop at **the step rescue** :
![20191214_120206](https://user-images.githubusercontent.com/34623058/70847907-4159eb00-1e6a-11ea-9224-a52477bfd8ee.jpg)


Or do you put the newer version on the workshop via chrome?

Because I tried both and none of these 2 cases worked for me :/

**Comment by RedGl0w** [comment]
I go to the end

**Comment by RedGl0w** [comment]
Is it working now? If yes, please close this issue :)

**Comment by RedGl0w** [comment]
Without any news, I think this issue can be closed

**Comment by Ecco** [comment]
I think you're right @RedGl0w . Thanks 😄 

@Flirno , feel free to reopen if you still run into this issue.
