### ISSUE TITLE
Add natural writing input

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#125]
Input in natural writing (using the symbols rather than using a lot of parentheses) is already done for the output, but it would be even more useful in the input, in order to not get lost in expressions with dozens of parentheses.

**Comment by ian-abbott** [comment]
Do you mean like the "MathIO" mode on Casio calculators?

**Comment by Zezombye** [comment]
Yes, "Math" vs "Linear", like this:
[img]http://puu.sh/xyI91.png[/img]

**Comment by adriweb** [comment]
"MathPrint" vs. "Classic" on the TI-82/83/84.
On the TI-Nspire, well, everything is "MathPrint".

**Comment by artaxxx** [comment]
This feature is now available : v 1.5.0
