### ISSUE TITLE
x values not displayed in big tables

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#126]
In Functions: Table
With 3 (or more) displayed functions, navigation in table (want to see h(x) values for example) will hide x column. Quite Annoying.

Solutions:
- Always display x values
- Add a way to freeze or not column display

Enhancement
Software version: 1.1.2

**Comment by artaxxx** [comment]
This is something we plan to do. We chose your first solution.

That would be something like that:

![valeurs](https://user-images.githubusercontent.com/20040032/30379482-ebf27dc2-9896-11e7-8795-1bca9dbc28d1.png)

**Comment by Zezombye** [comment]
Why not shorten the width of the columns? If there are always 7 significative numbers, there is useless space on the left.

**Comment by artaxxx** [comment]
Because it would be the same problem with 3 "functions" columns as you can see on the draft screenshot I enclosed

**Comment by Zezombye** [comment]
Yes but there would be no need to scroll.

**Comment by artaxxx** [comment]
Fixed
