### ISSUE TITLE
Quote masked with \ n or \ t

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1269]
#### Describe the bug
If I add a \ n or \ t in a character string, the quotation mark on the right is hidden.
Is it wanted? Is this a bug?

#### Screenshots
![1](https://user-images.githubusercontent.com/52292872/72112420-d81ca900-333d-11ea-941a-fa7d31c5ee4d.png)
![2](https://user-images.githubusercontent.com/52292872/72112431-e074e400-333d-11ea-97de-26aacdbe6236.png)
![3](https://user-images.githubusercontent.com/52292872/72112434-e36fd480-333d-11ea-8d91-575518d1fce7.png)

#### Environment
The actual latest version of the online simulator (12.3.0)

**Comment by LeaNumworks** [comment]
Hello @A2drien, thanks for reporting this bug! It was also reported in #559.
This \n and \t behaviour is not wanted and should be fixed in the next software update :)

**Comment by RedGl0w** [comment]
This issue also appears when typing `"""""" `

**Comment by LeaNumworks** [comment]
I am closing the issue since this was fixed by 0f52335183a9b842f1a1a
@RedGl0w, the bug does not appear anymore for """"""
