### ISSUE TITLE
Problem with shift + clear in Python shell

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1272]
#### Describe the bug
If I once shift + clear in Python Shell to erase part of a word, then I redo shift + clear, the rest is "erased" but does not disappear.

#### Screenshots
![1](https://user-images.githubusercontent.com/52292872/72174218-7873db80-33d9-11ea-92e5-a462c9a2d12e.png)
![2](https://user-images.githubusercontent.com/52292872/72174226-79a50880-33d9-11ea-99cd-3da1fbbd2d24.png)
![3](https://user-images.githubusercontent.com/52292872/72174238-7f025300-33d9-11ea-8d14-d19619492ebc.png)

#### Environment
 - The latest vesion of the online simulator

**Comment by quentinguidee** [comment]
@boricj 
> Probably a bug in the rect invalidation code, but that's not Omega-specific. File an issue upstream.

**Comment by LeaNumworks** [comment]
Hello @A2drien! Thanks for reporting this bug, it should be displayed in the next update :)

**Comment by RedGl0w** [comment]
I think this issue happens also on probability amp and calculation app with the "en ligne" mode

**Comment by LeaNumworks** [comment]
I am closing the issue since this was fixed by commit 66cf4ed83fd
@RedGl0w, I can't see the bug now in Calculation and in Probability, so I guess it was indeed the same bug!
