### ISSUE TITLE
Inconsistent cursor position in natural mode

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1278]
#### Describe the bug
When typing "sqrt(sqrt(sqrt(i))", the cursor may jump unexpectedly.

#### Screenshots
![screenshot (1)](https://user-images.githubusercontent.com/55989/72826761-70246780-3c47-11ea-868b-21ada8de8702.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type 'sqrt(sqrt(i))', by pressing the square button twice and then the i button
3. Press OK
3. Scroll up, and press OK
4. Press left until the cursor is right before the i.
5. Press "sqrt" : the root is added, but the cursor jumped to the *right* of the i.

#### Expected behavior
The cursor should have stayed on the *left* of the i.

*Note*: The behavior is correct when you type the entire expression straight away by doing the following:
1. Press "sqrt", "sqrt", "i"
2. Press "left", so the cursor is right before the i
3. Press "sqrt" again. At this point, the cursor remains on the left of i.

**Comment by LeaNumworks** [comment]
Hi @Ecco,
Thanks for reporting this bug! The fix will be available in the next update :)

**Comment by LeaNumworks** [comment]
Closing as this was solved by commit 8554bbd8c86389
