### ISSUE TITLE
Absolute value of a square root is not simplified at some point

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1279]
#### Describe the bug
Computing `abs(sqrt(sqrt(sqrt(sqrt(sqrt(i))))))` yields an exact `1`, but `abs(sqrt(sqrt(sqrt(sqrt(sqrt(i))))))` returns an odd result.

#### Screenshots
![screenshot (2)](https://user-images.githubusercontent.com/55989/72827811-76b3de80-3c49-11ea-85bb-0bbf3532a04b.png)

#### Expected behavior
Just `1`, no matter the depth of square roots.

**Comment by EmilieNumworks** [comment]
Hello @Ecco,
The explanation for the difference between `abs(sqrt(sqrt(sqrt(sqrt(sqrt(i))))))` and `abs(sqrt(sqrt(sqrt(sqrt(sqrt(i))))))` behaviours is the following: when simplifying expressions involving complexes, we try to 'bubble up' the Cartesian form a+ib. Doing so, the expression can become quite complicated (especially when simplifying powers, this can insert arctan, sign functions...). If it leads to too "complicated" output, we simplify without trying to keep the cartesian form of the complex (see `Poincare::ComplexCartesian::interruptComputationIfManyNodes`).

So in the first case, the absolute value can be simplified by computing `sqrt(a^2+b^2)` but not in the second case.
![screenshot](https://user-images.githubusercontent.com/31415152/72993845-5d03ca00-3df6-11ea-9bc8-c03edca1a698.png)
![screenshot-2](https://user-images.githubusercontent.com/31415152/72993844-5d03ca00-3df6-11ea-8b6d-b6a622b611a4.png)

But, by implementing rules as:
- |x^y| = |x|^y if y is real
- |x*y| = |x|*|y|
- And by removing the rule `i^(p/q) -> e^(i*Pi*p/2q)` (which is not really used anymore now that complexes are handled through ComplexCartesian class), we can actually simplify `abs(sqrt(sqrt(sqrt(sqrt(sqrt(i))))))` without requiring the cartesian form.

These fixes will be available in the next update!



However,

**Comment by LeaNumworks** [comment]
Closing as this was solved by  1f02e8e381fbca0cba6f2e1cf78b14 and 855cec527f65c7d1a85e4
