### ISSUE TITLE
Problem with f (x) = x! in Function

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1280]
#### Describe the bug
The values of f (x) = x! do not appear in Function => Graph (display undef))

#### Screenshots
![num 1](https://user-images.githubusercontent.com/52292872/72924131-af8aab00-3d50-11ea-9fd4-3313a2049889.png)
![num 2](https://user-images.githubusercontent.com/52292872/72924135-b0bbd800-3d50-11ea-8669-61da15c10559.png)
![num 3](https://user-images.githubusercontent.com/52292872/72924137-b1ed0500-3d50-11ea-9126-6a13d1426325.png)

#### Environment
 - Simulator Online (latest version)

**Comment by EmilieNumworks** [comment]
Hi @A2drien,
The function x -> x! is defined on positive integers only. Plotting a function defined punctually is quite difficult as you have to find specific points in a continuous range.
However, the banner "x= 4, f(x)=undef" is indeed wrong. Thank you for spotting this!

**Comment by artaxxx** [comment]
Fixed in 15.0.0
