### ISSUE TITLE
X * 1234.5 ^ power Bug

### ISSUE THREAD

**Issue by mouzg** [numworks/epsilon#1283]
So if i enter on my X*1234.5 ^ power everything works as it should, at the moment i change it to X1234.5^pow (remove the * sign) it transforms to X1234 *0.5^power.
![screenshot](https://user-images.githubusercontent.com/29000307/73207826-12fc4a80-414e-11ea-98ae-3b6a5122ed5b.png)
[Edit] Actually it has nothing to do with power "^", if i enter a number ending in decimal that starts with a variable without the * sign the number gets interpreted different than it should, if the variable is at the end it works as it should.
![screenshot3](https://user-images.githubusercontent.com/29000307/73216142-1f889f00-415e-11ea-8531-9cf3bcb8a069.png)

it happened on epsilon version 12.0.0 but also in online emulator version 12.3.8

**Comment by nsajko** [comment]
@mouzg 
This is not actually a bug: the misunderstanding arises from the fact that in math classes identifiers of variables are usually single letters. But one may want an indentifier/variable name to be longer than a single letter, and also to potentially include numbers. This is what is happening here: when Epsilon sees `x1234`, it knows that is (part of) a variable name, then the `.` comes, thus the variable name has come to an end, and what follows (`.5`) is a literal number - 0.5, which is implicitly multiplied with the variable `x1234`.

**Comment by RubenNumworks** [comment]
Thank you @mouzg for your feedback. @nsajko explained quite precisely what happens. This behavior conforms to our design. I close this issue but please feel free to comment on or to report in another issue if you would like a different behavior.
