### ISSUE TITLE
Message if none python function in "var"

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1286]
#### Problem you'd like to fix
When you press the var key in Python and you haven't defined a function, it's just empty.
Why not put a text like: "You have not yet defined python functions. Use def Function_Name (): to create one." ?
This is what var does in Calculations with Expressions and / or Empty Functions.

#### Screenshots
![screenshot (10)](https://user-images.githubusercontent.com/52292872/73363526-32f45100-42a9-11ea-93eb-5691493eafbb.png)

**Comment by Ecco** [comment]
That's a good idea. Thanks!

**Comment by artaxxx** [comment]
Fixed in 14.4.0
