### ISSUE TITLE
hardware_test issue when cancelling

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1287]
#### Describe the bug / To Reproduce
When you go to FCC ID, you press 6 to enter in hardware_test, and you cancel, the FCC ID cell stay highlighted (but your cursor move to the first cell)

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/73381874-cab46800-42c6-11ea-9054-aa13d67a77df.png)
![image](https://user-images.githubusercontent.com/43498612/73381909-d6a02a00-42c6-11ea-9bde-67fef953640a.png)

#### Expected behavior
To make the cursor stay at the FCC ID, or to have the cell disabled

#### Environment
 - Epsilon master
 - All

**Comment by LeaNumworks** [comment]
Hello @RedGl0w, thanks for reporting this issue!
It will be fixed in the next update :)

**Comment by LeaNumworks** [comment]
Closing as this was solved by bb2e8ad3c504
