### ISSUE TITLE
Change the "cut" action (shift + "x, n, t")

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1288]
#### Describe the bug
"cut" does the same action as "copy" (shift + var), like Ctrl + C does.

#### Expected behavior
I think it would be better than "cut" does the same action as Ctrl + X.

#### Environment
 - Version 12.3

**Comment by LeaNumworks** [comment]
Hi @A2drien, thanks for creating this issue.
Could you please provide a scenario where cut does not behave like you would expect?

If you are using a compiled version of the current top of master, please note that any odd behaviour might have been corrected by the last commits.

**Comment by A2drien** [comment]
The behavior has not changed if we do "cut" in the history in "Calculation" and the python console in 13.0.0.

![bug1](https://user-images.githubusercontent.com/52292872/74446682-8ef9d080-4e78-11ea-83d1-9a55d12307a5.png)
![bug2](https://user-images.githubusercontent.com/52292872/74446702-94571b00-4e78-11ea-9bd6-202cdf85dc26.png)

(Tested in 13.0.0, screenshots in 12.3 because I don't know how to launch the simulator from Github x))

**Comment by boricj** [comment]
You can't cut content from a Unix or Windows terminal, I don't see why epsilon would allow this for the Calculation and Python app terminals.

**Comment by LeaNumworks** [comment]
As @boricj said, we do not want this kind of behaviour for now in Calculation and Python, because this is not the way other terminals work. You can still copy the lines and then delete them using the Backspace key.
I am closing the issue, but thanks again for the feedback.
