### ISSUE TITLE
It is not possible to interrupt the "Functions" app while it is plotting

### ISSUE THREAD

**Issue by nsajko** [numworks/epsilon#1293]
#### Describe the bug
Providing "Functions" with a function that is hard to plot causes the entire Numworks to, almost, freeze: there does not seem to be a way to interrupt the plotting other than by resetting the Numworks.

#### Screenshots
![screenshotEnter](https://user-images.githubusercontent.com/4944410/73743579-ce247500-4746-11ea-8c5f-67e65667c3e2.png)

#### To Reproduce
1. Go to the Functions app
2. Provide a hard to compute function, like a second derivative of something.
3. Select "Plot graph"
4. Try to interrupt or stop the plotting

#### Expected behavior
Pressing the back button should interrupt the plotting.

#### Environment
 - d146381
 - actual device

**Comment by nsajko** [comment]
Actually, this is not a problem just with second derivatives, it is also a problem with fast-to-compute functions like polynomials, but in slightly different cases: eg., if one wants to scroll 5 times to the right (or left, it does not matter) it is necessary to wait for the graph to be recomputed and redrawn 5 times. This is also annoying.

The same is true of scrolling, panning around, of zooming.

**Comment by RedGl0w** [comment]
Graphing, like calculation can be canceled by using a circuit breaker (the back button for exemple : https://github.com/numworks/epsilon/blob/61399d07eb1bdcc397f8ccf878569e03d8353f95/poincare/src/expression.cpp#L58-L67), but a lot of operators doesn't support the circuit breaker (I don't know why). By adding a few lines in the operator, you can easily make them stops when you press back (exemple : https://youtu.be/JaHZiGmIn2g). You can for exemple, stop the execution of `f(x) = 5x` on epsilon master, but not the `diff()`.

**Comment by artaxxx** [comment]
Fixed in version 16
