### ISSUE TITLE
Quartiles and Interquartile range incorrect. (Only with even number of values)

### ISSUE THREAD

**Issue by abhobe** [numworks/epsilon#1295]
#### Describe the bug
The quartiles in the statistics app are incorrect. The interquartile range is also wrong only because the quartiles are wrong, too. Values: 9, 2, 5, 3, 7, 8, 4, 6 | Sizes: All are 1
[Numworks Answer in brackets] (Correct Answer in Parentheses)
Quartile 1: [3] (3.5)
Median: [5.5] (5.5)
Quartile 3: [7] (7.5)
Interquartile Range: [4] (4)
#### Screenshots
![screenshot](https://user-images.githubusercontent.com/29938963/73790661-af79aa80-4755-11ea-8e41-f0a6ce3405d3.png)
![screenshot (1)](https://user-images.githubusercontent.com/29938963/73790681-b7d1e580-4755-11ea-9d8f-406026b02d61.png)
#### To Reproduce
1. Go to the **Statistics** app
2. Type **Any set of even number of values** (Must be a multiple of 4)
3. Scroll down to **Stats Tab**

#### Expected behavior
I expect the quartiles and interquartile range to be correct.
#### Environment
 - Epsilon version: 12.3.0
 - The platform(s) on which the problem happens: **Online Simulator** and **Revision N100**

**Comment by adriweb** [comment]
Quartiles have various definition depending on the country. For instance France and USA don't have the same. Some calculators offer a setting to use one or the other definition.
See https://github.com/numworks/epsilon/issues/158

**Comment by abhobe** [comment]
Is there a way to change the formatting to the US Format?

**Comment by artaxxx** [comment]
I'm closing this issue because of #158 
We still have this enhancement in mind
