### ISSUE TITLE
Integral calculation

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1299]
I think the following occurs with many other functions. This isn't really serious :(

Obviously expect the result to be 0....
Especially since results are ok when splitting in 2.

![SmartSelect_20200209-101933_NumWorks](https://user-images.githubusercontent.com/55035114/74099627-0c92a900-4b26-11ea-8c26-2d8e659a2dd6.jpg)

![SmartSelect_20200209-101955_NumWorks](https://user-images.githubusercontent.com/55035114/74099633-203e0f80-4b26-11ea-861c-0b90d6105c3a.jpg)

![SmartSelect_20200209-102026_NumWorks](https://user-images.githubusercontent.com/55035114/74099662-4bc0fa00-4b26-11ea-8451-2f62317aa30a.jpg)

**Comment by Ecco** [comment]
That's how approximations work, unfortunately. Closing as I don't think there's anything we could do about this.

**Comment by suazhero** [comment]
Ok. You mean this is how your engine works, right? Does any calculator from competition return such misleading results?

**Comment by Ecco** [comment]
No, I mean this is how *any* non-symbolic engine has to work. Computing an integral using approximations will yield some (hopefully small) errors.

Note that you're complaining about 1E-16 not being zero, but if we write it down fully : `0.0000000000000001`. Hardly a "misleading" result.

Depending on the device/implementation, some other calculators may return an even zero here, but those that don't do CAS will return similar results for some variations of `int(sin(x),x,0,2kπ)`.

**Comment by suazhero** [comment]
Just for the record

![image](https://user-images.githubusercontent.com/55035114/74835416-92300900-531d-11ea-9281-fedde760a2c4.png)

![image](https://user-images.githubusercontent.com/55035114/74835950-b0e2cf80-531e-11ea-9c83-913c66610594.png)

**Comment by nsajko** [comment]
@suazhero There are two things that can cause this "issue".

* Numworks Epsilon currently does not support symbolic computation. This is an important feature for Numworks because the calculator's intended market are students that can only use approved calculators for examinations, and calculators that support symbolic computation are usually not approved.

* Numworks can give more precise results than other calculators. It uses (I think) IEEE 754 floating point representation for rational numbers, which has high accuracy around zero. That is, some other calculator would "round" the result to zero, while Epsilon/Numworks give the user more info. This is definitely a good thing.

However, ...

**Comment by nsajko** [comment]
Maybe Epsilon should have a setting for "Fixed-point" "Result format". That would probably satisfy suazhero.

**Comment by suazhero** [comment]
> @suazhero There are two things that can cause this "issue".
> 
> * Numworks Epsilon currently does not support symbolic computation. This is an important feature for Numworks because the calculator's intended market are students that can only use approved calculators for examinations, and calculators that support symbolic computation are usually not approved.
> * Numworks can give more precise results than other calculators. It uses (I think) IEEE 754 floating point representation for rational numbers, which has high accuracy around zero. That is, some other calculator would "round" the result to zero, while Epsilon/Numworks give the user more info. This is definitely a good thing.
> 
> However, ...

Sounds both indeed. As Ecco explained at least for the first point. 
I'm just sitting in for students who may find it disturbing, although shouldn't be too surprised. 

> Maybe Epsilon should have a setting for "Fixed-point" "Result format". That would probably satisfy suazhero.

Your proposal may fit. Question may be where to stop

**Comment by suazhero** [comment]
Ok I may get what I find inconsistent.
When setting the result format to decimal with 7 significant digits (default, used for the test here), what's the rationale to output the result the way it is? All 7 digits being zeros.
