### ISSUE TITLE
Sans titre, vous comprenez déjà

### ISSUE THREAD

**Issue by quentinguidee** [numworks/epsilon#1302]
Bonjour Numworks <3 !

Dans Omega, nous passons un temps assez conséquent à respecter les modes examens des différents pays. Certaines personnes de notre communauté lisent les textes de loi pour vérifier que tout reste légal. Nous passons un temps conséquent à rester fidèle à votre entreprise et à vos choix, et notre communauté vous livre des dizaines d'issues découvertes dans le cadre des beta test Omega. Nous refusons aussi toutes demandes de modification du firmware à des fins de triche, et bannissons de notre communauté ceux-ci.

Je comprends très bien votre peur. Mais à cause du fichier CC BY-NC-ND (pas besoin de vous montrer lequel), une personne qui compile avec `make epsilon.official.dfu` et qui tape le mot clé `yes` juste après peut aisément tricher, car nous ne sommes plus en mesure d'ajouter notre précieux mode examen "sans symbolique (+ blocage de certaines apps)" que nous avions. Ne serait-ce pas un peu se tirer une balle dans le pied ?

Nous aidons des profs (qui veulent faire passer leur classe complète à Omega), des élèves (qui sautent sur l'occasion de rejoindre notre communauté), de jeunes développeurs (qui rêvent d'apprendre à développer grâce à votre firmware), de plus grands développeurs (qui aimeraient faire vivre leurs modifications sur un firmware unique). On a regroupé les personnes les plus fans de votre calculatrice sur Omega. Je souhaitais garder un fork refusant toute triche, peu importe le pays, dans le respect de vos choix. Mais un fichier sous cette licence risque de nous empêcher de bloquer des fonctionnalités dans certains modes examens.

J'en profite pour vous dire que si vous avez tout problème contre moi, mon mail est ouvert et se trouve sur mon compte GitHub.

Quentin — Omega

**Comment by Ecco** [comment]
Bonjour @quentinguidee 

Vous n'avez peut-être pas bien compris la raison et l'impact de la modification que nous avons apportée à ce sujet.

Concrètement le seul fichier sous licence CC BY-NC-ND que nous avons rajouté concerne le mode examen Hollandais. Il faut savoir que pour être conforme au mode examen Hollandais, une build précise d'un firmware donné doit être testée et approuvée manuellement par un organisme d'état, en collaboration avec le constructeur. Par conséquent, tout firmware tiers est _de facto_  non-conforme, et toute personne le distribuant se rendrait donc responsable de complicité de fraude à un examen.

C'est pour protéger les forks de cet épineux problème que nous avons explicité la non-possibilité de redistribution de ce fichier. Et d'ailleurs les builds faites par défaut n'utilisent pas ce fichier et gardent un comportement identique à ce qui était fait dans la version précédente.

Par ailleurs, le reste du code est totalement inchangé, que ce soit en termes de license ou de fonctionnalité. Ce qui était possible avant le demeure, et qui ne l'était pas aussi.

J'espère avoir répondu à vos inquiétude.

**Comment by quentinguidee** [comment]
Bonjour @Ecco 

Merci pour votre réponse. Je comprends bien. Si tel est le cas, j'aimerais dès lors vous demander des conseils par rapport à la suite de notre fork, pour être sûr d'être en accord.

Premièrement, vous nous conseillez dès lors de retirer le mode examen Dutch ? (si jamais il n'est pas retiré par défaut ; je n'ai pas encore bien eu le temps de tester)

Ensuite, le message qui apparait dans la version/about m'a l'air extrêmement handicapant pour des élèves français. Nous en avons discuté avec certaines personnes mieux placées que moi pour en juger, et nous ont conseillé de retirer le message.... Seulement, vous le savez, je n'ai pas envie d'aller à l'encontre de vos choix. Ce message ne vise justement que les examens "Dutch" ? Si **oui**, ne pouvons-nous pas le modifier en ce sens dans notre fork ? Quelque chose du type "Logiciel incompatible avec le mode examen des Pays-Bas" ? Si **non**, ne peut-on pas nous entendre sur quelque chose de moins "violent" ? J'ai très peur que des élèves totalement innocents ne se fassent recaler par ce message. Nous combattons autant que vous la triche, et ce serait vraiment handicapant. Par ailleurs, on observe clairement que notre interface est très différente, pour justement éviter la triche. Mais ce message, si j'étais prof, me fait dire "que le mode examen a été trafiqué"... Nous pouvons aussi laisser le message tel qu'il est sur GitHub et le modifier dans nos binpacks. Je vous laisse libre choix ; mais ce message fait peur à beaucoup d'entre nous.

Merci beaucoup!

Quentin — Omega

**Comment by Ecco** [comment]
Rebonjour @quentinguidee 

> Premièrement, vous nous conseillez dès lors de retirer le mode examen Dutch ?

Très vivement, le plus rapidement possible. Vous vous rendriez de fait et indiscutablement responsable de fraude au Pays-Bas le cas échant…

>  (si jamais il n'est pas retiré par défaut ; je n'ai pas encore bien eu le temps de tester)

Justement, il l'est ! C'est précisément pour cette raison que nous avons créé une cible secondaire avec confirmation explicite.

> le message qui apparait dans la exam_mode/about message (...) ne vise justement que les examens "Dutch" ?

Non, il vise tout mode examen.

>  (ce message) m'a l'air extrêmement handicapant pour des élèves français.

Je comprends votre inquiétude, mais cela nous a semblé un mal nécessaire.

En pratique, selon la license d'Epsilon, vous avez le droit de supprimer cette mention sur un firmware que vous redistribueriez. Mais néanmoins nous vous le déconseillons **très formellement**, car la license n'est tout simplement pas le sujet.

Le problème, c'est qu'en distribuant un firmware, vous engagez votre responsabilité. Que se passe-t-il par exemple si le logiciel que vous avez distribué entraine un problème pendant un examen ? Vous pourriez être personnellement poursuivi…

De notre côté nous engageons notre responsabilité sur les logiciels que nous livrons, mais ne pouvons évidemment pas garantir ceux modifiés par des tiers (sans préjuger de la qualité des modifications apportées, entendons-nous bien). C'est pourquoi il nous a semblé indispensable d'ajouter un message en ce sens.

Notre recommandation serait donc de **laisser la mention en place et de l'augmenter** pour dire que "ni NumWorks, ni \<autre auteur\>" ne garantissent la conformité.

Si malgré tout vous souhaitez engager votre propre responsabilité, libre à vous. Je vous invite néanmoins dans ce cas à laisser la mention en place car, en faisant le choix de la supprimer, vous laisseriez croire que NumWorks engage la sienne, ce qui n'est pas la cas. Et l'on pourrait également vous reprocher de chercher à dissimuler des modifications. Deux points qui vous exposeraient à nouveau…

Concernant les élèves enfin, ce n'est pas parce que la conformité d'un logiciel n'est pas garantie qu'il ne l'est pas dans les faits. Chacun est libre d'utiliser le matériel qu'il souhaite et de prendre ses propres responsabilités face à la règlementation. Vous remarquerez que le message ne dit en aucun cas que le mode examen (d'un logiciel tiers) est incompatible avec la règlementation : il dit simplement que NumWorks ne garantie pas sa compatibilité. C'est extrêmement différent !

**Comment by parisseb** [comment]
Le risque est quand meme important que suite aux bugs du mode examen sur d'autres modeles, les regles se rigidifient, par exemple que soit exigee des versions clairement identifiees de firmware.
Cela va donc etre une question de confiance entre l'education nationale et les auteurs de firmware tiers (ayant une bonne visibilite sur Internet, je pense a Omega ou/et Delta + KhiCAS). La question risque donc de se poser d'un possible hebergement de firmwares tiers chez Numworks sans pour autant engager la responsabilite de Numworks sur les modifications apportees, car cela donnerait certainement confiance a l'institution question tracabilite (et assurerait l'egalite d'acces pour les candidats a un examen). Numworks serait-il favorable a une telle idee (une fois les questions legales de rediffusion resolues, personnellement par exemple je pense pouvoir obtenir des detenteurs des droits patrimoniaux sur KhiCAS l'autorisation de le diffuser comme firmware tiers, i.e. non installe sur les calculatrices vendues) ?
