### ISSUE TITLE
Missing an onkeypress event in python editor.

### ISSUE THREAD

**Issue by lucasdeman** [numworks/epsilon#1305]
When I want to make a game (like flappy bird) in the python editor I ran into a problem.  There is no function to get which key is pressed in real time. I would recommend a "onkeypress"- function in which you can also get what key was pressed.

**Comment by Ecco** [comment]
It's here already, as`ion.keydown`. See #1201
Note that it will be made available in version 13 which hasn't been released to the public just yet.
