### ISSUE TITLE
To be able to convert time period and frequency to distance

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1307]
#### Problem you'd like to fix
The unit converter is great, but it is impossible to convert units of distance to frequency and time and vice versa.

#### Describe the solution you'd like
There is the formula λ = v / f and λ = v × T, with λ which is the length of wave, v which is the speed of light (c for the French) (= 3.00 × 10**8), f which is the frequency of the wave and T which is the time period (in seconds).

#### Describe alternatives you've considered
"What we type on the calculator"          =              "Result returned"                (= which corresponds to)
            (distance λ)_m➔_Hz                   =    (3.00 × 10**8 / distance λ)  _Hz       (= frequency f)
            (frequency f)_Hz➔_m                 =    (3.00 × 10**8 / frequency f) _m       (= distance λ)
              (distance λ)_m➔_s                   =    (distance λ / 3.00 × 10**8) _s          (= time period T)
            (time period T)_s➔_m                =   (3.00 × 10**8 × time period T)_m    (= distance λ)

**Comment by Ecco** [comment]
Wat?

**Comment by RubenNumworks** [comment]
Aren't you assuming that the speed in the formula `distance = duration * speed` should always be equal to the speed of light in vacuum?

**Comment by Ecco** [comment]
Well, of course, wavelength and period are linked for **one given celerity**. However like @RubenNumworks said, the actual celerity of the wave is dependent on a bunch of factors, such as the kind of wave (light, sound, ripple, etc…) and whatever it's propagating in (vacuum, water, metal, etc…).

Long story short, there's just no way to convert a time to a distance without any extra context.

I think you'll simply want to do store the celerity of your wave in a constant (e.g. `300000_m/s->v`, and then input `3_m/v` to get the resulting period 😄
