### ISSUE TITLE
Numpy support

### ISSUE THREAD

**Issue by loretoparisi** [numworks/epsilon#1310]
#### Problem you'd like to fix
Enhanced support for N-dimensional arrays calculation.

#### Describe the solution you'd like
Add support as a library to [Numpy](https://numpy.org/). At least in the SDK, so that developers could optionally build a sdk branch with numpy included.

#### Describe alternatives you've considered
At this time there is no comparable alternative to Numpy in Python.

#### Additional context
To operate n-dimensional arrays on the calculator, would help to build simple machine learning and neural network based algorithms (from Gradient Descend implementation of Loss and Activation functions).

**Comment by nsajko** [comment]
Numpy is probably impossible, but maybe this could fit: https://github.com/v923z/micropython-ulab

**Comment by loretoparisi** [comment]
@nsajko Amazing! I was not aware about ulab! That would be a great starting point!

**Comment by KaiJan57** [comment]
I actually habe a pending pull request for Omega (which is a fork of epsilon that extends its features): [Pull request](https://github.com/Omega-Numworks/Omega/pull/294)

**Comment by artaxxx** [comment]
Fixed

**Comment by loretoparisi** [comment]
> Enhanced support for N-dimensional arrays calculation.

Amazing news! Will it come in the next release?

**Comment by RedGl0w** [comment]
> Amazing news! Will it come in the next release?

Already avaible in the beta of version 21
