### ISSUE TITLE
[Python] Input always returns ""

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon#1315]
#### Describe the bug
When using input in python, it always returns an empty string, no matter what we write

#### Screenshots
![Peek 19-02-2020 09-48](https://user-images.githubusercontent.com/57234558/74817384-1756f600-52fd-11ea-94f7-a5f32189039b.gif)

#### To Reproduce
1. Go to code app
2. Open python, shell
3. Type `input()`
4. input something

#### Expected behavior
We should get back what we inputted

#### Environment
 - Epsilon version 1.13.0 (latest master, commit 269305)
 - The platform(s) on which the problem happens: n0110, n0100, all simulators

**Comment by LeaNumworks** [comment]
Hi @M4xi1m3, thanks a lot for catching this! It should be solved by #1320.
