### ISSUE TITLE
[Python] Back doesn't have any effect in while True loop.

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon#1316]
#### Describe the bug
Pressing back while in an infinite loop doesn't exit the program

#### Screenshots
![ezgif-6-841ed56a5d2f](https://user-images.githubusercontent.com/57234558/74818424-e7105700-52fe-11ea-9890-eeae16c87944.gif)

#### To Reproduce
1. Go to the code app
2. Create new script
```python
while True:
  print("test")
```
3. Run the script
4. Try pressing back

#### Expected behavior
The script should be exited with a KeyboardInterrupt. You have to reset the calculator to exit.

#### Environment
 - Epsilon version 1.13.0 (latest master, commit 269305)
 - The platform(s) on which the problem happens: n0110, n0100, all simulators

**Comment by Tim-ats-d** [comment]
If you spam the back button, at some point, you will exit the program.

**Comment by nsajko** [comment]
The fix for this is probably highly related to the fix for #1293.

**Comment by LeaNumworks** [comment]
Hi @M4xi1m3, thanks for spotting this!
The PR #1321 should fix it.

@nsajko, the interruption process is not the same in the Python app and for mathematical processing, so unfortunately #1293 won't be fixed by this PR.
