### ISSUE TITLE
Display the shortest fraction corresponding to an approximation

### ISSUE THREAD

**Issue by Nawor3565** [numworks/epsilon#1329]
#### Describe the bug
When squaring a repeating decimal, the calculator can sometimes give very odd results.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/19783632/74973740-f91ef200-53f1-11ea-9436-10d034503aee.png)

#### To Reproduce
1. Calculate "0.5(-2/3). The calculator will correctly give the answer -0.333... with the equivalent fraction of -1/3
2. Calculate "ans^2"
3. The calculator will interpret "ans" as "-3.3333333333333e-1"
4. While the answer of 0.1111111 is correct, the calculator doesn't understand that the decimal should be repeating, and so it says that the equivalent fraction is a ridiculously long number instead of simply 1/9.

#### Expected behavior
For the calculator to understand that the decimal is repeating, and give the same answer as "(-1/3)^2

#### Environment
Happens on both the actual hardware and emulator.

**Comment by nsajko** [comment]
A data point: everything works as expected if `1/2` instead of `0.5`. This is probably just a documentation bug; I am guessing Epsilon tries to represent numbers as rations only if no part of the input is in the floating point form?

**Comment by Ecco** [comment]
Thanks for reporting this @Nawor3565 ! This behavior doesn't have anything to do with squaring, so I'm changing the title.

Indeed your example can be simplified a lot: just type `1/3` then select the approximation and press enter. Then press the up arrow to select it.

![screenshot (1)](https://user-images.githubusercontent.com/55989/74989013-52e0e580-540d-11ea-9648-374ff9262377.png)

What you're seeing here isn't an error. Indeed,  `0.333` is exactly `333/1000`, *not* `1/3`.

That being said, given we display an `≈` sign, we could try to find a shorter approximation. I'm tagging this as an improvement request.

**Comment by Nawor3565** [comment]
Thanks for the reply. Displaying a shorter approximation would definitely help, but would it not make more sense to change the "ans" function so that it uses the fractional equivalent of the previous answer, instead of using the decimal approximation? Not only would that avoid weird problems such as this one, but by not using approximations, it should provide more accurate results.

**Comment by nsajko** [comment]
@Ecco What exactly are you proposing/promising/announcing? You say:

> find a shorter approximation

Is that referring to the representation of the result as a ration (to the left)?

In any case;

* "less precision" seems to follow from "shorter approximation"

* "find" (from "find a shorter approximation") maybe implies some kind of problem whose solving at run time could slow down Epsilon

Thus I think it would be better to put that feature behind an option in the settings?

**Comment by nsajko** [comment]
@Nawor3565 

> would it not make more sense to change the "ans" function so that it uses the fractional equivalent of the previous answer

That would not help. What you really want is for Epsilon to convert all floats that it lexes to rationals, before calculation. This is probably not a good idea as it would slow things down, at it would rarely help with anything.

**Comment by Nawor3565** [comment]
@nsajko You're right that the problem only manifests when you combine a decimal and a fraction. In the example above, it would be easy to use "1/2" instead of "0.5", but there are certainly situations where it is far easier to type a decimal than a fraction. What I propose is that the calculation use the equivalent fraction that was already calculated along with the answer for the "ans" key.

To clarify, in the first example, the calculator knows that "0.5(-2/3)" is equivalent to "-1/3". However, for some reason, the "ans" key takes the _approximate_ -0.3333333 to do the following calculation, instead of just using the fraction, which isn't approximate. It just seems silly for the "ans" key to use the, by definition, less precise option, and it seems unintentional since the problem doesn't occur unless you use a decimal to begin with.

**Comment by nsajko** [comment]
I failed to realize Epsilon actually knows the first expression is exactly equal to -1/3. Anyway, that should maybe be a separate bug report, since echo changed this one's title.

**Comment by Nawor3565** [comment]
@nsajko I agree, this a legitimate bug because it's using the rounded approximation for the calculations when it could just as easily use the non-approximate fractions. I opened #1330 instead, hopefully I was able to better describe the problem in that issue.

**Comment by RubenNumworks** [comment]
Related to https://github.com/numworks/epsilon/issues/887#issuecomment-460130431

**Comment by artaxxx** [comment]
Actually this is the same issue than #1330 and the answer is the same
