### ISSUE TITLE
Add conversion from/to bin, oct, dec, hex

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#133]
For engineering, these conversions could be useful. Also allow binary operators (and, or, not, xor, xnor...).

**Comment by adriweb** [comment]
Or rather, arbitrary base conversion. But some useful shortcuts like other calculators have.
For instance with a base prefix + conversion suffix/helper: `0b0101110▶Base16` on the Nspire, but it could also be `toHex(...)`.

**Comment by ian-abbott** [comment]
This is as good a place as any to discuss possible input and display formats for hexadecimal, octal, and binary numbers. A prefix starting with a `0`, such as `0h` for hexadecimal might be a bit ambiguous, so how about `:h` or `?h` as a hexadecimal prefix?

**Comment by boricj** [comment]
Given poincare's available symbols in its lexer and the NumWorks keyboard, we could use the format `xxxx_yy`, where `100_16` = `100_h` = 256 and pretty-print it to ![equation](http://www.sciweavers.org/tex2img.php?eq=100_%7B16%7D&bc=White&fc=Black&im=png&fs=10&ff=arev&edit=0). Then, typing `ans_2` would print ![equation](http://www.sciweavers.org/tex2img.php?eq=100000000_2&bc=White&fc=Black&im=png&fs=10&ff=arev&edit=0). Like angles, a radix unit in the settings app would specify the default radix.

**Comment by ian-abbott** [comment]
@boricj There would be more back-tracking in the input parsing that way. In order to prevent `10A2_16` being parsed as `10*A*2_16` (with implicit multiplication), there would need to be greedy backtracking to reparse the previous hex digits that have already been parsed as something else.

**Comment by boricj** [comment]
Not unless hex input is restricted to lowercase. Which would be easier to input anyways on the real calculator.

**Comment by RedGl0w** [comment]
This issue can be closed since https://github.com/numworks/epsilon/commit/7c2ef5847b81141525320880c289f893a598491f

**Comment by boricj** [comment]
@RedGl0w Octal is missing IRRC.

**Comment by Ecco** [comment]
@boricj So is base 47 😄 

I'm going to close this issue since most of it has been addressed. Feel free to open new issues if needed .

**Comment by debrouxl** [comment]
Well, handling octal in upstream would be easy and take little space, given that the framework for base conversion is already fully operational ;)
I recentely and infrequently needed octal conversions, to investigate WTF happened for some Linux files to have mode 1363. Yup, it was decimal 755 instead of octal 755. I did the computation by hand, but with octal support, I could have used my NumWorks calculator to perform the computation... oh wait, I don't have one :)

**Comment by Ecco** [comment]
> Well, handling octal in upstream would be easy and take little space, given that the framework for base conversion is already fully operational ;)

Yes, you're right, it wouldn't be a lot of work to support octal numbers. But they're *very* uncommon! I don't think I've ever seen anyone using them outside of UNIX file permissions…

Another problem with octal numbers is their input. `0x123` and `0b101` are pretty common ways to input hex/bin numbers, and I don't think this notation conflicts with anything else. When someone types `0x123`, I think we can be fairly confident they meant `291`. But the common way to input octal numbers is to prefix them with a zero, and I'm positive that parsing `012` as `10` would confuse a bunch of people.

**Comment by debrouxl** [comment]
Maybe a `0o` prefix for octal numbers ? I saw that somewhere, probably to avoid puzzling users the way you described.
