### ISSUE TITLE
When using both decimals and fractions, the "ans" key will use the decimal approximation of the previous answer, instead of the equivalent fraction.

### ISSUE THREAD

**Issue by Nawor3565** [numworks/epsilon#1330]
#### Describe the bug
When the previous calculation resulted in a fraction with a repeating decimal, using the "ans" key will take the imprecise decimal approximation instead of simply using the fraction itself. This would appear to be unintentional, as you get the expected behavior if you use only fractions.

#### Screenshots
![1screenshot](https://user-images.githubusercontent.com/19783632/74994929-6c8a2900-541d-11ea-8987-c2e87b778357.png)
![2screenshot](https://user-images.githubusercontent.com/19783632/74994931-6dbb5600-541d-11ea-8583-8b3e3082e518.png)
![3screenshot](https://user-images.githubusercontent.com/19783632/74994938-6f851980-541d-11ea-9709-83494c520c3f.png)

#### To Reproduce
1. Calculate `0.5(1/3)`, the calculator will say that the answer is aprox. 0.1666667. Press `up` to see that the exact answer is actually `1/6`.
2. Calculate `ans*2`. Press up to see that the exact answer is not simply `1/3`, but is a very long (and incorrect) fraction instead. This is because the `ans` key used the rounded approximation of `1/6`, instead of simply using the fraction itself.

#### Expected behavior
After multiplying the previous answer by 2, the result should have been `1/3`. You get the correct behavior when you do the same calculation, but use the fractional representation of "one half" instead of the decimal representation.

![4screenshot](https://user-images.githubusercontent.com/19783632/74995325-8ed07680-541e-11ea-872b-cd33cb77393e.png)
![5screenshot](https://user-images.githubusercontent.com/19783632/74995326-9132d080-541e-11ea-909f-9e45c160071c.png)
![6screenshot](https://user-images.githubusercontent.com/19783632/74995327-92fc9400-541e-11ea-9721-2df080e1709c.png)

#### Environment
Happens with version 12.0.0 on both hardware and emulator.

**Comment by nsajko** [comment]
Also happens on 13.0.0 (80c0322).

**Comment by Ecco** [comment]
Well, `Ans` is short for answer, so it's only logical we re-use the last *answer*, isn't it?

**Comment by nsajko** [comment]
@Ecco The "main" answer is floating-point, but notice how to the left of it an exact answer as a fraction is also given. It would be better to use that ratio(nal)/fraction in continued calculation, if possible.

**Comment by suazhero** [comment]
I would expect the result to be decimal & approximated as long as it was input this way.
The fraction right next to it is a best guess and an indication that's added to give an idea.

To keep it consistent and not confusing especially in students minds, the rule should be simple: You input decimal values, you stick to decimal results. You input fractions, you stick to fractions results.

And ans should take what's been computed according to the input, which matches the behaviour i described.

**Comment by EmilieNumworks** [comment]
The intended (and current) behaviour is exactly what @suazhero just said; we display the decimal value as the main result as soon as one decimal value was given as input. Similarly, 'ans' stores the decimal result as soon as the input involves any decimal value.

**Comment by nsajko** [comment]
Sure, it makes sense that the main result would be a decimal approximation, but the other (exact) result is already computed; so why not use it in continued calculation (with Ans)? What is the downside?

**Comment by suazhero** [comment]
Is it really computed? Or only approximated when highlighting result? 
And if compted already, good idea. Downside? Memory?

**Comment by artaxxx** [comment]
The intention is to be consistent with the input. I couldn't have said any better than @suazhero did. Decimal inputs are most often used in physics where you want to get a decimal result. We provide the exact one in case you needed it. But it is not displayed by default. This is the same for the "ans" key. It takes the main result (which is approximated here) and if you want to use the exact one, just select it and press OK.
