### ISSUE TITLE
Pressing an arrow key quickly enough after some other key can cause it to be misinterpreted

### ISSUE THREAD

**Issue by nsajko** [numworks/epsilon#1331]
#### Describe the bug
To expand on the title, the arrow key that is pressed instead causes an action as if another key was pressed. I have had this happen in both "Calculation" (LEFT gets interpreted as UP) and "Settings" (DOWN gets interpreted as OK) apps.

I think it is not a hardware issue, though, because the interval that causes the bug to manifest is sometimes quite long, I think (very approximately) about half a second is sometimes short enough for the keys to be confused by Numworks.

#### Screenshots
Not applicable.

#### To Reproduce
1. Go to the Settings app.
2. Start repeatedly and quite frequently pressing the DOWN key
4. See error: one of the menu items will be selected.

#### Expected behavior
Pressing a key should act as expected.

#### Environment
 - Epsilon version 13.0.0 80c0322
 - The platform(s) on which the problem happens: Numworks device

**Comment by Ecco** [comment]
This is most likely due to the fact that this is how d-pads work. It can happen that you pressed "Up" aiming for "Left", and "Right" aiming for "Down" (note that "Right" acts as "OK" in the Settings app).

I'm closing this as this is a hardware consideration.

**Comment by nsajko** [comment]
@Ecco 

It seems a video is necessary: https://drive.google.com/open?id=1I2m1H1spRNSldnGAIs_RI8YzrjJvL3MY

There are a couple of manifestations of the bug in the video. I think the first one comes up after 0:28.

I took extra care to keep my finger on the bottom-most part of the d-pad bottom key, so there would be no confusion as to which key was pressed.

**Comment by Ecco** [comment]
Thanks for the video @nsajko 😄 

Definitely **not** a software issue. Actually you don't even need to jam the key: depending on how you angle your finger and force, you can definitely make a "Down + Right" keypress by touching only the lower part of the D-pad. This is how D-pads are supposed to work.
