### ISSUE TITLE
Warning when building python

### ISSUE THREAD

**Issue by NicoloZorzetto** [numworks/epsilon#1342]
#### Describe the bug
I am running MacOS Catalina, with python3 as default. When I run 'make' I get a bunch of python errors.

#### Screenshots
<img width="1680" alt="Schermata 2020-02-21 alle 7 30 30 PM" src="https://user-images.githubusercontent.com/56208253/75061270-acfeab00-54e0-11ea-8a20-cb010fdc19d5.png">

#### To Reproduce
1. run 'make'

#### Expected behavior
It shouldn't give errors, I think

#### Environment
 - Epsilon master branch
 - MacOS Catalina and zsh

**Comment by adriweb** [comment]
Those are warnings, not errors.

**Comment by NicoloZorzetto** [comment]
> Those are warnings, not errors (and it's in external code).

thanks. I will now close the issue. I have opened another one for flashing not starting, if you could have a look at that it would be awesome

**Comment by nsajko** [comment]
I think this is fixed in the next micropython release.

**Comment by Ecco** [comment]
It is an interesting warning though. Reopening.

**Comment by RedGl0w** [comment]
It seems that's it's not patch on mpy 1.12
```
python/src/py/scope.c:36:22: attention: la conversion non-signée de « int » vers « unsigned char » change la valeur de « 293 » en « 37 » [-Woverflow]
   36 |     [SCOPE_LAMBDA] = MP_QSTR__lt_lambda_gt_,
      |                      ^~~~~~~~~~~~~~~~~~~~~~
python/src/py/scope.c:37:25: attention: la conversion non-signée de « int » vers « unsigned char » change la valeur de « 294 » en « 38 » [-Woverflow]
   37 |     [SCOPE_LIST_COMP] = MP_QSTR__lt_listcomp_gt_,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
python/src/py/scope.c:38:25: attention: la conversion non-signée de « int » vers « unsigned char » change la valeur de « 295 » en « 39 » [-Woverflow]
   38 |     [SCOPE_DICT_COMP] = MP_QSTR__lt_dictcomp_gt_,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
python/src/py/scope.c:39:24: attention: la conversion non-signée de « int » vers « unsigned char » change la valeur de « 296 » en « 40 » [-Woverflow]
   39 |     [SCOPE_SET_COMP] = MP_QSTR__lt_setcomp_gt_,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
python/src/py/scope.c:40:24: attention: la conversion non-signée de « int » vers « unsigned char » change la valeur de « 297 » en « 41 » [-Woverflow]
   40 |     [SCOPE_GEN_EXPR] = MP_QSTR__lt_genexpr_gt_,
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
```
Tested with epsilon master (and mpy updated 
![image](https://user-images.githubusercontent.com/43498612/78988844-5140bd80-7b32-11ea-8fe3-a7ecd2db58bf.png)
