### ISSUE TITLE
Dutch interface?

### ISSUE THREAD

**Issue by moorlag** [numworks/epsilon#1348]
#### Problem you'd like to fix
The next version of Epsilon could use a Dutch interface. It's missing and students need to focus on math. Not on the English version of a concept and then translating it into Dutch. The cognitive load needs to be directed to understanding Math, computational thinking and digital literacy. 

#### Screenshots
![numworks_nl](https://user-images.githubusercontent.com/2832006/75113192-ddaf2380-564b-11ea-8ecd-c53fad4d04ce.jpg)

#### Describe the solution you'd like
Translating the interface into Dutch, in line with the Dutch version of the website. I've added a Dutch version of the boot screen /sarcasm

**Comment by Ecco** [comment]
@moorlag I think you overlooked an [major item](https://en.wikipedia.org/wiki/Gouda_cheese#/media/File:WikiCheese_-_Gouda_36_mois_03.jpg) in your boot screen 😄

**Comment by moorlag** [comment]
@Ecco Cheese is going to be in the -second- Dutch update.

**Comment by artaxxx** [comment]
Het is klaar! (version 14.4.0)
