### ISSUE TITLE
Why use an out-of-date OpenBSD math library? Epsilon should use a better library for math.

### ISSUE THREAD

**Issue by nsajko** [numworks/epsilon#1370]
Currently Numworks Epsilon uses an ancient OpenBSD revision libm. This is a quite perplexing choice, seemingly because supposedly:

> This version still has all the double function (and not the long-double ones). And apart from this, it's virtually identical to the 6.0 code.

(See 3adc5d9fac733fe04a4739b10cd2da616a0ebd0f.)

But the current OpenBSD libm does, in fact, implement both double and long double (not to mention float) versions of math functions! Some clarification is needed here. Which double implementations are missing? @Ecco 

Apart from the out-of-datedness, the very choice of using the OpenBSD libm seems sub-optimal, crucially so for a calculator. OpenBSD's and FreeBSD's libm and msun are, AFAIK, both based on the same code. The difference is that the FreeBSD project develops their math library much more, with OpenBSD's most real changes to their libm being imports from FreeBSD. But, OpenBSD only sometimes and irregularly synchronizes with FreeBSD!

Another project that is based on FreeBSD's math library is openlibm, but they, too, have not kept up with FreeBSD.

Apart from FreeBSD's msun, an option is to use musl's math library. Or maybe ARM's, not sure how complete or correct it is, but musl incorporated some of their work, so it must be good.

See https://github.com/numworks/epsilon/pull/1343#discussion_r384495973 for an example of an OpenBSD math bug.

Links:

* https://github.com/ARM-software/optimized-routines/tree/master/math

* https://git.musl-libc.org/cgit/musl/log/src/math

* https://github.com/openbsd/src/tree/master/lib/libm/src

* https://github.com/JuliaMath/openlibm

* https://github.com/freebsd/freebsd/tree/master/lib/msun/src

**Comment by Ecco** [comment]
I think we did consider all those libm, and eventually reached the following conclusions:
* They're all extremely similar. Sure some are more "maintained", but from what we saw the maintenance was essentially coding style related.
* Because our hardware has a SP FPU, we need an implementation that *natively* supports both 32 and 64 bits floats. We would use the 32 bit version for speed and the 64 bit version for accuracy.

From our experience so far the libm implementation we use seems do be doing a great job.

If not, would you mind sharing some examples where it would fail from a user's standpoint?

**Comment by nsajko** [comment]
I could not find any liba deficiencies that would trip up an end-user currently, but note that

* That is hard to do, thus QA is a profession.

* Leaving liba as is could backfire at any time, even just a compiler update could trigger a "miscompilation" because of all the tiny UBs that the OpenBSD guys are not fixing even now. 

* There are performance improvements available. By choosing implementations with differring algorithms, or by stuff like sincos.

**Comment by Ecco** [comment]
Hi @nsajko,

Indeed, there might be better libm available around. That being said, we haven't found one that fully supports single (32 bits) and double (64 bits) precisions floating numbers.

I'm going to close this issue, but feel free to reopen if you have a better candidate that supports 32 and 64 bits floats or if you find an actual problem with the current libm 😄
