### ISSUE TITLE
Complex atanh loses imaginary part of result

### ISSUE THREAD

**Issue by nsajko** [numworks/epsilon#1373]
#### Describe the bug
See the screenshot, the result is shown as a real number (note that the number does correctly correspond to both real(atanh(given input)) and to atanh(real(given input))). Considering Calculation uses double precision floating point/binary64 (which can represent numbers like 1e-320) and imag(correct result) is approximately 5.0e-16, this is a significant error.

Comparisons with C++ standard library (GNU) and Go(lang) standard library, which are to be expected to give similar results as Numworks Epsilon considering all of them use binary64, are given below. Five input values were chosen for this test, all of which produce OK results with both Go and C++, while Epsilon fails miserably.

C++ source:
```
#include <iostream>
#include <complex>
 
int
main() {
#define iR 0.99999999999
#define oR 13.010791601744723916808
	std::complex<double> i0(iR, 1.0e-26), i1(iR, 1.0e-60), i2(iR, 1.0e-150), i3(iR, 1.0e-250), i4(iR, 1.0e-300),
		o0(oR, 5.0000000000250000000001e-16),
		o1(oR, 5.0000000000250000000001e-50),
		o2(oR, 5.0000000000250000000001e-140),
		o3(oR, 5.0000000000250000000001e-240),
		o4(oR, 5.0000000000250000000001e-290);

	std::cout <<
		std::atanh(i0) << '\n' <<
		std::atanh(i0) - o0 << '\n' << '\n' <<
		std::atanh(i1) << '\n' <<
		std::atanh(i1) - o1 << '\n' << '\n' <<
		std::atanh(i2) << '\n' <<
		std::atanh(i2) - o2 << '\n' << '\n' <<
		std::atanh(i3) << '\n' <<
		std::atanh(i3) - o3 << '\n' << '\n' <<
		std::atanh(i4) << '\n' <<
		std::atanh(i4) - o4 << '\n';
}
```

C++ std:atanh results and errors (same with `-O0`, `-O3`, or without optimization options):
```
(13.0108,5e-16)
(-4.13702e-08,-4.13702e-23)

(13.0108,5e-50)
(-4.13702e-08,-4.13702e-57)

(13.0108,5e-140)
(-4.13702e-08,-4.13702e-147)

(13.0108,5e-240)
(-4.13702e-08,-4.13702e-247)

(13.0108,5e-290)
(-4.13702e-08,-4.13702e-297)
```

Go playground link for Go source and output: https://play.golang.org/p/vvQd4NQoW3t

Go cmplx.Atanh results and errors:
```
Result: (13.01079156037454+4.99999958629818e-16i)
Error: (-4.137018372318835e-08-4.137268206283146e-23i)

Result: (13.01079156037454+4.999999586298179e-50i)
Error: (-4.137018372318835e-08-4.137268205797551e-57i)

Result: (13.01079156037454+4.99999958629818e-140i)
Error: (-4.137018372318835e-08-4.137268199607741e-147i)

Result: (13.01079156037454+4.999999586298179e-240i)
Error: (-4.137018372318835e-08-4.137268211085086e-247i)

Result: (13.01079156037454+4.9999995862981794e-290i)
Error: (-4.137018372318835e-08-4.137268206639525e-297i)
```

#### Screenshots
![atanh_input](https://user-images.githubusercontent.com/4944410/75618713-17ab8880-5b6a-11ea-9072-b95b78ffa249.png)

#### To Reproduce
1. Go to the Calculation app
2. Type as in screenshot, or choose another of the selected five inputs, or a similar input

#### Expected behavior
A result in line with correctness achieved by other functions that use binary64 from common libraries.

#### Environment
 - Epsilon versions 12.3.0, 13.0.0
 - The platform(s) on which the problem happens: online simulator, actual device

**Comment by nsajko** [comment]
I think the culprit is Trigonometry::RoundToMeaningfulDigits. The function is **meant to remove correctness from results**, which is asking for trouble, but in this case it is especially absurd.

**Comment by nsajko** [comment]
And even the current implementation is weird, instead of `std::round(result/precision)*precision` it would be less horrible to just clear some least significant bits.

**Comment by EmilieNumworks** [comment]
Very good catch, thanks!
PR #1360 fixes it.
