### ISSUE TITLE
[Bug] Python input is broken since E13

### ISSUE THREAD

**Issue by coco33920** [numworks/epsilon#1374]
#### Describe the bug
The input function of python is broken and don't output the right thing

#### Screenshots
![unknown](https://user-images.githubusercontent.com/17108449/75623947-d9d15300-5baf-11ea-9748-fb481622a127.png)

#### To Reproduce
1. Go to python
2. Create a simple script like "i = input("test ") and print(i)" to test
3. Test

#### Expected behavior
The execution must print i but it do not work.

#### Environment
Epsilon 13.0.0
Tested on linux simulator and on actual device
( thanks to A2drien#2797 )

**Comment by Ecco** [comment]
Hi @coco33920 ! You're right, thank you! However this is something that's already been reported and fixed 😄 See #1315

**Comment by coco33920** [comment]
Yes i seen that but i tested on the latest epsilon master after the merge of the fixes pull request

**Comment by LeaNumworks** [comment]
Hi @coco33920, thanks for the issue!
The problem did not appear on the macOS simulator, that's why I missed it :)
It should be fixed by #1377
