### ISSUE TITLE
Problem in window redrawing (SDL?)

### ISSUE THREAD

**Issue by LeaNumworks** [numworks/epsilon#1378]
#### Describe the bug
The macOS simulator is not always redrawn properly. This might be a SDL problem, because resizing the window redraws the badly drawn area.

#### Screenshots + scenario
Run the following script
![Screenshot 2020-03-02 at 14 02 46](https://user-images.githubusercontent.com/32390188/75679087-41120480-5c8f-11ea-89f6-6ef62a527878.png)

Enter some input and press OK -> the prompt is not properly redrawn
![Screenshot 2020-03-02 at 14 09 34](https://user-images.githubusercontent.com/32390188/75679221-7e769200-5c8f-11ea-9c91-6d2321b685dc.png)

Resize the window -> the prompt appears
![Screenshot 2020-03-02 at 14 09 40](https://user-images.githubusercontent.com/32390188/75679230-820a1900-5c8f-11ea-98a0-a9fe2fedd52b.png)

#### Expected behavior
The prompt should appear after the user presses OK

#### Environment
 - Epsilon master (a06660e)
 - Simulator macOS, not on the actual device

**Comment by nsajko** [comment]
Maybe related: #1300

**Comment by adri1numworks** [comment]
Cannot reproduce, seems solved
