### ISSUE TITLE
link not working - website -

### ISSUE THREAD

**Issue by moorlag** [numworks/epsilon#1381]
The link 'community' on the website isn't working. 
[Error 500 ](https://workshop.numworks.com/community)

<img width="504" alt="Schermafbeelding 2020-03-03 om 09 56 53" src="https://user-images.githubusercontent.com/2832006/75759116-580b3200-5d35-11ea-9b45-7d1df29d0d26.png">

**Comment by LeaNumworks** [comment]
Hi @moorlag, thanks for the issue, I think the link has been fixed now!
