### ISSUE TITLE
diff(|x| , x, 0) = 0 ?

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1393]
#### Describe the bug
The number derived from f(x) = |x| by 0 displays 0.

#### Screenshots
![bug1](https://user-images.githubusercontent.com/52292872/76349936-34cf1c80-630b-11ea-80a1-7f2e589052ce.png)

#### To Reproduce
1. Go to the Calculation app
2. Make `diff(|x|, x, 0)`
3. See error

#### Expected behavior
I thought I would get an "undef" back because |x| is not derivable at 0.

#### Environment
 - Epsilon version 12.3

**Comment by suazhero** [comment]
-1 or 1 would have made more sense eventually. But ya, probably undef is the most suitable option

**Comment by RedGl0w** [comment]
Seems to be fixed with epsilon 15

**Comment by LeaNumworks** [comment]
Indeed, good catch @RedGl0w!
`diff(|x|,x,0)` now returns undef.

**Comment by suazhero** [comment]
Hello, many fixes apparently on version 15 but continuous integration fails and artifacts for windows aren't available. Any idea when windows build will be fixed so that we can test those? Thx

**Comment by RedGl0w** [comment]
> Hello, many fixes apparently on version 15 but continuous integration fails and artifacts for windows aren't available. Any idea when windows build will be fixed so that we can test those? Thx

I opened #1708, which fixes the Windows CI. By the way, the epsilon 15 source aren't public yet, so you can't test it now on simulator

**Comment by suazhero** [comment]
Thx @RedGl0w 
I indeed noticed that it's only 14.4.1 based on web simulator. 
Will wait for 15 to appear somewhere then
