### ISSUE TITLE
Binomial law in Numworks does not behave correctly

### ISSUE THREAD

**Issue by bibi6** [numworks/epsilon#1403]
#### Describe the bug
Let X be a random variable following a binomial law B(2; 0.5). It is well-known that P(X=1) = P (1 <= X <= 1) = 0.5; but the Numworks emulator says it is 0...
This seems to happen with every binomial law. Looks like this is a problem of inequalities.

Soit X une variable aléatoire suivant une loi binomiale B(2;0,5). Il est 'évident' que P(X = 1) = P(1 <= X <= 1) = 0.5; or l'émulateur Numworks dit que c'est nul...
Cela semble se produire avec toutes les loi binomiales. Cela semble être un problème d'inégalités.

#### Screenshots
![numworks_bug](https://user-images.githubusercontent.com/5127314/76696353-bc5db800-668a-11ea-998b-8f757708374c.png)

#### Environment
Online emulator with the following settings:
![numworks_bug_version](https://user-images.githubusercontent.com/5127314/76696368-f3cc6480-668a-11ea-9c93-2f25a87cfc82.png)

**Comment by LeaNumworks** [comment]
Hi @bibi6, good catch, thank you!
This should be fixed by PR #1405
