### ISSUE TITLE
Why hidden commits ?

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1427]
Hello the numworks team :grinning: 
This issue can be summarized only by its name...
Why don't you show all the commits, but release all in one second ?
And also, why isn't the matplotlib library, which is released with "epsilon" 13.2 on this repository ?
Thanks

**Comment by EmilieNumworks** [comment]
Hi @RedGl0w!
Because good things come to those who wait for 😁
The matplotlib.pyplot library is now available!
