### ISSUE TITLE
wrong normalcdf() evaluation

### ISSUE THREAD

**Issue by yesmarcliu** [numworks/epsilon#1429]
#### Describe the bug
wrong normcdf() evaluation

#### Screenshots
![screenshot-2](https://user-images.githubusercontent.com/37192442/78101272-d3471e80-739b-11ea-8cd1-cb911346c872.png)

#### Expected behavior
correct answer (as provided by ti-84 and accepted by homework grader): ≈0.9056

#### Environment
 - Epsilon version 13.1.1.
 - online emulator; iPhone app

**Comment by LeaNumworks** [comment]
Hi @yesmarcliu,
Our normcdf function takes as parameters: a, mu and sigma **squared**

![screenshot-2](https://user-images.githubusercontent.com/32390188/78115960-dbd33f80-7403-11ea-9bc5-7970773793c0.png)

Maybe you thought you were inputting sigma?

![screenshot](https://user-images.githubusercontent.com/32390188/78116036-fd342b80-7403-11ea-91c3-030ddfdc8d06.png)

I am closing the issue, as I think the result is correct.

**Comment by yesmarcliu** [comment]
> Hi @yesmarcliu,
> Our normcdf function takes as parameters: a, mu and sigma **squared**
> 
> ![screenshot-2](https://user-images.githubusercontent.com/32390188/78115960-dbd33f80-7403-11ea-9bc5-7970773793c0.png)
> 
> Maybe you thought you were inputting sigma?
> 
> ![screenshot](https://user-images.githubusercontent.com/32390188/78116036-fd342b80-7403-11ea-91c3-030ddfdc8d06.png)
> 
> I am closing the issue, as I think the result is correct.

ah i see. thank you very much :)
