### ISSUE TITLE
more complete statistical package

### ISSUE THREAD

**Issue by marcuhroni** [numworks/epsilon#1430]
stats teacher includes several more distributions in curriculum (geometric, hypergeometric, negative binomial, poisson) as well as tests (z-tests, t-tests, z-int, t-int, goodness of fit, anova, etc).

essentially would love to see ti-84 stats features on Epsilon.

thank you very much!

**Comment by artaxxx** [comment]
Thanks @marcuhroni ! We recently added some distributions such as Geometric. Poisson was already here. 
I'm closing your issue because there is the same about tests : #958 
Feel free to open a new issue for Hypergeometric and Negative binomial distributions :)
