### ISSUE TITLE
Get the factors of a number.

### ISSUE THREAD

**Issue by EliteAsian123** [numworks/epsilon#1449]
#### Problem you'd like to fix
Sometimes, you need to find the factors of a number. It would be very cool if you could find the factors of a number.

#### Screenshots
Here is a quick concept of the function:
![e](https://user-images.githubusercontent.com/29520859/78507541-86be6300-774e-11ea-882c-a8d99e0c96be.png)

#### Describe the solution you'd like
A `factors()` function would be cool but I could see some problems with that (such as in the graph app). Also it could be confused with that integer factorization function: `factor()`.

**Thanks!** *I hope I'm not being stupid and a feature like this already exists*

**Comment by Ecco** [comment]
Thanks for the suggestion @EliteAsian123 !

Well, we have `factor` which does something very, very similar 😄 
![screenshot (5)](https://user-images.githubusercontent.com/55989/78512033-47543e80-776f-11ea-9014-ff23eba083b0.png)

I don't think we'd be interested in replying a list, as this could become very very large for no real reason 😄
