### ISSUE TITLE
Black trail appears when function curve touches top of screen

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1458]
#### Describe the bug
When a function's curve touches the top of the screen, moving the cursor creates a black trail.

#### Screenshots
![bug_black_trail](https://user-images.githubusercontent.com/49091098/78560003-a076ad80-7815-11ea-8712-42f8f75b3519.jpg)

#### To Reproduce

1. Go to the Functions app
2. Create the function `sin(tan(cos(cos(sin(x)))))`
3. Plot graph
4. Move the cursor

#### Expected behavior
The cursor should move without leaving any trail behind it.

#### What it is doing
The cursor is leaving a black trail behind it.

#### Environment
 - Epsilon version : 13.2.0
 - Platform : actual device

**Comment by LeaNumworks** [comment]
Hello @sagessylu, thanks for spotting this bug! It should be fixed by #1553.
