### ISSUE TITLE
Misc errors in German translation

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1473]
#### Describe the bug

Apparently some [German text is wrong](https://www.reddit.com/r/numworks/comments/fs0loi/translation_errors/).

##### Part A

```
ActivateExamMode = "Starten Testmodus"
ActiveExamModeMessage1 = "Alle Ihre Daten werden "
ActiveExamModeMessage2 = "gelöscht, wenn Sie den "
ActiveExamModeMessage3 = "Testmodus einschalten."
```

IMHO, `Testmodus` shall be replaced by `Prüfungsmodus`.

##### Part B

English `Axis` corresponds to German `Achse` (both sg.).

##### Part C

```
StorageMemoryFull1 = "Der Speicher ist voll. Löschen Sie"
StorageMemoryFull2 = "von Daten und versuchen Sie es erneut."
```

This shall read: `... Löschen Sie einige Daten ...`

##### Part D

Open Settings in German:

Go to angular units: `Gone` shall read `Gon`.

Return and go to `Komplex` (should read `Komplexe Zahlen`):
`Reel` shall read `Reell`.
`Algebraisch` shall read `Rechtwinklig` or `Kartesisch` (choose one).

Return. "Python-Schriftgröße" lacks the hyphen.

"Testmodus" shall read "Prüfungsmodus", and within it should read "Prüfungsmodus starten".

And the last point shall read "Über".

##### Part E

Open Probabilities in German:

`Uniform` shall read `Gleichverteilung`. And the symbolic graph for this distribution should be entirely filled like its siblings.

**Comment by EmilieNumworks** [comment]
Part A has been done by @FloMiau in PR #1469
