### ISSUE TITLE
Flash never starts when flashing custom firmware.

### ISSUE THREAD

**Issue by EliteAsian123** [numworks/epsilon#1476]
Hello!
I know there are already multiple issue addressing this, but none of them helped me.

When running `make MODEL=n0100 epsilon_flash` in MSYS2 (I'm on Windows 10 and have a model N0100) it simply outputs:
```
DFU     epsilon_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
```
And then it does nothing. I do not know what I am doing wrong.

Thank you.

**Comment by 0b101** [comment]
Did you press the reset button on the back of the calculator after plugging it into your computer? This will make the calculator enter dfu mode.

You might be missing the dfu Windows driver. You can download it on the flash page on NumWorks’ website.

**Comment by EliteAsian123** [comment]
> Did you press the reset button on the back of the calculator after plugging it into your computer?

It doesn't work if I press the reset button on the back of the calculator, and gives me the same result.

> You can download it on the flash page on NumWorks’ website.

If you mean the page where you can update your calculator's firmware, yes I installed the driver.

Thanks!

**Comment by artaxxx** [comment]
Hi @EliteAsian123 , I'm closing this issue since this is not a epsilon related bug/enhancement. Seems like it's a support issue. You should try the regular update process, change the USB cable or ask for help on https://www.reddit.com/r/numworks/

**Comment by EliteAsian123** [comment]
Thanks anyways!

**Comment by MixedMatched** [comment]
@EliteAsian123 you need to install a libusb variation for Windows through [Zadig](https://zadig.akeo.ie/).
