### ISSUE TITLE
[Python] Execute script bug var menu

### ISSUE THREAD

**Issue by AntoninLoubiere** [numworks/epsilon#1481]
#### Describe the bug
Var menu don't take care about "Execute script option". If you execute a script with the option in the sub menu, var will show functions of all scripts. Moreover if you have deselect the auto import of the script who you are executing, functions of this script will not appear in the toolbox.

#### Screenshot
Test with squares auto import disabled
![Capture d’écran du 2020-04-08 18-20-14](https://user-images.githubusercontent.com/40536532/78808436-b4f9a800-79c5-11ea-8256-af446b82193d.png)
We don't see the squares function
![Capture d’écran du 2020-04-08 18-20-37](https://user-images.githubusercontent.com/40536532/78808442-b6c36b80-79c5-11ea-87ad-8a3e3f416da6.png)

#### To Reproduce
Just disable auto import and execute the script in the same sub menu.

#### Expected behaviour
Have only functions of the script executed.

#### Environment
 - Epsilon version: last version in development
 - The platforms: device n0110 and simulator on Linux

**Comment by RedGl0w** [comment]
> Var menu don't take care about "Execute script option". If you execute a script with the option in the sub menu, var will show functions of all scripts.

I think it's the best behavior, because people expect this key to have the same behavior in any circumstance.

> Moreover if you have deselect the auto import of the script who you are executing, functions of this script will not appear in the toolbox.
This will be patched in next version : https://github.com/numworks/epsilon/pull/1460

**Comment by artaxxx** [comment]
Fixed by 14.4.0
