### ISSUE TITLE
Bresenham line drawing in line.cpp in kandinsky doesn't draw a line

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1485]
#### Describe the bug
The bresenham line drawing in https://github.com/numworks/epsilon/blob/master/kandinsky/src/line.cpp doesn't draw a line.

Reported by @artaxxx : https://github.com/numworks/epsilon/pull/1327#issuecomment-610832377

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/78869265-94246780-7a44-11ea-969a-12b0496ce134.png)
Zoomed : 
![image](https://user-images.githubusercontent.com/43498612/78869244-8a026900-7a44-11ea-8727-11deea23bce1.png)

#### Expected behavior
Have a straight line :trollface: 

#### Environment
 - Epsilon master
 - All platform

BTW I'm trying to find why...

**Comment by Ecco** [comment]
I'm going to close this issue since this code isn't used *anywhere* at the moment, so it has absolutely no impact whatsoever.
