### ISSUE TITLE
Add the turtle defaults colors to the kandinsky module in Python app

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1489]
#### Enhancement idea

It would be nice if you could use for example "orange" as a correct setting for the kandinsky module, just like for the turtle module.

#### Screenshot

Just like this :
![screenshot](https://user-images.githubusercontent.com/49091098/78898989-04e37800-7a75-11ea-80aa-6594fe1283c1.png)

**Comment by sagessylu** [comment]
@RedGl0w : Does this mean that this turtle feature I'd like to have in kandinsky is not a standard feature ? Oh... :cry:

**Comment by RedGl0w** [comment]
Kandinsky is not a Standart feature, so your idea is possible. I'm currently working on it

**Comment by RedGl0w** [comment]
It will be fixed with https://github.com/numworks/epsilon/issues/1533
