### ISSUE TITLE
Equation app fails when ignoring matrix variables

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#1491]
#### Describe the bug
Storing a matrix in a variable prevents any equation solving with this variable.

#### Screenshots
![screenshot (53)](https://user-images.githubusercontent.com/20040032/78902460-1aa76c00-7a7a-11ea-9010-b3a398b10051.png)
![screenshot (54)](https://user-images.githubusercontent.com/20040032/78902463-1bd89900-7a7a-11ea-8865-2670838af4ba.png)

#### Expected behavior
The equation should be solved and the solution should mention the ignored variable.

**Comment by Ecco** [comment]
This is due in part to the fact that `Equal::standardEquation` returns `undef` if the expression contains a Matrix (this is called by `Equation::Model::standardForm`).

Note that this behavior would be exactly the same if one tried to solve `x+[1]=0`.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
