### ISSUE TITLE
[Bug] The simulator defaults to French instead of English

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1493]
#### Describe the bug
In #1454 it mentions making the first listed language the default, but it defaults to the second listed language instead,

Here is the list from build/config.mk: `EPSILON_I18N ?= en fr es de pt` 

#### Expected behavior
The first listed language in build/config.mk should be the default.

**Comment by RedGl0w** [comment]
There's definitely something not working well : the default language when I compile is es...

**Comment by RedGl0w** [comment]
It seems that the ion_main with args (with language) is called, even when there's no args : by commenting these lines https://github.com/numworks/epsilon/blob/4a9bfca1f6a02edfcea5fb5068891f48bfe309e7/apps/main.cpp#L38, the language is the right one. I think this comes from another PR.

**Comment by LeaNumworks** [comment]
Hi @0b101, thanks for reporting this bug!
Should be fixed by #1496.
