### ISSUE TITLE
The LED can't be tested in the SDL simulator

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#1499]
When developing an exam-related feature, the color of the LED is hard to test because a physical device has to be used. To remedy this, a section of the SDL window should be dedicated to LED color.

**Comment by Ecco** [comment]
> When developing an exam-related feature

Doesn't start so well 😄

> is hard to test because a physical device has to be used

I don't find it hard 😄 

Seriously though, not something we're interested in fixing at the moment.
