### ISSUE TITLE
[Suggestion] Allow comma to separate rows of matrix

### ISSUE THREAD

**Issue by ian-abbott** [numworks/epsilon#150]
Although it saves typing, I find the lack of commas between rows when entering a matrix in linear form slightly unnatural, e.g. entering `[[A,B][C,D]]` rather than `[[A,B],[C,D]]`.

It would be easy enough to allow both forms of entry, treating the lack of a comma between rows as an "implied comma". But then, which form should be the default when copying a matrix from the calculation history to the input for editing?

**Comment by artaxxx** [comment]
This issue has been open for a long time and we have no plans at this time to change the syntax of the matrix input. So let me close it
