### ISSUE TITLE
More python intercompatibility between calculators

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1500]
#### Problem you'd like to fix / Describe the solution you'd like

Like critor said [here](https://tiplanet.org/forum/viewtopic.php?p=252337#p252337), [here](https://tiplanet.org/forum/viewtopic.php?f=49&t=23665#p252319) and also [here](https://tiplanet.org/forum/viewtopic.php?f=49&t=23667&p=252324#p252324) some python changes in some "universal" modules could be usefull for intercompatibility between calculators. Here are they :

* Turtle :
    * `turtle.colormode(1.0)` for choosing the colormode (on casio the color is a tuple of float from 0 to 1, so with this function, you could just use it with 1.0 and the casio scripts could run on numworks)
    *  `turtle.write()` for drawing text
    * `turtle.circle()` with negative diameter for drawing backward
* Matplotlib.pyplot :
    * The possibility to show an empty graph
    * A third argument in `matplotlib.pyplot.plot()` for choosing the color (like on https://github.com/numworks/epsilon/issues/1489)
    * A third argument in `matplotlib.pyplot.plot()` for choosing the point style
    * A fifth argument in `matplotlib.pyplot.arrow()` for choosing the headwidth
    * `matplotlib.pyplot.boxplot()`

For the matplotlib.pyplot functions, the other arguments should also be bypassed if you don't plan to add them.

**Comment by Ecco** [comment]
Good points, thanks!

May I ask you to, in the future, create one issue per **single** improvement/bug? That's something we ask for in our templates:

> Please describe a **single** bug per issue. Feel free to create multiple issues though!
> Please describe a **single** improvement per issue. Feel free to open multiple issues though!

It makes it very hard to track each point individually otherwise. Thanks 😄

**Comment by RedGl0w** [comment]
Yes, but it would make about 25000 issues, and all the additions we could make are to only one thing : intercompatobolity

**Comment by Ecco** [comment]
> Yes, but it would make about 25000 issues,

Not a problem. It's easier to triage 25000 well-written issue than a single poorly-written one.

Real problems arise if we only intend to do some of issue and discard the others. Or if we want to schedule them for different releases.

**Comment by adriweb** [comment]
This current one might serve as a meta issue I suppose and link the in individual ones on each of the bulletin points (btw those can be checkmarked so that github actually tracks the progress, but it's not quite helpful for commits since you can't reference a "subtask", hence the need of individual issues indeed)

**Comment by Ecco** [comment]
Thanks @RedGl0w !
