### ISSUE TITLE
turtle.write()

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1505]
#### Describe the solution you'd like
I woud like to see in turtle a `write()` function for drawing strings. Maybe this function couldn't handle the heading, because it would be a piece of garbage.

**Comment by artaxxx** [comment]
We could add this function as `write("text")` without extra arguments using the standard default rules of turtle:
* the turtle doesn't move after writing
* the text is left-aligned

And using our large font.

**Comment by Ecco** [comment]
I don't think the heading of the turtle is taken into account on CPython either. At least the [doc doesn't tell](https://docs.python.org/3.8/library/turtle.html#turtle.write).

**Comment by RedGl0w** [comment]
> I don't think the heading of the turtle is taken into account on CPython either. At least the [doc doesn't tell](https://docs.python.org/3.8/library/turtle.html#turtle.write).

That's perfect !

**Comment by artaxxx** [comment]
Fixed in 14.4.0
