### ISSUE TITLE
[Bug] Usage of 10^x with parenthesis broken

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#151]
![image](https://user-images.githubusercontent.com/10530980/30559838-4f00722a-9cb6-11e7-8479-8b0de4650bde.png)

**Comment by ian-abbott** [comment]
You are not the first person to raise an issue about the function of the x10^x key, but it should be thought of as a numeric entry key (like `.` is a numeric entry key), rather than as a x10^x operator key.

**Comment by gpotter2** [comment]
Alright.
Maybe the key could have been name 'E' more than 10^x :/
