### ISSUE TITLE
Simple quote on keyboard

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1518]
#### Problem you'd like to fix
The simple quote is quite usefull in python (like the percent), but isn't in the keyboard, and is far in the toolbox.

#### Screenshots
All the submenus to find the simple quote :
![image](https://user-images.githubusercontent.com/43498612/79219304-4b105100-7e52-11ea-866e-901700b9f398.png)
![image](https://user-images.githubusercontent.com/43498612/79219338-5fece480-7e52-11ea-9680-89aad038d789.png)
To add a double quote, you have to press 2 buttons, to add a simple, you have to press 13 buttons...

#### Describe the solution you'd like
With the same idea as https://github.com/numworks/epsilon/pull/1479, a solution could be to have the toolbox key mapped like that :
- With shiftalphastatus default : open the toolbox
- With shift : paste
- With alpha : add a double quote
- With shift alpha : add a simple quote

**Comment by artaxxx** [comment]
I'm not sure that the simple quote is used that much (that's why it's secondary) and this mechanism is not clear enough for the user. So I'm closing this issue.
