### ISSUE TITLE
[Graphics] Very unclear: divisions on powers

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#152]
![image](https://user-images.githubusercontent.com/10530980/30559915-859b2e10-9cb6-11e7-8468-fdbf2337442e.png)
Simple case. Incredibly hard to read. Bigger examples make it worst.

On powers, maybe the basic `/`  could be used ? Or increase the indent ?

**Comment by Zezombye** [comment]
Increasing the indent should be enough, like on the HP prime:
![](http://puu.sh/xIzFo.png)

**Comment by artaxxx** [comment]
Fixed by #247
