### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by toml12953** [numworks/epsilon#1524]
#### Describe the bug
I'm using Zorin OS (a variant of Ubutu) I get the following error when trying to compile:

`LD      epsilon.elf
/tmp/ccVoLW3Q.ltrans8.ltrans.o: In function ExpressionField::inputViewHeight() const:
/home/tom/Downloads/epsilon/escher/src/expression_field.cpp:119: undefined reference to 'ExpressionField::k_maximalHeight'
/home/tom/Downloads/epsilon/escher/src/expression_field.cpp:119: undefined reference to 'ExpressionField::k_minimalHeight'
collect2: error: ld returned 1 exit status
build/rules.mk:76: recipe for target 'output/release/device/n0100/epsilon.elf' failed
make: *** [output/release/device/n0100/epsilon.elf] Error 1`

#### Expected behavior
I expected to return to a bash prompt with no error.

#### Environment
Version: epsilon-master from github
Platform Zorin OS 15

**Comment by RedGl0w** [comment]
Can you try :
```bash
rm -rfd output/
```
And then restart compiling

**Comment by toml12953** [comment]
The exact same error happens.

 

Tom L

**Comment by RedGl0w** [comment]
Have you installed the official ARM toolchain from their website ? (the ld in apt repository doesn't work very well)

**Comment by Ecco** [comment]
Hi @toml12953 ! Our Ubuntu-based pipeline is working just fine. This is most likely a bug due to your personal setup, so I'm going to close this. Feel free to reopen if you have evidence that this problem is related to Epsilon codebase.

**Comment by RedGl0w** [comment]
You can send a message on numwork's reddit, I'll try to help you @toml12953 :) !

**Comment by Ecco** [comment]
Actually I may have closed this one too fast.

**Comment by Ecco** [comment]
Might be the same kind of issue as 4d981fbfb

**Comment by EmilieNumworks** [comment]
#1526 should fixe the issue you encoutered

**Comment by toml12953** [comment]
Yes, indeed it did. Everything goes to completion now. Thank you all!

 

Tom Lake
