### ISSUE TITLE
Add y = ax model in the Regression app

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#1529]
#### Problem you'd like to fix
This model is not available and could be very useful! 

#### Screenshots
![screenshot (71)](https://user-images.githubusercontent.com/20040032/79853035-ced4bb00-83c7-11ea-99cf-ffd8196a9c08.png)

**Comment by BoltzmannSolver** [comment]
It could be useful to add R² parameter in proportional regression.

**Comment by LeaNumworks** [comment]
> It could be useful to add R² parameter in proportional regression.

Hello @BoltzmannSolver, thanks for the suggestion!
We plan to add R² for all regressions, see #1530
