### ISSUE TITLE
Device not detected with Ubuntu 16.04 and kernel 4.4.0-96-generic

### ISSUE THREAD

**Issue by ysalmon** [numworks/epsilon#153]
I am trying to flash the software on the device I recently received.

The Bridge application is not available for Linux.

I finally managed to build the SDK, but ```make app_flash``` fails. Apparently, my device is not detected at all by the system : the output of ```lsusb``` remains the same when the device is plugged in and powered on or not.

Any clues ?

**Comment by boricj** [comment]
Did you press the reset button on the back of the calculator while plugged in?

**Comment by ysalmon** [comment]
No. Thanks, this allowed for detection as 0483:df11.
The instructions are a bit misleading I think as invoking ```make app_flash``` gives
```
OBJCOPY app.bin
DFU     app_flash
INFO    About to flash your device. Please plug your device to your computer
        using an USB cable and press the RESET button the back of your device.
```
which looks like a prompt to do so now, when in fact you should do it before invoking the command.

**Comment by madhatter0** [comment]
On my system (Fedora 26) it works fine if I follow the instructions as given, connect the calculator after the prompt appears, then press reset.

**Comment by Ecco** [comment]
The way this was designed is that both cases should work: plugging the device before or after the prompt. We've tested it on macOS too, and it worked well.

**Comment by Ecco** [comment]
Having had no other report of this issue I'm going to close it. Don't hesitate to reopen if this is still biting you 😄
