### ISSUE TITLE
Add a row to the regression table to show the full regressed function

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#1532]
To copy a regressed function from the regression app, you have to copy the regression, then a, b, c, etc. There should be a row on the table that describes the full function by replacing the variables in the function with their regressed values.

![screenshot](https://user-images.githubusercontent.com/30960626/79882167-2e2ecd00-83c0-11ea-896f-964d2bb24c2e.png)

In this example, the "full" row would say `y=-1x^2+11.8x+-25.4`, or the formatted version of `y=-x^2+11.8x-25.4` .

**Comment by artaxxx** [comment]
I don't know if it's the best way to get the full function but we certainly have to allow the user to copy the full function!

**Comment by schreibeLehmann** [comment]
For me it would fit best, if we **add** the row with the full function. 
So that we have both representations, the current one and the "full" one.
