### ISSUE TITLE
Setting interval without confirming it shouldn't recompute

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1539]
#### Describe the bug
When in the graph app, in the list view, you set the interval, but you go back without confirming it, it will still update the intervaL

#### Screenshots
![Peek 02-05-2020 08-57](https://user-images.githubusercontent.com/43498612/80857494-ed05ab00-8c52-11ea-874c-6c1c20ef6040.gif)

#### To Reproduce
1. Go to graph app
2. Create a function
3. Go to the list view
4. Change the interval **without** confirming it
5. Press back

#### Expected behavior
The interval shouldn't change.

#### Environment
 - Epsilon master (9b419acf4039f2730d9763cf1831a24613b2797a)
 - The platform(s) on which the problem happens: all

**Comment by firelop** [comment]
Ok je vais essayer de fix ça (j'ai 13 donc je sais pas si je vais pouvoir le faire)

**Comment by RedGl0w** [comment]
C'est assez simple, donc je l'ai déjà fait, mais j'ai oublié de push

**Comment by LeGmask** [comment]
Ptdrrrrr

**Comment by firelop** [comment]
RedGL0w je n'avais accès qu'au fichier comprésser ! Mais j'avais fini par trouvé le bug.... Du coup c'est cool si tu l'as fix.

**Comment by artaxxx** [comment]
Thanks for reporting that! I think we should also fix it in Functions > Graph > Axes

**Comment by LeaNumworks** [comment]
Fixed by #1632
