### ISSUE TITLE
Need for a "Sophus" App

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#154]
Hello,

I work since several years now on a language called [Sophus](http://irem.univ-reunion.fr/spip.php?rubrique188) which allows to write (if v is the name of a variable)

* augment v by D instead of v⟵v+D
* diminish v by D instead of v⟵v-D
* multiply v by D instead of v⟵v×D
* divide v by D instead of v⟵v/D
* augment v by T percents instead of v⟵v*(1+T/100)
* diminish v by T percents instead of v⟵v*(1-T/100)
* multiply v by T percents instead of v⟵v×T/100
* divide v by T percents instead of v⟵v/T*100 (and similarly with some fractions)
* double v instead of v⟵v×2 (and similarly with triple, etc)
* halve v instead of v⟵v/2
* raise v to the square instead of v⟵v×v (idem for "raise v to the power P")
* invert v instead of v⟵1/v
*  more natural loops loke "repeat until" or "repeat 8 times"

When practicing with this tool, my pupils asked to me why there is nothing like that inside their calculator. So it means that it should be interesting for them to have a Sophus app inside their calculator. And nowadays the only way to have that is to use an open source calculator :rofl:

Alas I never programmed in C++ and working with Debian Jessie, I don't even manage to update my numworks. I am ready to help in any way that I can

**Comment by Ecco** [comment]
Hi @AlainBusser ! That's an interesting suggestion. As a start, you should read our [software engineering](https://www.numworks.com/resources/engineering/software/) pages. They include a step-by-step tutorial to build your own firmware and flash it on your devices. It works on a bunch of different OSes, including Debian.

**Comment by Zezombye** [comment]
I think the "x=" operators could do what you want:

- v += D
- v -= D
- v *= D
- v /= D
- v %+= T
- v %-= T
- v %*= T
- v %/= T
- v *= 2
- v /= 2
- v **= 2
- v **= -1

Though the percent operators do not exist in python, but I don't see why you would need percentages so frequently that you'd make an operator for it.

I think python should be enough for your students, it's easy enough to understand for beginners.

**Comment by AlainBusser** [comment]
I don't agree on the fact that it is easier than natural language. And more important, my pupils don't agree either :wink:

First of all, I want it to be clear that I don't want to replace Python by another App, but to add a Sophus app to the other ones. Or allow something like from sophus import * or even, in the calculator app, allow to write functions like augmenter(v,de,5,pourcents). That is something which my pupils would understand more than, for example, algobox. I begin to wonder if it would not be even more interesting to add this kind of function inside poincare: One could do 8 sto V then augmenter(V,de,3,quarts) and display V to see what happened to it. Which would basically be an enhancement over the M+ of the small calculators.

As for the reason why I need so often to use percentages, it is easy to find out: in the technology sections (STMG, STI2D) there is always an exercise with percentages. Always!

**Comment by AlainBusser** [comment]
I think I begin to understand a little better how poincare is made: The parser looks for operations and the assignment is just a peculiar operation, am I right?

If so, it is possible to add Sophus-like instructions (not functions but instructions eh?) inside Poincare. For example multiplyBy would exist in two versions with two different signatures:

1. with 2 arguments, the first one being an uppercase letter which is the name of the variable to multiply (let's call it the multiplicand); the second one (let's call it "multiplier") being a poincare expression which value is by how much the multiplicand is to be multiplied. For example multiply(A,2) means "please double the content of A".
2. with 3 arguments, the first one being the (name of the) multiplicand as above, the second still being an expression and the third being a modificator of the second: The second argument could be called numerator and the third one is the corresponding denominator. For example multiply(A,2,percents) has the meaning of "please divide the content of A by 50".

For example, if I want to check that 10 augmentations by 5% do not yield the same result than one augmentation by 50%, in [Sofus](https://alainbusser.github.io/Sofus/Sofus_en.html) I can use this program:

![percentages](https://user-images.githubusercontent.com/3930757/31804065-2464a462-b568-11e7-84df-aaf247989b15.png)


If there be instructions like the one above inside Poincare, I could use the Sequence app to have the answer easily, programming the sequence u as recurrent, and choosing u(n+1)=add(u(n),5,percents) as definition of the sequence (the initial term would be u(0)=80 in my example). And if there be poincare inside the Python app it would be even better :stuck_out_tongue_winking_eye: 

The following instructions would be necessary (and could be inside a category accessible by the toolbox button):

- add (2 or 3 arguments)
- subtract (2 or 3 arguments)
- multiply (2 or 3 arguments)
- divide (2 or 3 arguments)
- raise (2 arguments, the second being either the power, or a word like square or cube)
- invert (1 argument)
- double, triple, halve etc (1 argument)


So that I would not have to create an app from scratch (task which I am right now totally unable to complete). I don't think it would weigh too much epsilon (although ideally it should be implemented on complex numbers and matrices as well) and it would just be an enhancement over the [M+] and [M-] one can find on any inexpensive calculator but not on a so-called "scientific" one :stuck_out_tongue: 


As for the Python app,as it is wearing to use a small keyboard for a long time, please take a look at [plurialgo](http://raffinat.perso.univ-pau.fr/plurialgo/gwt/index.html) which allows to create programming structures with modal dialog boxes and the keyboard will be necessary only afterwards to complete or correct the program (@adriweb there is even a Ti version!)

**Comment by artaxxx** [comment]
This issue has been open for a long time and we have no plans at this time to include a Sophus app in the official firmware. This is why I close this one
