### ISSUE TITLE
Essential unit prefixes used in electronics engineering are missing

### ISSUE THREAD

**Issue by bmuessig** [numworks/epsilon#1549]
#### Problem you'd like to fix
Currently, the calculator only provides a very limited number of unit prefixes for electronics engineering. There are no nano-prefixes anywhere (which are used a lot in electronics engineering) and especially the Resistance units are missing a lot of required prefixes.
Especially in this day and age of ultra low power electronics, the proposed prefixes are just essential. The changes proposed should be very lightweight and easy to implement.

#### Screenshots
E.g. a screenshot of the very sparse resistance range:
![screenshot(4)](https://user-images.githubusercontent.com/2276327/81591010-037ed580-93bc-11ea-8c8b-562bdce09440.png)

#### Describe the solution you'd like
I would like to see the following, very often used, unit prefixes added:
nA (nano Ampere, 10E-9)
pA (pico Ampere, 10E-12)
nW (nano Watt, 10E-9)
MV (mega Volt, 10E+6)
nV (nano Volt, 10E-9)
nF (nano Farad, 10E-9)
pF (pico Farad, 10E-12)
mOhm (milli Ohm, 10E-3)
MOhm (mega Ohm, 10E+6)
uHenry (micro Henry, 10E-6)
nHenry (nano Henry, 10E-9)

#### Describe alternatives you've considered
Generally, the prefixes can be directly written as 10^(3*x), but since there already is a nice unit system, it's much better to just improve it to a point of being useful.

**Comment by bmuessig** [comment]
I'd be quite happy to see this added to Epsilon. If you would be interested in implementing this, but lack the time, I would be happy to prepare a pull-request.

**Comment by bmuessig** [comment]
I've reviewed the code involved in handling the unit conversions. Basically, most of the work is already done. Apparently, the missing prefixes are already supported, but have to be added to the menus. This change would only involve adding the new menu entries and a few missing strings.

On a side note, I find the handling of the unit conversions strange in some parts. In some units, entering a large number, e.g. 125kA, results in a mixed scientific, mixed unit display, as such:
![Selection_281](https://user-images.githubusercontent.com/2276327/81594248-e0a2f000-93c0-11ea-89ab-e09f22b054da.png)

I like how in calculations, some unit combinations are resolved to their equivalent unit (e.g. V/A = Ohm). But turning on engineering mode, completely "breaks" the unit display (why would you ever want 10E-3 GOhm displayed?):
![Selection_280](https://user-images.githubusercontent.com/2276327/81594306-fa443780-93c0-11ea-894e-1267711d71d9.png)

**Comment by artaxxx** [comment]
All prefixes are deliberately not in the Toolbox menu. Indeed, the Toolbox menu has been voluntarily lightened to show a small overview of the possibilities. We do not plan to enrich this menu as the possibilities would be too many.

**Comment by bmuessig** [comment]
So, you're rendering it useless intentionally. Oh well.

**Comment by artaxxx** [comment]
But you can use these units! Just type `nA` if you need nanoamperes for instance:

![screenshot (79)](https://user-images.githubusercontent.com/20040032/83157153-8e253b80-a103-11ea-9580-dcd66116bbbd.png)

**Comment by MixedMatched** [comment]
@artaxxx using an 6 by 5 alphabetical keyboard isn't exactly intuitive or fast, though. Would making a copy/paste history be possible? Similar to the functionality of the HP prime.

**Comment by bmuessig** [comment]
> All prefixes are deliberately not in the Toolbox menu. Indeed, the Toolbox menu has been voluntarily  lightened to show a small overview of the possibilities. We do not plan to enrich this menu as the possibilities would be too many.
To comment on your statement more precisely. The toolbox is segmented into various sub menus grouped by category. Concerning your selection of toolbox items, the number of available unit prefixes is not the same everywhere. Some groups contain fewer prefixes than others, so there was already some thought going into the chosen prefixes.
Isn't the idea of the toolbox to be a useful quick entry? Why does leaving e.g. the nano out make it a more useful selection than without. Code space certainly shouldn't be an issue here, as I've reviewed the code involved in the toolbox display. Adding the missing items would only be a small addition.
Entering the prefixes by hand is tiresome and more or less renders them useless. Why do I have to press so many buttons to get to the underscore, and two lowercase or uppercase letters.
Concerning my proposed list of additions - they're not many.
I'm sure your electronics engineers have also used the nano-prefix designing the power supply section of the Numworks calculator ;-)

Generally, the toolbox should one day be changed to additionally allow selecting items by number and not scrolling through the list manually. Perhaps the unit entry could also be improved further. As it stands, it's implementation is just a gimmick.
