### ISSUE TITLE
Units in engineering mode don't behave as expected

### ISSUE THREAD

**Issue by bmuessig** [numworks/epsilon#1550]
#### Describe the bug
In engineering mode, with all other settings set to their default values, units are not correctly handled. While the result of the calculation is correct, the displayed format is not.
Another part of this problem is, that units are adjusted inconsistently:
E.g. `180_MH` is represented as `180E6_H`, while `180_MΩ` shows up as `180E-3_GΩ`.

#### Screenshots
Incorrect format and inconsistent simplification of various electrical units:
![Screenshot](https://user-images.githubusercontent.com/2276327/81596412-5492c780-93c4-11ea-804a-0ae020cfc06b.png)

#### To Reproduce
1. Set the calculator to engineering mode
2. Go to the 'Calculation' app
3. Type '1.8_V / 10_nA' or '180_MΩ'
4. Press EXE
5. Type '180_MH' and complete with EXE again
6. Compare the format of the two results

#### Expected behavior
E.g. when calculating `1.8_V / 10_nA` the result should be `180_MΩ`, not `180E-3_GΩ`.
On the other hand, `180_MH` should be displayed as such and not as `180E6_H`.
Generally, when using units, the unit should always be adjusted accordingly in steps of 10^3. The scientific exponent should be suppressed, whenever possible.
Also, the simplification (or adaption to the output format) should be consistent across all units.

#### Environment
 - Epsilon version: 13.2.0
 - The platform(s) on which the problem happens: all

**Comment by artaxxx** [comment]
Fixed in 15.0.0
