### ISSUE TITLE
Epsilon build issue, Ubuntu 16.04, error: ‘ColorMode’ is not a class

### ISSUE THREAD

**Issue by RandoSY** [numworks/epsilon#1557]
First off, WOW! What a great project! A soon as I saw it was open source, 100$ for a new Numworks calc went into the post-Corvid19 budget!
---
Just stumbling around day one with epsilon, to see if I could this to build with my neglected Ubuntu 16.04 box. Instructions were clear, and it was easy to get started. First off I had to rename my Anaconda install directory to "anaconda3_temp" to avoid some conflicts, and this allowed me to say ...
make PLATFORM=simulator clean
make PLATFORM=simulator

The make command "PLATFORM=simulator" ran quite a ways, but then died with this error. 

build/rules.mk:21: recipe for target 'output/release/simulator/linux/python/port/port.o' failed
make: *** [output/release/simulator/linux/python/port/port.o] Error 1
(base) rasyoung@vic2016:~/numworks/epsilon$ make PLATFORM=simulator
CXX     python/port/port.o
python/port/port.cpp: In static member function ‘static KDColor MicroPython::ColorParser::ParseColor(mp_obj_t, MicroPython::ColorParser::ColorMode)’:
python/port/port.cpp:167:61: **error: ‘ColorMode’ is not a class, namespace, or enumeration**
   static constexpr int maxColorIntensity = static_cast<int>(ColorMode::MaxInten
                                                             ^
build/rules.mk:21: recipe for target 'output/release/simulator/linux/python/port/port.o' failed

I checked into this just a little, and saw there has been some recent PR activity on just this topic. I wondered if I'm checked out on the wrong path for my build? I believe this just returns the main branch ...

git clone https://github.com/numworks/epsilon.git

Thanks ...

(Might make sense to build on a box, with a more recent Ubuntu, and maybe no Anaconda)

**Comment by RedGl0w** [comment]
Mhhh...
Very strange
When I tested the changes of @EmilieNumworks on https://github.com/numworks/epsilon/pull/1534, I didn't have issue :thinking: (I use arch btw). I compiled and I don't have this issue.

**Comment by RandoSY** [comment]
Just a quick update, I was able to just walk in the front room, and test on a much more modern build of Ubuntu, (20.04) and it built without issues, even regarding the glitch with Anadonda3, which didn't have to have it's home directory renamed.  So clear sailing so far. 

Now, at a certain risk of appearing as dense as a flagstone, I'm scratching my head at this ...

"./epsilon.elf" 

I would assume that I would have to invoke that particular binary + debug info into some kind of facility that could emulate the Numworks calculator hardware graphically under Linux. 

I took a stab at finding the epsilon.elf file in my build tree and haven't stumbled across it yet. 

Can anyone point me to NOOB friendly guidance on what to do next? Here's where I'm working from ...

https://www.numworks.com/resources/engineering/software/build/

**Comment by RedGl0w** [comment]
The simulator binary is at a specific place depending of the platform
For Linux : `./output/release/simulator/linux/epsilon.bin`

**Comment by RedGl0w** [comment]
By the way, if you manage to compile, you should probably close this issue and if you still have issues, create a message on the subreddit of numworks

**Comment by Ecco** [comment]
Hi @RandoSY ! I'm going to close this issue since you found a solution. And we (probably) wouldn't support such an old distro anyway (since it probably ships with an older compiler). Thanks for the good vibes though 😄

**Comment by RandoSY** [comment]
For sure! Thanks again for your help.
