### ISSUE TITLE
Derivation function

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1561]
Hi there!

I really like the feature, that epsilon can calculate the derivation values of a function (in table mode).

It is possible to add a feature, that epsilon can calculate the **derivation function**?

Like that:
(1) I define a function f:    `x^2 --> f(x)`
(2) I can store the derivation function maybe like:   `derivationfunction(f(x),x) --> f1(x)`

I may be able to name it differently, like
`derivationfunction(f(x),x) --> fderv1(x)`
`derivationfunction(f(x),x) --> g(x)`

With this i could store the first, second, third derivation.
`derivationfunction(f(x),x) --> f1(x)`
`derivationfunction(f1(x),x) --> f2(x)`
`derivationfunction(f2(x),x) --> f3(x)`

What do you think?

**Comment by Ecco** [comment]
Well, it's actually already possible, using pretty much exactly the syntax you mentionned 😄 

```
cos(x)→f(x)
diff(f(x),x,t)→g(t)
```

Then `g(0)` will return `0`.

I'm going to close this issue, but I'd be interested to know why it didn't work when you tried it 😄

**Comment by schreibeLehmann** [comment]
Thanks for your quick reply.
I didnt get it to work early. Maybe the problem in my understanding was, that i assumed that epsilon stores the derivation function, like

`x^2 --> f(x)`
then
`diff(f(x),x,x) --> g(x)`

it will get to
`f(1) = 1` whereas
`g(1) = 2`. That is correct.

But when i want to display the **function** (**term**) like 
`g(x)`... it will say `undefined`

Is there a way to display the derivation function?
I would expect, that epsilon will say
`g(x) = 2*x`

Thanks for your help!
