### ISSUE TITLE
Hypergeometric Distribution

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1566]
Hi there,

would you please add the `hypergeometric distribution` to the great numworks/epsilon?

[Link: https://en.wikipedia.org/wiki/Hypergeometric_distribution](https://en.wikipedia.org/wiki/Hypergeometric_distribution)

This distribution is part of the german curricula:)

Thanks for your great work!

**Comment by schreibeLehmann** [comment]
Hi @artaxxx , thank you for adding this feature to a later milestone:) 

I know, that nobody can say for sure, when a new version of epsilon will be released, but could you maybe just give me a hint, whether the **hypergeometric distributions** will be there in 2020/2021/2022 probably? Because we need those over here for our german **curricula**. So we can use this calculator in our schools:)
Thanks in advance!

**Comment by EmilieNumworks** [comment]
Hi @schreibeLehmann,
We would be interested in discussing in more details the needs of the German curricula. If you have some times, we would be glad to call you or talk to you by email. If so, could you please send an email to Clothilde, my colleague handling our development in Europe: clothilde.relin@numworks.com.
Thanks!

**Comment by artaxxx** [comment]
Fixed in version 20
