### ISSUE TITLE
Solving equation, wrong/missing solution

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1567]
#### Describe the bug
Today i discovered a bug, that the 'Calculation' App gives one or two answers depending on the choosen interval. But both solutions should be displayed in both intervals.

<br>

#### Screenshots
![01-functions](https://user-images.githubusercontent.com/54598856/83009021-660bde80-a016-11ea-86cf-d3b3df31f2a1.png)
(1) Define functions in 'Calculation' App and show them in 'Functions' App
<br><br>

![02-equations](https://user-images.githubusercontent.com/54598856/83009032-686e3880-a016-11ea-951c-53a5072ec2a5.png)
(2) Equation App
<br><br>

![03-intervall-1](https://user-images.githubusercontent.com/54598856/83009038-6a37fc00-a016-11ea-84e1-7cd0c173f2db.png)
(3) Set interval -100 to 100
<br><br>

![04-solution-correct](https://user-images.githubusercontent.com/54598856/83009043-6c01bf80-a016-11ea-9588-e2b62002fbd1.png)
(4) Correct answers
<br><br>

![05-intervall-2](https://user-images.githubusercontent.com/54598856/83009049-6dcb8300-a016-11ea-8be6-5eccbe9d1a74.png)
(5) Change interval to -1000 to 1000
<br><br>

![06-solution-wrong](https://user-images.githubusercontent.com/54598856/83009116-88056100-a016-11ea-9fd4-748a927b9f3a.png)
(6) Wrong/missing answer appears
<br><br>

#### To Reproduce
1. Go to the 'Calculation' app and define function f with `x^2 --> f(x)`. Then Define function f1 with `diff(f(x),x,x) --> f1(x)`
2. Go to the 'Equations' App and type `f(x)=f1(x)`
3. Set the intervall from `-100 to 100`
4. The correct answer appears (`x1=0 and x2=2`)
5. Go back to the intervall and set the interval to `-1000 to 1000` 
6. The wrong/missing answers appears (`x1=0`). So the second solution `x2=2` is missing.

<br>

#### Expected behavior
The 'Equations' App should print the two solutions because both solutions are within both invervals

#### Environment
 - Android App, Epsilon 13.2.0
- and also in online simulation 13.2.0

**Comment by schreibeLehmann** [comment]
#### UPDATE
Today i tried to solve just one equation and this error occurred again.
I think, it might have something to do with the "steps for iteration"?

<br>

#### Reproduce
1) In 'Equation' app type `ln(2*x^2-15)=0`
2) Chose Intervall `xmin = -100` to `xmax=100`
3) Epsilon will find `No solution in the interval`

4) But if you chose the inverval from `xmin=-10` to `xmax=10` then epsilon will find
`x1 = -2.828427`and `x2=2.828427`

<br>

#### Screenshots

![equation-1](https://user-images.githubusercontent.com/54598856/83197821-669f9480-a13e-11ea-989b-5b7a55c24c54.png)
1)Type in equation
<br>

![equation-2](https://user-images.githubusercontent.com/54598856/83197856-75864700-a13e-11ea-820b-558c7cd7bfff.png)
2)Chose interval
<br>

![equation-3](https://user-images.githubusercontent.com/54598856/83197875-7fa84580-a13e-11ea-90b1-a61a09d6e7e0.png)
3)No Solution found
<br><br>

#### Expected 
![equation-4](https://user-images.githubusercontent.com/54598856/83197903-92227f00-a13e-11ea-8cc5-c33e8c8da9d5.png)
4)But if you chose interval `xmin=-10` to `xmax=10`, then correct solution appears. This should also be the solution for the interval above (-100 to 100).
<br>

I hope this helps:)

**Comment by artaxxx** [comment]
Fixed in version 16
