### ISSUE TITLE
Function App - Graph problem with derivation function

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1568]
#### Describe the bug
I discovered a display problem of a graph in 'Function' App.
It might be, because i define the second (blue) function as a derivation?

<br>

#### Screenshots
![graph-prob0-functions](https://user-images.githubusercontent.com/54598856/83014302-c010a200-a01e-11ea-959b-4d2a208ee0f6.png)
(1) Define function f and f1 in 'Calculate' App and show them in 'Functions' App.
<br><br>

![graph-prob1](https://user-images.githubusercontent.com/54598856/83014364-dae31680-a01e-11ea-9508-2d2718104b25.png)
(2) Display the graphs, zooom out and go left. The blue graph is `f1(x)=diff(f(x),x,x) = 2*x`, so it should be a straight line, but is isnt displayed as a solid line.
<br><br>

![graph-prob2](https://user-images.githubusercontent.com/54598856/83014458-09f98800-a01f-11ea-80a1-392d1a269dc4.png)
(3) Zoom in a little bit. It gets werid.
<br><br>

#### To Reproduce
1. Go to the 'Calculate' app and define f and f1. Then go to 'Functions' app and show the functions.
2. Go to 'Functions' app and let show the graphs, then zoom out and go to the left.
3. Zoom in a bit

#### Expected behavior
The blue graph should be displayed as a solid line.

#### Environment
 - Android: 13.2.0
- Online Simulation 13.2.0

**Comment by suazhero** [comment]
Also relates to this one : #1222

**Comment by RedGl0w** [comment]
It seems to be fixed with epsilon 15

**Comment by HugoNumworks** [comment]
Issue resolved by @GabrielNumworks with V-15, probably with [this commit](https://github.com/numworks/epsilon/commit/648cdbaa29222cda1f9fb672bfa95fa8d8a65211) too.
