### ISSUE TITLE
Add sample standard deviation

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#157]
For now, the calculator only gives the population standard deviation in Statistics:
<img width="370" alt="capture d ecran 2017-09-20 a 11 55 09" src="https://user-images.githubusercontent.com/20040032/30638133-b362186e-9dfa-11e7-806c-1d43fb8b0c99.png">
But some requested the sample standard deviation:
<img width="207" alt="capture d ecran 2017-09-20 a 11 55 20" src="https://user-images.githubusercontent.com/20040032/30638163-c3cd8e2c-9dfa-11e7-9242-44a94cea5693.png">

The problem is that it may be confusing for the student to have 2 standard deviation side by side. It seems to be common in the US to have sigma and s but in France we should name sigma as ("Ecart-type" with sigma symbol) and s as ("Ecart-type expérimental s") and put it at the end of the list.

**Comment by parisseb** [comment]
Estimateur non biaise de l'ecart type de la population a partir d'un echantillon

**Comment by tryptofan68** [comment]
Agree with artaxxx, s (sample standard deviation) is the most important estimator in statistics, in particular for experimental sciences, and it should be accessible in the "Stats" section.
Indeed, the "Statistics" app is devoted to true statistics and sampling from a population, not to probabilities, therefore we should not keep <sigma>, and replace it with <s>.

**Comment by artaxxx** [comment]
For now we just added it in the app instead of replacing it. First step :)

So it's fixed #165
