### ISSUE TITLE
Add angular units

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1573]
#### Problem you'd like to fix
In engineering, you often need to convert rad/s to rpm, and need to switch from radians to degrees very often.

#### Describe the solution you'd like
I'd like units for angles that would work with trigonometric functions as well as conversions.
Proposed units :
- Radians (rad)
- Degrees (deg)
- Turns or Revolutions
- Arcminutes and Arcseconds

**Comment by Moddingear** [comment]
Also, an angular speed * a distance could make a linear speed (V = omega * R)

**Comment by artaxxx** [comment]
Fixed in version 20
