### ISSUE TITLE
Calculator image doesn't include the percent symbol

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1574]
#### Describe the bug
When i download the offline simulator **numworks-3547a2aa** from the website [(https://www.numworks.com/simulator/)](https://www.numworks.com/simulator/) i noticed, that the **background.jpg** is still the old **N0100** key-version, **without the % key** 
 <br>

*UPDATE
I noticed this problem also in android app version 13.2.0*

<br>

#### Screenshots
![background](https://user-images.githubusercontent.com/54598856/83292414-5644f380-a1ea-11ea-813a-375bc268ffe9.jpg)
Old Key, without %

<br>

![newkey](https://user-images.githubusercontent.com/54598856/83292506-7f658400-a1ea-11ea-82e6-1161d63ff3d1.PNG)
New keyboard, with the %

<br>

#### Expected behavior
Expected background.jpg like the second screenshot

#### Environment
 - Download from website (like described in the beginning)
- **and also android app version 13.2.0**

**Comment by Ecco** [comment]
Indeed. Thanks for reporting this one @schreibeLehmann !

**Comment by RedGl0w** [comment]
This is fixed by https://github.com/numworks/epsilon/commit/71ac56f8a750f99476154b9d0fcddbbbb239c4eb

**Comment by artaxxx** [comment]
Fixed
