### ISSUE TITLE
[Android] blackscreen when changing app 

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1575]
#### Describe the bug
When i open the numworks app, then switching to an other app and then back to numworks, a blackscreen appears.
I can kind of solve the problem with screen rotation. That means, when i turn my phone, the blackscreen goes away and numwork app works again.

#### To Reproduce
1. Open the Numworks app on android
2. Open an other app
3. Switch back to numworks app
4. See error - blackscreen

--5. If you rotate your phone (changing between horizontal and landscape mode), the blackscreen should go away.

#### Expected behavior
Numwork app will work normally after switching back to it from an other app.

#### Environment
 - Epsilon version 13.2.0
 - The platform(s) on which the problem happens: android

**Comment by RedGl0w** [comment]
Maybe related to #1300

**Comment by Ecco** [comment]
Thanks for the report @schreibeLehmann ! Would you mind providing us with more info? Namely:

* Name/model of the Android device
* Full Android version

Thanks!

**Comment by RedGl0w** [comment]
> Thanks for the report @schreibeLehmann ! Would you mind providing us with more info? Namely:
> 
>     * Name/model of the Android device
> 
>     * Full Android version
> 
> 
> Thanks!

I think this issue appears on all model and all version (because when rotating, this should interpreted like a resize of the window, and so the sdl is redrawn, like it is said [here](https://github.com/numworks/epsilon/issues/1300#issuecomment-585791957)), but personally, I have this issue on a redmi note 7 with android 9.

**Comment by RedGl0w** [comment]
I testée, and when relayouting when the apps receive WINDOWEVENT_EXPOSED, it doesn't seems to fix this issue.

**Comment by RedGl0w** [comment]
> I tested, and when relayouting when the apps receive WINDOWEVENT_EXPOSED, it doesn't seems to fix this issue. But commenting the specified lines seems to patch the issue, so there's probably an event for that.
> 
> Edit : I'm dumb : when `setNeedsRefresh()`, the refresh will only appear on next display change, so when you come back in app, the event `WINDOWEVENT_EXPOSED` is triggered, and we need directly to refresh, and not to wait something is pushed to the framebuffer.

**Comment by schreibeLehmann** [comment]
> Thanks for the report @schreibeLehmann ! Would you mind providing us with more info? Namely:
> 
> * Name/model of the Android device
> * Full Android version
> 
> Thanks!

<br> 

Hi, i'm not sure, whether this information is still needed, but here it is anyways:

**DEVICE 1**
HTC Mediapad M5 8 (Wifi) [SHT-W09]
Android-Version: 9 with 4.9.148 Kernel

**DEVICE 2**
Pixel 3a XL
Android-Version: 10 with 4.9.200 Kernel

The described error occurs on both devices.

**Comment by suazhero** [comment]
Same here on Samsung Note 8 android 9 kernel 4.4.111

Occurs when "alt tabing"
