### ISSUE TITLE
[Translation][german] translation error, real number

### ISSUE THREAD

**Issue by schreibeLehmann** [numworks/epsilon#1576]
#### Describe the bug
In german settings menu are some minor errors in translation.

#### Screenshots
![translation-german-reel1](https://user-images.githubusercontent.com/54598856/83296542-411f9300-a1f1-11ea-82d1-8dfcbb86e802.PNG)
and
![translation-german-reel2](https://user-images.githubusercontent.com/54598856/83296554-454bb080-a1f1-11ea-9201-08193b549c7e.PNG)
**reel** should better be written **reell**

<br> 

#### To Reproduce
1. Go to the 'settings' app
2. Change language to german 'Deutsch'
3. Go to the 'settings' app again
4. See error in line 4 "Komplex - reel" instead of "Komplex - reell"

#### Expected behavior
Real Number should be written "reell" in german (with to "L" at the end).

#### Environment
 - Epsilon version 13.2.0
 - The platform(s) on which the problem happens: all

**Comment by bmuessig** [comment]
And "Algebraische" should be "Algebraisch"

**Comment by RedGl0w** [comment]
> And "Algebraische" should be "Algebraisch"

This is already fixed by https://github.com/numworks/epsilon/commit/2d0d4a3a8df7115939c5bcd5a16403d85d80c7ce#

**Comment by RedGl0w** [comment]
This issue is fixed by https://github.com/numworks/epsilon/commit/b59085bd7f415386485b569fa47574e37ebe5cbd

**Comment by bmuessig** [comment]
> > And "Algebraische" should be "Algebraisch"
> 
> This is already fixed by [2d0d4a3](https://github.com/numworks/epsilon/commit/2d0d4a3a8df7115939c5bcd5a16403d85d80c7ce)

Thanks for pointing that out.
Unfortunately, they introduced a new bug with these changes:
`ComplexFormat = "Komplex Zahlen"` used to be `ComplexFormat = "Komplex"`
"Komplex Zahlen" is grammatically wrong and should be changed to "Komplex**e** Zahlen"

**Comment by EmilieNumworks** [comment]
This was resolved by #1535.
