### ISSUE TITLE
Copying something with a missing field doesn't work when in the Calculation app

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1578]
#### Describe the bug
When you copy something with a mssing field when in the calculation app, pasting it output a string with missing characters (which appear to be parenthesis when pasted in the Python shell for example)

#### Screenshots
![screenshot1](https://user-images.githubusercontent.com/49091098/83355828-1dc82580-a362-11ea-9c90-6fcf544dd168.png)
![screenshot2](https://user-images.githubusercontent.com/49091098/83355857-4d772d80-a362-11ea-81d1-ad0244ac3f1d.png)

#### To Reproduce
1. Go to the Calculation app
2. Type the "sqrt" key
3. Copy it
4. Paste it -> see error

#### Environment
 - Epsilon version : 13.2.0
 - The platform(s) on which the problem happens: online simulator and actual device

**Comment by artaxxx** [comment]
Fixed in 15.0.0
