### ISSUE TITLE
Weird rounding to "0." in Functions app

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1579]
#### Describe the bug
Sometimes, when the curve of a function is really near to the x-axis (below 10^-310), the value of f(x) appears to be rounded to "0."

#### Screenshot
![screenshot](https://user-images.githubusercontent.com/49091098/83434296-7e2a9600-a43a-11ea-9841-8a210c104046.png)

#### To Reproduce
1. Go to the Functions app
2. Plot the function x^(1-x)
3. Go to x=146
4. The text "f(x)=0." is printed

Note that it didn't work with functions such as: 
- x^(-x)
- 1/x^100

#### Expected behavior
Epsilon should round it to "0" instead of "0."

#### Environment
 - Epsilon version : 13.2.0
 - Appears on all platforms

**Comment by RedGl0w** [comment]
In fact, the graph banner view only shows `=` (see https://github.com/numworks/epsilon/blob/899e0d4a6b1eb1655d1af9dfa9399764eb676422/apps/shared/function_banner_delegate.cpp#L30). Also, this banner view get the current cursor location, without getting if this position is rounded or not.

**Comment by artaxxx** [comment]
The bug doesn't appear in version 16
