### ISSUE TITLE
"t" or "b" is sometimes displayed when looking at Additional Results

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1580]
#### Screenshots
![bug](https://user-images.githubusercontent.com/29680628/83452121-c2f40400-a41d-11ea-8dd6-5b8e0d0ff476.png)

#### To Reproduce
1. Go to the "CALCULATION" app
2. Type "sin(45)"
3. Go to "Additional Results" by clicking on the ellipses

#### Expected behavior
The additional results should display properly

#### What could be causing it
This problem was probably introduced in #1569 due to the partial rewrite of #1345.

**Comment by LeaNumworks** [comment]
Hi @0b101, thanks for the issue!
Should be fixed by #1581
