### ISSUE TITLE
Incorrect baseline in Calculation

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1587]
#### Describe the bug
Results for fractions are sometimes displayed with the wrong baseline. For example: 1/(2/(3/4)) displays the result (3/8) inline with the 1 (see screenshot 1). If you type in: (1/(2/(3/4)))/16, the result (3/128) has the correct baseline (see screenshot 2).

#### Screenshots
1 Issue:
![Issue1](https://user-images.githubusercontent.com/29680628/83905965-45373d80-a728-11ea-83ce-cd8ed30aec16.png)

2 Working:
![Normal](https://user-images.githubusercontent.com/29680628/83905979-4a948800-a728-11ea-8500-43dc7691abff.png)

3 Result displayed in middle:
![Issue2](https://user-images.githubusercontent.com/29680628/83906384-153c6a00-a729-11ea-9451-f01befd1ef61.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type '1/(2/(3/4))'
3. See error
4. Type '(1/(2/(3/4)))/16'
5. See correct behavior 

#### Expected behavior
The result of 1/(2/(3/4)) should be bottom aligned like the answer of (1/(2/(3/4)))/16

Here is the correct behavior (from #1345):

![correct](https://user-images.githubusercontent.com/29680628/83906802-de1a8880-a729-11ea-9847-903d98e06192.png)

**Comment by Ecco** [comment]
Hi @0b101 !

I'm afraid this is working as intended. The fractions are supposed to be aligned as if there was an "=" sign between them.

**Comment by 0b101** [comment]
![issue3](https://user-images.githubusercontent.com/29680628/83909983-694a4d00-a72f-11ea-869c-4ca0fad158a0.png)

> I'm afraid this is working as intended. The fractions are supposed to be aligned as if there was an equal sign between them.

@Ecco This can cause issues where the result isn't actually displayed on screen and pressing the up arrow does not move the result to be in view.

**Comment by Ecco** [comment]
Indeed. Then those would be separate issues 😄

**Comment by RedGl0w** [comment]
> Indeed. Then those would be separate issues 😄 

See #1595
