### ISSUE TITLE
Result is hidden after doing tall calculation

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1595]
#### Describe the bug
When performing a tall calculation, the result is hidden. Pressing the "up" one arrow does not jump to the hidden result's location. The only way to see it is either by pressing "up" and then "enter" or "up" twice to go to the previous answer.

#### Screenshots
![image](https://user-images.githubusercontent.com/29680628/84551067-14c84400-acd2-11ea-9e8f-582e07f88f67.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type '1/2/3/4/5/6/7/8/9/10'
3. See error

#### Expected behavior
The answer should either clearly be in view (baseline change or display tall calculations in a non-compact form) and/or the view should correctly move when the "up" arrow is pressed.

#### Environment
 - Latest Beta (from Website)

**Comment by artaxxx** [comment]
Fixed in 14.4.0
