### ISSUE TITLE
Inliner silently fails on MSYS2

### ISSUE THREAD

**Issue by ZanderBrown** [numworks/epsilon#16]
Inliner will successful compile (on the travis branch) but failed silently when run, meaning no CPP/H files are generated and the build fails overall

```
gdb: unknown target exception 0xc0000008 at 0x77c36b12

Thread 1 "inliner" received signal ?, Unknown signal.
0x77c36b12 in ntdll!EtwDeliverDataBlock () from /c/WINDOWS/SYSTEM32/ntdll.dll
(gdb) backtrace
#0  0x77c36b12 in ntdll!EtwDeliverDataBlock () from /c/WINDOWS/SYSTEM32/ntdll.dll
#1  0x77c14258 in ntdll!RtlEnterCriticalSection () from /c/WINDOWS/SYSTEM32/ntdll.dll
#2  0x77c14175 in ntdll!RtlEnterCriticalSection () from /c/WINDOWS/SYSTEM32/ntdll.dll
#3  0x77a68eb3 in unlock () from /c/WINDOWS/System32/msvcrt.dll
#4  0x77a792ef in msvcrt!fread () from /c/WINDOWS/System32/msvcrt.dll
#5  0x77a79288 in msvcrt!fread () from /c/WINDOWS/System32/msvcrt.dll
#6  0x68d4f600 in ?? () from /mingw32/bin/libpng16-16.dll
#7  0x68d590fb in ?? () from /mingw32/bin/libpng16-16.dll
#8  0x68d4a448 in ?? () from /mingw32/bin/libpng16-16.dll
#9  0x00401378 in main ()
```

**Comment by mjopenglsdl** [comment]
I got exactly same problem from compiling and running another program(not this one). It seems an MSYS2 compability issue with libpng16-16 on windows(I am using /mingw64)

```
#0  0x00007ff8076dbe6b in ntdll!RtlDllShutdownInProgress ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ff8076b0c49 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ff8076b0b60 in ntdll!RtlEnterCriticalSection ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ff80633cc93 in msvcrt!fread () from C:\WINDOWS\System32\msvcrt.dll
#4  0x00007ff80633cc18 in msvcrt!fread () from C:\WINDOWS\System32\msvcrt.dll
#5  0x0000000068b4f405 in ?? () from D:\dev\msys2\mingw64\bin\libpng16-16.dll
#6  0x0000000068b58ea7 in ?? () from D:\dev\msys2\mingw64\bin\libpng16-16.dll
#7  0x0000000068b4a2cb in ?? () from D:\dev\msys2\mingw64\bin\libpng16-16.dll
#8  0x000000010040473c in small3d::Image::loadFromFile(std::string) ()
#9  0x00000001004043c5 in small3d::Image::Image(std::string) ()
#10 0x00000001004025c0 in AvoidTheBug3D::GameLogic::GameLogic() ()
#11 0x000000010040c5e3 in main ()
```

**Comment by ZanderBrown** [comment]
Was a comment deleted? I received a notification yet there seems to be no change

**Comment by mjopenglsdl** [comment]
Yeah, it's me :).  I encountered another problem in another project. So I searched the _github_ and found this post. I use gdb in **MSYS2** and got exactly same result with **libpng16-16.dll** and **msvcrt.dll** stuffs(I am using mingw64 for **MSYS2**). And I thought this has something to do with the libpng library compatibility in **MSYS2**
Sorry but later I deleted the comment since I thought it has nothing to do with this project

**Comment by Ecco** [comment]
Given noone else has ever reported this issue I'm going to close it. Maybe something was wrong with your initial Msys2 setup?

**Comment by ZanderBrown** [comment]
It did actually crop up on both my machines, suspect @mjopenglsdl may be right that this is happening upstream somewhere

**Comment by Ecco** [comment]
What's weird is that we have [CI environment](https://ci.appveyor.com/project/Ecco/epsilon-n2hn8/branch/master) setup for Windows, and it's been building just fine.
