### ISSUE TITLE
Change subview style in graph

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1601]
#### Problem you'd like to fix
The fact that the banner view get hided when going on tab has issues : the graph need to be redrawn (which takes time and block user of navigating in the tabs), and a part of the graph isn't visible until the banner view disappear (which is an issue : when you set the window to a y range, a part will be hided). 

#### Describe the solution you'd like
Why not reducing the graph view to the actual size - banner view, and instead of hiding the banner view, hiding the text on it (and maybe changing the he background to a darker gray).

**Comment by artaxxx** [comment]
@RedGl0w , can I close this issue? The legend banner can be larger or smaller depending on what it contains. The real problem I see here is that the graph is partially redrawn when you go up on the tab bar. But this is a problem that is referenced here: #1294

Now, it is also possible to display the graph in full screen which is rather enjoyable!
