### ISSUE TITLE
Arrange shift + Ans transforms a selection of code in commentary in Python app

### ISSUE THREAD

**Issue by Tim-ats-d** [numworks/epsilon#1604]
#### Problem you'd like to fix

Often, when I code in Epsilon Python app I want to make sure a piece of code doesn't contain a bug.

#### Describe the solution you'd like
Arrange `shift + Ans` transforms a selection of code in commentary in Python app to make debugging simpler.

**Comment by RedGl0w** [comment]
This shortcut is not easy at all. Why not adding a category in the toolbox for when a text is selected, with in it, a button to comment all the selection.

**Comment by artaxxx** [comment]
I'm closing this issue because the shortcut is not discoverable enough. As @RedGl0w suggested, the current solution is quite simple: just go to Toolbox > Catalog > # (first item) to comment the line
