### ISSUE TITLE
Move toolbox above the input line

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#1605]
#### Problem you'd like to fix
Right now, the math toolbox blocks the input line in calculation from being visible.

#### Screenshots
What it currently looks like:
![screenshot](https://user-images.githubusercontent.com/29680628/86006608-d7ef9300-b9db-11ea-9d1e-cf6f16bba059.png)

What it could look like:
![toolboxUp](https://user-images.githubusercontent.com/29680628/86006367-77f8ec80-b9db-11ea-9fa8-487bc8585947.png)

#### Describe the solution you'd like
Make the toolbox move to always show up above the input line instead of over it.

#### Describe alternatives you've considered
The toolbox could come down from the top, or TI-89/HP Prime style category menus work work too.

**Comment by RedGl0w** [comment]
The issue is that with exponents, this would look very bad, because it wouldn't be aligned at all
![image](https://user-images.githubusercontent.com/43498612/97427415-c29c5e00-1914-11eb-8fb7-bee8edeae80a.png)
