### ISSUE TITLE
Italian translation too long

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1618]
#### Describe the bug
The italian translation for "auto-import in shell" in the Python app is too long. As a result, the toggle button is not visible!

#### Screenshots
![screenshot (22)](https://user-images.githubusercontent.com/55989/87247717-7c81c400-c423-11ea-88ff-941e44ff6aab.png)

#### To Reproduce
1. Go to the 'Python' app
2. Select the ellipsis on the right of `squares.py`
3. Press OK

#### Environment
 - Epsilon version 14.4

Originally reported [on Reddit](https://www.reddit.com/r/numworks/comments/hpqcle/bug_in_italian_translation_python/).

**Comment by RedGl0w** [comment]
Why not using scrollable cell ?
This would avoid a lot of issues with menu, and would be more precise (because currently, when a text is too large, it's changed, and doesn't exactly means the previous text)

**Comment by Ecco** [comment]
> Why not using scrollable cell ?

Because they're annoying. It's a lot more convenient to be able to understand what the cell is about at once.
