### ISSUE TITLE
Error trying to store a value in "w"

### ISSUE THREAD

**Issue by Braskar** [numworks/epsilon#1622]
#### Describe the bug
You get a syntax error when you try to store a value in the variable w

#### Screenshots
![screenshot(7)](https://user-images.githubusercontent.com/68294916/87456193-7d228200-c5fe-11ea-851b-1afafb2f0374.png)

![screenshot(6)](https://user-images.githubusercontent.com/68294916/87456120-62e8a400-c5fe-11ea-9943-790720263782.png)

#### To Reproduce
1. Go to the calculation app
2. Type any value 
3. Type shift > sto
4. Type alpha > w

#### Expected behavior
Not a error message...

#### Environment
 - version 14.4.0
 - online simulator and actual device

**Comment by RedGl0w** [comment]
Indeed, you can't store in u, v and w (see : https://github.com/numworks/epsilon/blob/2af89fb5468be68dfdc1188a8be2a1feb4451bc4/poincare/src/parsing/parser.cpp#L41-L52)

**Comment by LeaNumworks** [comment]
Hello @Braskar,
Thank you for the issue.
As @RedGl0w said, u, v and w are reserved for now (they are the names of the available sequences), so you cannot use them to store a value.
