### ISSUE TITLE
Bug empty character cannot be copied / pasted

### ISSUE THREAD

**Issue by LeGmask** [numworks/epsilon#1628]
#### Describe the bug
Empty character cannot be copied.

#### Screenshots

![image](https://user-images.githubusercontent.com/53308142/87851677-52387680-c8fb-11ea-8018-12c86535ca14.png)

#### To Reproduce
1. type a void character (root, or exposant)
2. cut
3. paste

#### Expected behavior
It put some undefind char.

#### Environment
 - Epsilon latest
 - Simulators, device

**Comment by RedGl0w** [comment]
Somehow related to https://github.com/numworks/epsilon/issues/1206 ?

**Comment by sagessylu** [comment]
Also, isn't this a duplicate of #1578 ?

**Comment by LeGmask** [comment]
duplicate of #1578
