### ISSUE TITLE
Calculation cell calculate hidden undef in output size

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1631]
#### Describe the bug
In the calculation app, enter :
```
5x+8π+2π²→f(x)
```
And you'll see that the compact result will use 2 lines (instead of one), because the hidden "undef" approximate result is counted in output size.

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/87946808-ca8d6c00-caa2-11ea-815d-53b524b8ab03.png)

#### Expected behavior
I would expect to see this calculation cell on only one line

#### Environment
 - Epsilon 14
 - The platform(s) on which the problem happens: All

**Comment by HugoNumworks** [comment]
Hi @RedGl0w , 
Thanks for spotting the issue, it should be fixed by #1636 where I took into account non togglable expressions when computing display size.
