### ISSUE TITLE
Poincaré's definition for the astronomical unit has a typo

### ISSUE THREAD

**Issue by Volleo6144** [numworks/epsilon#1637]
#### Describe the bug
The astronomical unit's value in metres (defined in [`poincare/include/poincare/unit.h:294`](https://github.com/numworks/epsilon/blob/master/poincare/include/poincare/unit.h#L294)) is `149587870700_m` (amusingly, `149587870700` has more than a full page of results on Google, so y'all aren't the first to make this mistake; `149597870700` has almost 300,000) instead of `149597870700_m` (the definition as per the "Astronomical unit" article on Wikipedia, which cites PDF page 3 of [this](https://www.iau.org/static/resolutions/IAU2012_English.pdf) as its source).

#### Screenshots
![_au→_m = 1.495879ᴇ11_m](https://user-images.githubusercontent.com/38385509/89112778-a419ea00-d42d-11ea-95ad-10765cc55652.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type '_au→_m'
3. There's a typo in the answer

#### Expected behavior
That the result would be shown as 149 5**9**7 870 700 m instead of 149 5**8**7 870 700 m

#### Environment
 - Epsilon version (Settings > About > Software version): 14.4.0
 - The platform(s) on which the problem happens: I've reproduced this on both online simulator and actual device, and tracked the exact line of the error

...And yes, I am well aware that it would be difficult to have an issue of a lower priority than this.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
