### ISSUE TITLE
Inconsistency in unit prefix handling during formatting

### ISSUE THREAD

**Issue by Volleo6144** [numworks/epsilon#1638]
#### Describe the bug
In some cases, the "milli-" prefix will not be used under circumstances where it should (as can be shown by dividing the result by 1000, which would use the "micro-" prefix).

Auto-formatting units works like this in Epsilon (ignoring compound units like `_m^2` or `_J _s`):

1. For each possible unprefixed representative, calculate which allowable prefix has a floored 10-exponent closest to the value (`99_mm = 9.9ᴇ-2_m` has a 10-exponent of -2, which rounds down to -3). This effectively means choosing whichever prefix leads to a value between 0.1 and 99.9, unless such a prefix isn't allowed for auto format (such as positive prefixes on seconds). [This means that the value of `180_MΩ` mentioned in #1550 can be replaced with any value from `100_MΩ` to `999_MΩ`.]
2. Choose whichever prefixed representative has its value closest to 1, where "closest" means "minimize the maximum of `x` and `1/x` (ignoring negatives)". This effectively means setting the boundary between two units at their geometric mean, with boundary cases such as `10_kPa` going to whichever side comes first in the internal order (`10.000000000001_kPa` still rounds up to `0.1_bar`).

The issue is that step 2 is implemented by iterating through each representative and checking if the value is closer to 1 than the current best representative, with "the current best unit" being initialized to the unprefixed SI unit (so, for `50_ms`, it checks `0.05_s` [20] before `50_ms` [50] before `0.0008333_min` [1200] before `0.00001389_h` [72,000]).

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/38385509/89121452-9ba0ce00-d484-11ea-8345-283969be0226.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Type `32_ms` and press EXE; the result is shown as `0.032_s` (`31_ms` is still `31_ms`)
3. For intended behavior, type `99_ns` (the μ symbol is kind of hard to get to) and press EXE; the result is shown as `99_ns` as it should (`100_ns` is `0.1_μs`)

#### Expected behavior
Values from `32_ms` to `99_ms` (and other similar values with other units) should be formatted with the `m` prefix instead of no prefix.

#### Environment
 - Epsilon version (Settings > About > Software version): 14.4.0
 - The platform(s) on which the problem happens: tested on both online simulator and actual device, and found in the source (Poincaré's `unit.cpp`, I think? I don't remember anymore).

**Comment by artaxxx** [comment]
Fixed
