### ISSUE TITLE
[Python] can't interrupt some infinite loops

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1649]
#### Describe the bug
See [this reddit post](https://www.reddit.com/r/numworks/comments/ifnern/frozen_screen_on_python_reset_of_the_calculator/)

#### To Reproduce
See the post

#### Expected behavior
We should be able to stop the execution of the script

**Comment by boricj** [comment]
In theory, there's a hook for exiting the MicroPython mainloop when the "Back" key is pressed (`micropython_port_vm_hook_loop()`). However, for performance reasons the "Back" key is checked only once every 20,000 iterations, so the user has to press and hold that key until Python execution is halted to break out of the interpreter. That number should probably be tweaked.

**Comment by melimelo3** [comment]
Thank you for your respond. Does this problem has been already reported to the technical staff of numworks ?

**Comment by adriweb** [comment]
This page is precisely the report to the team, this is the official repo of the OS :)

**Comment by RedGl0w** [comment]
A good (but a bit dirty) fix could be to have an interrupt driver on epsilon, and attach interrupt on the column of the back key during long actions.

**Comment by GabrielNumworks** [comment]
Thanks for the report. Pull request #1652 fixes this issue (and other related problems) by using a timer instead of a counter to space out the checks for interruption. This should make it possible to comfortably interrupt scripts, even when a lengthy amount of time passes between calls to `micropython_port_vm_hook_loop`.

**Comment by LeaNumworks** [comment]
Closing since #1652 has been merged!
