### ISSUE TITLE
Allow the user to configure the delay for dimming the screen and putting the machine to sleep

### ISSUE THREAD

**Issue by ethandudu** [numworks/epsilon#1659]
#### Problem you'd like to fix

Allow the user to configure the delay for dimming the screen and putting the machine to sleep

#### Describe the solution you'd like

An option in the Settings app

#### Additional context
Here's a screenshot from a Casio emulator

![image](https://user-images.githubusercontent.com/41381482/92491100-1bdbf100-f1f2-11ea-8d3b-b4be63369366.png)

**Comment by RedGl0w** [comment]
https://github.com/numworks/epsilon/pull/1474

**Comment by Ecco** [comment]
Hi @ethandudu ! Thanks for this suggestion! Also, please try to use english next time, it makes it easier for people 
 around the globe to collaborate 😄

**Comment by Ecco** [comment]
Also, @RedGl0w is right, we can definitely close this issue since it's a duplicate of #1474.
