### ISSUE TITLE
Bug that causes the calculator to freeze

### ISSUE THREAD

**Issue by ixul2** [numworks/epsilon#1661]
#### Describe the bug
if you execute time.sleep(-0.01) in the python shell the calculator completely freezes. If you try it on the online simulator of the calculator, the tab crashes. The same happens if you replace "-0.01" with any negative number with at least 2 digits after the point

#### Screenshots
![crash_test](https://user-images.githubusercontent.com/44448949/93005663-62637f80-f553-11ea-915b-c8d4a2321788.png)

#### To Reproduce
1. Go to the Python app
2. Create a new script
3. write the following script:
from time import sleep
sleep(-0.01)
4. Save it
5. Execute it

#### Expected behavior
If you try to execute the same script with CPython, an exception is raised. If you execute time.sleep(-2) in the python app of the calculator it seems to produce the same result as time.sleep(0). So I guess those would be better ways of executing the line than what the calculator currently does.

#### Environment
 - Epsilon version 14.4.0.
 - The platform(s) on which the problem happens: both the physical version and the simulator

**Comment by artaxxx** [comment]
Fixed

**Comment by RedGl0w** [comment]
> Fixed

I guess I can close https://github.com/numworks/epsilon/pull/1662 so ?

**Comment by artaxxx** [comment]
Yes!
