### ISSUE TITLE
Graph often gives a value for f(x) when it's actually undefined

### ISSUE THREAD

**Issue by ComradeEcho** [numworks/epsilon#1667]
#### Describe the bug
I often find that when the graph scale is nice and even and I arrow over to a value that *should* be undefined, it will give a value erroneously.

#### Screenshots
In this example, X = 2 should be undefined and the table agrees... but according to the graph, it has a value. 

However, If I if I "go to" X = 2 from the menu, it correctly says it's undefined and will continue to say that X=2 is undefined even if I arrow back and forth along the graph.

![Screen Shot 2020-09-20 at 8 30 51 PM](https://user-images.githubusercontent.com/4523694/93727393-9147aa00-fb80-11ea-8d84-17dd912040c2.png)
![Screen Shot 2020-09-20 at 8 31 31 PM](https://user-images.githubusercontent.com/4523694/93727398-93aa0400-fb80-11ea-8036-2ccecde927c4.png)
![Screen Shot 2020-09-20 at 8 31 16 PM](https://user-images.githubusercontent.com/4523694/93727399-94db3100-fb80-11ea-9199-7a78500b57e8.png)

#### To Reproduce
1. go to function app
2. enter (x^2 - 4) / (x-2)
3. graph it
4. arrow over to x=2
5. graph erroneously shows that when x=2, f(x) = 4

6. hit "OK" and use the menu to go to x=2
7. graph now correctly shows that when x=2, f(x) is undefined
#### Expected behavior
Calculator should show that when x=2, f(x) = undefined

#### Environment
14.4.0
Both the actual device, and online simulator

**Comment by HugoNumworks** [comment]
Hi @AdieAdior , 
Thanks for spotting this bug, it should be solved in the next update !

**Comment by suazhero** [comment]
Interesting to notice that 
![image](https://user-images.githubusercontent.com/55035114/94236058-dcf5ad00-ff0c-11ea-99d4-59d71c910187.png)
who can be reduced similarly (in this case to 3x-2) doesn't trigger the same issue.

**Comment by HugoNumworks** [comment]
This issue has been fixed for V-15 in [this commit](https://github.com/numworks/epsilon/commit/9e12b61849d56709da05b6d9903b737fbfe53992).
