### ISSUE TITLE
Calculator suddenly reset

### ISSUE THREAD

**Issue by Escartem** [numworks/epsilon#1670]
#### Describe the bug
The calculator ran out of memory and suddenly reset and removed everything inside.

#### To Reproduce
1. Fill up the memory of the calculator
2. Open another program
3. The calculator restart and reset

#### Environment
 - Epsilon version 14.4.0
 - Happened on the actual device, could not test the emulator because the webpage crashed

**Comment by RedGl0w** [comment]
Could you be a bit more clear on the step to reproduce?
Because in "filling memory" the memory could be a lot of things, and juste pressing home switch to another app...

**Comment by Escartem** [comment]
What I mean by "filling memory" is having the available space to write programs very low. And then I opened another python program that made the calculator reset

**Comment by HugoNumworks** [comment]
Hi @Escartem,  
Thanks for raising this issue.
From the few steps you described, I think we fixed this issue internally, for the next update.

**Comment by Escartem** [comment]
Thanks ! And does there is a way the get back the programs or they are lost forever?

**Comment by RedGl0w** [comment]
> Thanks ! And does there is a way the get back the programs or they are lost forever?

They're lost indeed

**Comment by HugoNumworks** [comment]
Sadly, they are lost, unless you saved your scripts on our workshop.

**Comment by RedGl0w** [comment]
#1547 could fix that

**Comment by Escartem** [comment]
I will take a look at what you mentioned and I'm closing the issue for now.
Thanks for your help
