### ISSUE TITLE
Unit's additional result exit issue

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1674]
#### Describe the bug
When exiting an additional result of unit, the ellipsis view won't display, until you scroll back to the calculation cell.

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/95241569-3c599400-080e-11eb-91f6-eae67c682e1c.png)
![image](https://user-images.githubusercontent.com/43498612/95241593-44b1cf00-080e-11eb-9c76-9f6d5626334c.png)
![image](https://user-images.githubusercontent.com/43498612/95241610-49768300-080e-11eb-823f-9315f6ed80d5.png)

#### To Reproduce
1. Go to the calculation App
2. Type `5_L`
3. Open the additional results of this calculation
4. Press back
5. See that the ellipsis view isn't drawn

#### Expected behavior
With other additional results (trigonometry for exemple), when exiting the additional results, the ellipsis view is visible, so it should react like that too (on epsilon 14 it does).

#### Environment
 - Epsilon master
 - The platform(s) on which the problem happens: all

**Comment by GabrielNumworks** [comment]
Thanks for raising this issue.
The value of the additional result itself is also bothering ; at no point should it be equal to 0_m^3... Both problems should be fixed in the next version.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
