### ISSUE TITLE
'Error: Expecting a packed glyph width' appeared when compiling (Issue recreated for improving itself content)

### ISSUE THREAD

**Issue by Uhucream** [numworks/epsilon#1677]
#### Describe the bug
I want to add translation of japanese and I'm working it now.
But epsilon doesn't any japanese characters, so although I tried to add japanese fonts to epsilon, compiling error occur.

The width of font is different between Japanese and others.
e.g. Ａ (Japanese fullwidth character(In Japanese: Zenkaku(全角)) ),  A(Latin half-width character(In Japanese: Hankaku(半角) ) )

Then, there are different width characters in most Japanese fonts, and in many cases, Zenkaku characters is used 1:1 aspect ratio and Hankaku characters is used 0.5:1 ratio in Japanese fonts.
But epsilon compiling is not appeared to be corresponding multiple width.

#### Screenshots
  - compiling error
    <img width="400" alt="image" src="https://user-images.githubusercontent.com/16385352/95674970-c9c22d00-0bee-11eb-9a47-002e43716b63.png">
  - The width of characters differ from language to language
    - Latin half-width 'a'
    <img width="400 " alt="スクリーンショット 2020-10-12 午後11 33 04" src="https://user-images.githubusercontent.com/16385352/95759073-3539f680-0ce4-11eb-99dc-a3f54a26a701.png">

    - Full-width 'a'
    <img width="400" alt="スクリーンショット 2020-10-12 午後11 34 44" src="https://user-images.githubusercontent.com/16385352/95759184-57337900-0ce4-11eb-87ba-b11203c37ea0.png">

    - Japanese Hiragana 'あ'
      <img width="400" alt="スクリーンショット 2020-10-12 午後11 35 37" src="https://user-images.githubusercontent.com/16385352/95759523-c4470e80-0ce4-11eb-8c18-cae84e471723.png">

#### To Reproduce
1. merge characters of japanese which is used 1:1 aspect ratio into Small Font and Large Font
2. Do compile
3. 'Error: Expecting a packed glyph width' appear

#### Expected behavior
It shoud be compiled even if there are different width caracters on the font.

#### Environment
 - Epsilon master
 - The platform(s) on which the problem happens: all

#### Extra note
I want to solve it to complete Japanese translation and submit Pull Request.

**Comment by artaxxx** [comment]
I would like to close this issue because we have no plans to change it in the near future
