### ISSUE TITLE
Y-auto doesn’t stay off when unset by user

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1679]
#### Describe the bug
Y-auto auto-activates every time you enter a new function

#### To Reproduce
Steps to reproduce the behavior in the Function app
1. Set any given graphing window and uncheck auto
2. Erase the function, enter a new one
3. Y-auto is activated by default

#### Expected behavior
When unsetting Y-auto, I expect it to stay off.

#### Environment
 - Epsilon version 14.4.0
 - Every platform: online simulator, actual device and phone app

**Comment by Ecco** [comment]
You're a 100% right. This behavior will be revamped in the next software update.

**Comment by XanderLeaDaren** [comment]
As a follow-up, a colleague of mine and I just discovered a tricky behaviour about the automatic activation of Y-auto, also supporting the idea it should stay off when unsetted by user:

Let’s say you would like to have a graphing window [−10;10] × [−10;10], or maybe [−10;10]×[−5;5].

The usual idea is to use pre-adjustment (basic settings + orthonormal). You will have [-10;10] for _x_ with basic settings, but alas, if you’re plotting a function with vertical asymptote, using orthonormal will change the _x_ values entered by the user to be in accordance to the automatic auto-Y values. And so you have to change the four values of the window.

**Comment by Ecco** [comment]
Indeed. Thanks for this scenario!

We've significantly redesigned the automatic zoom behavior in version 15, and we hope to release it pretty soon. The "auto" status will now be explicitly controlled by the user 😄

**Comment by artaxxx** [comment]
This is actually better now with version 15.0.0 :)
