### ISSUE TITLE
Displaying solutions for a quadratic equation

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1681]
#### Problem you'd like to fix
To have the solutions displayed the way pupils are used to learn them, I suggest they appear with the square-root part near the end of the fraction

#### Screenshots
Currently:
![Capture d’écran de 2020-10-13 14-05-34](https://user-images.githubusercontent.com/28948599/95858855-07919380-0d5e-11eb-83d1-fb041e7ae167.png)

#### Describe the solution you'd like
For the example above, the exact values for the roots would have to be displayed in the format
![Capture d’écran de 2020-10-13 14-05-49](https://user-images.githubusercontent.com/28948599/95859858-8affb480-0d5f-11eb-927c-efb72f66dec6.png)

This is in accordance with the way French curriculum teaches,
![{_displaystyle x_{1}={_frac {-b+{_sqrt {_Delta }}}{2a}}_quad {_text{et}}_quad x_{2}={_frac {-b-{_sqrt {_Delta }}}{2a}} }](https://user-images.githubusercontent.com/28948599/95859649-3ceab100-0d5f-11eb-96f3-1b5705558d5a.png)

and the English-speaking world as well:
![330px-Quadratic_formula svg](https://user-images.githubusercontent.com/28948599/95859782-699ec880-0d5f-11eb-882b-23b7e5e514a4.png)

#### Describe alternatives you've considered
None found

**Comment by Ecco** [comment]
Great suggestion. Thanks!

**Comment by RedGl0w** [comment]
Moreover, `sqrt(x)` <=> `x^(1/2)`, and because childrens are sorted by decreasing exponents, it would make sense.
On casio graph 35+E it works like that too...

**Comment by Stephan-P** [comment]
May I add to this that the minus sqrt(D) solution is calculated first and the plus sqrt(D) second?
This way the two results will be given in order of magnitude: the smaller first and the larger next.

![image](https://user-images.githubusercontent.com/10008599/114239196-0d230b80-9986-11eb-9612-03abd3a3af80.png)

**Comment by artaxxx** [comment]
Fixed in 19.0.0
