### ISSUE TITLE
Function definition range shouldn't be 2*Pi in angle

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1682]
#### Problem you'd like to fix
When you draw f(theta) = 1, in degrees, and then you change to radians, coming back to the graph will make the calculator freeze, because it will draw a lot of times the graph (0 to 360 in radians, so about 57 times).

#### Describe the solution you'd like
In [this line](https://github.com/numworks/epsilon/blob/c91c2a6e3fae7908ebe20952c6b3b6f61387a7bb/apps/shared/continuous_function.cpp#L133), when setting a type of function, the range shouldn't be changed. The solution which would be needed would be to have a bool on the range, which contains if the range is the default one, or is changed, and when calculating the function at a value, if the function range is unchanged, setting the range of the function to default one of the type of function.

#### Describe alternatives you've considered
Changing it manually

**Comment by artaxxx** [comment]
Fixed in version 20
