### ISSUE TITLE
Micro and/or Omega shortcut key (and other Unit and Character implementations)

### ISSUE THREAD

**Issue by JWayn596** [numworks/epsilon#1683]
**Problem**
When calculating or typing in a unit at the micro level, applying the µ symbol for micro is troublesome and requires isolating the unit from an existing defined unit in the toolbox.  The same goes for the Omega symbol for Ohms however it isn't as important as being able to type the µ symbol for micro.

**Easiest Solution**
This can probably be solved by using a key that doesn't yet have a shift event yet.  I recommend 7 for the micro character.  Why 7?  Because on the keypad 7's Alpha event is m or M.  Since the µ symbol stands for micro it would make perfect sense for it to be on 7.  If you were to also implement the Omega symbol in a short cut I would recommend 9 because of the Alpha event O.

**Alternate Solutions**
An alternative would be to implement one, some, or all of these.
1. Have an application that shows all SI prefixes from Tera- to pico- besides the Unit menu that also allows copy paste.
2. Add a list of all available prefixes in the Units menu for reference or selection.  I understand some units don't have things like Gigaamperes but it would be helpful to add other prefixes in a separate list for a more complete experience for specifying exactly which one to use.
    EXAMPLE:
 Toolbox > Units > SI Prefixes
- T _Tera_
- G _Giga_
- M _Mega_
- k _kilo_
- m _milli_
- µ _micro_
- n _nano_
- p _pico_

This would simultaneously allow a power user to use prefixes outside of the defined prefixes in each category, and it would not harm the user-friendly vision of the Units menu.

3. Implement a shortcut key (as first described above), Alternative 2 (as listed above), AND a whole list of special Greek and/or mathematical symbols in the Toolbox for use as only variables or simply units.  It doesn't even have to be a complete comprehensive list, but just include the basics such as Theta, Phi, Sigma, Epsilon, Rho, Alpha, Beta, Gamma, and other symbols for constants as well.

A previous submission desired all categories to include all prefixes, and a developer replied that there were several issues with that.
1. It would be too much work
2. It would make it look less user friendly
3. The capabilities of the OS can calculate the full range of prefixes not included in some categories

The solutions presented here, particularly Alternative Solution 2 and the Shortcut Key solution are given with these issues in mind to provide users with clear messaging that the system can convert the full range of common SI prefixes, ease of implementation for the developers, and does not detract from the overall vision of the UI.

**Comment by artaxxx** [comment]
Duplicates #1803
