### ISSUE TITLE
ION::Console has wrong AlternateFunction for n0100

### ISSUE THREAD

**Issue by DSchndr** [numworks/epsilon#1686]
#### Describe the bug
Line 16 in `/ion/src/device/n0100/drivers/config/console.h` should be
`constexpr static GPIO::AFR::AlternateFunction AlternateFunction = GPIO::AFR::AlternateFunction::AF7;`

instead of 
`constexpr static GPIO::AFR::AlternateFunction AlternateFunction = GPIO::AFR::AlternateFunction::AF8;`

#### To Reproduce
Compile epsilon with an app which accesses ION::Console -> no UART output on UART pads

#### Expected behavior
Serial Console output from pads labeled "uart" on the pcb

#### Environment
 - Epsilon since 14.4.0 (https://github.com/numworks/epsilon/commit/7640805093a4d3a08b10013a184f167b24ac4988)
 - N0100

**Comment by DSchndr** [comment]
By the way, how can i "disable" the console dummy?

**Comment by RedGl0w** [comment]
> By the way, how can i "disable" the console dummy?
> 

https://www.github.com/numworks/epsilon/tree/master/ion%2Fsrc%2Fdevice%2Fshared%2Fdrivers%2Fboard.cpp
I think that without enabling this "device" it will be disabled

**Comment by RedGl0w** [comment]
This issue comes from a [1 year old](https://github.com/numworks/epsilon/commit/7640805093a4d3a08b10013a184f167b24ac4988#diff-25cd339eca5fbd38d684e358ca3b1dd6ad877c03803414c64c3153cdca46afd6L38) commit.
GG for having found it x3

**Comment by DSchndr** [comment]
I actually had this issue in the beginning of the year but for some reason forgot to write a bug report for epsilon xD
(https://github.com/Omega-Numworks/Omega/issues/277#issuecomment-590988797)
Now that i got asked to update my rpi branch of omega i flew over my commits and saw that it is still not fixed in epsilon

**Comment by EmilieNumworks** [comment]
Good catch! The PR #1689 fixes it.
