### ISSUE TITLE
Functions app: sometimes plotting vertical asympotes

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1687]
#### Describe the bug
When plotting a rational function with a denominator having roots, using the zoom feature and moving the window left or right, an asymptote sometimes appears.

#### To Reproduce
1. Go to the Functions app
2. Define e.g. this function:

![ekrano-kopio 2020-10-19 à 12 02 35](https://user-images.githubusercontent.com/28948599/96431483-dbfe2580-1203-11eb-8b44-5103339b5361.jpg)

3. Change the zoom and position of the graphing window to have an asymptote appear sometimes.

4. Some examples with, for each row of three pictures: same zoom level, asymptote there or not depending on where you “look”:
![example1](https://user-images.githubusercontent.com/28948599/96432285-f4227480-1204-11eb-9ba4-483e30a3ac4b.jpg)
![example3](https://user-images.githubusercontent.com/28948599/96432269-ed93fd00-1204-11eb-8a01-f92f09e8d473.jpg)
![example2](https://user-images.githubusercontent.com/28948599/96432278-f1278400-1204-11eb-8551-4d52c9a18f5f.jpg)

#### Expected behavior
The asymptote should never appear.

#### Environment
 - Epsilon version 14.4.0
 - Platforms: online simulator, actual device (maybe app?)

**Comment by GabrielNumworks** [comment]
Hi ! Thanks for reporting this ugly issue.
It was caused by rounding errors when approximating the developed form of a polynomial with a "flat" root.
Pull request #1691 fixes the problem.
