### ISSUE TITLE
Functions: table of values providing values for undefined images 

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1688]
#### Describe the bug
With a function having non-existing images, typically a fraction with denominator having a root, the table of values proves to be wrong, providing values for images supposed to be undefined. Fortunately, the Calculation app is correct.

#### To Reproduce
For example, define this function:
![ekrano-kopio 2020-10-19 à 12 21 12](https://user-images.githubusercontent.com/28948599/96435852-18328580-1206-11eb-9d92-de32548e5a4d.jpg)

The table of values gives _f_(2)=0 which is not correct.
![ekrano-kopio 2020-10-19 à 12 20 55](https://user-images.githubusercontent.com/28948599/96437335-7bbcb300-1206-11eb-9bfe-8e865d3651f3.jpg)

Fortunately, the Calculation app is correct. Strangely enough, even using the definition of _f_ !
![ekrano-kopio 2020-10-19 à 12 30 50](https://user-images.githubusercontent.com/28948599/96439288-fd144580-1206-11eb-97e4-16feae46f47c.jpg)

#### Expected behavior
The function _f_ is defined for _x_ in ]2;+∞[ so no value should be given for _f_(2).

#### Environment
 - Epsilon version 14.4.0
 - Platforms: online simulator, actual device, (maybe the app?)

**Comment by HugoNumworks** [comment]
Hi @XanderLeaDaren ,
Thanks for reporting this issue, we fixed it for the next version !

**Comment by artaxxx** [comment]
Fixed in 15.0.0
