### ISSUE TITLE
Powered function

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1703]
#### Problem you'd like to fix
Currently, you have to input `cos(180)²` in order to calculate the square of the cosinus of 180, but generally maths teacher will prefer writing it `cos²(180)`.

#### Describe the solution you'd like
Change the parser of function to handle `cos²(180)` as `cos(180)²` is handled yet, and `cos(180)²` as `(cos(180))²`.

**Comment by artaxxx** [comment]
Fixed in version 20
