### ISSUE TITLE
MicroPython: round(x,n) not implemented for use with integer x values

### ISSUE THREAD

**Issue by ComradeEcho** [numworks/epsilon#1709]
#### Describe the bug
round(1,10) results in a NotImplimentedError
round(1) results in 1
round(1.0,10) results in 1.0

rounding an integer works in a desktop installation of MicroPython, so I wasn't sure if this functionality was removed intentionally (perhaps to save space?)

#### Screenshots
![Screen Shot 2020-11-17 at 10 56 10 AM](https://user-images.githubusercontent.com/4523694/99421053-947ebe00-28c3-11eb-8194-2f3be6fb32fd.png)
![Screen Shot 2020-11-17 at 10 56 27 AM](https://user-images.githubusercontent.com/4523694/99421063-96e11800-28c3-11eb-95e8-62ead2ffce28.png)

#### Expected behavior
I expect round(1,10) to return 1

#### Environment
14.4.0, web and physical

**Comment by RedGl0w** [comment]
> rounding an integer works in a desktop installation of MicroPython, so I wasn't sure if this functionality was removed intentionally (perhaps to save space?)
Indeed, they didn't disable it : it is not enable by default
https://github.com/numworks/epsilon/blob/e0dcdcea286f7f31b9fbee4d43456a2292ac5bc8/python/src/py/mpconfig.h#L923 
On desktop client, micropython enabled it, but numworks didn't enable / disable it.

**Comment by LeaNumworks** [comment]
Hi @ComradeEcho, thanks for reporting this issue. @RedGl0w made a PR to enable the integer rounding on MicroPython, and it's been merged.
