### ISSUE TITLE
Add a new "power model" in the regression app: y=a*b^x

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#1715]
#### Problem you'd like to fix
For now, you can't use the model `y=a*b^x`. There's the exponential model (`y=a*exp(bx)`) but it requires to calculate `b'=exp(b)` to become `y=a*b'^x`.

#### Describe the solution you'd like
Add a new model: `y=a*b^x`. 
For now I have no idea about the name we should give to this model.

**Comment by weathon** [comment]
I am just wondering this also, I am thinking is it possible to make a python script to do so or write a custom firmware. And there is also a discussion on Reddit about it. https://www.reddit.com/r/numworks/comments/jxukbp/can_i_do_regression_for_abx/gcys2sx/

**Comment by artaxxx** [comment]
Fixed in 19.0.0
