### ISSUE TITLE
Variable inputted by the x,n,t key is always n in sums/products

### ISSUE THREAD

**Issue by MDLC01** [numworks/epsilon#1723]
#### Describe the bug
Within a sum or product, the variable that is inputted when pressing the x,n,t key is always `n`, regardless of which variable is actually used in the sum/product.

#### Screenshots
Here, the sum uses the variable `i`, but `n` is inputted when pressing x,n,t.
![screenshot](https://user-images.githubusercontent.com/57839069/100794204-87161780-341d-11eb-803c-1879a675b8c3.png)

#### To Reproduce
1. Go to the 'Calculation' app
2. Open the Toolbox menu and, under 'Calculation', select 'Sum' or 'Product'
3. Replace `n` by another variable to the left of the `=` sign
4. Move the cursor inside the parenthesis
5. Press x,n,t
6. `n` is inputted, instead of `i`

#### Expected behavior
When pressing x,n,t within the brackets of a sum/product, the variable used by this sum/product should be inputted (`n` by default).

#### Environment
 - Epsilon version: 14.4.0 & 15.0.0
 - The platform(s) on which the problem happens: everywhere

**Comment by artaxxx** [comment]
Fixed in version 16
