### ISSUE TITLE
Add a function in Ion python module

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1724]
#### Problem you'd like to fix
In order to get the pressed key in python, the only solution is to iterate on all the keys with key down. It could be very useful to get a function returning a keyboard state for some optimisations.

**Comment by Ecco** [comment]
We considered it and reached the conclusion that this would yield a negligible speed improvement, if any. So I'm going to close this issue.

If you have a benchmark that proves otherwise, feel free to reopen!
