### ISSUE TITLE
Poor automatic zoom on exponential-like function

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1726]
#### Describe the bug

The automatic zoom on the function `(-x+1)exp(1/(-x+1))` gives a default window which is not so good.

#### Screenshots

![input](https://user-images.githubusercontent.com/55989/101401710-b5be4300-38a0-11eb-871b-e9b697786e07.png)
![graph](https://user-images.githubusercontent.com/55989/101401715-b7880680-38a0-11eb-804d-6a042c1299a3.png)

#### Expected behavior
The window should probably be zoomed-out a little.

#### Environment
 - Epsilon version (15.1.0 0f95b579a).
 - Web, Sim

**Comment by GabrielNumworks** [comment]
Fixed in version-15 by this commit: https://github.com/numworks/epsilon/commit/35bfb8ec16b3e9ac4be1a05620d66a3b804c4744
