### ISSUE TITLE
CAS doesn't calculate root(x^n, n) correctly.

### ISSUE THREAD

**Issue by eklipse2009** [numworks/epsilon#1729]
#### Describe the bug
I've opened this issue also in Omega repository and got pointed out that it is dependent on CAS implementation of Epsilon.
https://github.com/Omega-Numworks/Omega/issues/431
I'm posting this here, because Omega CAS depends on Epsilon's implementation of CAS, which is currently hidden.

#### Screenshots
Screenshots are from Omega and HP Prime. Omega (based on Epsilon, with CAS returned) yields incorrect result, while HP Prime, based on giac, is correct.
![image](https://user-images.githubusercontent.com/4990107/101694428-c545b380-3a7b-11eb-98fd-76dfaf00ebb2.png)
![image](https://user-images.githubusercontent.com/4990107/101694457-cecf1b80-3a7b-11eb-93e3-b3d5dfb6f3a2.png)

#### To Reproduce
1. Turn on CAS by installing Omega or recomplining Epsilon.
2. Enter (root(x^2, 2).

#### Expected behavior
Seeing abs(x) instead of root(x^2, 2)

#### Environment
Omega 1.20.3, based on Epsilon 14.

**Comment by Ecco** [comment]
Hi @eklipse2009 ! As far as I can tell, this issue cannot be reproduced on Epsilon, so I'm going to close it. Feel free to reopen if you have a working example though!

**Comment by quentinguidee** [comment]
Hi @Ecco! I could have missed something, I didn't look any further than that, but changing the last parameter here on Epsilon https://github.com/numworks/epsilon/blob/e9b35efe1641314a0f02840e79f18b19e9183bc2/apps/calculation/calculation_store.cpp#L101
give me the following result

<img width="318" alt="Capture d’écran 2020-12-10 à 11 06 41" src="https://user-images.githubusercontent.com/12123721/101759562-0c629180-3ada-11eb-810e-3e74a24c171f.png">

(That said I did not look further than this line, there may be something else to change…)

**Comment by Ecco** [comment]
Well, you're a 100% right: in that case that would be a bug! But my point is that it's *not* code we ship! In other words, as far as I can tell, this (erroneous) behavior cannot be seen in our *current* software.
