### ISSUE TITLE
Add a new type of regression : no regression

### ISSUE THREAD

**Issue by DegrangeM** [numworks/epsilon#1731]
#### Problem you'd like to fix
When doing linear regression, i often would like to be able to hide the line. Either to be able to see more clearly the points that are hidden by the line, or because I want to be able to show points to my student to try to make a manual linear regression before showing the computed linear regression.

#### Describe the solution you'd like
It would be nice to have a way to hide the regression in the regression app. An easy possibility would be to add a regression type "No regression" among the regression type (linear, exponential, etc.) we can choose when we press ok.

**Comment by Ecco** [comment]
That's a very interesting suggestion, thanks @DegrangeM !

**Comment by artaxxx** [comment]
Fixed in 19.0.0
