### ISSUE TITLE
The online doc is not enough

### ISSUE THREAD

**Issue by weathon** [numworks/epsilon#1733]
What if I want to add an app? Add a language? They are not in the docs

**Comment by RedGl0w** [comment]
The online documentation is made to explain how the project is built. For example, Escher, which is a way more complex part of epsilon (if you don't understand how it should work) than Ion, which is just a classical HAL, is not explained at all.
This documentation, currently, is not specially made to explain how to contribute to the project, but more how the numworks team imagined epsilon.

**Comment by Ecco** [comment]
Well, you're right @weathon , the online doc is a bit light. We probably should invest some time into making it better. We haven't had the time to do it just yet though.

**Comment by weathon** [comment]
OK, thanks
