### ISSUE TITLE
"Numéro de série" is too long

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1745]
#### Describe the bug
The "Numéro de série" text is too long in about, hiding the serial number
This is due to dummy on simulator being 12 char long, instead of 16 in base64, and this I18n has been found probably on simulator, which wrong so... 

#### Solution 
The ° symbol could be used to shorten the text?

**Comment by artaxxx** [comment]
Thanks! It will be fixed in version 16 :)

**Comment by artaxxx** [comment]
Fixed in version 16
