### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1747]
This is a "meta" issue for the translation issue
It will be updated with every translation incomplete I found while merging epsilon 15 on omega.
Sometime omega commits will be linked with the translation (because for example, we added imperial units before epsilon 15 was released, and every unit was translated).

#### List of translation issues :
- A lot of missing translation (translated in english) in `apps/toolbox` in the following language : `de` (see https://github.com/Omega-Numworks/Omega/commit/acb71d29759a3dadac9221570058159adedb7da6#diff-debb5e7025a4a04338a734947a0df6759f6cb863dd54221e32a5b739d4e7aac2)

**Comment by artaxxx** [comment]
Thanks @RedGl0w ! But I don't understand :| 
The link you provided shows translations we already have in version 15. Could you tell me more? Maybe I don't see where the missing translations are and you can set a list?

**Comment by RedGl0w** [comment]
> Thanks @RedGl0w ! But I don't understand :| 
> The link you provided shows translations we already have in version 15. Could you tell me more? Maybe I don't see where the missing translations are and you can set a list?

Yep I will be more precise as soon as I will work again on the merge :p

**Comment by RedGl0w** [comment]
For exemple, the commit I referenced above fixed the translation missing in toolbox.de.i18n in apps/ line 75

**Comment by artaxxx** [comment]
Thanks!

**Comment by RedGl0w** [comment]
Indeed, I didn't find so many translations missing, so this issue is now a report of the previously mentioned translation
