### ISSUE TITLE
Another automatic index of summation

### ISSUE THREAD

**Issue by arthur-jacquin** [numworks/epsilon#1749]
#### Problem you'd like to fix

The automatic index of summation is *n*. I guess you made that choice so that it is easily accessible *via* the "x, n, t" button. However that does not make much mathematical sense, as the index is much more often *k* or *i*. One could argue that it involves an extra "alpha" press, but pressing "alpha" is not harder that going in the toolbox to get the summation operator.

#### Describe the solution you'd like

A 'k' or an 'i' as the automatic index of summation.

**Comment by artaxxx** [comment]
Thanks for this nice issue. You're totally right. Changing the index of summation would be great!

**Comment by artaxxx** [comment]
Fixed in version 16
