### ISSUE TITLE
Error when compiling apps/calculation/calculation.cpp

### ISSUE THREAD

**Issue by eried** [numworks/epsilon#175]
I get the following error :/ any hint?

```
CXX     apps/calculation/calculation.o
apps/calculation/calculation.cpp: In constructor 'Calculation::Calculation::Calculation()':
apps/calculation/calculation.cpp:14:25: error: incompatible types in assignment of 'const char [1]' to 'char [100]'
   m_outputLayout(nullptr)
                         ^
apps/calculation/calculation.cpp:14:25: error: incompatible types in assignment of 'const char [1]' to 'char [200]'
Makefile:117: recipe for target 'apps/calculation/calculation.o' failed
make: *** [apps/calculation/calculation.o] Error 1
eried@SURFACE:/mnt/c/Users/erwin/Documents/GitHub/NumWorks-Epsilon$
```

**Comment by boricj** [comment]
Your toolchain is probably too old. What's your C++ compiler version?

**Comment by eried** [comment]
It is `gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

**Comment by boricj** [comment]
Are you building the firmware (default, cross-compiles to the STM32F4) or the simulator (`PLATFORM=simulator`)?

I don't have access to my development rig right now, but I'm using Debian Stretch (gcc 6.3.0, clang 3.8, gcc-arm-none-eabi 5.4.0) with no issues last time I tried. CI with Travis seems to work too (https://travis-ci.org/numworks/epsilon/builds/280932724).

**Comment by eried** [comment]
Thanks, this is just the default `make`, not the simulator. I'll try to update gcc.

**Comment by adriweb** [comment]
Note that the simulator build will use clang. 
Try `make info` to see what’s used.

**Comment by eried** [comment]
```
eried@SURFACE:/mnt/c/Users/erwin/Documents/GitHub/NumWorks-Epsilon$ make info
========= BUILD SETTINGS ======
DEBUG = 0
PLATFORM = device
CC = arm-none-eabi-gcc
CXX = arm-none-eabi-g++
LD = arm-none-eabi-ld.bfd
CFLAGS = -std=c99
CXXFLAGS = -std=c++11 -fno-exceptions -fno-rtti -fno-threadsafe-statics
SFLAGS = -mthumb -march=armv7e-m -mfloat-abi=hard -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -DDEBUG=0 -DOS_WITH_ONBOARDING_APP=1
 -DOS_WITH_SOFTWARE_UPDATE_PROMPT=1 -DQUIZ_USE_CONSOLE=0 -Os -fdata-sections -ffunction-sections -Ilib -I. -Wall -MD -MP
 -ffreestanding -nostdinc -nostdlib -Iliba/include -Ilibaxx/include -Iion/include -DKD_CONFIG_H=1 -Ikandinsky/include -I
poincare/include -Ipython/src -Ipython/port -Iescher/include -Iquiz/include
LDFLAGS = --gc-sections -T ion/src/device/boot/flash.ld -M -Map output.map
===============================
```

**Comment by eried** [comment]
I tried following the Windows instructions https://www.numworks.com/resources/engineering/software/sdk/windows/

And not all the dependencies are installed after following the guide:
```
erwin@MSI MSYS /d/GitHub/NumWorks-Epsilon
$ make
CXX     apps/on_boarding/logo_icon.o
make: arm-none-eabi-g++: Command not found
make: *** [Makefile:118: apps/on_boarding/logo_icon.o] Error 127
```

**Comment by boricj** [comment]
These instructions for Windows do not install an ARM cross-compiler toolchain but only a native one. I don't know if Arch's `arm-none-eabi-gcc` package is available under MSYS2 though.

Can you build the simulator? It would at least prove you have a working native development setup.

**Comment by debrouxl** [comment]
Ubuntu 16.04 LTS has a GCC 4.9 as arm-none-eabi-gcc: https://packages.ubuntu.com/xenial/devel/gcc-arm-none-eabi . As for the simulator, I experienced issues building my optimized fork with Clang 3.8, but newer versions work correctly.

**Comment by eried** [comment]
Hi, the same happens with 4.9

![image](https://user-images.githubusercontent.com/1091420/31051187-e64e7500-a661-11e7-878b-d740c8309f0e.png)

I tried several gcc versions 4.8, 4.9, 5.4, 6.3. Must be something else. Does anyone uses Ubuntu for the compilation? I am not much of a Linux user, maybe I will try with a Debian virtual machine.

**Comment by adriweb** [comment]
Yeah 4.9 is known to cause issues. However, I haven't had any trouble with clang 3.9+ or gcc 6.3+ (now using 7.2 anyway).
Have been building fine on macOS, Linux Debian 9, Ubuntu 16.04, Fedora 25.

But anyway, for a simulator build (which is using clang, so go fetch the latest you can get :)), just do `make PLATFORM=simulator` (with the appropriate -j for your system), probably with a `make PLATFORM=simulator clean` beforehand just in case.

As for the arm toolchain, it's available (v6.3 IIRC?) with an `apt-get gcc-arm-none-eabi`, but if it's not a good version, there's always this way: https://github.com/numworks/epsilon/blob/f1374e584e38aa068334a8fc548a2e33ee8ea66a/.travis.yml#L14

**Comment by ian-abbott** [comment]
On Ubuntu, you can use the [GNU ARM Embedded Toolchain PPA](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa):

    # Some of these might be needed to allow 'add-apt-repository' to work:
    sudo apt-get update
    sudo apt-get install software-properties-common
    # Set up the GNU ARM Embedded Toolchain repository:
    sudo  add-apt-repository ppa:team-gcc-arm-embedded/ppa
    sudo apt-get update
    # Remove existing toolchain:
    sudo apt-get remove gcc-arm-none-eabi binutils-arm-none-eabi
    sudo apt-get autoremove
    # Install new toolchain:
    sudo apt-get install gcc-arm-embedded

**Comment by ian-abbott** [comment]
On Debian "testing" (Buster), the standard `gcc-arm-non-eabi` packages seem to work fine.

**Comment by eried** [comment]
Awesome! thanks @ian-abbott you are a wizard 🥇 

![image](https://user-images.githubusercontent.com/1091420/31101629-e314c7f4-a7ce-11e7-89f8-42876af30409.png)
