### ISSUE TITLE
Fail to ignore variable

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1750]
See here : https://www.reddit.com/r/numworks/comments/l16rih/bug_%C3%A9quation/

#### Describe the bug
Try to solve `x^2-2x+1=0` with x defined.
It will show the infinite solutions view

#### Environment
 - Epsilon 15.3 
 - The platform(s) on which the problem happens: all

**Comment by artaxxx** [comment]
Thanks @RedGl0w , we fixed the problem in v16!

**Comment by artaxxx** [comment]
Fixed in version 16
