### ISSUE TITLE
Cannot use "v" or "u"

### ISSUE THREAD

**Issue by theTisch21** [numworks/epsilon#1751]
#### Describe the bug
Typing lowercase "v" or "u" causes a syntax error, even though it should return "undefined" or just a standard variable
I also cannot store a number to either of those as variables
Uppercase "V" or "U" work just fine

#### Screenshots
![screenshot (1)](https://user-images.githubusercontent.com/20461232/105271883-29fd2f00-5b4d-11eb-945c-6cbcc8ac4bd3.png)
![screenshot (2)](https://user-images.githubusercontent.com/20461232/105271887-2b2e5c00-5b4d-11eb-8578-1020c5759200.png)
![screenshot](https://user-images.githubusercontent.com/20461232/105272376-13a3a300-5b4e-11eb-8e42-d8e057e780ca.png)

#### To Reproduce
1. Go to the 'calculation' app
2. Type 'v' or 'u'
3. Press OK
4. See syntax error
5. Go to the 'functions' app
6. Create a new function
7. Type 'v' or 'u' in the function
8. See syntax error

#### Expected behavior
I expected it to return "undef" in calculations like any other variable without a value attached to it (see screenshots)
In 'Functions', I expected it to not graph a function, but it instead gives me a syntax error.

#### Environment
It happens on my N0110 and the online simulator
Simulator: 49b74fb
Calculator: 15.3.0

#### Note
I first discovered this bug when using the fork [Omega](https://github.com/Omega-Numworks/Omega), so I originally made an issue there [444](https://github.com/Omega-Numworks/Omega/issues/444) I ended up closing it as it is an epsilon problem, not a problem with Omega.

**Comment by RedGl0w** [comment]
Indeed, it's somehow duplicate of https://github.com/numworks/epsilon/issues/1622

**Comment by artaxxx** [comment]
Actually, `u` and `v` are reserved for sequences. Just as `ln` is a reserved named for logarithm. So when you type `v(2)` you get `undef` but when you type `v` it's a syntax error.
I don't know if we can improve this behavior but the main problem here is that the error message isn't enough precise!

**Comment by theTisch21** [comment]
As it is not a bug, I'm going to close this issue.
