### ISSUE TITLE
The sequence of scrolling through points in Regressions app is sometimes wrong

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1753]
#### Describe the bug
In particular cases, scrolling through the points in the Regressions app loops between the "average" point and the point in the middle.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/49091098/105578381-14238000-5d80-11eb-9a62-ebfb76886a01.png)

#### To Reproduce
1. Go to the Regressions app
2. Type what is shown on the screenshot
3. Print the graph
4. Try to go on the left
-> It loops between P(2) and P(mean)

#### Expected behavior
It should go to P(mean), and then to P(1)

#### Environment
 - Epsilon 15.3.0
 - All platforms

**Comment by artaxxx** [comment]
Thanks! Nice catch!
