### ISSUE TITLE
Pasting "exp(n)" in Calculation app makes unnecessary parentheses appear

### ISSUE THREAD

**Issue by Shadaki** [numworks/epsilon#1758]
#### Describe the bug
When you paste the string "exp(n)" in the Calculation app (n being any number), the exponent is put between unnecessary parentheses.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/49091098/105992843-e0a96400-60a5-11eb-951e-87921927cee2.png)

#### To Reproduce
1. Go to the Python app
2. Type exp(0) somewhere
3. Copy it, paste it into Calculation app
4. There are unnecessary parentheses

#### Expected behavior
There should be no parentheses.

#### Environment
 - Epsilon 15.3.0, any platform

**Comment by artaxxx** [comment]
Thanks! We decided this behavior in order to correctly handle the copy/paste function between Calculations and Python

**Comment by artaxxx** [comment]
Fixed in version 20
