### ISSUE TITLE
All "e" are replaced with "ᴇ" when pasting strings in Calculations, which (e.g.) has effects on ceil(x)

### ISSUE THREAD

**Issue by sagessylu** [numworks/epsilon#1759]
#### Describe the bug
When you paste, for example, ceil(x) into the Calculations app, it isn't converted to |¯x¯| like it should, but to cᴇil(x).

#### Screenshots
![screenshot(1)](https://user-images.githubusercontent.com/49091098/105995082-cc1a9b00-60a8-11eb-94d9-5261ac83e9b8.png)

#### To Reproduce
1. Go to the Python app
2. Type ceil(x) somewhere
3. Copy it, paste it in Calculations app
4. It is converted badly

#### Expected behavior
The expression should be converted to |¯x¯| instead of cᴇil(x).

#### Environment
 - Epsilon 15.3.0, all platforms

**Comment by artaxxx** [comment]
Thanks for reporting!

**Comment by GabrielNumworks** [comment]
This will be fixed in version-16.
