### ISSUE TITLE
Defining the variable n with a matrix causes a bug in the display of Un in the Toolbox

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1760]
I think showing this is enough to understand the problem. (Look below the u.)
![image](https://user-images.githubusercontent.com/52292872/106040981-82977380-60db-11eb-970f-10d0b5e6533f.png)

#### To Reproduce
1. Define the variable n like this:
![image](https://user-images.githubusercontent.com/52292872/106043077-30a41d00-60de-11eb-93ad-2a6a57fe75b8.png)

2. Go to **Sequences** and set Un = n
3. Return to **Calculations**, open the toolbox and go to sequences: contemplate the aberration.

#### Expected behavior
I'm just supposed to see _Un_ on the left.
 
- Epsilon version 15.3.0.
- N100, Simulator

**Comment by Ecco** [comment]
Good catch, thanks!

**Comment by RedGl0w** [comment]
Indeed, that's not specific to matrix. The issue is that in the sequence formula the n is replaced by the symbol stored in n
