### ISSUE TITLE
memory allocation failed allocating 1024 bytes

### ISSUE THREAD

**Issue by OS4** [numworks/epsilon#1761]
#### Describe the bug
I have a Python app that draws successive polygons one after another. However, any more than three sides and I always get "memory allocation failed allocating 1024 bytes" after only a very few polygons have been plotted. It happens using plot or arrow. The app is not using recursion, and when dropped to the shell by the exception I can plot the line it errored on just fine. I added more show()s and introduce a sleep for a second between polygons, but they didn't work either. I added a sleep(1) between each line plot and even though it took a loooong time, the error still occurred. 

I'm happy to be told it's my Python skills, :-), but I have the exact same code running on other platforms, including calculators, without issue.

#### Screenshots
Please provide at least one screenshot of the issue happening. This is by far the best way to quickly show any issue! To attach a screenshot, just go to our [online simulator](https://www.numworks.com/simulator), navigate to reproduce your issue, and click the "screenshot" button. Then drag'n'drop the file here!

Problem is either my script is breaking the online simulator or it's broken anyway, but I'm unable to comply at the moment. I'll keep trying. I've downloaded the simulator so will try locally as well

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to the my learn3.py private app, happy to share it with you
2. Just execute it
3. See error

#### Expected behaviour
It should just draw the polygons.

#### Environment
 - Epsilon version 15.3.0.
 - The platform(s) on which the problem happens: online simulator (which it completely breaks, tried both FireFox and Chrome), actual device

**Comment by RedGl0w** [comment]
Indeed, that's neither your script which is broken, nor the calculator. The reason why this error message is shown is because you're trying to use to much RAM in your script.

**Comment by OS4** [comment]
Hi RedG10w, many thanks for the reply.
Do I have access to garbage collection, or can I define a larger heap? I am using just integers and floats, how can I determine what is using the RAM? Is it the individual plots that are not releasing the RAM or is it the overall resulting plotted polygons. If the latter is there anyway around this issue? Do I need to limit the axis size depending on the number of sides in the polygon?

**Comment by RedGl0w** [comment]
> Do I have access to garbage collection, or can I define a larger heap?

Indeed, the heap is 32Ko and can't be changed without editing [the source](https://github.com/numworks/epsilon/blob/11ef4bd99692aa1e45bdb57539a2eec8506552cb/apps/code/app.h#L76). Currently, numworks keep it 32Ko long, because if one day they would have to decrease it, it would be a big mess (I think).
The garbage collector is enabled by default.

**Comment by OS4** [comment]
Many thanks for your help, I'll restrict the axis size for polygons with sides > 3. I'll close this issue.

**Comment by OS4** [comment]
In case it's of any use: I restricted axis size and it worked ok. Then rewrote to use Turtle and it runs for all polygons to full screen size.
