### ISSUE TITLE
[Functions] Abs(x) plotting

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1768]
#### Describe the bug
Bottom of the graph hidden by the coord bar when plotting abs(x) in auto mode

#### Screenshots
![image](https://user-images.githubusercontent.com/55035114/106399881-91ec2900-641b-11eb-9a2d-87fe71c1634c.png)

#### To Reproduce
1. Go to the 'Functions' app
2. Type 'abs(x).'
3. Scroll down to 'plot graph'

#### Expected behavior
Same behavior as when plotting x² where the origin is clearly displayed above coord bar

![image](https://user-images.githubusercontent.com/55035114/106399948-eee7df00-641b-11eb-9d0a-d915cddaed9d.png)

#### Environment
 - Epsilon version 15.3.0
 - All platforms

**Comment by artaxxx** [comment]
Fixed in version 16
