### ISSUE TITLE
[Functions] Allow the user to input x=... functions

### ISSUE THREAD

**Issue by suazhero** [numworks/epsilon#1769]
Eveything's already been discussed here: Allow X graphing #425 
The workaround was to input it as a parametric funtion which i still believe is not an option for most high school students.

There is still a plotting scale issue on 15.3.0 btw (opening a bug for that)

**Comment by artaxxx** [comment]
Thanks! You're right! We'll try to find a way to plot such expressions

**Comment by suazhero** [comment]
On other calc it's an option in the function type. Then input as x=2 for instance. Or even x function of y i guess could be possible (never really tested on casio). So i assume it could be proposed as a new function type just like parametric etc...

**Comment by artaxxx** [comment]
It's now in version 17
