### ISSUE TITLE
round() not always work

### ISSUE THREAD

**Issue by Escartem** [numworks/epsilon#1773]
Here is an example program : 
![screenshot](https://user-images.githubusercontent.com/43405304/106595607-1346d700-6554-11eb-8395-42ec77528bc9.png)

It calculates the sin of **i** ten times and then prints the rounded result with 3 numbers after the comma
And here is the result : 
![screenshot](https://user-images.githubusercontent.com/43405304/106595732-47ba9300-6554-11eb-95c5-e37c2647bfae.png)

As we can see round(sin(8), 3) don't work
![screenshot](https://user-images.githubusercontent.com/43405304/106596009-b861af80-6554-11eb-81da-7363ea6e8307.png)

This happened for a while and is still present in the latest version of epsilon (15.3.0) and happens on both physical calculator and online emulator.

**Comment by Ecco** [comment]
You're right. This is a bug in upstream [MicroPython](https://github.com/micropython/micropython/issues/4212). I'm going to close this issue since it's tracked on the uPY repository directly.

**Comment by Escartem** [comment]
Okay thank !
So no need to open an issue there ? They already know about and will fix it soon.
