### ISSUE TITLE
Simulator does not build on new ARM-based Macs

### ISSUE THREAD

**Issue by mvanaltvorst** [numworks/epsilon#1776]
#### Behavior
During one of the final steps during compilation, linking fails because an ARM dylib (libpng) is being linked against a x86_64 file:

```
...
CXX     apps/statistics/app.o
LD      epsilon.bin
ld: warning: ignoring file /opt/homebrew/Cellar/libpng/1.6.37/lib/libpng16.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
Notice that this is just a warning from LD, but the resulting binary does not run.

#### To Reproduce
1. Build epsilon on a Mac based on the Apple M1-chip: `make PLATFORM=simulator epsilon_run`

#### Expected behavior
Build succeeds

#### Environment
- Latest git commit of Epsilon
- `pkg-config: stable 0.29.2 (bottled)`
- `freetype: stable 2.10.4 (bottled)`

This issue might also be relevant for Raspberry Pi's (also ARM-based), not sure. I could imagine this is not a very high priority for Numworks right now. Please let me know if you need any more details, or want me to test the simulator on my 2020 ARM-based MacBook Pro 13" in the future.

**Comment by RedGl0w** [comment]
Same as https://github.com/numworks/epsilon/issues/1642 but for mac
