### ISSUE TITLE
[Enhancement] Connected series

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#178]
![sans titre](https://user-images.githubusercontent.com/10530980/31029458-0bcefe14-a552-11e7-8921-6dfa8c21614a.png)
![2sans titre](https://user-images.githubusercontent.com/10530980/31029459-0bf0e18c-a552-11e7-9bf2-9b8417c03f5f.png)

**Comment by ian-abbott** [comment]
I'm not convinced this is a bug. There is nothing in the manual that says you can interlink the sequences like that. You could have written `2*n-1` for v_n.

**Comment by artaxxx** [comment]
Right! It's definitely an enhancement, a very good and primary one! I just change the title to "[enhancement]"! Thanks @gpotter2

**Comment by ian-abbott** [comment]
I can see a use case for _recursive_ sequences of two (or more) variables, where expressions for the current iteration could use values from _previous_ iterations of all sequences, but the only use-case for expressions referring to values from the _current_ iteration of all sequences is to save typing! It would also require the calculator to determine the order of execution of the sequences and checks for circular dependencies.

An example use for recursive sequences of two variables is for simple predator-prey population simulations.

**Comment by boricj** [comment]
@ian-abbott Answering questions about a series that contains another series in its definition is a typical exercise in the French _Baccalauréat_ (the full story being that questions are first asked on the initial, simple series before moving on to the more complex one).

**Comment by parisseb** [comment]
Auxiliary sequences are typically introduced to solve arithmetico-geometric sequences.

**Comment by artaxxx** [comment]
Fixed by #289
