### ISSUE TITLE
Small graphical bug with banners in probability app

### ISSUE THREAD

**Issue by Trixciel** [numworks/epsilon#1782]
#### Describe the bug
One line of pixels is missing when showing a probability graph.

#### Screenshots
This is when the probabilty parameters need to be entered
![image](https://user-images.githubusercontent.com/59417613/107930344-28bbf800-6f7b-11eb-807c-ad78b3832038.png)
And this is when the graph is shown
![image](https://user-images.githubusercontent.com/59417613/107930424-42f5d600-6f7b-11eb-84d5-6f88d36ead8f.png)

#### To Reproduce
1. Go to the Probability app
2. Select any Probabilty form
3. Look at the dark grey banner, and show the probability graph
4. See that a line of dark grey pixels is missing (If needed, press back and reshow the graph again)

#### Expected behavior
The banner shouldn't change size.

#### Environment
 - Epsilon version : 15.3.0
 - Platform : Every numworks calculator with epsilon + simulator

**Comment by HugoNumworks** [comment]
Banners in this view are handled like other stack views, such as in Graph :
![image](https://user-images.githubusercontent.com/67104016/108705318-700f2f00-750d-11eb-9b90-528a917a708a.png)
However, background and border color is here overridden to a same color to look like banners.

Borders in-between stackView title cells are shared.  The bottom title cell override the bottom border of the top title cell.
Here, when entering probability parameters, the added title cell overrides the border in a lighter gray, which looks like a missing pixel line.

  Fixing this will probably require a deeper rework of the Probability app’s StackViewController.

**Comment by artaxxx** [comment]
Fixed in version 16
