### ISSUE TITLE
Add the arrow symbol in the toolbox

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1789]
#### Problem you'd like to fix
For newcomers, the unit converter can be a bit dark, especially the forced type operator (the arrow). In the toolbox, there are all units, with their underscore prefix, but there isn't the arrow of conversion.

#### Describe the solution you'd like
Why not adding in the top of the unit submenu of toolbox the arrow symbol, with a short description explaining it.

**Comment by artaxxx** [comment]
Indeed, this is what we plan to do :)

**Comment by artaxxx** [comment]
It's in version 16
