### ISSUE TITLE
Battery fully charged: notification?

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1791]
#### Problem you'd like to fix
İt would be a nice addition to be able to know when the battery is fully charged.

#### Describe the solution you'd like
Either one or a combination of those:
* new battery icon meaning it is full
* popup message, in a similar way to the one when the calculator is USB-connected to a computer
* flashing LED with a green color
* …

#### Describe alternatives you've considered
Just wait for an amount of time supposed to be long enough! 😅

**Comment by EmilieNumworks** [comment]
This is already supposed to be the case on the N0110! Feel free to reopen an issue if you detect a bug relatively to this.

**Comment by XanderLeaDaren** [comment]
OK, what about on the N0100 İ own, then? Do İ have to consider it a bug that İ get no notification? 😕

**Comment by EmilieNumworks** [comment]
Unfortunately, this feature required a hardware update to work, which was done on N0110.
