### ISSUE TITLE
[poincaré] Can't simplify really complex expression

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon#1792]
#### Describe the bug
Was trying to solve 3° polynomials equations when I stumbled across a weird simplification issue with poincaré. It can't simplify expressions such as `(-(6×√(3)+10)^(2/3)-root(6×√(3)+10,3)+2)/(3×root(6×√(3)+10,3))`. The expression is approximated correctly to -1 but this expression really simplifies to -1, not approximates to -1.

Edit: Wtf, after adding an unit just after the expression, it's simplified correctly to -1.

#### Screenshots
![image](https://user-images.githubusercontent.com/57234558/109311451-23499200-7846-11eb-98a4-e7abf0e7d084.png)

With unit
![image](https://user-images.githubusercontent.com/57234558/109313344-64db3c80-7848-11eb-8005-c1deb9ccb6c5.png)

#### To Reproduce
1. Go to the 'calculation' app
2. Type `(-(6×√(3)+10)^(2/3)-root(6×√(3)+10,3)+2)/(3×root(6×√(3)+10,3))`
3. Observe

#### Expected behavior
The simplified result should be -1 and there should be no approximate result.

#### Environment
 - Epsilon version: 15.3.0.
 - The platform(s) on which the problem happens: all

**Comment by artaxxx** [comment]
Thanks! Indeed, Epsilon doesn't support denesting for now. It's not that easy. We are working on square root denesting but it won't solve the problem as you're dealing with cube roots. 

It's the same thing with or without units. But with units, the output doesn't show the exact result

**Comment by M4xi1m3** [comment]
Oh ok, I guess it's a duplicate of #1215, I'm closing then.
