### ISSUE TITLE
[poincare] Determination of unrealness doesn't work properly with functions

### ISSUE THREAD

**Issue by M4xi1m3** [numworks/epsilon#1798]
#### Describe the bug
In real mode, entering `exp(i*3*pi)` outputs -1 (as expected), but putting `exp(i*x*pi)` in a function and calculating `f(3)` outputs `unreal`

#### Screenshots
![image](https://user-images.githubusercontent.com/57234558/110294704-7f53a980-7ff0-11eb-8f3c-e7c707e4346b.png)

#### To Reproduce
1. Make sure you're in real mode
2. Go to the calculation app
3. Type `ℯ^(π×𝐢×x)→f(x)` then `f(3)`
4. Observe

#### Expected behavior
Should return -1 instead of unreal

#### Environment
 - Epsilon version 15.3.3
 - The platform(s) on which the problem happens: all

**Comment by artaxxx** [comment]
Thanks @M4xi1m3 !

**Comment by artaxxx** [comment]
Fixed in version 20
