### ISSUE TITLE
(Units) Reordering and more categories

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1804]
#### Problem you'd like to fix
Units are scattered in a single menu. I suggest splitting them into multiple menus

#### Describe the solution you'd like
- USI
-- Seconds 
-- Meters
--- Area
--- Volume 
-- Mass
-- K
-- mol
-- Amps
-- Candela
--- lumen
- Electrical/Magnetic
-- Volts
-- Amps
-- Tesla
-- Ohms
--- Siemens 
-- Farads
-- Henry
-- Coulombs
- Physical
-- kg
-- N
-- Pa
-- N.m
- Potential
-- Energy
-- Volts
-- Tesla
-- K
-- N
-- Pa
-- rad
-- m
- Flux
-- Watts
-- Amps
-- m/s
-- rad/s
-- m3/s

Some units are missing but that's only a first draft (Hz, Sr, lux), and others are duplicated on purpose.

**Comment by artaxxx** [comment]
Thanks for your issue. That's what we plan to do. It won't be the same classification as yours but we found something similar!

**Comment by artaxxx** [comment]
We designed new categories in version 16
