### ISSUE TITLE
[Calculation] Add vector additional result

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1806]
#### Describe the solution you'd like
This could be cool to have some additional results for the vectors (for 2D ones) :
- the 1×2 matrix could be displayed with an arrow and some info (its norm for instance) 
- the dot product could show the graphical construction of it

#### Additional context
I'm currently working on dot product :p (I'm in 1ere)

**Comment by artaxxx** [comment]
Fixed in version 20
