### ISSUE TITLE
Math solver with steps

### ISSUE THREAD

**Issue by jeremychamboultou** [numworks/epsilon#1808]
Hello,

I am searching a way to have a math solver for equation and formal calcul on my numworks. I installed omega to get back the formal calcul but I search a way to have the solve steps. 

Does anyone know anything that could help me ?

Thank's in advance.

Jérémy.

**Comment by Ecco** [comment]
Hi @jeremychamboultou . Thanks for the suggesion, but we don't have plans to add this sort of feature at the moment!
