### ISSUE TITLE
Copy point from functions app.

### ISSUE THREAD

**Issue by eclecticfluff** [numworks/epsilon#1809]
#### Problem you'd like to fix
It's not uncommon to use the calculate intersection/maximum/minimum features to find values for use in further calculation, but there's no way to get precise results into the calculations app from the functions app.

#### Describe the solution you'd like
At any point when in the graph view, pressing copy, and maybe some other button that is easier to access would copy the x, y, and (if visible) derivative, which could then be pasted as a list, or maybe one would be user selected when copying. 
 
#### Describe alternatives you've considered
The current workaround is memorizing the values displayed and typing them out again, or in the case of the x value, copying the field. Still, this leaves the question of precision even ignoring how awkward it is.

**Comment by artaxxx** [comment]
Thanks @eclecticfluff ! This is interesting. I don't know if we should allow copying directly from the "Maximum" screen or change the behavior.

**Comment by artaxxx** [comment]
Fixed in version 20
