### ISSUE TITLE
[Poincare] sign function doesn't work on units product

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1810]
#### Describe the bug
Using `sign(1_m)` won't return 1 (even if it's the case). Neither `abs(1_m)` is simplified. 

#### Expected behavior
I would expect it to return 1

#### Environment
 - Epsilon 15
 - All platform

#### Context
I was today working on the coulomb law, which involves some absolute value of units

**Comment by artaxxx** [comment]
Thanks @RedGl0w for this issue!

**Comment by RedGl0w** [comment]
It's pretty easy to fix, but in both function, the main solution to calculate the result of the function is always to approximate. I don't get why, and some comments would have been nice here

**Comment by artaxxx** [comment]
Fixed
