### ISSUE TITLE
Inequations feature

### ISSUE THREAD

**Issue by thePeras** [numworks/epsilon#1812]
#### Inequations
Epsilon has an app to solve equations.
But there isn't a way to solve inequations.

example of an inequation:
<img width="43" alt="Captura de ecrã 2021-03-20, às 14 29 19" src="https://user-images.githubusercontent.com/53405284/111873567-c0e93a80-8988-11eb-965b-e9d5b683deb0.png">

It would be nice the calculator be able to solve inequations. 
It very helpful when students are confirming answers.

#### Equations and Inequations
For a clean and user-friend ui, this feature could be integrate in the Equations app, and the only thing need to do was change the signal = to for example <
<img width="65" alt="Captura de ecrã 2021-03-20, às 14 28 23" src="https://user-images.githubusercontent.com/53405284/111873558-b890ff80-8988-11eb-9451-ad65266fd32c.png">
<img width="65" alt="Captura de ecrã 2021-03-20, às 14 28 44" src="https://user-images.githubusercontent.com/53405284/111873560-bc248680-8988-11eb-922f-0b63706596a7.png">

But that is only an ideia

**Comment by artaxxx** [comment]
I'm closing this issue because it duplicates #905
