### ISSUE TITLE
Prevent user for stopping python program

### ISSUE THREAD

**Issue by Escartem** [numworks/epsilon#1813]
#### Describe the bug
If a python program is made, and there is ``try:`` at the beginning of the program and a ``except:`` at the end, the except will run if any error happens, but, when the program is stopped by the user, it raise an error that can activate the except.

Here is an example program: 
```py
def func():
    try:
        while True:
            pass
    except:
        print("You can't stop this program")
        func()

func()
```

By doing this kind of program, it will make the user unable to stop, unless the calculator runs out of battery or is reset.

I don't know if this feature should be removed because it can be useful to run some code when the user quits the program but there should be some kind of security to prevent this kind of malicious program.

#### Environment
 - Epsilon version: 15.3.0 but should also happen on older versions
 - The platforms on which the problem happens: online simulator and actual device (probably an issue coming from micropython directly so everything that runs it might be affected)

**Comment by Escartem** [comment]
I tried this again on version 16.3.0 and looks like the bug is still here.

**Comment by artaxxx** [comment]
The Home or Power keys now interrupt the program :)

**Comment by Escartem** [comment]
I just tried in the simulator available on the numworks website and the home and power keys don't seem to do anything 🤔 I'm guessing this is because the change is only in the repo and it will be available on the next epsilon update.

**Comment by RedGl0w** [comment]
> I just tried in the simulator available on the numworks website and the home and power keys don't seem to do anything 🤔 I'm guessing this is because the change is only in the repo and it will be available on the next epsilon update.

For the simulator, it is completly normal : the simulator is a **simulator**. It doesn't reproduce at all the hardware. Hardware interruption would be a pain to reproduce on a simulator, and even more with empterpreter. You should test it on real device to know if it works.
