### ISSUE TITLE
Precisely select a data to copy in Graph.

### ISSUE THREAD

**Issue by A2drien** [numworks/epsilon#1814]
#### Problem you'd like to fix
In the Functions application, it is very difficult to select the value to copy to Graph.
Indeed, shift + copy only copies the x value (never other data like f(x) or f'(x)).

#### Screenshots
![image](https://user-images.githubusercontent.com/52292872/112697312-8fd8a080-8e87-11eb-9b84-40419d99bf0b.png)

#### Describe the solution you'd like
I think that the best solution would be that when the user wishes to copy a data, the data x is highlighted (in dark gray?), but that we can change the selected data with the directional cross. Finally, the selection would be validated with OK.

**Comment by artaxxx** [comment]
Fixed in version 20
