### ISSUE TITLE
[Poincare] equal aren't parsed anymore

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1815]
#### Describe the bug
In epsilon 14, we were able to compare expression with the `=` char in calculation for instance. Since epsilon 15, it isn't possible anymore, and it returns always an parser error.

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/112718701-f8119b80-8ef4-11eb-87c5-3e360b95422b.png)

#### To Reproduce
1. Go in calculation
2. Enter `5=8`
3. Expect to have `undef`
4. Enter `0=0`
5. Expect to have `1`

#### Environment
 - Epsilon 15
 - The platform(s) on which the problem happens: all

**Comment by artaxxx** [comment]
Fixed in version 20
