### ISSUE TITLE
Cannot do literal calculation within python scripts

### ISSUE THREAD

**Issue by StandardGage** [numworks/epsilon#1816]
**Problem**
Unable to solve equations which include variables within python scripts as is done within the Equations app.

**Solution I'd like to see**
A way for the python scripts to interact with the Equations app. Such as sending an equation or equations to be solved and getting a return of the solution. With ways to show the equation app as well as return back to the script running

**Other solution**
The addition of a python library that can solve literal equations

**Comment by artaxxx** [comment]
Thanks @StandardGage . We don't plan to add any CAS library in Python for the moment. So let me close this issue.
