### ISSUE TITLE
Units missing

### ISSUE THREAD

**Issue by jeremychamboultou** [numworks/epsilon#1817]
In the Units menu, in Distance, there is the metrics units but the cm is missing.

In Volume, the is not anymore the metrics units (cm^3, m^3...)

**Comment by RedGl0w** [comment]
> In the Units menu, in Distance, there is the metrics units but the cm is missing.

T'es this is strange. 
> In Volume, the is not anymore the metrics units (cm^3, m^3...)

This could be cool indeed to have in this menu an exemple of complex unit, with these two very current units I think. Why not having in eras m^2 and cm^2 too?

**Comment by artaxxx** [comment]
Thanks for this issue @jeremychamboultou . We already did the change to add _cm in version 16! For now, you can simply type `_cm` to use centimeters.

Also, we deliberately didn't put the units of Volume, Surface, Speed, ... because all the units can be composed `_cm^2`, `_km*_h^-1` etc.

**Comment by artaxxx** [comment]
Fixed in version 16
