### ISSUE TITLE
DMS function?

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1822]
I think I'm missing the function DMS, which can be found on other calculators like Casio or HP.
The function DMS converts a decimal number into Degrees, Minutes and Seconds or if you like Hours, Minutes and Seconds.
Could this function be added tot the Toolbox?

**Comment by artaxxx** [comment]
Thanks @Stephan-P ! We are going to find a way to implement it

**Comment by Stephan-P** [comment]
Here's a Python script as an intermediate solution
(Slightly modified code that I fount on StackOverflow. 
Too bad I can't get rid of the spaces in front to the dms characters.
Also too bad that the [ans] button does not work in the Python shell.)

def dec2dms(dd):
    negative = dd < 0
    dd = abs(dd)
    minutes,seconds = divmod(dd*3600,60)
    degrees,minutes = divmod(minutes,60)
    if negative:
        if degrees > 0:
            degrees = -degrees
        elif minutes > 0:
            minutes = -minutes
        else:
            seconds = -seconds
    print(int(degrees),'\u00B0', int(minutes), '\u0027', seconds, '\u0022')

**Comment by Stephan-P** [comment]
Is this still in sight?

**Comment by artaxxx** [comment]
Yes we are behind schedule but it's still in our plans!

**Comment by Stephan-P** [comment]
Reminder for v19

**Comment by artaxxx** [comment]
Fixed in version 20

**Comment by Stephan-P** [comment]
@artaxxx I can see that a method has been added in v20 to enter values in degrees, minutes, seconds format.
But does this also provide for a method to convert any decimal calculation result into DMS-format, like the example code I provided above?

**Comment by RedGl0w** [comment]
> @artaxxx I can see that a method has been added in v20 to enter values in degrees, minutes, seconds format. But does this also provide for a method to convert any decimal calculation result into DMS-format, like the example code I provided above?

Any calculation with time units in it will let in additional result what you need
![image](https://user-images.githubusercontent.com/43498612/206452734-83b5ba9d-9bff-4af3-9929-4d3fc3b32da9.png)

**Comment by artaxxx** [comment]
Yes if you input a value in degrees or radians you'll get the DMS result in the additional results:

![screenshot (2)](https://user-images.githubusercontent.com/20040032/206453847-ee0bdc4e-1a11-42e2-b430-979a1cfd3d28.png)
![screenshot (3)](https://user-images.githubusercontent.com/20040032/206453852-2a19db5f-3a51-4d77-b700-e1050e91baaf.png)

**Comment by Stephan-P** [comment]
Aha...
- So I calculate: 1278/17=75.176...
- Next I type: [Ans] ° = 1,3120... rad
- Next cursor up, right, right towards the ellipsis
- And then I'm able to see the DMS conversion 75°10'35.294..."

Slightly quicker when adding the ° in the first calculation:
- 1278/17 ° = 1,3120... rad
- Cursor up, right, right towards the ellipsis
- DMS notation 75°10'35.294..."

That's doable for those that know. 
It's equally cumbersome as with the TI-84 and not as easy as with other calculators. 

Just for comparison:
![image](https://user-images.githubusercontent.com/10008599/206476806-b4636d5f-dd58-40f7-9caa-7efa86b8bfc5.png)
or
![image](https://user-images.githubusercontent.com/10008599/206474667-f308eab2-d559-49b8-96ea-4bc6a142fe92.png)
or
![image](https://user-images.githubusercontent.com/10008599/206473551-292de14f-e39b-4d67-a4e9-d3ec55395ed0.png)

**Comment by Dummykid** [comment]
> Yes if you input a value in degrees or radians you'll get the DMS result in the additional results:
> 
> ![screenshot (2)](https://user-images.githubusercontent.com/20040032/206453847-ee0bdc4e-1a11-42e2-b430-979a1cfd3d28.png) ![screenshot (3)](https://user-images.githubusercontent.com/20040032/206453852-2a19db5f-3a51-4d77-b700-e1050e91baaf.png)

how do you input "degree" symbol in numwork? I am new to this calculator and i can't find the "degree" symbol.

**Comment by Stephan-P** [comment]
Only in v20 (beta)

- Toolbox
- Units and constants
- Length and angle
- Angle
- °

**Comment by Stephan-P** [comment]
https://user-images.githubusercontent.com/10008599/215865681-d1a19d4a-5474-41d3-a4c4-e89d22d08074.mp4

**Comment by Dummykid** [comment]
> 2023-01-31.20.40.55.mp4

Thank you and this is helpful, I am an Engineer and do a lot of DMS calculation for surveying, it looks like it would take a lot of steps to input "degree, mins and seconds". Which Numwork can assign a button for it.
