### ISSUE TITLE
Graphical issue with exam mode popup

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1825]
#### To Reproduce
1. Enter exam mode
2. Connect USB (the exam popup opens)
3. Disconnect USB
4. Recconect USB (you should enter DFU mode)
5. Press back
6. Disconnect and reconnect USB

#### Expected behavior
I would expect the text of the popup to be drawn (or when I disconnect USB I would expect the exam popup to close ?)

#### Environment
 - Epsilon 15
 - The platform(s) on which the problem happens:  n0110 (and probably n0100)

**Comment by Acssiohm** [comment]
This bug also happens, when you :
- Click on the Exam mode button ( the popup shows up )
- Connect USB ( should enter DFU mode )
- Disconnect USB
- Go again to click on the exam mode button, the popup shows up again, but incorrectly

**Comment by artaxxx** [comment]
This behavior has been changed in version 16
