### ISSUE TITLE
User defined functions with multiple arguments

### ISSUE THREAD

**Issue by OlegAlexander** [numworks/epsilon#1827]
Dear Numworks team,

I'd like the ability to create user defined functions with more than one argument in the Calculation app. Currently, it seems that I can only create functions with one argument. For example, I'd like to create the following function: `w*h -> area(w,h)`. For comparison, I'm able to do this on the TI-89 with `Define area(w,h) = w*h`.

The current workaround is to define the function in Python and use the Python interpreter. But I would prefer to define functions with multiple arguments in the Calculation app, where I spend most of my time.

Thank you.

**Comment by RedGl0w** [comment]
This is a duplicate of #1562

**Comment by OlegAlexander** [comment]
Ah yes. Before I posted my issue, I searched for "function arguments" and "function parameters", but not "function variables" :)  I will close this issue and subscribe to the other one. Thank you.
