### ISSUE TITLE
Opened and mixed intervals

### ISSUE THREAD

**Issue by thePeras** [numworks/epsilon#1829]
#### Problem you'd like to fix
When adding functions graphics there is the option to choose the interval we want to see the function (plot range).
However, we can only choose closed intervals.

![plote range](https://user-images.githubusercontent.com/53405284/115773342-19f12780-a3a8-11eb-95a7-1483dca1baa8.png)

#### Describe the solution you'd like
It would be nice if we could choose opened intervals or mixed. like

![mixed](https://user-images.githubusercontent.com/53405284/115774353-612be800-a3a9-11eb-92af-c639a00449d4.png)
![opened both](https://user-images.githubusercontent.com/53405284/115774354-61c47e80-a3a9-11eb-9aff-6e235fc5268a.png)

This could be done in the following panel by adding a switch to turn the interval closed or open.
Or a more mathematically solution.

 ![switch](https://user-images.githubusercontent.com/53405284/115774130-1a3df280-a3a9-11eb-9075-600f48bee57c.png)

By doing that, the plot will respect the domains that sometimes is required with open and closed points:
example on [5, 6[

![closed on 5, opened on 6](https://user-images.githubusercontent.com/53405284/115775048-4443e480-a3aa-11eb-86f1-8e00bd1b805b.png)

**Comment by artaxxx** [comment]
Now handled with piecewise functions in version 20
