### ISSUE TITLE
Functions with branches

### ISSUE THREAD

**Issue by thePeras** [numworks/epsilon#1830]
#### Problem you'd like to fix
Today we can't add functions plots with different branches. For example, defining f(x)=2x when x<2 and f(x)=4x when x>=2
This is useful, for example, when adding a function that the equation change in it's domain
example: 

![MTcase](https://user-images.githubusercontent.com/53405284/115775783-3478d000-a3ab-11eb-81e9-517ee937b16c.jpg)

The only solution to that is by adding more than one function and changing the interval of both.

So, the new solution pass by defining the function equation differently for different intervals by some mechanism.
Honestly, I don't know were is the best position and how this would be implemented for a simple and practical UI.

For this new enhancement would be needed the #1829 already implemented, I think.

**Comment by bgregorys** [comment]
Piecewise defined functions could be achieved by adding inequality testing to calculation mode. For example, if epsilon could parse the statements `a>b`, `a>=b`, and `a=b` (outputting 1 for true and 0 for false), then function above could be defined as follows.

`f(x) = a*(x<-1) + b*(-1<=x)*(x<0) + c*(0<=x)*(x<1) + d*(x>=1)`

**Comment by metawops** [comment]
Excellent feature wish!
I'd like to add that I's like to be able to use a similar thing in the definition of sequences.
Prominent example: the Collatz conjecture. (3n+1 problem)
So I'd like to define u_{n+1} to be either 3*u_n+1 if u_n is odd or to be u_n/2 if u_n is even.

**Comment by artaxxx** [comment]
Fixed in version 20
