### ISSUE TITLE
Error when computing a finite interval with a value assigned to x

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#1831]
#### Describe the bug
The output of `int(x+1/x,x,1,2)` changes if `x` is given a value.

#### Screenshots
![screenshot (49)](https://user-images.githubusercontent.com/55989/115785258-3764c800-a38d-11eb-925d-f6a568492758.png)
![screenshot (50)](https://user-images.githubusercontent.com/55989/115785260-392e8b80-a38d-11eb-84d9-9821c11dc009.png)

#### To Reproduce
See https://workshop.numworks.com/simulators/y573zk

#### Environment
 - Epsilon version 15
 - Every platform

**Comment by Ecco** [comment]
It seems like `x+1/x` is turned into `(x^2+1)/x` (that's ok), and then the `x` in the denominator is turned into a `1`, but not the one on the numerator. This yields `int(x^2+1,x,1,2)` which is indeed close to `3.3333`. If you put 2 into `x` then you get `1.66667` which would be compatible with this hypothesis.

**Comment by Ecco** [comment]
Instrumenting `Evaluation<T> IntegralNode::templatedApproximate(ApproximationContext approximationContext) const` shows that this is indeed what's going on.

**Comment by artaxxx** [comment]
@HugoNumworks , it's fixed right?

**Comment by HugoNumworks** [comment]
@artaxxx yes, it is fixed for V-16 !
