### ISSUE TITLE
A more recognizable exam mode

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1835]
At present a Numworks calculator IN or OUT OF exam mode can be distinguished by:

- Blinking led
- Graduation hat icon in the top status bar

In my opinion this is a little ... unimpressing, inconspicuous.

With another colour for the top status bar, the exam mode would be easier to identify from afar.
Maybe also the Graduation hat icon could be made to blink, so that it stands out more.

In the Netherlands, the TI-84 CE-T and HP Prime show an orange top status bar for the Dutch exam mode, as opposed to a black  GUI theme in normal mode. Confusingly, the Numworks calculator has an orange theme in normal mode and now I'm asking for another theme colour in exam mode. It's all going topsy turvy.
Anyway, I still think that the Numworks exam mode should be easier to identify from a far distance.

**Comment by artaxxx** [comment]
Thank you @Stephan-P . This is indeed a very important question. I'm going to close this issue because we work regularly with the CvTE on these subjects.
