### ISSUE TITLE
Physical calculator does not match simulator

### ISSUE THREAD

**Issue by theTisch21** [numworks/epsilon#1842]
#### Describe the bug
On complicated integrals, the online simulator does not match the physical calculator. I checked against Desmos, and the simulator is accurate.

#### Screenshots
![IMG_1620](https://user-images.githubusercontent.com/20461232/118176229-0143c280-b3e6-11eb-94cf-c3837f2f4d53.jpg)
Sorry about the image quality, I had to take the photo on my phone to show the physical calculator.

#### To Reproduce
1. Go to the 'calculation' app on the physical device
2. Type the integral shown in my screenshot
3. Press OK/EXE
4. Calculator will give incorrect result
5. Go to the simulator
6. Type the same integral
7. Press OK/EXE
8. Simulator will give correct result

#### Expected behavior
I expected the physical calculator to return 0.21034 like the simulator and like Desmos

#### Environment
 - Epsilon version 15.3.0
 - Actual device (N0110)

**Comment by artaxxx** [comment]
Hello @theTisch21 , by any chance, did you store a number in the `x` variable (on the device)?

**Comment by theTisch21** [comment]
There was a value stored in `x`! I cleared it, and it is now working normally. I'll make sure to clear my variables before integrating.  
Thanks!

**Comment by artaxxx** [comment]
For information, in the next version, we plan to ignore stored variables when calculating integrals

**Comment by theTisch21** [comment]
@artaxxx 
I've had this same thing happen to derivatives, will derivatives ignore stored variables as well?

**Comment by artaxxx** [comment]
Yes! They will also be ignored in derivatives!
