### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1843]
Could you please publish the Release notes here at github, at least for the latest version 15.5, but preferably for earlier versions as well?

https://github.com/numworks/epsilon/releases

Edit: link added

**Comment by artaxxx** [comment]
Hello @Stephan-P , we have chosen to publish our release notes on our website: https://my.numworks.com/firmwares. This allows us to adapt the language according to the country. The changes in version 15.5 do not really have an impact on the user, so we haven't changed the notes from the original version 15.
