### ISSUE TITLE
Python basic function problem.

### ISSUE THREAD

**Issue by Qwaks913** [numworks/epsilon#1848]
Hi, there is a major concern in the python's functions: when I execute a simple program like that:

```python
from math import *
import matplotlib.pyplot as plt
y = input("enter some function ")
a = 2

def x(t):
    return eval(y)
u = x(a)
print(u)
```

Python can't access to the function variable. I get an error message "Name error, t is not defined" but t is the input of the function... that sound stupid... Thank for fixing that quickly..

**Comment by adriweb** [comment]
It's not a Numworks issue, that's just not how python works, with the eval context/environment. 
You may be able to pass variables to its environment, I haven't really read in detail, but it looks like it's only working for globals (?) for MicroPython: http://docs.micropython.org/en/v1.15/genrst/core_language.html#code-running-in-eval-function-doesn-t-have-access-to-local-variables

**Comment by Qwaks913** [comment]
> It's not a Numworks issue, that's just not how python works, with the eval context/environment.
> You may be able to pass variables to its environment, I haven't really read in detail, but it looks like it's only working for globals (?) for MicroPython: http://docs.micropython.org/en/v1.15/genrst/core_language.html#code-running-in-eval-function-doesn-t-have-access-to-local-variables

actually, it is, python accept parameters in function (it's kinda basic) and uses it as a variable in the function. This program works perfectly on my computer, i often use functions like that for my digital analysis courses. look:
![image](https://user-images.githubusercontent.com/80359280/120118615-bff83480-c193-11eb-9bef-cbdfc325d817.png)

**Comment by adriweb** [comment]
Your computer is using Python, not MicroPython. This is not something NumWorks has developed. See my link again that mentions the difference with eval().

**Comment by artaxxx** [comment]
Thanks @Qwaks913 , I'm going to close this issue since is not concerning Epsilon
