### ISSUE TITLE
Add ability to do Normal Quantile Plotting(even if manually)

### ISSUE THREAD

**Issue by 133794m3r** [numworks/epsilon#1852]
#### Problem you'd like to fix
The current calculator doesn't let you select the plot type from the stats tab. If it let me plot a dot-plot with a line connecting values I could approximate the Normal Quantile graph. I've been using it through my stats course since I bought this calculator to use throughout college as the Python capabilities has helped me through it and I've found work-arounds/manual ways to do my work with it previously.

#### Screenshots
None

#### Describe the solution you'd like

Basically it'd work like thus.

Values 1 would be your input data.
Number 1 would be some formula(that'd let you call back a previous row and fill it) like you would in Excel/Spreadsheet software. It'd be PreviousColumn + FirstColumn*2. With FirstColumn = 1/Size. Then you'd apply invnorm(Amount,0,1) to each row when plotting the Y values. X would be the value itself.

This would then let you approximate the plotting type.

#### Describe alternatives you've considered
Since Python scripts can't write to the Stats data like you can on a TI calculator with the List variables I can't simply write a script to generate my data.

#### Additional context
This is for my Stats I course at the VCCS college they're teaching from Pearson so I'm certain that a _ton_ of students will also be using the same thing as Pearson is the primary textbook seller for all Virginia Community College Students and probably across the united states overall.

I'm not a C++ expert at all but if my solution seems doable I may try to hack something together if your team says it won' be a herculean task.

**Comment by artaxxx** [comment]
Fixed in 19.0.0
