### ISSUE TITLE
Python app make shift+arrows move across lines.

### ISSUE THREAD

**Issue by 133794m3r** [numworks/epsilon#1853]
#### Problem you'd like to fix
On the TI series calculators when you pressed 2nd+ arrow key it'd cause it to be modified when you're programming. If you pressed 2nd+left it'd move to the front of the line, if you pressed 2nd+right it'd move to the end. I'd like to see a similar thing in the Python application. Where if you pressed shift+left it'd take you to the front of the line and if you pressed shift+right it'd move the cursor to the end.

#### Describe the solution you'd like
Described above. It'd require modifying the input handler to add this special case to the cursor movements and add a modifier check.

#### Describe alternatives you've considered
Nothing else is considered.

**Comment by artaxxx** [comment]
Thank you @133794m3r! This is the behaviour we had at the beginning in the Python editor. We have modified this behaviour to allow the user to select a part of a text. Unfortunately, I don't think we're going to go backwards

**Comment by A2drien** [comment]
Why not use alpha + arrows, then ?

**Comment by artaxxx** [comment]
This is the eternal debate about hidden shortcuts. And this one is unfortunately very difficult to find :/

**Comment by 133794m3r** [comment]
I didn't even know that shift+arrows would highlight text for you when moving across it. This feature would _also_ help in the calculator application as I reuse formulas again and again and want to just modify a single or other variable. It'd make it a lot easier to be able to move around the lines more easily.
