### ISSUE TITLE
Occitan language not available

### ISSUE THREAD

**Issue by Mejans** [numworks/epsilon#1858]
Hello,
I cannot find the Occitan language.
I just come from your blog where you say you accept enhancements but apparently this one was never merged.
Why so?
Please update the software with Occitan in it.

**Comment by artaxxx** [comment]
A new language requires memory in the software, thus impacting every user worldwide. In addition to that, adding a new language means extra work for every software update. Today we do not have enough users who want to use the calculator in Occitan to distribute and maintain this translation
