### ISSUE TITLE
Python keydown() function doesn't work ( Epsilon 16.1.0 )

### ISSUE THREAD

**Issue by Acssiohm** [numworks/epsilon#1859]
#### Describe the bug
The python "keydown" function seems to return True whenever there is a key pressed in the same column.

#### To Reproduce
1. Create a python file 
2. Type for example , this program :

from ion import *
while not keydown(KEY_BACK) :
  if keydown(KEY_EIGHT) :
    print("8 key is pressed")
print("Back key has been pressed")

3. Execute the program 
4. Try to press the keys on the same column as the 8 key, like "5", "2", "cos" ...etc.
and you will see the message "8 key is pressed"
5. You can make the program stop by pressing the "Back" key, or every key on the same column, like "Backspace", "x^y" or "x²"

#### Expected behavior
The function should return True, only if the right key is pressed 

#### Environment
 - Epsilon version : 16.1.0
 - The platform : N0110 device

**Comment by Acssiohm** [comment]
Can't we access the source code of Epsilon 16 ?

**Comment by RedGl0w** [comment]
> Can't we access the source code of Epsilon 16 ?

Not yet. Numworks releases the source generally a few day after the stable release

**Comment by artaxxx** [comment]
It's fixed, we'll release a new beta soon

**Comment by Acssiohm** [comment]
> > Can't we access the source code of Epsilon 16 ?
> 
> Not yet. Numworks releases the source generally a few day after the stable release

Thank you @RedGl0w , I just start discovering Epsilon and git and GitHub so I'm a little bit lost ( it's the first time I look at a big project like this )

**Comment by RedGl0w** [comment]
> Thank you @RedGl0w , I just start discovering Epsilon and git and GitHub so I'm a little bit lost ( it's the first time I look at a big project like this )

It's not a generalized behaviour for project to have fully internal developpement (only some companies are doing that I think), but it's normal to be a bit lost :p
