### ISSUE TITLE
Cursor can't move the left when shift button is pressed ( Epsilon 16.1.0 )

### ISSUE THREAD

**Issue by Acssiohm** [numworks/epsilon#1860]
#### Describe the bug
In a text input ( and text area ) we cannot move the cursor to the left while holding down the shift key, but we can move it to the right

#### To Reproduce
1. Go to any app where you can type text
2. Type something 
3. Press the shift key ( and hold it down )
4. Press the Left key , it shouldn't move ( there is the problem )

#### Expected behavior
I expect the cursor to select the letters on the left, one by one, while I'm holding the Shift and Left key pressed, like it does on the right

#### Environment
 - Epsilon version : Epsilon 16.1.0
 - The platform : N0110 device

**Comment by artaxxx** [comment]
It's fixed, we'll release a new beta soon
