### ISSUE TITLE
Decimal comma as a separator for specific countries

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1867]
#### Problem you'd like to fix
The decimal separator is either a point or comma depending on where you do math.
Since Epsilon provides a way to specify language and country, this separator should follow accordingly.

#### Describe the solution you'd like
According to [this map](https://commons.wikimedia.org/wiki/File:DecimalSeparator.svg) from Wikimedia Commons,
![image](https://user-images.githubusercontent.com/28948599/132097195-1fd886b6-bc63-487d-ac64-812178eaca3f.png)

the settings in Epsilon should be as follow:
· point for: USA, UK
· comma for: France, Germany, İtaly, Netherlands, Portugal, Spain
· Canada depending on the language (point for English, comma for French)

**Comment by RedGl0w** [comment]
@artaxxx already explained the choice of space as separator [here](https://github.com/numworks/epsilon/issues/184#issuecomment-814708155).

**Comment by artaxxx** [comment]
Thanks @XanderLeaDaren . Yes indeed, this is something we thought a lot about when designing this new feature. Finally, we chose the most international standard for the thousands separator. The comma raised issues because it is used differently in the software. For the moment, there are no plans to change, so let me close this issue.

**Comment by Ecco** [comment]
Indeed we thought about this for a bit, and figured that this would yield a bunch of problems:
* What would happen when the user presses the `.` key on the numerical keypad? Would a `,` appear? Or would one need to use the smaller `,` key to input decimals?
* Sometimes the comma is used as a separator. For example, to separate arguments of multivariate functions (e.g. `root(2.5,3)`). Then this means we would need to come up with yet another syntax for locales using a comma as a decimal marker. Maybe something like `root(2,5;3)`. But then then semi-colon is even harder to type…

After thinking about all those issues, we reached the conclusion that it probably wasn't worth it 😄
