### ISSUE TITLE
Green led still on when calculator is switched off ...

### ISSUE THREAD

**Issue by SadE54** [numworks/epsilon#1870]
Hi, since the last firmware update (16.3) , my numworks has its led continuously green when calculator is off. 
And the led switch off when the calc is on 🤔
I understand now why it's discharging faster ...
I tried to reset it , still the same problem ...

**Comment by EmilieNumworks** [comment]
Hi @SadE54,
This sounds like a potential hardware issue with your calculator. Could you please send an email to contact@numworks.com describing your problem specifying the model you have (N0100 or N0110, written on the back of your device)?

**Comment by SadE54** [comment]
thx i just received a mail to send it back to Numworks 
What worries me i that I'm not the only one with the same problem.
https://www.reddit.com/r/numworks/comments/iqkbg7/help_my_green_led_wont_turn_offma_led_verte_ne/
 I just don' t want to send every 2 months the calculator back to SAV ... 🙄

**Comment by SadE54** [comment]
Afters some tris , I think it's definitely a software problem:
If I'm charging the calculator, whatever the calc is switched OFF or ON : the led is orange 
If I unplug the power, whatever the calc is off is OFF or ON : the leds becomes green.
Then each time I press the power button : the led is  toogled green/off 
It means that if I unplug the power while the calculator is off , the state of the  green led is always inverted.
It sounds like a software problem, not an hardware on ...

**Comment by cazeip** [comment]
What happens when you reset it using the button on the back?

What happens to the LED when you turn on exam mode?

**Comment by SadE54** [comment]
If i reset using the button on the back , nothing is changing.
And if activate the exam mode , the led is flashing red (ok) .
To deactivate ir from last firmware, yo have to plus it to a data usb. Asap it's deactivated the led is orange (charging)
When disconnect it the led becomes green. After that and it seems random , each powerpress can toggle the led or keep it green :-/
