### ISSUE TITLE
Version history - what's new

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1877]
I've requested before if proper release information could be published here at github, but that was deemed undesirable.

This time I'd like to request that the Version history as published on https://my.numworks.com/firmware is made less fuzzy, and more specific with **no repetition** of new/changed features that have already been listed in prior release notes. Please let the version history focus on the true what's new/changed?
I'm sure the public won't mind if it's a brief list.

**Comment by rkfritzsch** [comment]
I do explicitely support this request. Comparing https://my.numworks.com/firmwares#version-16-4-0 vs. https://my.numworks.com/firmwares#version-16-3-0 one gets the impression the one and only change was the date (September 23, 2021 vs. August 12, 2021)

**Comment by artaxxx** [comment]
We decided to publish all our changelogs on our website: https://www.numworks.com/calculator/update/
