### ISSUE TITLE
Keyboard shortcuts on the Home menu

### ISSUE THREAD

**Issue by Lesaloon** [numworks/epsilon#1883]
Hello,

### Problem you want to solve
Being a Casio user until very recently, I found it too bad that the shortcuts in the main menu are lost.

For example quickly press 1 to go into the "RUN MAT" application instead of using the arrow and then pressing "EXE". Also, pressing the 1 button puts our hands directly on the calculator's number pad, which will certainly be used right after.

### Describe the solution you want
I think adding this feature would increase usability and help Casio users in their transition. In addition to making the Numworks faster for power users

### Describe the alternatives you have considered
Maybe adding this feature would impact the user interface so maybe make it available in the settings

I did a test by adding icons on the interface:
![test UI](https://user-images.githubusercontent.com/47109666/135752192-ddd27d61-dfe1-41f5-902f-9bf9a5aaaac7.png)

**Comment by artaxxx** [comment]
Thanks @Lesaloon for your issue. I've just removed the FR version and added a title in English
