### ISSUE TITLE
Make the bootloader public

### ISSUE THREAD

**Issue by matteoturini** [numworks/epsilon#1899]
#### Problem you'd like to fix
Make the bootloader public so we can *actually* build the firmware.

#### Describe the solution you'd like
Making the bootloader repository for the calculator public so building the firmware works.

**Comment by Thauxeeb** [comment]
This was the reason I've bought this calculator...
It's supposed to be open-source. 🖕

**Comment by RhinoCodes** [comment]
THIS

**Comment by matteoturini** [comment]
> This was the reason I've bought this calculator... It's supposed to be open-source. middle_finger

They marked the comment as disruptive lmao

**Comment by Thauxeeb** [comment]
Maybe I’m disturbing their policy haha

**Comment by j0ni** [comment]
Is it literally impossible to follow the instructions on the website? That is, the entire page which explains how trivial it is to build and flash, with happy exclamation marks at the end, is in fact worthless because it doesn't tell you to initialize the submodule without which the build will fail, or that the repo will not in fact install because it is inaccessible to the reader? (I assume the authors don't read it, and that they have access to this repo).

I think you may have destroyed the nascent ambition of at least a handful of ADHD kids.

**Comment by loretoparisi** [comment]
This shall be done! This is what Texas Instruments finally realized it has to be done, and they finally did!  It does not make any sense to lock a calculator that as the main feature runs python, an open source language.
As a old times TI-90 [developer](https://github.com/loretoparisi/control-system-toolbox-for-ti89), I'm definitely disappointed.  Having the ability to make custom installs, made the TI-89 one of the greatest calculator ever! 

Please make this little jewel of the Numworks free again.


https://github.com/UpsilonNumworks/Upsilon/issues/158

**Comment by artaxxx** [comment]
You can build the userland and flash it: 

`if [[ $(python3 build/device/dfu.py -l | grep "0x90000000") ]]; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else; make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;`

We updated: https://www.numworks.com/resources/engineering/software/build/

However, we don't plan to release the sources of the bootloader.

**Comment by matteoturini** [comment]
> You can build the userland and flash it:
> 
> `if [[ $(python3 build/device/dfu.py -l | grep "0x90000000") ]]; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else; make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;`
> 
> We updated: https://www.numworks.com/resources/engineering/software/build/
> 
> However, we don't plan to release the sources of the bootloader.

Amazing! Many thanks. The problem (misleading documentation) was fixed.
