### ISSUE TITLE
HW test app triggered on wrong row

### ISSUE THREAD

**Issue by rhaamo** [numworks/epsilon#19]
In code, https://github.com/numworks/epsilon/blob/master/apps/settings/sub_controller.cpp#L67-L72 there is the following comment : 

>  We hide here the activation hardware test app: in the menu "about", by
>  clicking on '6' on the serial number row.

However, after test, the trigger works on the "FCC ID" Line, not serial number.

**Comment by Ecco** [comment]
Fixed by #60
