### ISSUE TITLE
Have functionality to draw pixels directly to the screen on external apps

### ISSUE THREAD

**Issue by matteoturini** [numworks/epsilon#1900]
#### Problem you'd like to fix
Drawing pixels faster, by directly drawing without the syscalls.

#### Describe the solution you'd like
A way to draw pixels to the screen directly, or pass an array of rgb values to draw.

#### PS
This would allow to do vsync, with eadk_display_wait_for_vblank

**Comment by Ecco** [comment]
This is unfortunately not going to happen. That's the whole point of having a kernel in place.

**Comment by matteoturini** [comment]
> This is unfortunately not going to happen. Being able to have some level of supervision over the userland is the whole point of having a kernel in the first place.

So, you push external apps as a replacement to custom firmware, then say you can't get the same level of customizability?

I upgraded to E16 not knowing you would impose such horrible restrictions, and lock me in. I bought this calculator with a promise of freedom, being able to flash firmware. I will gladly reset my calculator once my Raspberry Pi arrives.
