### ISSUE TITLE
Unable to "make"

### ISSUE THREAD

**Issue by MoreOwO** [numworks/epsilon#1901]
#### Describe the bug
When trying to make a "make", file named "logo_image.h"

#### Screenshots
![image](https://user-images.githubusercontent.com/62758885/141683994-19d64bc6-813d-4faf-b1b6-c41a2d13eed1.png)

#### Expected behavior
Well, no errors appearing

#### Environment
Windows 10 Msys2

**Comment by RedGl0w** [comment]
https://github.com/numworks/epsilon/issues/1873#issuecomment-922422912

**Comment by MoreOwO** [comment]
Thanks
