### ISSUE TITLE
[Beta 17] French terms in Functions app

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1904]
A big "Congrats!" for the work done in this version on functions! 🥳 

#### Problem you'd like to fix
Some terms are not the one used in French curriculum

#### Terms to use
* for e.g. f(x) = cos(x) : <strike>Cartésienne</strike> −> “Fonction” (or “Courbe représentative”?)
* for e.g. y = 5 x + 2 : <strike>Droite</strike> −> “Équation réduite”
* for e.g. -5 x + 3 y + 2 = 0 : <strike>Droite</strike> −> “Équation cartésienne”
* options menu: <strike>Domaine de tracé</strike> −> “Ensemble de déf.” (“Ensemble de définition” would be too long)
* for a line: m <strike>Pente</strike> −> “Coefficient directeur”
* in Calculus > Calculate > <strike>Zéros</strike> −> “Racines”

#### Additional context
Version 17.0.0 on actual device

#### Resource
French curriculum, classe de 2<sup>de</sup>.
[programme_2de_2019-01.pdf](https://github.com/numworks/epsilon/files/7611476/programme_2de_2019-01.pdf)

**Comment by Ecco** [comment]
`“Ensemble de déf.”` An abbreviation? Oh no! 😄

**Comment by Ecco** [comment]
> “Racines”

Actually, we've had the exact *opposite* request a while ago. A teacher argued that "racines" really only apply to [polynomials](https://fr.wikipedia.org/wiki/Racine_d%27un_polyn%C3%B4me), and that therefore we should use the more generic "zéros" name.

**Comment by artaxxx** [comment]
Some of them were improved in version 20. About "ensemble de définition" it's not actually this: it's a real Domaine de tracé, the function stays defined everywhere
