### ISSUE TITLE
Provide an easy way to simplify radiant angles

### ISSUE THREAD

**Issue by HarmoGlace** [numworks/epsilon#1905]
#### Problem you'd like to fix
I'm always frustrated when I have a radiant angle which is not simplified, and when I want to know its value, belonging to ]0;2π]. The calculator is able to simplify it (it is only a modulo 2π operation), but does not provide a way to do it easily. The angle is not simplified when applying some trigonometrical functions such as cos, sin or tan in the advanced menu.

#### Screenshots
Here is an example, when writing cos(9π/4), I would expect it to give θ = π/4 (or 0.25π, basically the same) in the θ line
<img width="194" alt="image" src="https://user-images.githubusercontent.com/23212967/143934335-7def341c-b16d-4789-9cb2-10f2bd095b8f.png">

#### Describe the solution you'd like
I would like to be able to get an angle simplified for instance when using cos, sin or tan, like in the above menu in the θ line.

#### Describe alternatives you've considered
I've also considered adding a function in the toolbox to simplify an angle, which would basically give the same angle but between ]0;2π]. It is a good alternative in my opinion.

#### Additional context
N/A

**Comment by artaxxx** [comment]
Nice idea!

**Comment by RedGl0w** [comment]
Maybe when inputing `cos(7π/4)` additional results could show `θ=7π/4≡3π/4≡-π/4` ?

**Comment by artaxxx** [comment]
Fixed in version 20
