### ISSUE TITLE
(-3)^-1.2 does not give the same result when the calculator is set on complex than when it's set on real

### ISSUE THREAD

**Issue by DegrangeM** [numworks/epsilon#1906]
<s>

#### Describe the bug
(-3)^-1.2 return ≈ 0,27 while the calculator is set in real mode but ≈ -0,22 - 0,16i while in complex mode.

#### Screenshots
![image](https://user-images.githubusercontent.com/53106394/144237389-495893ad-89fa-4ab9-a184-3da57d6972e7.png)

#### Expected behavior
I assume it should return unreal while in real mode ?

#### Additionnals info

There is the same issue with (-3)^1.2 but not with (-3)^1.3
It seems the issue require the number at the top to end with an even number
I think it try to convert (-3)^1.2 into (-3)²^0.6 but only do that if the top number end with an even number
But even if the last number is even, it does not always happen.
(-3)^0.78 will not bug for exemple

There is also the issue with any negative number at the bottom (instead of -3).

#### Environment
16.4.0 current online emulator</s>

**Comment by RedGl0w** [comment]
Somehow duplicate of https://github.com/numworks/epsilon/issues/1617

**Comment by DegrangeM** [comment]
> Somehow duplicate of #1617

Yes, closing this issue, I completly missed the fact that there was multiples solutions and the showed solution depend on the complex mode option.

**Comment by Ecco** [comment]
Well, it *is* a common problem, which is not that obvious. You'll probably want to read [this](https://en.wikipedia.org/wiki/Square_root#Principal_square_root_of_a_complex_number) and [that](https://en.wikipedia.org/wiki/Principal_value).

For the record, when computing a root, we use the following algorithm:
 - If the calculator is set in Real mode, we will return a real root, if any
 - If the calculator is in any Complex mode, we will return the principal root

Unfortunately, the principal root is not always real, so sometimes you get different outcomes, as you showed in your example. It is a bit confusing, but I'm not sure there's a better alternative. #1617 would definitely help though, but wouldn't completely solve the initial problem.
