### ISSUE TITLE
[Sequence] v_n shouldn't need u_n to be defined

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1911]
#### Describe the bug
You can't plot or get values of a sequence v if you haven't defined u.

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/146500967-278ee26a-1a7f-4e70-a186-b5afe94318e8.png)
![image](https://user-images.githubusercontent.com/43498612/146500986-a7ff73a8-0bcb-4008-88fa-3ccb6fae873c.png)

#### To Reproduce
1. Go to the sequence
2. Create an empty u_n
3. Create v_n = 5n
4. Remove u_n

#### Environment
 - All version since 15.5 (I guess)
 - The platform(s) on which the problem happens: all platform

**Comment by artaxxx** [comment]
Thanks @RedGl0w !

**Comment by HugoNumworks** [comment]
Fixed in 19.0.0
