### ISSUE TITLE
[Beta 17] correct French translation in Probabilities App

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#1915]
Thanks for the work already done with 17.1.0 on updating the French translation (see #1904)

İ noticed a remaining “flaw” in the French translation for Probabilities App: “Chi2” (in the listing) should be “Khi-2”, as it already is (“Loi du Khi-2”) after this distribution is chosen.

**Comment by KarineNumWorks** [comment]
Hello ! This change was done in version 23, I will close this issue consequently ! Thank you !
