### ISSUE TITLE
Améliorations dans les probabilités binomiales

### ISSUE THREAD

**Issue by BriacLP** [numworks/epsilon#192]
Bonsoir à vous !

Je ne sais pas si c'est ici que je dois écrire mais j'aimerais vous soumettre deux soucis que je rencontre avec la calculatrice (il y en a d'autre mais des sujets sont déjà en attente).

En effet dans le mode probabilité j'ai pu noter deux soucis, le premier se trouve dans les arrondies donnés par la calculatrice : pour une loi binomiale avec n=4 et p=0.125, quand je cherche P(X=4) je trouve 0. Normalement je devrais avoir 0.00024, alors certes on peut parler de négligeable mais ce soucis est très embêtant pour des calcules et résultats précis.

Le deuxième soucis vient quand cette fois je cherche P(0<X<1)=.... le résultat sur ma calculatrice est coupé et je n'ai donc pas accès au nombre exact.
![sqed](https://user-images.githubusercontent.com/32522843/31247193-1ea3426c-aa10-11e7-9bda-90e2a52e86e0.png)
Version de la calculette : 1.1.3

Merci de votre attention,

**Comment by Ecco** [comment]
Bonjour @BriacLP ! Merci beaucoup pour vos remarques ! Nous avons des contributeurs de différentes nationalités donc nous utilisons la langue anglaise pour faciliter l'échange.

Je me suis permis de traduire les problèmes que vous avez relevé : #193 et #194. Nous pouvons donc fermer ce ticket. Merci beaucoup !
