### ISSUE TITLE
Include Planck's Constant and Rydberg Energy Constant in list of Constants

### ISSUE THREAD

**Issue by kk723** [numworks/epsilon#1922]
#### Problem you'd like to fix
In a first semester General Chemistry Course, we need to do some calculations regarding Planck's Constant (h = 6.62607004 × 10^-34 J*s) and the Rydberg Energy Constant (R_y = 2.1798723611035×10^-18 J).

#### Describe the solution you'd like
Can you include those constants in Epsilon?

**Comment by mobluse** [comment]
I agree about _h, but it's probably more useful to have the Rydberg constant _Rdb = 10973731.53413/_m, because from that can be computed what you want _Rdb*_h*_c. Constants in TI-89: https://education.ti.com/en/customer-support/knowledge-base/other-graphing/product-usage/12143

**Comment by KarineNumWorks** [comment]
Duplicates #2225
