### ISSUE TITLE
Boîte à outil Proba/Dénombrement/arrangement et permutation

### ISSUE THREAD

**Issue by LaurBrug** [numworks/epsilon#1924]
Bonjour, pas certain d'être au bon endroit, mais je suis prof de maths utilisateur de la Numworks avec mes élèves et je constate des problèmes sur la boîte a outil "Dénombrement". 
Dans cette option, les "Arrangements" utilisent l'appellation "permute", or la permutation est également une fonction particulière et différente. 
D'autre part vous avez un tuto qui parle de "Dénombrement" de k parmi n (https://www.youtube.com/watch?v=XIpN6HeEMxw), alors qu'il devrait s'agir d'un Arrangement de k parmi n et que le résultat correspond à une "Combinaison".
Et pour finir la première ligne de la boîte à outil dénombrement n'a pas de nom, mais semble correspondre aux calculs de "Combinaisons". 
Bref j'ai l'impression qu'il faudrait reprendre cette rubrique Proba/Dénombrement, pour cela je vous conseille le cours d'Yvan Moka sur l'analyse combinatoire. https://www.youtube.com/watch?v=VVY4K-OT4FI Il dure 16 minutes et tout est dit ! ;-)
Merci, bon courage et votre calculatrice est par ailleurs géniale !!!

**Comment by artaxxx** [comment]
Merci pour votre issue ! 

Effectivement vous pouvez ici remonter des bugs ou des suggestions d'améliorations concernant le logiciel de la calculatrice. Il s'agit d'un espace d'échange international et les échanges se font donc en anglais pour que tout le monde puisse participer.

Dans la boite à outils, la syntaxe de la fonction est écrite en noir et la légende ou le nom en gris.

![screenshot - 2022-02-03T172713 647](https://user-images.githubusercontent.com/20040032/152384817-72a9f987-50c5-4164-94ef-88651f30ad8c.png)

* la fonction `permute()` correspond bien aux arrangements, son nom en noir est en anglais pour garder une syntaxe identique si vous changez la langue de la calculatrice (tout comme la fonction `random()` ou `sqrt()` en python par exemple) ; à titre de comparaison, dans Maple cette fonction est appelée `numbperm()` 
* le tutoriel est bien à propos du coefficient binomial ou combinaison, que nous appelons "k parmi n" dans la calculatrice ainsi que dans le tutoriel et que nous notons avec l'écriture habituelle : 
<img width="54" alt="Capture d’écran 2022-02-03 à 17 29 20" src="https://user-images.githubusercontent.com/20040032/152385209-d901d5f2-d322-447b-a052-2a649033fb19.png">

Je ferme cette issue mais je vous laisse en ouvrir une nouvelle en anglais si vous souhaitez proposer une amélioration ou remonter un bug !
