### ISSUE TITLE
Some "two-lines" calculation appear on one line

### ISSUE THREAD

**Issue by RedGl0w** [numworks/epsilon#1925]
#### Describe the bug
Some calculations which should appear on 2 different lines (`cos(pi/4)`) in some condition appears on 1 line, with the background of 2 lines

#### Screenshots
![image](https://user-images.githubusercontent.com/43498612/152579114-273b83fd-6c6e-4eda-ba88-e6d38ebca09b.png)

#### To Reproduce
1. Go to the calculation app
2. Add `cos(pi)` to calculation history and remove it
3. Add `cos(pi/4)`

https://my.numworks.com/simulators/1lqd2k1

#### Environment
 - Epsilon version 17
 - The platform(s) on which the problem happens: All

**Comment by artaxxx** [comment]
Thanks @RedGl0w for reporting this!

**Comment by artaxxx** [comment]
Fixed in version 19
