### ISSUE TITLE
Make another calculator model 

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#1926]
I'm always running into low memory issues, especially when doing large computations, and I liked the fact that the calculator used to be open source.
I believe that most High school students do not need higher compute capability but require the certification of their calculator for their exams.
Thus, I propose that you make another model of the calculator, physically different, with better compute capability and that isn't college certified. The fact that it isn't college certified means that the software can be open source once again.
This means that you'll need to maintain two versions of the os though.

**Comment by IoIxD** [comment]
If you don't mind it not being certified for either high school or college, and you don't mind getting your hands dirty, [you could mod a Raspberry Pi Zero into your calculator.](https://zardam.github.io/post/raspberrypi-numworks/) This is of course the extreme solution, however I don't think there is much of a need for a higher spec'd handheld calculator at the moment, as those who need more memory typically use a computer anyways...and on that note, you could also just use your phone.

**Comment by Moddingear** [comment]
> If you don't mind it not being certified for either high school or college, and you don't mind getting your hands dirty, [you could mod a Raspberry Pi Zero into your calculator.](https://zardam.github.io/post/raspberrypi-numworks/) This is of course the extreme solution, however I don't think there is much of a need for a higher spec'd handheld calculator at the moment, as those who need more memory typically use a computer anyways...and on that note, you could also just use your phone.

Those aren't calculators, they're computers with the problems coming with computers (slower boot times, higher consumption), and in the case of a phone, it doesn't have a dedicated keyboard and I haven't found a good calculator app for android yet.

**Comment by jmporcelg** [comment]
+1 Here, I would love a real open source calculator. Plenty of people don´t need to be concerned about "certified" devices for exams.

It should be easy to release the same hardware (or similar) but fully open, just a new model for tinkerers.

**Comment by IoIxD** [comment]
Open hardware calculator might be cool. However this is kind of the bare minimum for graphing calculators (TI's calculators are just unacceptable) and i would not expect a more powerful model. *Maybe* one with more RAM, but in the mean time this is fine.

**Comment by BloomyInDev** [comment]
I think they did what you wanted with the N120. Maybe ?
It's still software locked to epsilon so idk

**Comment by artaxxx** [comment]
I close this issue since we don't plan to design another calculator model
