### ISSUE TITLE
Icon no longer correspond to the calculated probability after going to the main menu

### ISSUE THREAD

**Issue by baptiste0928** [numworks/epsilon#1931]
#### Describe the bug
When you go to the main menu and then back to the Probabilities application, the icon designating the type of probability to be calculated no longer corresponds to what is selected. The bug is present whatever the selected probability law.

#### Screenshots
https://user-images.githubusercontent.com/22115890/156225070-bcdeeaa1-6412-404e-b495-90ce4d399500.mp4

#### To Reproduce
1. Go to the Probability app
2. Select one of the probability law and continue until you see the law.
3. Change the calculated probability using the left dropdown.
4. Press the 'Home' button.
5. Return to the Probability app
6. The icon returns to the default one and no longer corresponds to the calculated probability.

#### Expected behavior
The icon should correspond to the currently calculated probability.

#### Environment
 - Epsilon 17.2.0 (physical device and emulator)
 - Epsilon 18.0.0 (physical device, not tested using emulator)

**Comment by Ecco** [comment]
Thanks for the comprehensive bug report @baptiste0928 !

**Comment by HugoNumworks** [comment]
Hi @baptiste0928, thanks for the report !
The issue will be fixed in the upcoming version 🎉
