### ISSUE TITLE
Ability to write using the small font with kandinsky

### ISSUE THREAD

**Issue by Golem642** [numworks/epsilon#1932]
Hello ! I would like to ask you if it would be possible to add another argument to the kandinsky.draw_string function that would allow us to choose between the small font (used in the info bar at the top and when you change python police to small) and the normal one. That would be really cool to fit more things on the drawing screen. Thanks !

**Comment by artaxxx** [comment]
Duplicates #1895

**Comment by XanderLeaDaren** [comment]
Both this and duplicate #1895 were closed without explanation.
Is the ability to draw small font available somehow, or work on this not planned at all?
