### ISSUE TITLE
Issues with the accented letters in the eReader of Upsilon

### ISSUE THREAD

**Issue by mathUwUrin** [numworks/epsilon#1934]
when i put a .txt file in my calculator (under the last version of Upsilon), accented letters and apostrophes didn't show and let appear a "?" instead of the correct letter
#### Screenshots
![image](https://user-images.githubusercontent.com/101398581/157854906-d3e0fbff-caa7-4a5e-ba00-b260a321aff6.png)

#### To Reproduce
1. Go to the 'reader' app
2. click on a text with accented letters or apostrophes
3. see error

#### Expected behavior
i expected to see the accented letters

#### Environment
on Upsilon OS

**Comment by artaxxx** [comment]
Let's close this issue since it's not about epsilon
