### ISSUE TITLE
Is Github kept up-to-date?

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1936]
I'm surprised to see version 18.2 having been released this week while the code here at Github appears to have had its last update some 2 months ago.
Is Github not being used as the primary code repository, but rather as a public backup which got out of sync?

**Comment by Stephan-P** [comment]
![image](https://user-images.githubusercontent.com/10008599/158751538-7f730aed-1af5-482a-9af9-ef96f3aaca3a.png)

**Comment by adriweb** [comment]
They indeed have their own internal repo where development happens, then when it's ready enough it gets synced to GitHub.

**Comment by Stephan-P** [comment]
Anecdotal explanation provided by adriweb
Code appears to be updated
