### ISSUE TITLE
Closing bracket in Statistics - Histogram

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#1940]
![image](https://user-images.githubusercontent.com/10008599/159304554-483e52f5-2740-455a-ae79-9f719a36162a.png)
Interval [1.5; 2.5[
Surely that should be a closing bracket?

**Comment by adriweb** [comment]
If they mean that 2.5 is excluded from the interval, `[` is correct.

**Comment by Stephan-P** [comment]
Oooh, I wasn't aware of that notation.
Here in NL we'd use [1,5;2,5> for that.
Straight brackets for including the number, sharp brackets for excluding the number.
In that case I'd call this a language improvement suggestion

**Comment by adriweb** [comment]
In the USA it's also something else (that's more confusing...)

**Comment by adriweb** [comment]
France, at the very least :P

**Comment by Ecco** [comment]
Hi @Stephan-P, thanks for reporting this! Would you have any reference to an "official" specification for the `[a,b>` notation? As far as I know, the [ISO standard](https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints) only mentions `[a,b[` or `[a,b)`.

**Comment by Stephan-P** [comment]
I'm a mathematics teacher in the Netherlands and all Dutch secundary education schoolbooks for ages [12, 18] use the notation [1,5; 2,5>. (I can't seen to be able to type in the correct pointy right bracket here)

See also the Dutch wikipedia page on the mathematics interval: https://nl.wikipedia.org/wiki/Interval_(wiskunde)
![image](https://user-images.githubusercontent.com/10008599/159340327-5395c50b-bb0b-4d2c-b48d-734fc2761e20.png)

I can imagine that the Dutch way of writing intervals may be a bit peculiar (as we are wont to). At least I haven't come across other languages using the pointy brackets for open interval sides. 
After secundary education, mathematics is generally tought from English language books, so I gather the English notation [1.5; 2.5) would be quite acceptable as well. It would surely be easier to explain to the kids than the reversed brackets.

**Comment by Stephan-P** [comment]
Ah, they're called angle brackets or chevrons
https://en.wikipedia.org/wiki/Bracket
⟨ ⟩

**Comment by Ecco** [comment]
Awesome. Thank you so much!

**Comment by Stephan-P** [comment]
Solved in version 19.0
