### ISSUE TITLE
Prevent exam mode from flattening battery

### ISSUE THREAD

**Issue by parkermaths** [numworks/epsilon#1943]
Upon entering exam mode, the red LED starts flashing. From the perspective of a teacher, this is good for invigilating exams.

However, this light will just continue to flash indefinitely, even when the calculator is powered off until the battery is flat a day or so later. I realise that you can just plug the calculator in to fix this, but if we have 200 students sitting an exam, a significant minority would forget to do this and potentially arrive at their next exam with a flat battery.

This could be resolved by having an expiration on exam mode (e.g. 12 hours).

**Comment by Stephan-P** [comment]
Agreed. 8 hours would do as well. 
Additionally, there would need to be a place where one  can check the lapsed time or, better, the remaining time of the exam mode. E.g. the About menu or the Exam mode menu.

**Comment by artaxxx** [comment]
Unfortunately it is forbidden by some exam boards. So I'll have to close this issue
