### ISSUE TITLE
Improve accuracy in the statistics apps

### ISSUE THREAD

**Issue by BriacLP** [numworks/epsilon#195]
Hi !

In the Statistics app, I write values "4" and sizes "0.0006" etc. ...
The calculator rounds the number to 0 and therefore misstates the result obtained in "Stats".
I would like it to show 0.0006.

It's the same thing if I put 6.6 then I get 7etc.

![qfdzsqd](https://user-images.githubusercontent.com/32522843/31291831-70b63976-aad1-11e7-9b4a-4327bf195374.png)

**Comment by Ecco** [comment]
Interesting. When designing this app we thought sizes would always be integers. Apparently we were wrong. Would you mind giving us more context / more details about your use case? For example, are you trying to solve a specific exercise? Anyway, thank you very much for your feedback!

**Comment by BriacLP** [comment]
I am in Terminale S in France (end of high school).
Here is a summary of the statement in question:
We have a set of 32 cards, we draw 4 cards independently: X=number of aces drawn.
So the probability of drawing 1 AS is 1/8 (4/32). 
P (X=0) = 0.586181616406
P (X=1) = 0.3349609375
P (X=2) = 0.0717777734375
P (X=3) = 0.0068359375
P (X=4) = 0.00024140625
Seeing the worry I converted the results to have 58,33 etc... Otherwise I'd have had 0 or 1 all the time.

I also tried to "cheat" and write 2.4E-4 (for X=4) but here again we have a zero that appears.

**Comment by artaxxx** [comment]
Maybe the best thing to do to is to add a "custom" mode in Probability app. Instead of choosing Normal/Binomial/..., you would be able to select Custom and fill in a table:

| X | 0   | 1   | 2   | 3   |
|---|-----|-----|-----|-----|
| p | 0.1 | 0.2 | 0.5 | 0.2 |

I guess you want to find a standard deviation and E(X)?

Is there any other use of decimal values in "Sizes" ?

**Comment by BriacLP** [comment]
I'm not just looking for standard deviation and E (X), all the information in "Stats" is useful to me. Without forgetting that often we also need the box.
We can also imagine an exercise with dice, manufacturing percentages of a factory (15.5% of defective etc...).

**Comment by ian-abbott** [comment]
In your exam question about drawing cards, are the probabilities you give the observed (measured) probabilities? They seem to be close to (but not exactly equal to) the theoretical probabilities. Are you trying to measure how close the observed probabilities are to the theoretical probabilities?

**Aside**

Given:

* _N_ is the number of cards in the deck
* _A_ is the number of aces in the deck
* _k_ is the number of cards drawn randomly from the deck
* _x_ is the number of aces in the drawn cards

Then theoretically, the probability of drawing _x_ aces is given by:

>  P(_x_) = binomial(_k_, _x_) × binomial(_N_ − _k_, _A_ − _x_) / binomial(_N_, _k_)

When _N_ = 32, _A_ = 4, _k_ = 4, the theoretical P(_x_) values are:

* P(0) = 1 × 20475 / 35960 ≈ 0.569382647
* P(1) = 4 × 3276 / 35960 ≈ 0.364404894
* P(2) = 6 × 378 / 35960 ≈ 0.063070078
* P(3) = 4 × 28 / 35960 ≈ 0.003114572
* P(4) = 1 × 1 / 35960 ≈ 0.000027809

**Comment by BriacLP** [comment]
I rounded the results roughly because the problem is not here but on the calculator tool which is not precise enough (the standard deviation will be different what is in control makes lose all the points of the question because we don't necessarily have time to enter the whole formula :D).
And the fractions (like 20475 / 35960 or 1 / 35960) are also rounded.

**Comment by ian-abbott** [comment]
I can see that the mean value would be useful, as that is the "expectation value" for the number of aces drawn. I'm not so sure about the usefulness of the standard deviation as the distribution is not normal/Gaussian.

(For the curious, the theoretical mean in this case is exactly 1/2, and the (population) standard deviation is exactly sqrt(49/124).)

Still, other calculators do support non-integer sizes, so I guess Numworks should too.

**Comment by artaxxx** [comment]
Fixed by the last version (1.6.0)
