### ISSUE TITLE
Integral in complex cartesian mode takes too much time

### ISSUE THREAD

**Issue by Broyojo** [numworks/epsilon#1950]
When inputing the integral shown in the screenshot, epsilon freezes. This occurs on both models of calculator (N100, N110) as well as the simulator. The calculator is unusable and must be reset to recover. This only happens when cartesian format is enabled for complex numbers. I have tried with all other settings default, the only setting that makes this integral break is the cartesian mode. However, finding the integral with the grapher app works. By plotting the function and then finding the integral in the OK menu it works as expected and gives the correct answer. 

![67FF9D23-F45B-44C9-A102-8442DF645258](https://user-images.githubusercontent.com/20409082/165358486-ad4a4262-be4c-481b-9d66-1f5248b1e793.jpeg)

![BDD07F48-E86B-48FC-B342-AB21FF80E296](https://user-images.githubusercontent.com/20409082/165358660-0e66dea2-ea71-455e-9252-9c2697961477.jpeg)

1. Go to the Settings app.
2. Scroll down to Complex Format and click.
3. Select Cartesian.
4. Go to Calculator. 
5. Type in integral (integral of 44(x/100)^3*(1-x/100)^7 from 0 to 300).
6. Calculator Freezes.

I expect that it gives an answer of 270, but instead it hangs and I have to reset it.

 - Epsilon version: 15.5.0 & 18.2.2 (I tested these two, there are probably versions in-between and before).
 - Platforms affected: N100, N110, Simulator

**Comment by artaxxx** [comment]
Thanks for your issue! Indeed, this computation seems to take some time. It's not a crash since the calculator doesn't restart by itself. It's only a calculation that is too long to be done.

You can interrupt such calculations by pressing the Back arrow key!
