### ISSUE TITLE
Led is always green, even changing exam mode red led

### ISSUE THREAD

**Issue by Pokegali** [numworks/epsilon#1952]
#### Describe the bug
It's quite simple : the led is constantly green, even when the calculator is off and not charging (and reinstalling everything doesn't change anything)
Also when I turn on exam mode, the led blinks in red as it should, but after pressing the power button, which should not do anything to the exam mode, the led turns green (and switching the calulator on again doesn't make it red again)
The led also becomes orange when I charge it, so it's not dead or anything I guess, but after unplugging it, it becomes green again

#### Screenshots

https://user-images.githubusercontent.com/83755025/168117444-373cbea3-b6f6-4dc3-a4c6-c7ad6f66ee30.mp4

In this video, the exam mode is on (the red led is blinking), and after turning the calculator off, the led becomes green.
The exam mode is still active though

#### To Reproduce
I don't really know how it happens, however I think it has something to do with the usb, because the battery indicator always shows a tick, like if it was fully charged and still charging. 

#### Expected behavior
I would expect the led to turn off when I don't use the calculator, and also not to stop the exam led from blinking.

#### Environment
Latest version of espilon (18.2.3), numworks N0110

**Comment by artaxxx** [comment]
Thanks for your issue. It's a customer service issue here (it's not a bug but an uninvited and non reproductible behavior) I invite you to send an email to contact@numworks.com with your problem and your serial number
