### ISSUE TITLE
Add option to generate modified boxplot

### ISSUE THREAD

**Issue by beetshrimpraspberry** [numworks/epsilon#1954]
In AP Statistics, they often require something called a modified boxplot. This is a boxplot that excludes the outliers from min and max, and adds them as dots to the graph. 

See example from online:
![image](https://user-images.githubusercontent.com/105967255/169642100-86d5dc8b-799f-49a4-b7d2-8f1a0a725873.png)

**Comment by artaxxx** [comment]
Fixed in 19.0.0
