### ISSUE TITLE
Using different variable name (i,x) change the result 

### ISSUE THREAD

**Issue by philippe1973** [numworks/epsilon#1960]
#### Describe the bug
i,x variable has differents result for the same formula. Issue is in exponential function n! 

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/60552903/172059358-6538f48a-8ac5-4d9d-8876-c81d039aff82.png)

#### To Reproduce
Introduce  twice the same sum fomula one using default i variable the other using x variable 

#### Expected behavior
The 2 formula give the same result 2.718... -> e

#### Environment
Test on online simulator

**Comment by adriweb** [comment]
That `i` in bold represents the complex `i`.
See [the changelog](https://www.numworks.com/calculator/update/version-19/) where it says: "The characters `e` and `i` are now the characters used for the e of the exponential and the complex number i. Indexing of sums and products now uses the variable k."

**Comment by philippe1973** [comment]
erreur issue
