### ISSUE TITLE
Trigonométry

### ISSUE THREAD

**Issue by Skyzwaiy** [numworks/epsilon#1961]
I think It will be very useful to input a "trigonomy" part in our Numworks. There is to much thinks about trygo to doesn't input a "trigo" part

**Comment by matteoturini** [comment]
I think they meant an app that automatically calculates trigonometry values. Like inputting two measures, and it shows the entire triangle's measurements, or with one measure the calculations for the measurements.

**Comment by artaxxx** [comment]
For now we have improved the additional results in trigonometry. We don't plan to go further in the near future
