### ISSUE TITLE
Numworks isn't open source anymore.

### ISSUE THREAD

**Issue by WowLeDore** [numworks/epsilon#1962]
I think the point of having a Numworks Calculator was to install/modify anything you want or can but with the 1.16 and now the 1.18 it's simply not possible anymore.
I, as a French, find it a shame that a company from my country simply destroy what everyone says there were doing. Now a Ti or a Casio is exactly the same and it's pretty sad.

**Comment by artaxxx** [comment]
I close this issue since it's not in our plans to change this policy

**Comment by WowLeDore** [comment]
No worries i found a way to unlock it ^^
