### ISSUE TITLE
Cannot multiply percentages if they are at the left without parenthesis

### ISSUE THREAD

**Issue by AntoninLoubiere** [numworks/epsilon#1963]
#### Describe the bug
The ability to multiply percentages (which is really nice) is kind of inconsistent:
You can write 25 * 90%, but writing 90% * 25 will return a syntax error.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/40536532/172559724-9bf6027c-3a42-4fbd-91ad-8325c9115bc6.png)

#### To Reproduce
1. Go to calculation app
2. Write 25 * 90%
3. Press enter
4. The result should be 22.5
5. Write 90% * 25
6. Press enter
7. There is a syntax error

#### Expected behavior
90% * 25 should be interpreted as (90%) * 25.

#### Workaround
You can work around this issue by typing the percentage at the end or by putting parenthesis.

#### Environment
- Epsilon beta version 19 (emulator).

**Comment by HugoNumworks** [comment]
Fixed in 19.1.0
