### ISSUE TITLE
make: *** No rule to make target 'epsilon_flash'.  Stop.

### ISSUE THREAD

**Issue by UCYT5040** [numworks/epsilon#1972]
#### Describe the bug
I am trying to flash epsilon.
I run `make epsilon_flash`. Everytime I run this I get the error `make: *** No rule to make target 'epsilon_flash'.  Stop.`

#### Screenshots
Not related to the calculator.

#### To Reproduce
1. Just run `make epsilon_flash

#### Expected behavior
The OS to flash to the calculator.

#### Environment
 - Epsilon version: The current version on github
 - The platform(s) on which the problem happens: Trying to build on Ubuntu

**Comment by EmilieNumworks** [comment]
With your device plugged, try: 
`if [[ $(python3 build/device/dfu.py -l | grep "0x90000000") ]]; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else; make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;

Sources: instructions are [here](https://www.numworks.com/resources/engineering/software/build/)
