### ISSUE TITLE
LED On Exam Mode

### ISSUE THREAD

**Issue by Lisra-git** [numworks/epsilon#1975]
#### Describe the bug
Exam mode LED can be hijacked with in factory test menu

#### To Reproduce
1. Go to the Settings app
2. Enable Exam Mode
3. Go to the FCC Label and trigger the Test mode
4. Go through the steps and see the led change to a fixed led colour which is not the allowed

#### Expected behavior
LED Should keep it's exam function and doesn't change no matter what's done to it

Attempt to fix by blocking Test mode in Exam with #1951 

Also, it would be preferable that the flashing frequency does not vary during long calculations in exam mode in order to avoid any suspicion of cheating due to a simple defect of the OS

#### Environment
 - Epsilon version (Settings > About > Software version). 19.4.0
 - The platform(s) on which the problem happens: device

**Comment by artaxxx** [comment]
Fixed
