### ISSUE TITLE
Error when trying to setup calculator as third party app

### ISSUE THREAD

**Issue by integrated-circuit** [numworks/epsilon#1977]
#### Describe the bug
when trying to setup epsilon as an 3rd party app, got a syntax error which says "bash: erreur de syntaxe près du symbole inattendu « ; »"

#### Screenshots
![Capture d’écran du 2022-09-21 09-24-00](https://user-images.githubusercontent.com/68387582/191440969-28643966-4e08-4a6f-96a7-a00edd90f28a.png)

#### To Reproduce
1. Go to  https://www.numworks.com/resources/engineering/software/build/
2. go to Run Epsilon on your calculator as a third-party software part
3. Run make clean
if [[ $(python3 build/device/dfu.py -l | grep "0x90000000") ]]; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else; make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;

#### Environment
 - Epsilon 19.5
 - Numworks calculator n110 + ubuntu 22.04 install with WebDFU working and calculator being connected

**Comment by EmilieNumworks** [comment]
Thanks @integrated-circuit for the issue!
You're right: "[[" is bash-specific. I'll change the command for a more generic one...
Can you please try running the following command?
`if expr "$(python3 build/device/dfu.py -l | grep '0x90000000')" > /dev/null; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else; make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;`

**Comment by integrated-circuit** [comment]
same as be as before, ive got the same error "bash: erreur de syntaxe près du symbole inattendu « ; »"

**Comment by integrated-circuit** [comment]
calc is connected and listed in python3 build/device/dfu.py -l, here is what i got in the terminal : 
Bus 3 Device 014: ID 0483:a291
Memory Layout
    0x90010000 63 pages of  64K bytes
    0x90400000 64 pages of  64K bytes

**Comment by integrated-circuit** [comment]
im using bash as terminal

**Comment by EmilieNumworks** [comment]
To flash your calculator, you can just do:
```
make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu
```
However, I'm not sure about which ";" your bash version doesn't understand.

**Comment by EmilieNumworks** [comment]
Haha, can you try:
```
if expr "$(python3 build/device/dfu.py -l | grep '0x90000000')" > /dev/null; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;
```
?

**Comment by integrated-circuit** [comment]
it works but after that asks me to get an official update from numworks to run a 3rd party app

**Comment by integrated-circuit** [comment]
because of the kernel or smth, but im already on 19.5.0
Quick question: this manipulation unlocks the bootloader or not?

**Comment by EmilieNumworks** [comment]
The newly flashed userland should refer to the same EPSILON_VERSION than the current software your device is running. Make sure that `EPSILON_VERSION=19.5.0 `in `build/config.mak` and rerun 
```
make clean
if expr "$(python3 build/device/dfu.py -l | grep '0x90000000')" > /dev/null; then make userland.A.dfu; python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu; else make userland.B.dfu; python3 build/device/dfu.py -s 0x90410000:leave -D output/release/device/n0110/userland/userland.B.dfu; fi;
```
(I just updated the repo sources to the version 19.5.0 which is the last firmware available from the official update)

**Comment by EmilieNumworks** [comment]
The manipulation doesn't unlock the bootloader 😅

**Comment by integrated-circuit** [comment]
is it possible to unlock the bootloader with the SDK? I need to install custom apps on the numworks calculator

**Comment by integrated-circuit** [comment]
or could you give me a guide on how to install 3rd party apps on epsilon pls?

**Comment by EmilieNumworks** [comment]
You can find a documented example apps in [C++](https://github.com/numworks/epsilon-sample-app-cpp) and in [Rust](https://github.com/numworks/epsilon-sample-app-rust)
