### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by ChuckM** [numworks/epsilon#198]
The Font size on the current calculate app makes the digits 3mm tall which is probably half the size they need to be for easy legibility. A quick survey of existing calculators shows that 6mm is fairly typical for calculators of this size, with some specialist ones having 10 and even 12mm digits on the line of entry. 

At a minimum it would be useful to be able to set the size in Settings.

**Comment by yeKcim** [comment]
being able to set the size in Settings is a good idea, I personally think the font size is too big :-D

**Comment by AlainBusser** [comment]
:+1:  If you compute a probability the result may be invisible if there are too many digits: Having them smaller would yield the possibility to see them again

**Comment by Ecco** [comment]
So apparently it's the kind of situation where you cannot make everyone happy 😢 

We've made an extensive benchmark before settling on a font size. We've researched and compared existing graphing calculators. One the most basic ones the digits are indeed often larger, but we've yet to find a graphing calculators with 12mm-high digits: indeed, on those devices, one often need to display quite a few digits, so they just can't be too large.

Anyway, thank you @ChuckM for reporting this. I'm sorry we will most likely not change the default font size in the near future (unless a majority of users ask for it). That being said, thanks to the open nature of Epsilon you can run your very own NumWorks calculator with a larger font size (you can even use a custom font if you like). It should be as easy as [editing this line](https://github.com/numworks/epsilon/blob/2e6ee2e1f289af3bb0433f08e9b33741e9f03198/kandinsky/Makefile#L54) in the Makefile.
