### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by rorobiks-cube** [numworks/epsilon#1983]
Hi,
Why not add a 'equation-verification' app in the calculator, like that, why can see if we write is true or not. 
exemple:i tap 'x=2x' and the calculator return 'False'.
Thanks you for reading that and sorry for my english,
Romain

**Comment by Yaya-Cout** [comment]
You can take a look at b8544e3. This commit disables this behavior.

**Comment by artaxxx** [comment]
Fixed in version 20
