### ISSUE TITLE
Open Source License Clarification

### ISSUE THREAD

**Issue by Destroyinator69420** [numworks/epsilon#1985]
#### Problem you'd like to fix
There is no license listed to the side of your repository. I would like to know what license you license your OS under. I hear that it is a creative commons license. The unclear license means that I cannot use epsilon because I do not know what I am agreeing to.

**Comment by Yaya-Cout** [comment]
From Epsilon 16, the license is strong copyright (All right reserved, at the end of the README). Before, it was a Creative Common License. That's why Upsilon and Omega are based on Epsilon 15.
