### ISSUE TITLE
External App size

### ISSUE THREAD

**Issue by Lisra-git** [numworks/epsilon#1986]
The recents development around external apps showed that it was possible to overwrite second slot to be able to use it for big apps like KhiCas or apps which require high size external data such as video player.
nwlink and the my.numworks.com/apps installer shouldn't lock overwrite of second slot and doesn't set size of 4Mo as a per slot system, this should be modified to allow for more opening in use of apps on Epsilon.

**Comment by Lisra-git** [comment]
Also, having 1 permanent slot in ram/external flash to allow for data save would be needed

**Comment by EmilieNumworks** [comment]
In order to keep the upgrade process robust, we currently have no plan to support external apps using more than their designated slot space.

**Comment by Lisra-git** [comment]
Anyway, external apps are getting "cleared" from install as soon as you update?
I don't see how update make this not possible
