### ISSUE TITLE
Unable to move cursor to upper curve. 

### ISSUE THREAD

**Issue by ShreyasAyyengar** [numworks/epsilon#1988]
#### Describe the bug
When graphing a function that has two separate curves, there is no way to move the cursor to the upper/lower curves.

#### Screenshots
Please provide at least one screenshot of the issue happening. This is by far the best way to quickly show any issue! To attach a screenshot, just go to our [online simulator](https://www.numworks.com/simulator), navigate to reproduce your issue, and click the "screenshot" button. Then drag'n'drop the file here!

#### To Reproduce
1. Go to the 'Grapher' app
2. Type any function that has two curves, separated by an asymptote. I used `f(x)=3-(12/x+3)` I had a restriction of my x values for `[-9, 9]`
3. The cursor will default to the lower curve. According to the user manual:
<img width="527" alt="Screenshot 2022-11-01 at 12 36 07 PM" src="https://user-images.githubusercontent.com/65931801/199159612-d50e8be9-901f-47a5-a020-18251d8ef2c9.png">
However pressing the up arrow key, moves the cursor to the 'Auto' button, instead of moving the graphing cursor to the upper curve. 
<img width="368" alt="Screenshot 2022-11-01 at 12 32 53 PM" src="https://user-images.githubusercontent.com/65931801/199159843-8c83bf4d-0343-42c5-a8c8-8bc9e95c9cf1.png">

#### Expected behavior
When pressing the up arrow key, it should move the cursor to the lower/upper curve, and not to the header buttons. 

#### Environment
 - Epsilon version `19.5.0`
 - The platform(s) on which the problem happens: Online simulator & Phyiscal Device

**Comment by adriweb** [comment]
Well it's the same curve, so you'd want to navigate with left/right until
it "jumps" to the other side because of the undefined value. --
Thank you,
Adrien Bertrand

**Comment by RedGl0w** [comment]
As @adriweb told, the up and down keys can only be used to navigate between curves which are vertically aligned (for instance two functions defined at this x, a circle, ...)

**Comment by ShreyasAyyengar** [comment]
> Well it's the same curve, so you'd want to navigate with left/right until it "jumps" to the other side because of the undefined value.

When you mention navigate, do you mean use the navigate tool, to shift display until the lower curve cannot be seen, so the cursor defaults to the visible curve? Or do you mean use the left/right arrow keys so move the cursor until it snaps (because this doesn't work, it just stays still once it's reached the end of the curve and it won't snap up)

**Comment by adriweb** [comment]
Oh hm weird, I remember doing that just with the arrows, although that was some time ago...

**Comment by ShreyasAyyengar** [comment]
Is it still possible to do that now?

**Comment by adriweb** [comment]
I just checked, it works fine for me going left/right (it goes down a bit first, as expected) to jump from the two parts of the equation.

**Comment by ShreyasAyyengar** [comment]
> I just checked, it works fine for me going left/right (it goes down a bit first, as expected) to jump from the two parts of the equation.

Ahh, I see. I didn't realise I had to drag the cursor down quite a lot for it to snap back up. Thank you for your help!
