### ISSUE TITLE
How do we build on n0120 calculator ?

### ISSUE THREAD

**Issue by DarkBrines** [numworks/epsilon#1993]
I wanted to build my version of epsilon on my n0120 calculator, but the numworks website is not updated and we can't get this information here. So is it even possible to do it ? What dfu should I build ? At what address should I flash it ? Do the calculator need to be in rescue mode ?

Thanks for your answers.

**Comment by DarkBrines** [comment]
Do you have the answer ?

**Comment by RedGl0w** [comment]
- the kernel and the bootloader are private
- the userland is still accessible for everybody, but for now, [you can't reflash it](https://github.com/numworks/epsilon/blob/bb3baa7466f39f32b285f2d14b6dc1f28e22e7a5/build/platform.device.n0120.mak#L2)

**Comment by Stephan-P** [comment]
How about we all face it that the Numworks graphic calculator is no longer (fully) open source and just stop asking questions like these?
And I would suggest that Numworks also reflects this here on the various github landing pages, as well as the Numworks website.

**Comment by DarkBrines** [comment]
Probably
