### ISSUE TITLE
Website bug

### ISSUE THREAD

**Issue by Miniontoby** [numworks/epsilon#1994]
#### Describe the bug
Uhmm I made some code which gave me always the MemoryError, so I catched it, but I added i-=1 in my code and now it doesn't stop running and it crashes my browser tab. And I cannot edit my script anymore because of it

#### Screenshots
![image](https://user-images.githubusercontent.com/47940064/203852200-157c5f31-7af6-4302-8147-ae0679e2ac7d.png)

#### To Reproduce
1. Go to https://my.numworks.com/python/miniontoby/qr/edit (as admin, cause it is hidden and I cannot make it public anymore)
2. And your browser window will not react anymore after 10-20 seconds

#### Expected behavior
I hope you guys can edit the file somehow from the server side to remove the `i -= 1` line (somewhere near line 200)

#### Environment
 - [Website](https://my.numworks.com/python/miniontoby/qr/edit)

**Comment by LeaNumworks** [comment]
Hello @Miniontoby, I commented the two "i -= 1" lines in your script. Hope it works! We should try to better handle this kind of problems in our script editor.

**Comment by Miniontoby** [comment]
It still doesn't work...

**Comment by Miniontoby** [comment]
maybe just replace the
```py
for i in range(8):
  try:
    qrs.append(copy(qr))
  except MemoryError:
    sleep(1)
    #i-=1
```
into
```py
for i in range(8):
  qrs.append(copy(qr))
  sleep(1)
  #i-=1
```

Cause then it will at least give me the MemoryError instead of continueing

**Comment by LeaNumworks** [comment]
I commented all these lines, it should work now.

**Comment by Miniontoby** [comment]
Thx now it give me `IndexError: list index out of range` which is better than crashing the browser!
