### ISSUE TITLE
Phasor Support *My Solution*

### ISSUE THREAD

**Issue by ghost** [numworks/epsilon#1995]
I have heard a few people complain of troubles using phasors in degrees for problems such as circuit analysis. I have found a great solution and I do not know where else to post my results. I hope someone finds this useful.

I created two functions that give me what I need.

The first is to convert rectangular to pol with the angle in degrees.

![screenshot (1)](https://user-images.githubusercontent.com/71900640/204054452-bc93eaae-088b-41b8-b5cd-13c69bda7937.png)
![screenshot](https://user-images.githubusercontent.com/71900640/204054461-ccc385a3-6520-4095-97ad-55d5a7800116.png)

As you can see, you get the results in a matrix with magnitude and angle.

The next is to enter a complex number in magnitude and angle without using the exponential all the time.

![screenshot (2)](https://user-images.githubusercontent.com/71900640/204054521-c8e54217-e110-4ec9-bf66-4b57a7a944e5.png)
![screenshot (3)](https://user-images.githubusercontent.com/71900640/204054527-47df5b9c-86cb-42b5-a0be-0fb866e2e528.png)

I hope someone finds this useful, it does seem like an obvious solution looking back.

**Comment by adri1numworks** [comment]
Hello,
Phasor notation is already treated in two other issues, https://github.com/numworks/epsilon/issues/857 and https://github.com/numworks/epsilon/issues/1161

I close this issue as this would be a duplicate. Feel free to comment if ever I misunderstood your suggestion.

**Comment by imadnyc** [comment]
Oh my god, I can't believe I didn't use this before!

**Comment by achkasov** [comment]
It is a very convenient workaround. To bad that there is still no way to have a user defined functions catalogue which lives separately from the Graphing app (see: #2170).
