### ISSUE TITLE
SDK doc: make dfu_flash or app_flash ?

### ISSUE THREAD

**Issue by rhaamo** [numworks/epsilon#20]
When trying to do a ```make dfu_flash``` I got an error :

```
$ LC_ALL=C make dfu_flash
LD      dfu.elf
ion/src/device/boot/rt0.o: In function `start':
rt0.cpp:(.text.start+0x32): undefined reference to `ion_app()'
Makefile:88: recipe for target 'dfu.elf' failed
make: *** [dfu.elf] Error 1
```

It looks like it's ```app_flash``` instead, which launched dfu-util and flashed the calc.

**Comment by artaxxx** [comment]
The software documentation was changed according to your comments.
