### ISSUE TITLE
calculus history

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#200]
Enhancement: In calculus, left button could directly copy/paste previous formula (not ans)

**Comment by adriweb** [comment]
That would be too annoying if/when pressed on mistake.
AFAIK, recalling the previous input is only 3 presses: [up][up][enter], so it's not too bad.

**Comment by Ecco** [comment]
Thank you @yeKcim for the suggestion. However this is not something we're going to follow through with: like @adriweb mentioned, it only saves a couple keystrokes and can get really annoying if pressed by mistake. It's also not very recognizable/discoverable.
