### ISSUE TITLE
SIGMA summation and PI product functions

### ISSUE THREAD

**Issue by Stephan-P** [numworks/epsilon#2001]
Version 19.5 seems to be missing the SIGMA and PI functions for calculating the sum or product of direct function sequences.

TI-84 and HP Prime have such convenient functions in their toolboxes where one can easily and naturally define the summation from n=1 up until 12 of the sequence defined by a direct function, say 1/n.
Similarly the PI function can be defined to calculate the product of a sequence based upon a direct function.

![Screenshot_20221205-001700](https://user-images.githubusercontent.com/10008599/205521688-a3cea70b-eb31-4c65-a578-62ee8ecc858b.jpg)

Surely, it can be done today, using Toolbox, lists, list from function, Toolbox, lists, sum(L), paste the previous list, exe. But that is so not intuitive, so clumsy, so unnatural.

![Screenshot_20221205-002110_NumWorks](https://user-images.githubusercontent.com/10008599/205521886-4bcd7e84-ec30-4ecd-854c-8afe8b17abc0.jpg)

**Comment by josefdmiller** [comment]
If so then they are found under calculus in the toolbox.

**Comment by Stephan-P** [comment]
Calculus, Differentiaalrekening in Dutch (freely translated that would be 'differential calculations'), to me is 'all calculations related to dx'. 
I never thought to look for them there.
Thanks for the pointer. I'll try to widen my definition of calculus and remember to find these two over there.

**Comment by Stephan-P** [comment]
I'm having difficulties regarding the SIGMA and PI functions to fall in the category Calculus.

But maybe I am astray. 
If not, then I'd suggest moving the two items to Toolbox > Lists > 
![image](https://user-images.githubusercontent.com/10008599/205947010-04ffcedb-2684-4cc4-bb8c-84313d1e102f.png)
