### ISSUE TITLE
A glitched screen appeares in function mode

### ISSUE THREAD

**Issue by TSV3000** [numworks/epsilon#2002]
####Description
a glitched screen appeares

#### To Reproduce
1. Go to the function menu
2. Start drawing whatever function that takes time to draw ex:" f(x) = random() "
3. While it is drawning double click back button
4. The function should be half-drawn and graph selected
5. Click twice the start/stop button
6. See error

#### Expected behavior
Most of the screen is covered whith a black and white horizontal stripe pattern
Some pixel take a simingly random rgb value
This does not seem to impact the calculator otherwise

#### Environment
This bug works only on the calculator and not on the emulator

**Comment by pitonyak** [comment]
not able to reproduce on an actual calculator using 21.2.0

I will reword the steps that I used and you can correct me where I went wrong.

Lets start by defining the "go back button"
![image](https://github.com/numworks/epsilon/assets/98656/7d16df04-ac3c-45d9-bede-dd9fb00419b2)

Backspace button
![image](https://github.com/numworks/epsilon/assets/98656/bb9374ef-cd98-4c54-9d9c-23d0db975ae6)

The directions use the term "click", which makes me thing of the emulator as opposed to "press the button" on a calculator.  

I have no idea what is the "stop / start" button, I simply do not see one, but, the return button seems to do this.

1. From the home screen, select the Grapher application.
2. Select the "Expression" tab and add an element (I assume none exist).
3. Add the function "f(x) = random()"
4. Select "Plot Graph".
5. Consider the instruction "While it is drawing double click back button". By the back button I assume that this is the "go back" button and not the backspace button and not a button on the four arrow keys. 
6. The function should be half-drawn and graph selected. Not what I see. If I press the return button once so I will stop here and describe what I see below.
7. Click twice the start/stop button. Did not get here, see comment above as being unsure that I am pressing the correct buttons.

While the graph is drawing, if I press the return button once, then drawing is paused. If I press the button again, drawing resumes. Now press a third time and drawing pauses again. Now press a fourth time and I return to the Expressions tab (where I started).

So, assume (without steps), that I simply navigate to the Graph tab. The graph immediately begins drawing. Press the return button once and graphing pauses. Press a second time, it restarts. Press a third time and it pauses again. Press a fourth time and I return to the Expressions tab. 

Lets restart from the Expressions tab and select "Plot graph" and I kind of double tab the return key. I am guessing that if I press too fast it misses that I hit the button twice, but, I see slightly different behaviors that implies to me that it might see one key press or two and I might end up back at the Expression tab; which feels consistent depending on how many key presses it notices. 

In no case do I see with a black and white horizontal stripe pattern. While drawing, it is drawing the dots in red with a black background.

**Comment by TSV3000** [comment]
It was the case when I opened this post.
I was able to reproduce it but did not find a consistent way to obtain it.
