### ISSUE TITLE
Shift + number to access apps version 20 bêta

### ISSUE THREAD

**Issue by AngeDieu** [numworks/epsilon#2003]
Now there are twelve apps on numworks, how do we access to the last row, especially the settings app, using the shift+number method ?
Secondly, can this method let us directly enter the app instead of only selecting it ?
Thanks a lot.

**Comment by Ecco** [comment]
Shortcuts on the home screen don't involve the `shift` key at all: simply pressing a number key will select the corresponding app (for example, pressing `2` will select the second app, Grapher). To enter an app, just press the shortcut key twice: for example, typing `22` will select and then open the Grapher app. We only offer a shortcut for the first 9 apps, but starting from version 20, the Settings app has a dedicated one, `0`.
