### ISSUE TITLE
Disable periodic table in UK Exam Mode

### ISSUE THREAD

**Issue by parkermaths** [numworks/epsilon#2004]
Under JCQ Exam Regulations (almost all UK exams are bound by these rules), accessing a copy of the periodic table in any examination (not just Chemistry) would be prohibited.  Please could this be disabled when the calculator is in UK exam mode?

Copy of the rules here (page 19):

https://www.jcq.org.uk/wp-content/uploads/2020/10/ICE_20-21_FINAL.pd

**Comment by Miniontoby** [comment]
> Under JCQ Exam Regulations (almost all UK exams are bound by these rules), accessing a copy of the periodic table in any examination (not just Chemistry) would be prohibited. Please could this be disabled when the calculator is in UK exam mode?
> 
> Copy of the rules here (page 19):
> 
> https://www.jcq.org.uk/wp-content/uploads/2020/10/ICE_20-21_FINAL.pd

I cannot remember the Periodic table being inside the Epsilon!

You should go to the [upsilon repo](https://github.com/UpsilonNumworks/Upsilon) and submit your issue there and close this issue

**Comment by adriweb** [comment]
The periodic table will be an app in Epsilon 20, that's why.

**Comment by Miniontoby** [comment]
Oh...

**Comment by parkermaths** [comment]
It's in the Beta. I've been assured that there are ongoing discussions between Numworks and JCQ, so we'll see.

**Comment by fbeleznay** [comment]
I also see the elements app in the IB exam mode in Epsilon 20. A chemistry teacher colleague said that it contains information that are regularly asked on exams and that are not in the data booklet available for students on IB exams (I did not check this claim).

**Comment by artaxxx** [comment]
In Epsilon 20, the Elements app is disabled when you activate the UK exam mode: https://www.numworks.com/calculator/exams/a-level-and-gcse/.

The Elements app will be deactivated in IB exam mode starting from Epsilon 21.
