### ISSUE TITLE
[Fail] Upgrade from 19.5.1 to version 20 not working on N0100

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#2019]
#### Describe the bug
When updating through the dedicate page https://my.numworks.com/devices the calculator stays on version 19.5.1, although the page says the upgrade is correctly applied. Tried multiple times.

#### Environment
 - Serial Number DQAIgAFRODAxNTk4
 - FCC ID 2ALWP-N0100

**Comment by kiarn** [comment]
Hello,

I'm experiencing the same issue as @XanderLeaDaren with same FCC ID.

**Comment by Yaya-Cout** [comment]
I think this is because Epsilon 20 isn't released for the N0100 yet. (as visible on the Website : https://my.numworks.com/firmwares/n0100/stable.json)

**Comment by artaxxx** [comment]
Hello, thank you for creating this issue. Indeed, it is one of the first devices we created. The software of the previous version (version 19) has already reached the limits of the storage memory and we cannot add new features on these devices. So unfortunately, version 20 cannot be installed on N0100 calculators.
