### ISSUE TITLE
[Bug] derivative of absolute value

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#202]
<img width="179" alt="capture d ecran 2017-10-10 a 10 14 26" src="https://user-images.githubusercontent.com/20040032/31376043-d82fbae4-ada3-11e7-8346-1146c6843af7.png">

**Comment by AlainBusser** [comment]
It seems rather random: If I try with the functions App:

![heaviside1](https://user-images.githubusercontent.com/3930757/31805173-d9020c5a-b56f-11e7-927f-6624f150d92d.png)

the curve is OK:

![heaviside3](https://user-images.githubusercontent.com/3930757/31805184-e6092da2-b56f-11e7-9402-b00d231c2843.png)

but some values are undefined:

![heaviside2](https://user-images.githubusercontent.com/3930757/31805187-f1eca144-b56f-11e7-9e67-3568f8be1cc3.png)

By the way the derivative is 0 when x is minus a power of 2, so I would suspect a problem with Ridder's algorithm which is used in pincare/derivative.cpp

**Comment by artaxxx** [comment]
Fixed #305
