### ISSUE TITLE
No addition or Subtraction operations for temperature units:  Celsius or Fahrenheit

### ISSUE THREAD

**Issue by valdesvj** [numworks/epsilon#2022]
#### Describe the bug
Apparently it is not possible to do basic arithmetic operations(addition and subtraction) when temperature units are Celsius or Fahrenheit, but it is possible in Kelvin

#### Screenshots
![Screenshot from 2023-02-17 14-01-51](https://user-images.githubusercontent.com/13373048/219762701-518641a1-3eec-4e84-b5a4-87f331db25de.png)
![Screenshot from 2023-02-17 14-02-54](https://user-images.githubusercontent.com/13373048/219762853-1799e4d5-a529-43e2-870f-e4f6f6e275d0.png)

#### To Reproduce
Try to do some simple addition with Celsius, Fahrenheit and Kelvin

#### Expected behavior
At least able to add or subtract same unit temperatures when used units are Celsius or Fahrenheit
Basic addition and subtraction should be implemented by developers.

#### Environment
 - Epsilon version (20.3.0)
 - The platform(s) on which the problem happens: linux simulator, online simulator and device.

**Comment by Ecco** [comment]
Indeed, this is by design. Celsius and Fahrenheit aren't absolute units, so adding them doesn't have a clear definition. See [this discussion](https://physics.stackexchange.com/questions/132720/how-do-you-add-temperatures) for a more in-depth explanation of why you should not add non-Kelvin degrees.

**Comment by valdesvj** [comment]
@Ecco Thank you for the quick reply and pointing that discussion about absolute temperatures. 
I am able to do this in my other calculators (HP48, TI-nspire CX II)
It is very good that numworks is stricter than others in design. 
Thank you.

**Comment by mauroriccardi** [comment]
While I agree about sums of non-absolute temperatures, it should be possible to subtract temperatures in Celsius or Fahrenheit degrees, since a difference in temperature is always well defined. On my calculator (v. 20.4.0) this is currently not allowed.
