### ISSUE TITLE
Additional Results in Spanish for Prime Factors is in Portuguese. 

### ISSUE THREAD

**Issue by valdesvj** [numworks/epsilon#2023]
#### Describe the bug
Additional Results in Spanish for Prime Factors shows a Portuguese Translation 

#### Screenshots
![Screenshot from 2023-02-17 14-27-15](https://user-images.githubusercontent.com/13373048/219768777-48736a19-aaa9-4a7e-9c48-119c486ffff2.png)

#### To Reproduce
Set the calc on Spanish.
Write a number on the screen, select additional results and scroll down.

#### Expected behavior
The correct sentence is "Descomposición en Factores Primos"
The file base.es.i18n needs to be amended
PrimeFactors = "Decomposição em fatores primos"
PrimeFactors = "Descomposición en Factores Primos"
![Screenshot from 2023-02-17 14-37-41](https://user-images.githubusercontent.com/13373048/219772664-b150c9c3-cea1-4c2c-9bb9-96a3761e7868.png)

#### Environment
 - Epsilon version: 20.3.0
 - The platform(s) on which the problem happens: linux simulator, online simulator and actual device

**Comment by serval2412** [comment]
Just for the record, I created a pull request here:
https://github.com/numworks/epsilon/pull/2073

**Comment by PiaNumworks** [comment]
The translation has been fixed, thank you !
