### ISSUE TITLE
Calculator Name in Settings/About

### ISSUE THREAD

**Issue by GrvyMt** [numworks/epsilon#2030]
When updating the calculators, I like the ability to add a name to the calculator. Right now I have the names matching the number written on the side of the calculator. 

I would like to see this line in the about section in settings. Adding a new line to the Software Version, serial number, and FCC ID information for Device Name would be helpful. With this, I could assign a calculator to a student with their name in the position of the Device Name field. This would mean if a student left a calculator behind I wouldn't need to cross-reference the serial number with the student list. It would also allow students to keep track of their calculators if they borrowed a friend's calculator.

**Comment by Lisra-git** [comment]
The way the current security system works could make this tricky, the system exists in two parts called "Slot A" and "Slot B", if one slot fails, the system boots on the other slot, both systems are checked and the integrity cannot be tampered with.

One way to do this would be to use storage in RAM (which would be erased on reset/reboot).
Or have a new form of package in the external application sections but would need 2 copies in case it doesn't start in the slot with the name, or have a scan on both slots from any slot.

Lots of possibilities, this would be a good improvement :)

**Comment by artaxxx** [comment]
Now possible in version 22
