### ISSUE TITLE
Exam mode batterie drain

### ISSUE THREAD

**Issue by maDU59** [numworks/epsilon#2036]
When exam mode is toggled, the red led turns on which drain the entire battery in 2 days so if you forget about it, you'll not have battery for the next test.

What I sugger is to turn the led off after 30 minutes with the screen turned off

**Comment by Stephan-P** [comment]
See https://github.com/numworks/epsilon/issues/1943

**Comment by artaxxx** [comment]
Unfortunately it is forbidden by some exam boards. So I'll have to close this issue
