### ISSUE TITLE
Reset with the sequences app

### ISSUE THREAD

**Issue by Miner79** [numworks/epsilon#2053]
#### Describe the bug
By creating two sequences calling each other in the sequences app, the calculator resets itself.
This doesn't reset on the emulator but it just freezes.

#### Screenshots
![screenshot](https://user-images.githubusercontent.com/64258466/235990054-f468d535-5665-47cc-a2ee-188920b37217.png)

#### To Reproduce
1. Go to the 'sequences' app
2. Create a sequence u(n) = v(n) 
3. Create a sequence v(n) = u(n+1)
4. Go to the 'Graph' tab
5. See error

#### Expected behavior
I think the sequences should get labeled as undfined like in the grapher app

#### Environment
 - Epsilon version 20.4.0.
 - The platform(s) on which the problem happens: online simulator and actual device.

**Comment by artaxxx** [comment]
Thank you @Miner79 we'll fix it in the next release

**Comment by PiaNumworks** [comment]
Fixed in 21.1.0
