### ISSUE TITLE
Imprecision in "Calculation" due to rounding

### ISSUE THREAD

**Issue by BriacLP** [numworks/epsilon#206]
During a calculation for an absorbance in chemistry I entered the number 5.7E-6 but the calculator rounded it to 0.000006.
This rounding can distort an entire calculation (if after the result I still have to multiply it but I still have a rounding, at the end I go out with a big difference)
![sdqfqzs](https://user-images.githubusercontent.com/32522843/31439081-25eaa09a-ae8b-11e7-9840-168a1638accb.png)
The calculator should keep the input form.

**Comment by artaxxx** [comment]
Fixed in the last version 1.2.0
