### ISSUE TITLE
The text selection is reset when the selection cursor is out of the screen in Python editor

### ISSUE THREAD

**Issue by yannis300307** [numworks/epsilon#2063]
The text selection is reset when the cursor goes out of the screen in Python editor. It makes impossible to select a large text area.

#### Screenshots
The bug doesn't work on the emulator. 

Here is a video which show the bug (sorry for the bad quality of the recording) : 
https://github.com/numworks/epsilon/assets/52321382/7adefaf4-db06-401c-bc4a-4b2a69005891

#### To Reproduce
1. Go to the Python app
2. Open any program
3. press shift and move the cursor with the arrows

#### Expected behavior
 I think it's due to a lag when the screen scrolls. It releases the shift button.

#### Environment
 - Epsilon version : 20.4.0
 - The platform(s) on which the problem happens: actual device

**Comment by FelixNumworks** [comment]
Hello @yannis300307, thank you for bringing this problem to our attention.
This issue has been addressed by our development team in response to your report, and the fix will be effective in the next version of Epsilon in a few weeks.
Let us know if you have any other problems with the calculator.
:)
