### ISSUE TITLE
Pressing shift or alpha during Python program execution will make the calculator slowing down

### ISSUE THREAD

**Issue by yannis300307** [numworks/epsilon#2070]
#### Describe the bug
When we press shift or alpha during the execution of a Python program, the calculator will slow down.

#### Screenshots

https://github.com/numworks/epsilon/assets/52321382/58e402bb-61fb-461a-930d-9173e2eaffa1

#### To Reproduce
1. Go to the 'Python' app
2. Start a program wich takes a long time to perform like 'mandelbrot'
3. Press 'shift' or 'alpha' during the execution

#### Expected behavior
I don't really know why this bug is happening.

#### Environment
 - Epsilon version : 20.4.0
 - The platform(s) on which the problem happens: actual device

**Comment by EmilieNumworks** [comment]
This is a consequence of our [keyboard matrix design](https://www.numworks.com/resources/engineering/hardware/electrical/schematics/). When you press shift or alpha, we cannot rely anymore on hardware interruptions on the corresponding column pins to detect new key events. This forces us to scan regularly the keyboard slowing down the whole run loop.
