### ISSUE TITLE
Treat polar functions as first-class functions

### ISSUE THREAD

**Issue by ajacoby** [numworks/epsilon#2071]
While I can currently graph polar equations, I can't treat those equations as functions of θ in other contexts, like if I want to integrate to find area, or just do arithmetic with the values in the Calculation screen.

![screenshot-3](https://github.com/numworks/epsilon/assets/7581851/e73bc955-4908-4d64-908a-16a5b7bdf95b)
![screenshot-4](https://github.com/numworks/epsilon/assets/7581851/b18bb58f-e41f-4d38-b6db-f1c7bbf87fc2)

Note: the screenshot shows r * (pi/2), but I typed r(pi/2) and the calculator assumed implicit multiplication rather than function notation.

#### Desired resolution:
Be able to use function notation with polar functions and use them in the calculate screen, just like rectangular functions.

#### Alternatives
I tried creating my function f(x) and then graphing r=f(θ), but that doesn't seem to work either.  I can't seem to use user-defined functions in the definition of a polar equation to graph:

![screenshot](https://github.com/numworks/epsilon/assets/7581851/5f585cb3-a005-4bf8-8afb-1f1d237585ef)
![screenshot-2](https://github.com/numworks/epsilon/assets/7581851/8b16640a-049b-4e47-a6ae-95ebc0481533)

I'll post a separate feature request for this issue.

The less ideal workaround that remains is to just define the function twice: once as polar to graph it, and again as f(x) to do calculations with it.

**Comment by KarineNumWorks** [comment]
Hello ! This feature has been released in version 23: https://www.numworks.com/calculator/update/version-23/#:~:text=More%20improvements%20to%20the%20Grapher%20application

I will close this issue consequently !
