### ISSUE TITLE
Can not see the epsilon-core branch

### ISSUE THREAD

**Issue by CristXu** [numworks/epsilon#2076]
Hi
     I found that the epsilon-core is as a submodule, but I can not find it from the given link:
https://github.com/numworks/epsilon-core/tree/c250bfcd90610521265fa78499bb02f90b112164
     Could you please help where can I find that code.

Regards,
    Crist

**Comment by EmilieNumworks** [comment]
Hi CristXu, the epsilon-core repository is private (it contains sensitive information that are to be hidden to be compliant with exam boards). You don't need it to build a third-party userland though (https://www.numworks.com/resources/engineering/software/build/).
