### ISSUE TITLE
Broken link in the official documentation (flash.ld)

### ISSUE THREAD

**Issue by matm** [numworks/epsilon#2080]
#### Describe the bug
Section 3.3 at https://www.numworks.com/resources/engineering/software/ states
> You’ll find Epsilon’s linker script in [ion/src/device/n0110/flash.ld](https://github.com/numworks/epsilon/blob/master/ion/src/device/n0110/flash.ld) - it is heavily commented and should be self-explanatory.

However the link to https://github.com/numworks/epsilon/blob/master/ion/src/device/n0110/flash.ld returns a 404.

#### Screenshots
None.

#### To Reproduce
1. Click on the link in the doc
2. See the 404 GitHub error page

#### Expected behavior
Well, seeing the code.

#### Environment
Any web browser.

**Comment by Pigmy-penguin** [comment]
https://github.com/numworks/epsilon/blob/master/ion/src/device/include/n0120/config/board.h 
There should be everything here

**Comment by FelixNumworks** [comment]
Fixed by https://github.com/numworks/epsilon/pull/2086
