### ISSUE TITLE
Imperial/US engineering units.

### ISSUE THREAD

**Issue by eclecticfluff** [numworks/epsilon#2081]
#### Problem you'd like to fix

A significant number of problems I've had to solve for mechanics related work has involved units that are hard or impossible to enter accurately with the supported units, let alone read an answer in the desired conversion.

#### Describe the solution you'd like

I would like the following list of units to be included, roughly in order of importance. 
- pounds force (lbf), pound mass should be renamed to lbm.
- slug (slug)
- degree Rankine  (°R)
- inches of water (inH2O), ideally would accept all length units.
- inches of mercury (inHg), ideally would accept all length units.
- thermochemical calorie (cal or calth), see #1987.
- thermochemical kilocalorie (Cal, Calth, kcal, or kcalth)
- thermochemical British thermal unit (btu or btuth)
- pounds per square inch (psi)
- kilopounds force (kip)
- kilopounds per square inch (ksi)
- poundal (pdl), unlikely to see use.

#### Describe alternatives you've considered

Pounds force can be input as lb g0, but it's clunky, especially when used in more complex derived units.

#### Additional context

The conversions can be found at the [NIST table](https://www.nist.gov/pml/special-publication-811/nist-guide-si-appendix-b-conversion-factors/nist-guide-si-appendix-b9#MASSvolume) for it, though do note that some are not listed as exact conversions where exact conversions do exist.

**Comment by eclecticfluff** [comment]
Update to say that my thermodynamics II professor will be requiring some answers in btu, which makes it about as important as the slug for me considering how it would see regular use and can’t be derived from existing units and constants on the calculator.

**Comment by farinc** [comment]
I would say that as a chemical engineering student in the US, we use most of the units above fairly frequently (except for poundal and slug, but don't matter). I believe this would be very attractive for many students in my field and related. I also agree that the given support is not ideal when working in the odd units we work with. The numworks calculator already does all of what I need (and more) with this being the only downside (especially given that physics/chemistry constants are not just numbers but have units also). Please consider this a priority!

**Comment by adri1numworks** [comment]
Hello,
Thank you for your suggestions ! 

For now, we consider keeping only the most common units. Among the units above, we will implement the cal and kcal in a future version. Concerning pounds per square inch : this is feasible by dividing any mass by a surface, just as in the metric system. 

Then, the other units are not planned to be implemented any time soon. As such I close this ticket. We might reopen it if we reconsider this.

**Comment by eclecticfluff** [comment]
Also worth noting is that since US education puts equal emphasis on SI and US customary measurments. As it stands, the SI units included cover more than enough range to function in college level engineering and science courses while the US customary units included can only cover late elementery school subjects with workarounds. Unless the intent of including feet, pounds, Farenheit, etc. is on the off chance that a student in a fully metricized country might come across them I don′t see the point of this half measure. Admittedly inH2O, inHg, kip, ksi, pdl, and slug are less common even within the US system, but that still leaves a lot of vital units out. Even if gravities become usable as a unit, that does′t change how any problem as or more advanced than basic physics requires restating US derrived unit definitions and forcing of unit conversions. Common US units for energy, absolute temperature, force, and pressure exist. Btu for energy, °R for absolute temperature, lbf for force, and psi for pressure. Also, what is the present way of determining whether a unit is common? In my experience, hp is about as common as btu while the long ton is way less common than the short ton.

**Comment by eclecticfluff** [comment]
I have tried to gather a comparison of units available on the current flagship models by other calculator manufacturers in hopes that it may be more persuasive. Note that I skipped over fully written out derived and undocumented units. Nevertheless, this should provide a good picture of what the glaring are for the calculator.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ethan/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ethan/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#467886" vlink="#96607D">


 category | name  | casio | hp | TI Nspire | Numworks
-- | -- | -- | -- | -- | --
Length | fermi | fm | fermi | fm |  
  | angstrom | Å | Å | Å |  
  | meter | m | m | m | m
  | astronomical unit | AU | au | au | au
  | light year | l.y. | lyr | ltyr | ly
  | parsec | pc | pc | pc | pc
  | thousandth of an inch | Mil | Mil | mil |  
  | inch | in | in | in | in
  | US survey foot |   | ftUS |   |  
  | foot | ft | ft | ft | ft
  | yard | yd | yd | yd | yd
  | fathom | fath | fath | fath |  
  | rod | rd | rd | rd |  
  | chain |   | chain |   |  
  | US survey mile |   | miUS |   |  
  | statue mile | mile | mi | mi | mi
  | nautical mile | n mile | nmi | Nmi |  
Area | hectare | ha | ha | ha | ha
  | are |   | a |   |  
  | acre | acre | acre | acre | acre
  | barn |   | b |   |  
Volume | stere |   | st |   |  
  | liter | L | l | l | L
  | US fluid oz | fl_oz(US) | ozfl | floz | floz
  | UK fluid oz | fl_oz(UK) | ozUK | flozUK |  
  | US gallon | gal(US) | gal | gal | gal
  | UK gallon | gal(UK) | galUK | galUK |  
  | Canadian gallon |   | galC |   |  
  | pint | pt | liqpt | pt | pt
  | US quart |   | ptUK |   |  
  | quart | qt | qt | qt | qt
  | teaspoon | tsp | tsp | tsp | tsp
  | tablespoon | tbsp | tbsp | tbsp | tbsp
  | cup | cup | cu | cup | cup
  | barrel |   | bbl |   |  
  | bushel |   | buUS |   |  
  | peck |   | pk |   |  
  | board foot |   | fbm |   |  
time | second | s | s | s | s
  | minute | min | min | min | min
  | hour | h | h | hr | h
  | day | day | day | day | day
  | week | week |   | week | week
  | month |   |   |   | month
  | year | yr | yr | yr | year
  | sidereal year | s-yr |   |   |  
  | tropical year | t-yr |   |   |  
  | hertz |   | Hz |   |  
Temperature | degrees Celsius | °C | °C | °C | °C
  | kelvin | K | K | K | K
  | degrees Fahrenheit | °F | °F | °F | °F
  | degrees Rankine | °R | Rankine | °R |  
Velocity | kilometer per hour |   | kph |   |  
  | knot | knot | knot | knot |  
  | mile per hour |   | mph |   |  
Acceleration | std gravity | grav |   |   |  
  | gal | Gal |   |   |  
Mass | atomic mass unit | u | u | amu |  
  | carat |   | ct |   |  
  | kilogram | kg | kg | kg | kg
  | metric ton | mton | t | mton | t
  | avoirdupois ounce mass | oz | oz | oz | oz
  | avoirdupois pound mass | lb | lb | lb | lb
  | slug | slug | slug | slug |  
  | short ton | ton(short) | tonUS | tonUK | shtn
  | long ton | ton(long) | tonUK | tonUK | lgtn
  | grain |   | grain |   |  
  | tropy ounce mass |   | ozt |   |  
  | troy pound mass |   | lbt |   |  
Force | newton | N | N | N | N
  | dyne | dyne | dyn | dyne |  
  | gram force |   | gf |   |  
  | kologram force | kgf |   | kgf |  
  | ounce force |   | ozfl |   |  
  | pound force | lbf | lbf | lbf |  
  | kilopound force |   | kip |   |  
  | ton force | tonf |   | tonf |  
Pressure | pascal | Pa | Pa | Pa | Pa
  | millimeter of water | mmH₂O |   | mmH₂O |  
  | millimeter of Mercury | mmHg | mmHg | mmHg |  
  | atmosphere | atm | atm | atm |  
  | inch of water | inH₂O | inH2O | inH₂O |  
  | inch of Mercury | inHg | inHg | inHg |  
  | pound per square inch |   | psi | psi |  
  | bar | bar | bar | bar |  
  | torr |   | torr | torr |  
Energy & work | electron Volt | eV | eV | eV | eV
  | joule | J | J | J | J
  | watt hour |   | Wh |   |  
  | kilowatt hour |   |   | kWh |  
  | foot pound |   |   | ftlb |  
  | thermochemical calorie | calₜₕ |   |   |  
  | calorie (15°C) | cal₁₅ |   |   |  
  | international calorie | calIT | cal | cal |  
  | thermochemical kilocalorie | kcalₜₕ |   |   |  
  | kilocalorie (15°C) | kcal₁₅ |   |   |  
  | international kilocalorie | kcalT | kcal | kcal |  
  | liter atmosphere | l-atm |   | latm |  
  | British thermal unit IT | Btu | Btu | BTU |  
  | erg | erg | erg | erg |  
  | EEC therm |   | thermEC |   |  
  | US therm |   | thermUS |   |  
  | UK therm |   | thermUK |   |  
  | tonne of oil equivalent |   | toe |   |  
  | tonne of ? |   | tec |   |  
  | liter of ? |   | lep |   |  
  | barrel of ? |   | bblep |   |  
  | barrel of oil equivalent |   | boe |   |  
  | cubic foot gas |   | cf |   |  
Power | watt | W | W | W | W
  | metric horsepower |   |   | psi |  
  | horsepower | hp | hp | hp |  
electromagnetic | amp |   | A |   | A
  | volt |   | V |   | V
  | culomb |   | C |   | C
  | ohm |   | Ohm |   | Ω
  | farad |   | F |   | F
  | ? |   | Fdy |   |  
  | weber |   | Wb |   |  
  | henry |   | H |   | H
  | inverse ohm |   | mho |   |  
  | Siemens |   | S |   | S
  | tesla |   | T |   | T
light | candela |   | cd |   | cd
  | ? |   | flam |   |  
Viscocity | Poise |   | P |   |  
  | stokes |   | St |   |  
Radiation | becquerel |   | Bq |   |  
  | curie |   | Ci |   |  
  | gray |   | Gy |   |  
  | rad |   | rd |   |  
  | roentgen equivalent man |   | rem |   |  
  | sievert |   | Sv |   |  
  | roentgen |   | R |   |  
</body>

</html>
