### ISSUE TITLE
error compile epsilon (from version 14 to last version) n0120 

### ISSUE THREAD

**Issue by noco13** [numworks/epsilon#2093]
i got a model n0120 i try to compile my own epsilon sdk but i always get errors from include and compilation 
i don't know what to do

**Comment by ExplodingBottle** [comment]
Hello, after searching a bit, I found this as a workaround until an official fix:

- Build everything
- Wait for the error
- Navigate to build/debug_flags.mk
- Replace `--defsym ASSERTIONS=$(ASSERTIONS)` by `--defsym,ASSERTIONS=$(ASSERTIONS)`
- Save
- Launch your make command again

I hope this helps

**Comment by EmilieNumworks** [comment]
You can try running: `make MODEL=N0120 userland.A.dfu` or follow the [tutorial on NumWorks website](https://www.numworks.com/engineering/software/build/) (Cleaning the tutorial is a on-going project, sorry it's painful right now.

**Comment by ExplodingBottle** [comment]
My bad, I answered the wrong issue. I wanted to answer the issue that had more details inside of it.
