### ISSUE TITLE
Exam mode

### ISSUE THREAD

**Issue by LucasYooki** [numworks/epsilon#2098]
#### Advanced exam mode 
I have been using numwork for years now, I love working with it however it is not authorized for certain exams because of its different functionalities. The problem is that I have to use other calculators which are really not practical but they don't have as many tools.

The improvement I would like to see is being able to configure exam mode.

To do this, when we go to the settings then Exam Mode, we may have the option to activate or not the different calculator tools. For example, if I only want to have access to the calculation and graphing tools, we could select them so that they are active when exam mode is activated. Once exam mode has been validated, the other modules appear grayed out and cannot be used.

Another alternative could be to create a functionality for schools to configure the tools authorized during exams themselves. Once configured in the desired manner, each calculator would be connected once to the school system so that the exam mode is configured.

Thank you sincerely for considering my request.

**Comment by glyj** [comment]
This is a great idea. 
Here in France, calculators with formal computing are allowed . 
But installing those apps in the Numworks removes the exam mode unfortunately !

**Comment by artaxxx** [comment]
Thank you for your issue. In country "International" you can customize the features you disable. If this doesn't suit you, I'll let you reopen the issue and give me the names of the exams and features concerned.
