### ISSUE TITLE
Issue writing epsilon to calculator

### ISSUE THREAD

**Issue by Increedible** [numworks/epsilon#2107]
#### Describe the bug
I have been trying to write an up-to-date clone if this repo to my machine on wsl, and I got it to run on simulation. Following the tutorial at https://www.numworks.com/resources/engineering/software/build/ I gave up on wsys2 with too much errors, but now on linux I got it running with make PLATFORM=simulator epsilon_run. The issue rn is when I try to write to my calculator like the article says with python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu, it says I'm missing the dfu which is obvious, so I tried to build it with make userland.A.dfu, but that gave me the error of:
`error: ASSERTIONS=0: No such file or directory make: *** [build/rules.mk:83: output/release/device/n0110/userland/userland.A.elf] Error 1` the file is just plainly missing, and I have no idea what to do after googeling away.

#### Screenshots
No calculator screenshots aside the simulation working:
![image](https://github.com/numworks/epsilon/assets/108118527/dc027dfc-aa07-4ca5-96e2-da44db371bc2)

The calculator being detected:
![image](https://github.com/numworks/epsilon/assets/108118527/b5cab793-eff2-43fb-9d3d-edea39099a24)

and the error while writing to my calculator:
![image](https://github.com/numworks/epsilon/assets/108118527/23d5aa68-6cca-4d75-bf11-5fc799142f62)

#### To Reproduce
1. Install WSL and ubuntu
2. Follow the blog post on https://blog.golioth.io/program-mcu-from-wsl2-with-usb-support/ to connect usb to wsl 
3. Follow the instructions on https://www.numworks.com/resources/engineering/software/build/

#### Expected behavior
For it to build correctly, and write correctly. When running `python3 build/device/dfu.py -l`, the numworks calculator shows up.

#### Environment
 - Epsilon version: the simulator shows 21.2.1
 - The platform(s) on which the problem happens: linux subsystem for windows (wsl)

**Comment by EmilieNumworks** [comment]
We're working on fixing this!

**Comment by Sajid33bled** [comment]
Moi quand je veux flasher sur la calculatrice il me dit que je nais pas de permission ou que il y aune erreur avec l'appareil

**Comment by EmilieNumworks** [comment]
The initial issue has been fixed. Please open a new issue describing your problem.
