### ISSUE TITLE
Deeplink to NumWorks simulator in choosen language

### ISSUE THREAD

**Issue by Veul** [numworks/epsilon#2108]
#### Problem you'd like to fix
As a Dutch user, I always first need to change the language from English into Dutch before I can demo the NumWorks to my pupils in order to match the language with the language used by my pupils

#### Describe the solution you'd like
Add the language to the URL in order to enable me to deeplink direct to the simulator in Dutch

#### Describe alternatives you've considered
Add the language parameter in the cookie

**Comment by MarcNumworks** [comment]
Hi, thank you for your report.

If you change the language of the website (not from inside the calculator), you should end up on this page https://www.numworks.com/nl/emulator/ where the simulator starts in Dutch.

Is it what you were looking for ?

**Comment by Veul** [comment]
Hi,
This is what I was looking for… found the same workaround later in the
afternoon. Thx for your fast response, Marco

Op do 2 nov. 2023 om 09:53 schreef MarcNumworks ***@***.***>
