### ISSUE TITLE
DEBERIAN MEJORAR LO DE QUIMICA, TAMBIEN COLOCAR MAS FORMULAS DE DETERMINANTES

### ISSUE THREAD

**Issue by arin0e** [numworks/epsilon#2109]
Buenas noches en lo que es la tabla periódica deberían mejorar colocando formulas, también valencias y crear las nomenclaturas, eso seria de ayuda la verdad
También agregar una ventana para block de notas

**Comment by artaxxx** [comment]
Could you please open a new issue following the template and in English? Thank you very much!
