### ISSUE TITLE
require a more recent authetified kernel to be executed

### ISSUE THREAD

**Issue by Ardorax** [numworks/epsilon#2111]
#### Describe the bug
I want to compile my own version of epsilon, I haven't modify the code from github.
At the end of the step "Writing memory...", the following message is displayed on my calculator :
OFFICIAL UPGRADE REQUIRED
The software you were about to execute require a more recent authetified kernel to be executed.
Please upgrade your calculator with the last official software before trying again.

#### To Reproduce
My computer is on arch-linux. I have installed all the packages needed for the emulator.
My calculator is up-to-date (updated with website).
I used to have Omega OS on my calculator.

#### Expected behavior
I expect my version of the code to appear on the calculator ?

#### Environment
 - Epsilon version : 21.3.0, Model 0110
 - The platform(s) on which the problem happens: actual device

**Comment by EmilieNumworks** [comment]
The version given by your 'homemade' (or not) firmware has to match the one of the official kernel running on your calculator. When building from the GitHub code base, make sure that the version [here](https://github.com/numworks/epsilon/blob/803c58a5fb4aa0941d258fc4b2352a9926751849/build/config.mak#L7) is the same as on your calculator. The branch version-21 was up-to-date but not the master branch. I consequently just updated it! Thanks 😄
