### ISSUE TITLE
Save data module

### ISSUE THREAD

**Issue by Idaill** [numworks/epsilon#2118]
**Hi**, im Idaill (playidaill) and i wanted to know if create saving data from python program (maybe for exemple add a type of files in the python editor) or else, but i think it could be really useful.
_Have a nive day!_

Bonjour, je m'appelle Idaill (playidaill) et j'aimerais savoir si il est possible de créer un module sur python pour sauvegarder en cache ou tout simplement dans l'éditeur python (comme par exemple ajouter un nouveau type de fichier que .py CAD .txt par exemple)
_Sinon passez une bonne journée !_

**Comment by artaxxx** [comment]
Hello, thanks for your issue. Unfortunately it's not in our midterm plans for epsilon. We see the Python application as an introduction to algorithmics in high school.
