### ISSUE TITLE
Lack of decimal places in sequences app leading to incorrect solutions to exam questions.

### ISSUE THREAD

**Issue by jrkimber** [numworks/epsilon#2124]
Hi,

Currently, the sequences app gives solutions to six decimal places. This is a problem for UK A-Level students as often, iteration questions ask for the solution to 5 decimal places.

The problem occurs in scenarios like the following:

- The series converges to **1.15650485**
- The question asks students to give the solution to 5 decimal places. The solution should be **1.15650**
- The sequences app only displays the answer to 6 decimal places: **1.156505**
- Students then round this to 5 decimal places, **1.15651**
- This is incorrect and they lose the mark in the exam.

Could this be changed please to add more (at least one) decimal places? It's causing a significant problem for UK students otherwise.

Thanks,
James

**Comment by FelixNumworks** [comment]
Hello James, and thanks a lot for submitting this issue.

I am pleased to inform you that our team has already addressed this problem, and the solution will be implemented in the forthcoming Version 22 of our software, set to be released in a few weeks.

Starting from this version onward, the number of decimal places in the value tables of the Grapher and Sequence apps will align with the user's selected "significant digits" setting, which can be modified in the Settings app.

Thanks again for helping us improve our product.
Félix
