### ISSUE TITLE
Add Half Life field to Elements app

### ISSUE THREAD

**Issue by Arthur-GYT** [numworks/epsilon#2129]
All is in the title ^^.

To be honest, I've already started working on this (https://github.com/Arthur-GYT/epsilon/tree/apps/elements/half-life) ^^'.

If this is not a feature that will be added, please let me know ^^.

**Comment by adri1numworks** [comment]
Hello,
Thank your for your suggestion ! 
We decided not to display isotopes as some elements can have many of them. As such, elements are mostly stable up to approximately Bismuth. As we never encountered a periodic table displaying half-life of elements, we prefer not to do so ourselves. However, if you have an official resource at your disposal that could justify the implementation of this feature, please let us know if comment.
Meanwhile, I close this issue. 
Best
