### ISSUE TITLE
In ion/src/device/ion-core is not found as a repo

### ISSUE THREAD

**Issue by KOEGlike** [numworks/epsilon#2141]
Is this because it is a private repo?

**Comment by RedGl0w** [comment]
It is private indeed, since changes operated by numworks on [june 2021](https://www.numworks.com/blog/secure-software-for-exams/)

**Comment by KOEGlike** [comment]
Would it be hard for an intermediate c++ dev to rewrite the core, so i could make my own custom calculator?
