### ISSUE TITLE
charge level

### ISSUE THREAD

**Issue by ejacobs129** [numworks/epsilon#2142]
Please add a screen that shows how much charge is left.

**Comment by adri1numworks** [comment]
Hello,
Thank you for your suggestion. As of today, our hardware does not allow us to display the charge more precisely than what is displayed in the top right of the screen. In consequence, I close this issue. 
Have a good day

**Comment by ejacobs129** [comment]
It doesn't have to be a display at the top of the screen. It can be put
into a menu within the settings.

**Comment by adriweb** [comment]
It's not an issue of displaying the information - it's simply not possible on this hardware to precisely know the charge level, that's what they meant.
