### ISSUE TITLE
fatal error: regs/regs.h: No such file or directory

### ISSUE THREAD

**Issue by x893** [numworks/epsilon#2144]
Hello,
I try build epsilon for n010, n0115, n0120 with the same error
Looks as **epsilon-core** repo not exists

#### Describe the bug
`
CXX     ion/src/device/shared/drivers/serial_number.o

In file included from ion/src/device/shared/drivers/serial_number.cpp:3:
ion/src/device/include/n0110/config/serial_number.h:4:10: fatal error: regs/regs.h: No such file or directory

 #include <regs/regs.h>
                  ^~~~~~~~~~~~~
`
#### To Reproduce
1. Clone epsilon repo
2. cd epsilon
3. make PLATFORM=device MODEL=n0120

#### Environment
 - latest
 - Debian 11.8

Thanks in advance

**Comment by EmilieNumworks** [comment]
Hi @x893,
epsilon-core repository is private! You can customize/build the userland of the software as indicated [here](https://www.numworks.com/engineering/software/build/).
