### ISSUE TITLE
Sums in graph menu

### ISSUE THREAD

**Issue by Eloulord** [numworks/epsilon#2146]
#### Describe the bug
One can not draw a graph that has a sum that depends from x

#### Screenshots
![numworks1](https://github.com/numworks/epsilon/assets/157645180/8184bd7a-a906-4122-83ef-29c8823843e3)

![numworks2](https://github.com/numworks/epsilon/assets/157645180/811b9304-f94c-41de-bc44-9d1be77b859e)

#### To Reproduce
1. Go to the graher menu
2. Create a function
3. Create a sum
4. Put x somexhere in the expression of the sum

#### Expected behavior
It should be able to draw the graph by calculating that sum at any point

#### Environment
 - Epsilon version (Settings > About > Software version). (22.3.0)
 - It happens both online and on software verion

Thank you for reading !

**Comment by PiaNumworks** [comment]
Hello, thank you for taking the time to submit this issue.
I am pleased to inform you that our team has already addressed this problem, and the solution has be implemented for the next version of our software.
Thanks again for helping us improve our product.

**Comment by jjvereijken** [comment]
Hi @PiaNumworks, It is indeed working for v23 again! Can you point me to the PR that fixes this? Just curious. Thanks, Jan Joris

**Comment by PiaNumworks** [comment]
Unfortunately the PR is in our private repo, but once we release version 23 (and publish the sources) I will be able point you to the commits that fixed it.

**Comment by jjvereijken** [comment]
Ah, sorry, wasn't aware of the private/public repo-setup. Thanks, will check back when v23 is released :+1:

**Comment by jjvereijken** [comment]
> Unfortunately the PR is in our private repo, but once we release version 23 (and publish the sources) I will be able point you to the commits that fixed it.

Hi @PiaNumworks! Can you point me to the PR now?

**Comment by PiaNumworks** [comment]
Hi @jjvereijken!
Here is the commit that fixed it: https://github.com/numworks/epsilon/commit/181ae8205447e767415044405936b78ca4f9c44f

**Comment by jjvereijken** [comment]
Hi @PiaNumworks, Many thanks, very enlightening!
