### ISSUE TITLE
Screen Casting

### ISSUE THREAD

**Issue by zulujive** [numworks/epsilon#2151]
#### Simulator isn't as intuitive as the calculator
So here's the deal: there's no way to share the calculator screen. I think this is a struggle I've seen in my classes where teachers are trying to use the simulator and it's just a little too clunky.

#### Have a screen sharing feature
I think it'd be a wonderful idea to have a screen sharing feature built into Epsilon. Just open the NumWorks web app and have the option to share the calculator screen.

#### Alternatives
Of course, we can keep using the simulator, but I think the whole goal here is to provide more options to teachers in giving class instruction.

**Comment by yannis300307** [comment]
I think that Zulujive wants an application on the Numworks website which connects to the calculator and display the calculator screen onto it. This can make the teachers able to use their actual calculator and to show their pupils the calculator screen. Casio has made this application for their calculators called [Screen Receiver](https://www.casio-education.fr/produits/logiciel-screen-receiver/).

**Comment by adri1numworks** [comment]
Hello,
Thank you for your input ! Having the simulator and giving the complexity of developing such a feature, we will likely not develop it for the moment. I close this issue but feel free to reopen it if needed.
