### ISSUE TITLE
Yellow as default accent colour in graphing (instead of Red)

### ISSUE THREAD

**Issue by achkasov** [numworks/epsilon#2168]
#### Problem you'd like to fix
Currently, (in v22) the default chart colour in Grapher app and in the Calculator additional results pop-up is **Red**, which is not in spirit of the NumWorks calculator design language, which prefers **Yellow** as the accent colour.

I propose changing the default chart graphing colour from Red to Yellow.

#### Screenshots
**Now**:
![Screenshot 2024-03-08 093745](https://github.com/numworks/epsilon/assets/14052589/b907091b-3886-4a47-a63f-8619a4d38d0d)

**Proposed**:
![vec2 yellow](https://github.com/numworks/epsilon/assets/14052589/3bd8e707-f504-45ce-9c84-d8641c53ce52)

#### Describe the solution you'd like
Change the default chart graphing colour from Red to Yellow across all the calculator applications.

#### Describe alternatives you've considered
Keep everything as it is.

**Comment by jrkimber** [comment]
Hi,

I'd like to put forward an alternative opinion that red is superior and that it should not change. Red is much easier to see, especially on projector screens when the emulator is used in classrooms.

Thanks,
James

**Comment by EmilieNumworks** [comment]
Red was indeed chosen because of its readability. It's not a feature we wish to change yet!
Thanks for suggesting.
