### ISSUE TITLE
Unable to make a recurrent sequence of the first term U_1

### ISSUE THREAD

**Issue by BriacLP** [numworks/epsilon#217]
Today, in mathematics an exercise gave us the sequence defined on U_n+1= (n*Un+4)/ (n+1) and the first term U_1=1.
Unfortunately, it is impossible to put U_1 in the first term and only U_0, which means that the whole sequence is wrong (we get all the time 4 except for U_0=1)

![dsedsqx](https://user-images.githubusercontent.com/32522843/31830314-24057ec6-b5c0-11e7-8fef-146ee48e2c34.png)

**Comment by boricj** [comment]
Adding a "First term" setting on the sequence options screen is probably a good way to fix this.

**Comment by Ecco** [comment]
Oh, interesting! Thanks @BriacLP for reporting this!

**Comment by ian-abbott** [comment]
So, replace the initial "U<sub>0</sub>" and "U<sub>1</sub>" terms with "U<sub>a</sub>" and "U<sub>a+1</sub>", and add a setting for "a" as the initial value for "n"?

**Comment by BriacLP** [comment]
> So, replace the initial "U0" and "U1" terms with "Ua" and "Ua+1", and add a setting for "a" as the initial value for "n"?

Why not directly allow to choose between U_0, U_1 etc...?

**Comment by ian-abbott** [comment]
> Why not directly allow to choose between U_0, U_1 etc...?

Having an "a" setting would let you choose to start the sequence at U<sub>0</sub>, or U<sub>1</sub>, or U<sub>2</sub>, etc.

So for your example sequence, you could set "U<sub>n+1</sub> = (n * U<sub>n</sub> + 4) / (n + 1)", "a = 1", and "U<sub>a</sub> = 1".

**Comment by BriacLP** [comment]
I find it less easy (even if I understand how to do it) than directly being able to choose by clicking on "U_0" another first term. I saw this as if when we clicked on U_n and the computation proposes U_n, U_n+1 or U_n+2.

**Comment by artaxxx** [comment]
Fixed by #289
