### ISSUE TITLE
User custom function catalogue

### ISSUE THREAD

**Issue by achkasov** [numworks/epsilon#2170]
#### Problem you'd like to fix
Currently (In v22) there is no proper user function catalogue, any defined function is automatically considered to be the function for the Grapher app to plot, inheriting all the limitation (e.g. no multiple argument functions).

For example: I am unable to define a parallel addition function, which is frequently used in electrical engineering `( 1 / (1/R1 + 1/R2) ) -> Padd(R1,R2) `. But I cannot because the Grapher app thinks it must be able to plot it.

#### Describe the solution you'd like
It would be really convenient to have a separate user defined function catalogue for calculation purposes (not automatically added to the Grapher app), including functions with multiple arguments.

#### Describe alternatives you've considered
I cannot think of any.

#### Additional context
None

**Comment by adri1numworks** [comment]
Hello @achkasov ,
Sorry for the late reply. To be honest, this is not something we are likely to do soon as it would require quite an effort to setup. For now, I will close this issue. Feel free to reopen it in the future if the need for such a feature gets more important.
