### ISSUE TITLE
Stange result while sum up 2 percentage numbers

### ISSUE THREAD

**Issue by kopwei** [numworks/epsilon#2177]
#### Describe the bug
 I've encountered a bug in the calculator feature within the Numworks calculator. When attempting to calculate the sum of two percentages, the output does not seem to reflect the expected result. E.g. 50% + 50% ends up in 0.75 instead of 1

#### Screenshots

![screenshot](https://github.com/numworks/epsilon/assets/944672/16b99e3e-f1ca-4b7a-ab04-70003c254306)

![screenshot (1)](https://github.com/numworks/epsilon/assets/944672/4d49a22a-6bcc-4eb2-bce5-c35e8976b344)

#### To Reproduce
1. Open the "Calculations" app
2. Type 50% + 50%
3. Press "Exe" key

#### Expected behavior
The result should be 1

#### Environment
 - Epsilon version 22.2.0

**Comment by achkasov** [comment]
This is by design. According to the source code the +/- convention represents an arrow, showing an increase/decrease over the previous number. So the interpretation here is (50%)*1,5
