### ISSUE TITLE
Conserve Search Intervals in Equations

### ISSUE THREAD

**Issue by DOxidelyj** [numworks/epsilon#2178]
When I try to solve equations in the Equations app, I need to re-enter search intervals every time (as the default interval [-10, 10] is not what I need most of the time), despite the fact that the interval is often the same as the last time I solved it. I consider that it would be better if the search target interval could be stored so that there would be less repetitive entries.

**Comment by adri1numworks** [comment]
Thank you for your suggestion.

You can find the beta of version 23, in which we modified the search interval in the solver :  https://www.numworks.com/simulator/beta/

I think it will correspond to what you are asking. If not, feel free to reopen this issue.
