### ISSUE TITLE
unable to treat dependent series

### ISSUE THREAD

**Issue by yanntm** [numworks/epsilon#218]
I had  a problem of the form
u(n+1) = n*v(n) + u(n)
u(0) = 3
and
v(n+1) = (n-1)*u(n) +v(n)
v(0)= 5

So two mutually dependent series, but the calculator say they are undefined

Is it possible to do this in numworks ? it works on my casio.

**Comment by AlainBusser** [comment]
:+1: it should be possible with matrices

**Comment by boricj** [comment]
It's a duplicate of #178.

**Comment by Ecco** [comment]
Indeed this is a duplicate so I'm going to close this issue. Thank you @yanntm for reporting this. FYI, this is something we're looking forward to fixing very soon.
