### ISSUE TITLE
Intersection points between a function and its derivative

### ISSUE THREAD

**Issue by Ozero4** [numworks/epsilon#2182]
Hello
On beta version 23.0.0 the points of intersection between a function and its derivative are not marked. Is it voluntary?

![screenshot](https://github.com/numworks/epsilon/assets/114027116/ba50fe42-05a2-46b8-a392-4dc5dd3fcb2b)

**Comment by adri1numworks** [comment]
Hello,
We did not judge that points of intersection of a function and its derivative should be highlighted. If they do, would you have an example of exercise where it is the case ?

**Comment by Ozero4** [comment]
I don't have an example but I found it strange that the intersection was highlighted as a function but not as a derivative. But it's ultimately not useful.

**Comment by adri1numworks** [comment]
FYI : the reason behind this is that we do not consider derivative as an independent object, but as a sub-object of the primary function

Thank you for closing the ticket
