### ISSUE TITLE
Battery Percentage

### ISSUE THREAD

**Issue by Thejs1234** [numworks/epsilon#2183]
It would be great if there was an option to show the battery percentage next to the battery icon on the screen of the calculator. This could be a choice for the user, meaning that there could be a setting for it in the settings app of the calculator.

![screenshot](https://github.com/numworks/epsilon/assets/86871990/50ed90d6-f8fd-4f78-872b-4c5cbe09655c)

**Comment by Arthur-GYT** [comment]
Duplicate of https://github.com/numworks/epsilon/issues/1933
