### ISSUE TITLE
Convert speeds in the toolbox

### ISSUE THREAD

**Issue by Thejs1234** [numworks/epsilon#2184]
I noticed that there is no possibility to convert speeds in the toolbox.
It would therefore be great to have the ability to do that.
(For example, m/s to km/h, km/h to mi/h and so on)

**Comment by EmilieNumworks** [comment]
This is [possible](https://my.numworks.com/simulators/nb5Bz3?extended=true) with the "store" key:

![Capture d’écran 2024-04-08 à 16 45 01](https://github.com/numworks/epsilon/assets/31415152/d1916b75-2ccb-4189-b61f-178e27b894e0)
