### ISSUE TITLE
Transfer files between calculators

### ISSUE THREAD

**Issue by Thejs1234** [numworks/epsilon#2186]
#### Problem you'd like to fix

After switching to a NumWorks from a TI-83 (Premium CE Python Edition), I was of course really happy with the fact that the NumWorks is more user friendly and has more useful features (and it's French ;) ). The problem is, that you cannot share files between two NumWorks calculators, something that I was able to do with my TI before. This was great when we were in maths class and we needed to make small python programs ; we could share them but also make other cool programs with turtle or whatever and also share these ones. We didn't need to plug our calculators into a computer. (We could additionally share data (like lists and other stuff) and firmware to update our calculators without a computer, but that's not what I'm asking here)

#### Describe the solution you'd like

It would therefore be great to have the ability to plug two NumWorks calculators with a male to male USB cable and transfer python programs (depending on the model, this is in my opinion, definitely easier with the N0120 model which has a USB-C port (I don't know if a previous model has a USB-C port) and much more complicated to find a Micro USB to Micro USB cable for the previous models with a Micro USB port).

#### Describe alternatives you've considered

You can of course plug in your calculator into your computer but it's not always a solution because we don't always have our computers turned on/with us.

**Comment by adri1numworks** [comment]
Thank you for your suggestion !
We did consider developing such a feature. However, it is not only a software issue but also a hardware issue. This would require a lot of efforts and without a strong incentive, we prefer not to prioritize such a feature for now. 
As a consequence, I close this issue. Feel free to reopen it if needed.
