### ISSUE TITLE
Floating point issue

### ISSUE THREAD

**Issue by CodeMinister2008** [numworks/epsilon#2191]
#### Werid floating point issue in when using python app
The python shell displays numbers like 9.8 as a floating-point error and it can't be fixed for some reason (even when using the round() function, it still operates and acts like the normal number, it just displays it weird

#### Screenshots
![image](https://github.com/numworks/epsilon/assets/142717111/d2c22c0b-1586-4812-8098-0ac3e5d43912)

#### To Reproduce
1.Go to python app.
2. just simply type in 9.8 into the python shell and press enter (Even works with 9.8 or any of the other numbers with factors of 10).
#### Expected behavior
print(9.8)
(Output) 9.8

#### Environment
 Software version: 22.2.1
 Happens on: Online simulator and actual device

**Comment by Rexxt** [comment]
this is probably due to python itself and how floats are represented in binary

**Comment by adri1numworks** [comment]
Hello,
I confirm this is due to Python itself. We cannot do anything about this, so I close this ticket
