### ISSUE TITLE
Surveying Units

### ISSUE THREAD

**Issue by Sinwood** [numworks/epsilon#2193]
Please implement a way to convert a degree value into DMS. 

We already can convert any DMS value into degrees. However, not the other way around. DMS = degrees, minutes, seconds. 

Thank you!!

**Comment by RedGl0w** [comment]
This already exists since the degree was added as a unit in the additional result (when you select a calculation the three dots on the right)
![screenshot](https://github.com/numworks/epsilon/assets/43498612/9780880a-d7c3-4323-b69d-1098e436a680)

**Comment by adri1numworks** [comment]
Thank you for your suggestion. I'm closing this issue as the reply above answers this question. Feel free to reopen it if needed.
