### ISSUE TITLE
Calcul d'intégrale nulle

### ISSUE THREAD

**Issue by Jclrbt** [numworks/epsilon#2199]
#### Describe the bug
Quand une intégrale est égale à 0, le calcul d'intégrale de numworks fonctionnant par approximation donne un résultat perturbant pour les étudiants.

#### Screenshots
![image](https://github.com/numworks/epsilon/assets/153604562/e364e77b-ab9f-4aa2-bec8-38736aa7d5b5)

#### Environment
 - Epsilon version 22.2.0

**Comment by adri1numworks** [comment]
Bonjour, 
Le calcul formel (aussi appelé CAS) est interdit aux examens de plusieurs pays. La calculatrice étant désormais commercialisée à l’international, nous avons décidé de ne plus autoriser ce type de calcul. 

De ce fait, notre méthode de calcul d'une intégrale est donc numérique. Ceci explique que vous trouviez une valeur approchée pour le calcul ci-dessus.

Nous réfléchissons à une solution pour pouvoir améliorer nos calculs tout en respectant les règles de tous les pays.
