### ISSUE TITLE
precision issue

### ISSUE THREAD

**Issue by erwanh1** [numworks/epsilon#220]
Hi,
I want to calculate the value of this probability p(D>150) where D follows a normal distribution with µ=90 and s=15. (bac ES/métropole septembre 2017, exercice 2) The calculator gives me the value 0 (with automatic and scientific settings). I still have 0 when I copy and paste the value into the calculation apps. TI83PCE and casio both give me a non zero value (approx. 3,17E-5) which is small I agree but not that small too. It could be a good thing to get a more accurate result to that kind of probability.

Ps : This a copy of the message I left on the reddit forum. People I saw at the APMEP meeting in Nantes asked me to post it here.

**Comment by artaxxx** [comment]
Duplicates #193
