### ISSUE TITLE
Normal distribution range is displayed incorrectly for calculated probabilities

### ISSUE THREAD

**Issue by godfatherjohn** [numworks/epsilon#2201]
The range for which the normal distribution probability is calculated is shown incorrectly. Instead of  "<=" there should only be a "<". See the screenshot, I it will become totally clear to you.

![image](https://github.com/numworks/epsilon/assets/15203094/cedf5335-343a-4ef7-ada8-2c90966e5530)

**Comment by adriweb** [comment]
It seems both definitions exist? https://en.wikipedia.org/wiki/P-value#Definition for instance has lower-or-equal

**Comment by godfatherjohn** [comment]
<70 is different from <= 70    ... I see where the "<=" comes from but it doesn't really make sense. There is a reason that the world's top maths software provider uses "<" instead of "<=".

**Comment by adriweb** [comment]
Well I don't disagree, and I myself use Mathematica quite often!
The fact that there are different definitions here and there is however problematic.

**Comment by godfatherjohn** [comment]
Amending this by turning <= into < should not be too much work.

**Comment by EmilieNumworks** [comment]
For continuous probability density functions, P(X <= a) == P(X < a) and we wanted to be consistent with the interface for discrete density functions.
