### ISSUE TITLE
Cannot download scripts to the calculator

### ISSUE THREAD

**Issue by mobluse** [numworks/epsilon#2210]
#### Describe the bug
When I try to "Load to calculator" from https://my.numworks.com/python/mobluse I get:
"Error
We're very sorry but an error occured. Your device screen might have frozen or become black. If so, please unplug your device and press the RESET button on the back of your calculator using a paperclip. In any case, please set up your calculator again."
When I click "Report" nothing happens (but maybe something that is not visible). 
When I click "Set up my calculator" I come to a page where I can only click OK, and when I do I come back to the page where I can download my scripts.
I can press Back on the calculator i.e. it's not frozen.
I could update the calculator without problems and can still do this. I also run recovery, but still get the same error. I can upload the example scripts from the calculator using https://my.numworks.com/python/calculator and button "Load in my script library". "Delete from my calculator" also works.
I would like to repair the driver, but do not know where to download it. It says "If you are using Windows, it is possible that there was a problem during the installation of the driver. You have the choice to fix it. To do this, simply download the driver again and then double-click on the downloaded file. Windows will then ask you if you want to install or repair the program. Choose Repair and restart your computer." on https://www.numworks.com/support/connect/detect/ , but there is no link to the driver. I believe the built in drivers are used now. I have restarted the computer and downloading scripts still doesn't work.

#### Screenshots
![Scripts by mobluse — Python — NumWorks - Google Chrome 2024-07-16 17_34_44](https://github.com/user-attachments/assets/51e37413-6066-45f9-8137-4815844508f8)

#### To Reproduce
1. Go to https://my.numworks.com/python/mobluse (Maybe logged in as me)
2. Plug in calculator
2. Click a "Load to calculator" button
3. See error in browser.

#### Expected behavior
The script should be downloaded.

#### Environment
 - Epsilon version: 23.2.3, 9072ab8, 00.00, 0000000C, 52D6198B
 - The platform(s) on which the problem happens: actual device, Model N0110. Browser: most updated Chrome (Version 126.0.6478.127) in most updated Windows 10 (Version 10.0.19045.4651).

**Comment by EmilieNumworks** [comment]
Hi! There was indeed a bug, thanks for reporting it. This just has been fixed!
