### ISSUE TITLE
[Python] Add the error classes to the python catalogue 

### ISSUE THREAD

**Issue by yannis300307** [numworks/epsilon#2215]
#### Problem you'd like to fix
The names of the error classes are long, so it should be well to add it to the catalogue and add autocompletion.

#### Describe the solution you'd like
Add the error classes to the catalogue.

**Comment by adri1numworks** [comment]
Hello, 
Thank you for your contribution! 
I read the PR. I think it is too advanced for our standard highschool users. I'm afraid it will pollute the catalog with too many information. In addition, all these errors take a lot of space. 
For these reasons, I will close this issue without merging the PR. I hope you'll understand, thanks again
