### ISSUE TITLE
[Python] Add classes to the "functions" catalogue

### ISSUE THREAD

**Issue by yannis300307** [numworks/epsilon#2216]
#### Problem you'd like to fix
Making a class in Python can be long to type on the calculator.

#### Describe the solution you'd like
Rename the 'functions' catalogue to 'functions and classes' and add the class template in this category such as `class Name(parent):`, built-in functions `def __init__(self):`, self variable with the dot `self.` and decorators `@staticmethod`.

#### Describe alternatives you've considered
Create another category in the catalogue.

**Comment by adri1numworks** [comment]
Hi again,
For this one, I suggest to merge only `def function(x)`. Our calculator has not been designed to do object-oriented programming and we don't want to confuse our users. Your PR will be reviewed internally.
Thank you for your understanding
