### ISSUE TITLE
Need some help compiling a new app

### ISSUE THREAD

**Issue by Grahack** [numworks/epsilon#222]
Hi,
Meeting your team this week-end motivated me to start an app:
https://github.com/ClubExpressions/epsilon/tree/clubexpr/apps/clubexpr

What I just did: brutally copy-paste `calculation` then rename every «calculation» occurence in this new app (roughly) to «clubexpr». Now I have this error at compile time:

    $ make PLATFORM=simulator debug=1
    CXX     apps/clubexpr/edit_expression_controller.o
    apps/clubexpr/edit_expression_controller.cpp: In constructor ‘ClubExpr::EditExpressionController::ContentView::ContentView(Responder*, TableView*, Shared::TextFieldDelegate*)’:
    apps/clubexpr/edit_expression_controller.cpp:13:68: error: invalid conversion from ‘int’ to ‘char*’ [-fpermissive]
       m_textField(parentResponder, m_textBody, TextField::maxBufferSize(), textFieldDelegate)
                                                                        ^
    In file included from escher/include/escher/clipboard.h:4:0,
                     from escher/include/escher.h:11,
                     from apps/clubexpr/edit_expression_controller.h:4,
                     from apps/clubexpr/edit_expression_controller.cpp:1:
    escher/include/escher/text_field.h:11:3: note:   initializing argument 3 of ‘TextField::TextField(Responder*, char*, char*, size_t, TextFieldDelegate*, bool, KDText::FontSize, float, float, KDColor, KDColor)’
       TextField(Responder * parentResponder, char * textBuffer, char * draftTextBuffer, size_t textBufferSize,
       ^
    apps/clubexpr/edit_expression_controller.cpp:13:89: error: invalid conversion from ‘Shared::TextFieldDelegate*’ to ‘size_t {aka long unsigned int}’ [-fpermissive]
       m_textField(parentResponder, m_textBody, TextField::maxBufferSize(), textFieldDelegate)
                                                                                             ^
    In file included from escher/include/escher/clipboard.h:4:0,
                     from escher/include/escher.h:11,
                     from apps/clubexpr/edit_expression_controller.h:4,
                     from apps/clubexpr/edit_expression_controller.cpp:1:
    escher/include/escher/text_field.h:11:3: note:   initializing argument 4 of ‘TextField::TextField(Responder*, char*, char*, size_t, TextFieldDelegate*, bool, KDText::FontSize, float, float, KDColor, KDColor)’
       TextField(Responder * parentResponder, char * textBuffer, char * draftTextBuffer, size_t textBufferSize,
       ^
    Makefile:117: recipe for target 'apps/clubexpr/edit_expression_controller.o' failed
    make: *** [apps/clubexpr/edit_expression_controller.o] Error 1

Any idea ?

**Comment by adriweb** [comment]
Looks like it's not selecting https://github.com/numworks/epsilon/blob/fe1e6949df0fbd8bc3f8711939db7fcc4e9e499d/apps/calculation/text_field.h#L10 as the constructor of the appropriate TextField class, for some reason, but its parent...

**Comment by Grahack** [comment]
Thanks for the help, my renaming was not complete.
