### ISSUE TITLE
[Python] Add a library to easily create GUI such as tkinter

### ISSUE THREAD

**Issue by yannis300307** [numworks/epsilon#2220]
#### Problem you'd like to fix
Making user interfaces in pure python with kandinsky and ion is very hard to do. It's not optimised and it needs a lot of code.

#### Describe the solution you'd like
Provide a new python library to make user interfaces could be very useful and it could helps programers a lot to fit the Numworks UI style.

#### Describe alternatives you've considered
Add a UI interface in kandinksy.

**Comment by yannis300307** [comment]
It could be well to have a simple Python lib that can be used in the same way as Tkinter and that expose function to easily create UI elements such as buttons, labels, entries, ... The elements' style could be the same as the OS style.

**Comment by adri1numworks** [comment]
As for you other suggestions, we consider this package as too advanced for our students. We are afraid it might confuse them, rather than help them. I'll close this ticket but if your need gets more crucial, feel free to reopen it. 
Thank you for your understanding !
