### ISSUE TITLE
Adding flush to Python

### ISSUE THREAD

**Issue by S0d4Dev** [numworks/epsilon#2239]
I have worked in a simple mastermind game made in python, and made the following code to make the letters of the text appear with a delay between them (without making newlines).

```python
import time
def message(message, delay) :
    for letter in message :
        print(letter, flush=True)
        time.sleep(delay)
```
Unfortunately, this doesn't seem to work on the calculator, and results in a TypeError:
![screenshot](https://github.com/user-attachments/assets/cc17ac5c-3e11-4e07-8070-b744f9a776d2)

Another way of doing this is using escape codes, such as `\b` for a backspace. This does work but gives a unwanted output :
![screenshot (1)](https://github.com/user-attachments/assets/42e3a26c-6f5c-451a-b66c-3bb573389b8d)

To implement this flush feature, a first option would be to add the flush type, but that may not work if that is a limitation from Micropython itself. Another way to put it would be to add the sys module (or a part of it, such as stdout, if it can't fit in the calculator). The last option (that I can think of) would be to make the the escape codes such as `\b` work, but again, I don't know if there are some limitations around.

**Comment by mobluse** [comment]
It might be possible to solve using `kandinsky`:
```
# Type text with delay between letters.
import kandinsky as k
import time
def message(message, delay):
  r=11; c=1
  for letter in message:
    k.draw_string(letter, 10*c, 18*r+2)
    time.sleep(delay)
    c+=1
message("Hello, world.", 0.2)
```
https://my.numworks.com/python/mobluse/slowtext

Another solution might be to always have flush=True as default and not be able to change it.

**Comment by S0d4Dev** [comment]
I guess using `kandinsky` to resolve this is an option we can use now. 
Unfortunately, we can't really go back to the first lines, and making it possible with `kandinsky` will loose both a lot of time to develop and space on the device.
But again, unlike Classic Python, this version of Python for embedded devices does not have the flush capabilities by default (which you can try [here](https://micropython.org/unicorn/)), so I do not know how hard or at which cost (in terms of space) it will be implemented.

**Comment by mobluse** [comment]
At https://micropython.org/unicorn/ I tried:
```
import time
def message(message, delay) :
    for letter in message :
        print(end=letter)
        time.sleep(delay)
message("Hello, world.", 0.2)
```
And it works as expected because it has flush=True by default.

**Comment by adri1numworks** [comment]
After investigation, we do not have a simple solution to offer you. The workaround proposed by @mobluse seems to address your problem, at least partially. I close this issue in consequence
