### ISSUE TITLE
autorefresh(false) for Kandinsky Module

### ISSUE THREAD

**Issue by Idaill** [numworks/epsilon#2242]
Hi,
I know you guys have a lot of work, but i have an idea to make two fonctions for the kandinsky module

kandinsky.autorefresh(bool)
kandinsky.refresh()

Because when im drawing an image on the numeworks it takes too much time.
Have a great day !

**Comment by mobluse** [comment]
In addition to the [kandinsky module NumWorks also has a smaller version of the turtle module](https://www.numworks.com/manual/python/). The full `turtle` has some [animation control](https://docs.python.org/3/library/turtle.html#animation-control).

Then the corresponding methods in full `turtle` would be:
```
screen.tracer(sys.maxsize) # The sys module doesn't exist in Numworks now,
                           # but exists in MicroPython.
screen.update()
```

I think `tracer()` and `update()` could also apply to `kandinsky`. I think it would be better to expand `turtle` in NumWorks with e.g. [animation control](https://docs.python.org/3/library/turtle.html#animation-control) and [filling](https://docs.python.org/3/library/turtle.html#turtle.filling) and then the kandinsky module would hardly be needed.

**Comment by adri1numworks** [comment]
Hello,
Thanks for your suggestion. We don't estimate this to be a priority and I'll close this in consequence. Feel free to reopen the issue if needed
