### ISSUE TITLE
nwlink broken with latest Epsilon versions

### ISSUE THREAD

**Issue by Tatone26** [numworks/epsilon#2243]
#### Describe the bug
The command "nwlink install" doesn't seem to work on latest (beta) versions of epsilon. 
I never had any problems with it before, not even with beta updates. Any app.nwa installed this way just make the calculator crash (at least on N110, as I don't have any other one). 
Strangely, apps installed via the website and WebUSB work as intented. 
NWLink is a very useful package when trying to make an external app, so it would be great if it worked again !

#### To Reproduce
1. Install nwlink as a Node package
2. try to install a .nwa file via the nwlink install command 
3. crash on launching

#### Expected behavior
The app should work just fine, as it does when installed via my.numworks.com/apps

#### Environment
 - Epsilon version : 23.2.5, same problem with 23.2.3 before
 - N110
 - Linux (Ubuntu based) as a PC

**Comment by adri1numworks** [comment]
This issue has been reported internally, we'll keep you posted.
