### ISSUE TITLE
Sympy

### ISSUE THREAD

**Issue by Sclun** [numworks/epsilon#2244]
Hey,
I'm not so sure it is here, where it must be done, and may-be it already had been proposed before, but anyway.
I would love that you add sympy module of python to your calculator.  I do not realise how big it is, but it would be SO useful especially for literal calculation and exact values of several calculus.
Well that is it.
Thank for reading my request, hoping it is possible

**Comment by mobluse** [comment]
Since sympy is a CAS it could not be used in exam modes that don't allow CAS.

**Comment by adri1numworks** [comment]
Thanks for your request. Sympy is a pretty advanced module. Seeing the low demand and the effort to code it, plus the storage we would have to allow to Sympy, we've decided not to implement it. I close this issue, feel free to reopen it if needed
