### ISSUE TITLE
Exponential operator ** that works in Python should also work in Calculation

### ISSUE THREAD

**Issue by mobluse** [numworks/epsilon#2245]
#### Problem you'd like to fix
Since NumWorks is a calculator with Python and "power of" in Python is written `**` (instead of `^`). I think `**` should also work in Calculation. Now you get Syntax error.

#### Screenshots
![screenshot](https://github.com/user-attachments/assets/c429cf87-011b-445a-a041-40984dc2f4f9)

#### Describe the solution you'd like
If you have linear writing format 2^3 and 2**3 should do the same. If you have natural writing format it could change to writing exponent after the second pressed times sign.

#### Describe alternatives you've considered
An alternative is to use linear format always for double times signs even in natural mode.

#### Additional context
Some program languages and calculators such as R and GeoGebra already supports both `^` and `**` for the exponential operator. In Python and JavaScript it's only `**` since `^` is used for bitwise xor. Some older languages such as Fortran uses `**` with same associativity as Python and JavaScript (right to left) which is the same associativity NumWorks uses for linear `^`: `2**3**4 = 2^3^4 = 2.417852e+24`. In ZX81 BASIC `2**3**4 = 4096` and in ZX Spectrum and C64 BASIC V2 `2^3^4 = 4096` which is a less useful associativity (left to right).

**Comment by adri1numworks** [comment]
No we do not want `**` to work in Calculations. Our main users are highschool students and this would bring a lot of confusion. I'll close this issue, feel free to reopen it if needed
