### ISSUE TITLE
Would it be possible to run this on a esp32s3. Or build a custom calculator with stm32?

### ISSUE THREAD

**Issue by KOEGlike** [numworks/epsilon#2248]

**Comment by Spectralo** [comment]
if you have the same components some background knowledge about electronics and pcb designing yeah. but whats the point ? Just buy a used n0110 😅

**Comment by KOEGlike** [comment]
It would be a fun side project. And are you in hack club slack?

**Comment by Spectralo** [comment]
Yes I am 😅

**Comment by Spectralo** [comment]
I think open sourced PCBs of numworks are still somewhere but I don't really understand what will be the point of making one if you can't use it in school (because it won't be approved)

**Comment by Spectralo** [comment]
Making your own open source calculator could be sick !

**Comment by EmilieNumworks** [comment]
It's indeed possible. Some resources for the hardware can be found [here](https://www.numworks.com/engineering/hardware/electrical/)! You need to develop your own drivers though as epsilon-core is not a public repo.
I'll close this issue since it's out of the scope of the repo 😅
