### ISSUE TITLE
Find exact values in distributions

### ISSUE THREAD

**Issue by FaisalAhmed123** [numworks/epsilon#2254]
#### Problem you'd like to fix
Find exact values (where possible) in the distribution app, rather than having to carry out calculations manually. For example when inputting 1/3, this would get approximated to 0.33333333333. And lose a small amount of precision, but more importantly takes away the ability to get exact solutions.

**Comment by fbeleznay** [comment]
For small values of number of trials, some might find this useful for binomial probabilities (and maybe for other discrete distributions).
Having said this, a decimal value for me is more intuitive even in cases where an exact value can be found, especially if the exact value (as a fraction) has a large denominator, so if this is implemented, please keep the option to see the decimal approximation.
One possible compromise is to display the decimal approximation on the distribution screen, where the space is limited for the output, but keep an exact value when a user wants to store the output.
