### ISSUE TITLE
[Calculation] Union and intersection for lists

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#2257]
#### Problem you'd like to fix
In the toolbox, it is now possible to handle lists via the {1,2,3} format.
Alas! There is no way (known on my side) to get the union or intersection of two lists.

#### Describe the solution you'd like
· Either extend the workable parameters for “and”/“or” to make them handle lists
· Either (even better) create two new list operators displayed with dedicated symbols ⋃ and ⋂ for this

#### Describe alternatives you've considered
Using the Python app, with & and | operators

**Comment by mobluse** [comment]
Lists in Calculation look like sets in Python. Sets in Python have union and intersection.
```
{1,2,3}.union({3,4})
{1,2,3}.intersection({3,4})
```
work in Python shell on NumWorks.

**Comment by adri1numworks** [comment]
On our Calculations app, we consider `{ }` as lists and not sets (unlike in Python app). Lists are not relevant with union and intersection, as they can contain the same object multiple times (eg. [1,2]U[1,2] would be [1,1,2,2]...)

So, I'd suggest using Python as @mobluse suggested in his last comment. 

Thank you for your understanding
