### ISSUE TITLE
Should deleteCharPrecedingCursor() be private?

### ISSUE THREAD

**Issue by Grahack** [numworks/epsilon#226]
Hi all,

I'm trying to modify the behaviour of the Backspace key for a new app.
I'd like to call `deleteCharPrecedingCursor()` but I'm stuck because of it being *private*.

I changed it to *public* and I can do what I want now.

1. My C/C++ is still rusty, am I missing something ?
2. If yes, is there a good reason for it to be private ?

**Comment by Ecco** [comment]
Hi @Grahack ! That's a good question. The framework being young we're trying to make as few things public as possible. In the meantime, you can edit the text buffer manually and eventually call `reload` and `setCursorLocation`.
