### ISSUE TITLE
Change = to an approximate sign for asymptote

### ISSUE THREAD

**Issue by hatfield96** [numworks/epsilon#2264]
When in the graph tab, when approaching an asymptote, the number changes to a whole integer when the calculator run sout of decimal places but the equality does not change to an approximate sign (≈).  This seems like it would be a simple code update.

![Screenshot 2024-11-10 11 18 26 AM](https://github.com/user-attachments/assets/d7787c38-f637-4e6a-aef2-4cf1a891647c)
![Screenshot 2024-11-10 11 19 30 AM](https://github.com/user-attachments/assets/119f5787-66e6-4019-a6ea-93848475e55c)

Values for decimals that are estimates should always display as approximate.

Fractional answers would be a very helpful alternate as well, but would still need the approximate when the denominator becomes too large.

**Comment by adri1numworks** [comment]
Actually we calculate all values numerically so we would have to display an `≈` sign almost everywhere in the app. We consider this would be more confusing than anything else. 

Now, we could calculate exact results but it raises multiple questions, both in terms of how we should display those (for example irreductible fractions) and how we could even calculate these exact results (we are not using CAS, hence we necessarily estimate results at one point). 

As such, I prefer closing this issue. Feel free to reopen it if needed
