### ISSUE TITLE
Allow more user freedom with Epsilon

### ISSUE THREAD

**Issue by ADHyperActive** [numworks/epsilon#2270]
#### Problem you'd like to fix
If Epsilon is open source, it would make more sense to allow things like Omega and Upsilon on the N0120.

#### Describe the solution you'd like
Maybe allow a custom OS to be installed, but put a warning on the Numworks website stating that Numworks isn't liable for anything that installing the custom OS causes, and that cheating with the custom OS will cause a warranty void and end support for the calculator involved in the cheating (if it is student-owned).

#### Describe alternatives you've considered
Allow a custom OS to be installed, but state on the website that installing a custom OS will void the warranty and the calculator will not be allowed on tests.

**Comment by adri1numworks** [comment]
Thanks for your input. However, because of exams restrictions, this is not something we want to encourage. I close this issue as we will not go into this direction.

**Comment by EmilieNumworks** [comment]
Installing a custom OS is already possible but redistribution is not allowed for the reasons adr1numworks mentioned.
