### ISSUE TITLE
Simulators don't store state

### ISSUE THREAD

**Issue by Unexian** [numworks/epsilon#2278]
#### Describe the bug
The android simulator (and probably the other two as well) don't store state on exit and load on re-open.

#### Screenshots
N/A (requires closing simulator)

#### To Reproduce
1. Open the simulator
2. Do anything (e.g. run an expression)
3. Close the simulator
4. Open the simulator
5. Go back to what you did

#### Expected behavior
What you did in the last session gets carried over to the current session

#### Environment
Android Simulator v23.2.1 (0d2caeb)

((edit to remove template hints))

**Comment by XanderLeaDaren** [comment]
AFAIK, this is the expected behaviour for the (because it’s free!) mobile app

**Comment by Unexian** [comment]
Fair
