### ISSUE TITLE
Problems while building the web simulator

### ISSUE THREAD

**Issue by Grahack** [numworks/epsilon#229]
Hi,

Still very new to this codebase, I attempted to build the web simulator.  
Two issues:

**1)** I got many `xxx.o is not valid LLVM bitcode` errors. I guessed I needed to clean but `make clean` then `make PLATFORM=emscripten` triggered this:

    CXX     ion/src/emscripten/main.o
    In file included from ion/src/emscripten/main.cpp:4:
    ion/src/emscripten/../../../apps/global_preferences.h:4:10: fatal error: 'i18n.h'
          file not found
    #include "i18n.h"
             ^
    1 error generated.
    ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
    Makefile:117: recipe for target 'ion/src/emscripten/main.o' failed
    make: *** [ion/src/emscripten/main.o] Error 1

So I built with `make PLATFORM=simulator` then did `make PLATFORM=emscripten clean` and the build started correctly.

**2)** Now the build stops here:

    ...
    CXX     escher/src/window.o
    LD      app.html
    Exception in thread Thread-3:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
        task = get()
    TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

Any idea ?

**Comment by adriweb** [comment]
It's building fine for me (latest stable versions of everything). Are you sure you have the latest epsilon repo clone (in master) ? There were some i18n changes recently.

```bash
13:28:10 ⌂105% [:~/Documents/epsilon] coverity-fixes+* ± make PLATFORM=emscripten -j8 info
========= BUILD SETTINGS ======
DEBUG = 0
PLATFORM = emscripten
CC = emcc
CXX = emcc
LD = emcc
CFLAGS = -std=c99
CXXFLAGS = -std=c++11 -fno-exceptions -fno-rtti -fno-threadsafe-statics
SFLAGS = -DDEBUG=0 -DOS_WITH_ONBOARDING_APP=0 -DOS_WITH_SOFTWARE_UPDATE_PROMPT=0 -DQUIZ_USE_CONSOLE=0 -Os -Ilib -I. -Wall -MD -MP -Iliba/include/bridge -Iion/include -DKD_CONFIG_H=1 -Ikandinsky/include -Ipoincare/include -Ipython/src -Ipython/port -Iescher/include -Iquiz/include
LDFLAGS = -s EXPORTED_FUNCTIONS=[_main, _IonEventsEmscriptenPushEvent] -Os --shell-file ion/src/emscripten/shell.html
===============================
13:30:39 [:~/Documents/epsilon] coverity-fixes+* ± emcc --version
emcc (Emscripten gcc/clang-like replacement) 1.37.21 ()
```

![build on firefox](https://i.imgur.com/5XjXAx9.png)

**Comment by Grahack** [comment]
Thx @adriweb, with `emcc` version 1.36 it works ok (the faulty was 1.22, from my software repos).

Sorry for the noise everyone !

**Comment by Grahack** [comment]
Thx @adriweb, with `emcc` version 1.36 it works ok (the faulty was 1.22, from my software repos).

Sorry for the noise everyone !
