### ISSUE TITLE
[enhancement] to the infinity and beyond 

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#230]
In the calc app, it is possible to enter "inf" as an expression, and get a result like `0` if entered `1/inf`

It would be great if one could enter `inf` or `-inf` as a value in the functions and sequences apps, in the "go to" category; right now it says `undefined`

If for example one defines `u(n)` as a geometric sequence like `u(n)=50*0.9^n` and enter `inf` for the n value, one would get `0` which is actually the limit of the sequence. Idem if one entered `u(n)=re((0.6+0.4i)^n)`

In the Python app one should be able to use` float("inf")` too.

I know of no other calculator which can compute limits without symbolic calculus :stuck_out_tongue_winking_eye:

**Comment by boricj** [comment]
It's not mathematics' ideas of infinity and undefined, but IEEE754's. I'd rather not mix the two since they are not remotely equivalent.

**Comment by AlainBusser** [comment]
Actually there are mathematical theories explaining the choices of IEEE754; one of them is based on an [Aleksandrov construction](https://en.wikipedia.org/wiki/Alexandroff_extension); an other one is based on [projective geometry](https://en.wikipedia.org/wiki/Projective_space); the most important thing for me is that these theories seem more natural to my pupils than the rules of symbolic computing. For example, instead of saying that the ln function is defined only on positive numbers and approaches -∞ as x approaches 0, they prefer to imagine that any nonnegative number has a logarithm and that this logarithm is -∞ if x is 0. In other words they consider -∞ and +∞ as numbers and know more or less how to compute on these numbers.


Be it math or IEEE754, I prefer that a student write in this language than nothing at all, which is very frequent in the exams...

**Comment by artaxxx** [comment]
We don't plan to support inf as a value, so I'll close this issue. The best way would be to handle the computation of limits in an exact way (using CAS) as reported in #219
