### ISSUE TITLE
screen overflow in Python app

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#231]
The program `print(list(range(20)))` yields this screen:

![screenoverflow](https://user-images.githubusercontent.com/3930757/32112361-1eff0b2a-bb4e-11e7-98b6-eba97daddc3b.png)

There does not seem to be a way to navigate beyond the right side of the screen, so should not the display go automatically to the line?

**Comment by Ecco** [comment]
Indeed it should. Thank you @AlainBusser for reporting this!

**Comment by artaxxx** [comment]
As the Python app has been redesigned, I close this issue
