### ISSUE TITLE
infinity and multiplication

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#234]
Hello, in the Calc App,

- `inf+inf` yields `inf` as it should
- but `inf*2` and `2*inf` yield `undef` instead (the result should have been `inf`)
- `inf*inf` yield `undef` too instead of `inf`

And this bug implies an other one, by example `0.5^inf` yields `0` as it should but `1.5^inf` yields `undef` whereas the correct answer should be `inf`.

**Comment by AlainBusser** [comment]
I have found more about that: e^(-inf) yields 0 but e^(inf)  yields undefined. That is quite normal if inf is supposed to be a complex number (-inf is real, not complex, because of the minus sign). But e^(+inf) yields a syntax error. Any expression beginning with "+" seems to yield a syntax error by the way...

**Comment by AlainBusser** [comment]
I have just seen that in the Python App the bug is resolved: if I create a variable z=float("inf") I can print z+z and z*2 and still getting inf. Whereas 1/z yields 0.0

It would still be simpler not to have to use the Python app and directly get results with the calc app. And my pupils complain that there is no "∞" button on their calculator :stuck_out_tongue_winking_eye:

**Comment by artaxxx** [comment]
It's now fixed in 1.8.1 !
