### ISSUE TITLE
Glitchy graph

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#235]
1. add f(x)=x func. (or any func)
![image](https://user-images.githubusercontent.com/10530980/32683213-ef1e931c-c679-11e7-8a9f-70ecea0ef28e.png)
2. set a decimal value to the xmin
![image](https://user-images.githubusercontent.com/10530980/32683252-3d32a7fa-c67a-11e7-8fa1-f32638268ae0.png)
3. set pow values to xmax
![image](https://user-images.githubusercontent.com/10530980/32683268-5ed1fe2e-c67a-11e7-9e3b-a39484b38e64.png)
4. when pressing enter:
![image](https://user-images.githubusercontent.com/10530980/32683284-6abfdc88-c67a-11e7-98ef-b3b4f19869a9.png)

Seems buggy that Xmin suddenly changes itself

**Comment by adriweb** [comment]
Doesn't look like a bug to me: the Xmax value would have been lower than the Xmin value, so the calculator automatically readjusts the Xmin to be lower :)
If I'm not mistaken, the relevant code is [here](https://github.com/adriweb/epsilon/blob/17ac54cad5f13b75aab5ed0f44fb6b2cdb5cd7ed/apps/shared/interactive_curve_view_range_delegate.cpp#L9), from what I quickly gathered.

**Comment by gpotter2** [comment]
My bad you're right

**Comment by adriweb** [comment]
No problem - at least it was a well formatted post, making it easy to try :P
