### ISSUE TITLE
Pows: inconsistancy

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#236]
![image](https://user-images.githubusercontent.com/10530980/32683346-e82abc42-c67a-11e7-8a50-2d74b7b68f0f.png) gives  ![image](https://user-images.githubusercontent.com/10530980/32683356-f124c54a-c67a-11e7-98fb-1e4abaab7f74.png)

BUT

![image](https://user-images.githubusercontent.com/10530980/32683369-06c2a3cc-c67b-11e7-92bc-c5d6d420bca8.png) gives  ![image](https://user-images.githubusercontent.com/10530980/32683381-109add7e-c67b-11e7-9ade-86a2ac558148.png)

**Comment by artaxxx** [comment]
Thanks for reporting that one!

**Comment by artaxxx** [comment]
Fixed in the new version (1.5.0)
