### ISSUE TITLE
Graph: Y-auto doesn't play well with a vertical asympote

### ISSUE THREAD

**Issue by homeostasie** [numworks/epsilon#241]
For a function such as `1/c`, the `y-auto` option doesn't make much sense.

It tries to display values that are way too high which results in a shrunk-down plot.

![1/x](https://i.imgur.com/3nFs4q9.png)

And by the way, reaching the "axes/zoom/preadjustment" menu can be cumbersome.

> Original french version
>
> Pour une fonction comme 1/x l'option **Y auto** n'est pas du tout pertinente.
> 
> Il cherche à représenter des valeurs bien trop hautes et écrase alors la courbe dans un repère qui a de trop grandes graduations.
> 
> Exemple : https://i.imgur.com/3nFs4q9.png
> 
> De même l'accès au troisième sous menu : Axes; Zoom et Initialisation est souvent laborieuse.

**Comment by Ecco** [comment]
Thank you very much for your report @homeostasie ! I translated your original report to english because we have contributors who can't speak french.

**Comment by homeostasie** [comment]
Thanks for the translation, I'm not fluent and don't practice English enough lately...

**Comment by homeostasie** [comment]
I'm not sure.

I think  constants in  **epsilon/apps/shared/interactive_curve_view_range.h** are involved.

`
constexpr static float k_minFloat = 1E-8f;
constexpr static float k_upperMaxFloat = 1E+8f;
constexpr static float k_lowerMaxFloat = 9E+7f;
constexpr static float k_maxRatioPositionRange = 1E5f;
`

**Comment by homeostasie** [comment]
Nice.
