### ISSUE TITLE
Search for graphic intersections between two functions

### ISSUE THREAD

**Issue by BriacLP** [numworks/epsilon#244]
I would like, when I have two functions, to be able to search the intersections of them by clicking on a button (OK -> Find intersection as for "Go a")
![sqfdqsd](https://user-images.githubusercontent.com/32522843/32931778-6662caf6-cb66-11e7-92e4-e59e7aff7505.png)

**Comment by artaxxx** [comment]
Thanks Briac for your suggestion, this is indeed something we want to do. There is already an existing issue about this (#70) that's why I'm closing your issue. Thanks again!
