### ISSUE TITLE
Select previous results containing "ans"

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#250]
It's no longer possible to select previous results which used "ans" in their expressions.
Because it's already possible to select the calculation without its result, it is not something normal.

- To sum up; because it's possible to do this:
![image](https://user-images.githubusercontent.com/10530980/33623327-ec8316ca-d9f0-11e7-9934-18b60850c05e.png)
Then doing this:
![image](https://user-images.githubusercontent.com/10530980/33623226-9d50073e-d9f0-11e7-9e74-729531bd1196.png)
should give us the result "10" rather than the calculation containing "ans"

BTW very great job with 1.2.0 ! Amazing work

**Comment by Ecco** [comment]
Thanks for the kind words @gpotter2  😄 

Now, I'm not quite sure to understand what you're suggesting though… Do you mean "2*ans" should not even appear as a result?
