### ISSUE TITLE
int(e^(-x^2),0,10000) gives a false result

### ISSUE THREAD

**Issue by artaxxx** [numworks/epsilon#258]
<img width="205" alt="capture d ecran 2017-12-06 a 14 42 42" src="https://user-images.githubusercontent.com/20040032/33664393-c1a11ae4-da93-11e7-9185-4138fb0fda08.png">
The correct result is sqrt(pi)*erf(10000)/2 = 0.88...

**Comment by AlainBusser** [comment]
It seems that erf is not present in the version of C++ which is used. This would simplify the computing of this integral. As for the general case your example shows that the method of the rectangles is not always precise. Why not try to implement [this method](https://en.wikipedia.org/wiki/Gaussian_quadrature) instead ?

**Comment by artaxxx** [comment]
As there is no CAS for integration for now, erf woudn't be that helpful in this case. As you can see (poicare/src/integral), the method used for computing the integral is Gauss-Kronrod. It works for int(e^(-x^2),0,1000) but when you go further than 1000 (for instance 1005) the result is awkward

**Comment by rajdakin** [comment]
There is still a bug present around integrals: (the result should be 6pi = 18.85...)
![int((3x-2)sin(x),-pi,pi)](https://user-images.githubusercontent.com/19759122/115360237-bd331880-a1bf-11eb-9081-de625938e63a.png)
Tested on the last version of the simulator and the physical calculator, updated to the last version.

**Comment by artaxxx** [comment]
This is not a bug, you're in degrees:
![screenshot (29)](https://user-images.githubusercontent.com/20040032/115362533-ece32000-a1c1-11eb-962d-789ea662ee2a.png)

**Comment by rajdakin** [comment]
Yes, thank you... Now it works. (However the first integration is still wrong, I just checked.)

**Comment by artaxxx** [comment]
Fixed in 19.0.0
