### ISSUE TITLE
Error when computing the GCD of big integers

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#268]
`gcd(2^100-1,2^60-1)` gives `1`, should be `1048575`
 `gcd(2^99-1,2^60-1)` gives `31`, should be `7`

**Comment by parisseb** [comment]
2^64-1 is wrong. This should help localize the issue.

**Comment by Ecco** [comment]
Indeed, thank you very much!

**Comment by artaxxx** [comment]
Fixed (#270)
