### ISSUE TITLE
≈ is always used on scientific mode

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#278]
1- Turn on scientific mode
![image](https://user-images.githubusercontent.com/10530980/33806823-dd81c37a-ddcd-11e7-9a29-6e8735541adb.png)
2- `≈` should be `=`
![image](https://user-images.githubusercontent.com/10530980/33806824-e2bef92a-ddcd-11e7-97e5-01d3d8005c81.png)

This is very minor and could be ignored

**Comment by artaxxx** [comment]
Fixed in 1.3.0 release
