### ISSUE TITLE
Integer factorization

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#279]
In Toolbox → Arithmetic, function "Integer factorization" is missing and could be really cool

I tried to find a documentation to code this function myself, but didn't find… Have to look in the code or their is an manual somewhere to help?

Epsilon 1.2 (awesome) release

**Comment by AlainBusser** [comment]
:+1:  An even cooler thing would be "divisors", yielding a matrix containing the divisors of an integer. Very good way to reach the notion of gcd

**Comment by debrouxl** [comment]
The low amount of RAM prevents the integration of the factoring methods which can find large factors; however, beyond the obvious TF to low limits, Pollard's Rho heuristic works pretty well to shave small factors off composites, and it requires little memory.
Likewise, fast probabilistic primality testing can be done with 256 KB of RAM: TI did it on the TI-68k series.

**Comment by artaxxx** [comment]
Fixed #316
