### ISSUE TITLE
Logarithms with bases different from 10

### ISSUE THREAD

**Issue by polpodan** [numworks/epsilon#282]
Using firmware 1.2.0, there's seem to have a bug with the calculation of logarithms.  
If i enter log (2, 64), it gives me the same thing as if i enter log (64, 2).  Worst of all, entering log (2,64) displays log 64 (2)!!  Worst of all, log (6,8) gives 4,89!!  There's something wrong here!

**Comment by Ecco** [comment]
Indeed, thank you very much for reporting this! Several issues indeed:
`log(64,2)` should be simplified to `6` and not `6*log(2,2)`
`log(2,64)` should be `1/6` and not `6`

**Comment by Ecco** [comment]
This was fixed with #283. Thank you for reporting this issue @polpodan !
