### ISSUE TITLE
[apps/settings] Reducing languages number makes app crash

### ISSUE THREAD

**Issue by rapgenic** [numworks/epsilon#293]
When I compiled the code with `EPSILON_I18N_LANGUAGES=en` option Settings app started crashing on some entries.

Looking at the code I think this bug is caused by [this line](https://github.com/numworks/epsilon/blob/2452e3c2c1bc7642d853dba6d361b237ffd3e45e/apps/settings/sub_controller.h#L42) in sub_controller.h file:
```c++
constexpr static int k_totalNumberOfCell = I18n::NumberOfLanguages;
```
The number of allocated `MessageTableCellWithBuffer` depends on that constexpr, and while it works with 5 languages, when you use only one of them, the allocated cells are not enough to display submenus with more than one element.

I managed to get everything working by defaulting it to 5, but it's not a reliable solution, because someone might add a menu with 6 elements or more and the bug would show up again.

**Comment by adriweb** [comment]
Yep, this is a dup of #179 actually

**Comment by rapgenic** [comment]
Sorry, my fault. Closing it now.
