### ISSUE TITLE
simplify fraction

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#294]
12/8.4 = 10/7

Numworks only displays approximations with decimal fractions, it could be interesting to return simplification

release: 1.2.0

**Comment by ooxi** [comment]
This is an interesting problem. While simplifying integer fractions is trivial (but computationally expensive) I'm not aware of an algorithm for simplifying non integer fractions.

Could you maybe provide hints into the required math?

**Comment by Ecco** [comment]
I fail to see how decimal fractions would be fundamentally different from integer ones. Just convert both the numerator and the denominator to the corresponding integer fraction (e.g. `12/8.4` becomes `(12/1)/(84/10)`, and voilà, you're back in integer fractions world :-)

**Comment by franck179** [comment]
We could have a function (maybe in the tools box) to convert a decimal into a fraction when possible. For example the 0.4 result could be written 2/5 = 0.4 after applying such a function ? This seems very useful for many students !

**Comment by FrnchFrgg** [comment]
I think that indeed most of my (french, if that matters) fellow math teachers expected 0.3 to yield 3/10 = 0.3 when typed. One would have to take care about some approximate result being promoted to a fraction with a 10^16 denominator, but when typing a decimal number with a few places one almost always mean some x / 10^n fraction and not "I am typing by hand some approximation of a value".
Of course, if you are computing probabilities and type (0.38)^6, you might not care about the fact that it is (38/100)^6, but it does not hurt either to have a fractional result displayed.

**Comment by Ecco** [comment]
Great news: we've eventually solved this! We decided to do the following:

* Keep the previous behavior, since most of the time when a user types in a decimal value it was meant as an approximation
* If the user selects the approximated result, we offer the option to use the exact fractional result as well 😄 

![select exact fractional result](https://user-images.githubusercontent.com/55989/57911951-6e6cfd80-7889-11e9-8244-abcc22d6c602.gif)

**Comment by XanderLeaDaren** [comment]
Out of interest, why was it decided to desplay the exact fractional result only when selecting it, as opposed to always displaying it?

**Comment by Ecco** [comment]
The idea is that, most of the time, when the user types in a decimal number, he/she is only interested in the approximate result. This happens all the time in physics for instance: compute the current flowing through a 42.7 ohm resistor at 4.2 volts.
