### ISSUE TITLE
keyboard repeat too fast

### ISSUE THREAD

**Issue by notandxor** [numworks/epsilon#303]
The keyboard repeat (arrows, bs) is too fast and often accidentally triggered. I could not remember having this issue before release 1.2.0. Maybe as a result of #243 ?

adjusting ion/src/shared/events_keyboard.cpp:

constexpr int delayBeforeRepeat = 250;  // was 200, too fast
constexpr int delayBetweenRepeat = 100;  // was 50, too fast

works better but that's subjective. Going up to more than 300 (ms?) disables the keyboard repeat.

**Comment by Ecco** [comment]
Good catch! And it might indeed be a consequence of #243 - looks like we need to recalibrate our delay loop. Thank you for reporting this @notandxor !

**Comment by artaxxx** [comment]
Fixed in 1.3.0 release
