### ISSUE TITLE
Emulator : Can't compute binomial law with n=100 (revert to n=10)

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#318]
Go to the online emulator, in binomial section. Try to write n = 100 it will revert to n = 10. No issue found with other number. The problem doesn't exist on the real calculator.

google chrome Version 63.0.3239.132 (Build officiel) (64 bits).

**Comment by Ecco** [comment]
Wow, that's a weird bug! It does indeed only happen on the online simulator though. Thank you for findinf this @matheod!

**Comment by artaxxx** [comment]
This bug is no longer present on the emulator
