### ISSUE TITLE
factor(10007) should return 10007, not undef

### ISSUE THREAD

**Issue by parisseb** [numworks/epsilon#321]
The Numworks integer factorization algorithm is trial division up to 10000, but the github current implementation fails to observe that if an integer is smaller than 10000^2 (in fact strictly smaller than nextprime(10000)^2==10007^2) and all division tests have failed, then it *is* prime. This should really be fixed before the next release, otherwise a (good) highschool student (in 3eme or 2nde in France) would find the Numworks algorithm really dumb...

**Comment by EmilieNumworks** [comment]
Thank you for the advice, I am fixing that soon!

**Comment by adriweb** [comment]
@parisseb : Apparently fixed with https://github.com/numworks/epsilon/commit/3c5b840d5 :)

**Comment by artaxxx** [comment]
Fixed in 1.3.0
