### ISSUE TITLE
Docker image for sdk build ?

### ISSUE THREAD

**Issue by edi9999** [numworks/epsilon#330]
I've tried to install the sdk on my laptop to try to fix some bugs for fun, but already had some issues  when running the command `make PLATFORM=simulator`, as described in 
https://www.numworks.com/resources/engineering/software/sdk/ (I'm running fedora, and ftlk is not part of the packages out of the box): 

```
/bin/sh: fltk-config: command not found
```

As I now I can install it on my computer, that is something that is making contribution more complex.

Do you have a docker image that you could publish ?

**Comment by edi9999** [comment]
I got it working with following dockerfile /run.bash


```
docker build -t epsilon-app .
xhost +
docker rm epsilon -f >/dev/null 2>&1 || true
XSOCK=/tmp/.X11-unix

docker run \
	-ti \
	--name epsilon \
	-e DISPLAY="$DISPLAY" \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	epsilon-app \
	/var/epsilon/app.elf
```

```
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y bison build-essential dfu-util flex gcc-arm-none-eabi git libfltk1.3-dev libfreetype6-dev libpng12-dev python2.7
RUN ln -s /usr/bin/python2.7 /usr/bin/python
WORKDIR /var
RUN git clone https://github.com/numworks/epsilon.git
WORKDIR /var/epsilon
RUN git pull
RUN make PLATFORM=simulator clean
RUN make PLATFORM=simulator
CMD ["./app.elf"]
```

**Comment by Ecco** [comment]
That's an interesting suggestion, but we don't think it's needed. Thanks though!
