### ISSUE TITLE
The toolbox pop-up's title is not localized

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#343]
* Set language to French
* Press the "toolbox" key
* The title says "Toolbox".

![Screenshot](https://i.imgur.com/9TSC8IB.png)

**Comment by UDXS** [comment]
This appears to be a design decision as it is written "Toolbox" in all language files but I have made a PR for it.

**Comment by UDXS** [comment]
After testing it, this error has to do with the fact that the MathToolbox is not reinitialized after language change while PythonToolbox does it every time you open the python app so the translation applies. This also happens in the settings app once the language is changed where the window title does not change with it. I propose doing some form of system reset after language change, in the same way iOS does after one changes a language (black screen and text saying "Changing language...").

**Comment by LeaNumworks** [comment]
Closing since this was solved by fd407ce3d9938072902d73de
