### ISSUE TITLE
When building on macOS 10.13, Ion::random always returns zero

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#349]
When building on macOS 10.13 on the device, Ion::random always returns zero.

```shell
$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1
20170620 (release) [ARM/embedded-6-branch revision 249437]
```

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D47
```

Tested on revision 34d219f5

**Comment by parisseb** [comment]
For the random generator, I suggested to use Knuth &Lewis implicit congruential generator modulo 2^32
unsigned Random(){ static unsigned r=0; return r = 1664525*r+1013904223; }
For more randomness, call it twice and keep the 16 high bits.

**Comment by boricj** [comment]
My understanding is that this issue happens on the real device (using the hardware RNG of the STM32F4) when the firmware is compiled with macOS. So it's not about the software RNG in the simulator.

**Comment by parisseb** [comment]
Avoiding a call to the hardware RNG is one way to solve this issue. Moreover you have full control on what happens (how does the hardware RNG work? Can you trust it?), with the same behavior on all platforms. If a simple congruential RNG is considered not good enough (which I doubt considering the target audience of the Numworks), there are alternatives like Mersenne twister. The one I gave has one advantage, it is fast (32 bits arithmetic, no division).

**Comment by Ecco** [comment]
The subtle difference here is that the hardware RNG is an actual RNG, as opposed to PRNGs that you can code in software. In practice, using an actual RNG would yield different results for `random()` even after a reset, whereas a pseudo-random generator would always return a deterministic sequence.

Not that it matters much though, and we may indeed fall back to using a PRNG. But given a hardware RNG is here, we thought we might as well use it!

You can find comprehensive information about said RNG in section 15 of the [STM32F412 reference manual](https://www.numworks.com/assets/datasheets/stm32f412-arm-mcu-reference-manual-a03f5b0ae9bc9e4ee6627314302bf307debc10c6ece680af9eb1aeecc0e47493.pdf).

**Comment by Ecco** [comment]
One interesting example: imagine a class of students learning about the `random()` function. They've never used it before, and all start using it for the first time in class following teacher instructions. It would be kinda weird if all of them got the same results, wouldn't it?

**Comment by Ecco** [comment]
Back on the actual bug, following configuration yields a correct build:

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510
```

```shell
$ arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.2.1
20151202 (release) [ARM/embedded-5-branch revision 231848]
```

**Comment by Ecco** [comment]
Bug appears in the following configuration:

```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1510
```

```shell
$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
```

So it's most likely a new behavior in most recent toolchains that triggers this bug.

**Comment by Ecco** [comment]
Interestingly, both toolchains generate the exact same assembly for `uint32_t Ion::random()`.

```
00000000 <_ZN3Ion6randomEv>:
   0:	4812      	ldr	r0, [pc, #72]	; (4c <_ZN3Ion6randomEv+0x4c>)
   2:	2206      	movs	r2, #6
   4:	b538      	push	{r3, r4, r5, lr}
   6:	4611      	mov	r1, r2
   8:	6803      	ldr	r3, [r0, #0]
   a:	6804      	ldr	r4, [r0, #0]
   c:	2301      	movs	r3, #1
   e:	f7ff fffe 	bl	0 <_ZN3Ion6randomEv>
  12:	2202      	movs	r2, #2
  14:	2301      	movs	r3, #1
  16:	4611      	mov	r1, r2
  18:	480d      	ldr	r0, [pc, #52]	; (50 <_ZN3Ion6randomEv+0x50>)
  1a:	f7ff fffe 	bl	0 <_ZN3Ion6randomEv>
  1e:	4b0d      	ldr	r3, [pc, #52]	; (54 <_ZN3Ion6randomEv+0x54>)
  20:	09a4      	lsrs	r4, r4, #6
  22:	681a      	ldr	r2, [r3, #0]
  24:	681a      	ldr	r2, [r3, #0]
  26:	07d2      	lsls	r2, r2, #31
  28:	d5fb      	bpl.n	22 <_ZN3Ion6randomEv+0x22>
  2a:	4b0b      	ldr	r3, [pc, #44]	; (58 <_ZN3Ion6randomEv+0x58>)
  2c:	4808      	ldr	r0, [pc, #32]	; (50 <_ZN3Ion6randomEv+0x50>)
  2e:	681d      	ldr	r5, [r3, #0]
  30:	2202      	movs	r2, #2
  32:	4611      	mov	r1, r2
  34:	2300      	movs	r3, #0
  36:	f7ff fffe 	bl	0 <_ZN3Ion6randomEv>
  3a:	2206      	movs	r2, #6
  3c:	f004 0301 	and.w	r3, r4, #1
  40:	4611      	mov	r1, r2
  42:	4802      	ldr	r0, [pc, #8]	; (4c <_ZN3Ion6randomEv+0x4c>)
  44:	f7ff fffe 	bl	0 <_ZN3Ion6randomEv>
  48:	4628      	mov	r0, r5
  4a:	bd38      	pop	{r3, r4, r5, pc}
  4c:	40023834 	andmi	r3, r2, r4, lsr r8
  50:	50060800 	andpl	r0, r6, r0, lsl #16
  54:	50060804 	andpl	r0, r6, r4, lsl #16
  58:	50060808 	andpl	r0, r6, r8, lsl #16
```

**Comment by parisseb** [comment]
In theory, a group of students could indeed have the same sequence of random numbers, but in practice, unless they do an explicit seed or restart(), that will not happen, especially inside a CAS calculator, where random() is called implicitly, for example iif you simplify a fraction with 2 variables or more. And it's nice to have predictable pseudo-random numbers if you want to reproduce a bug in an algorithm where random() is called, this is also true for users programs. I'm not convinced by the need to have a hardware RNG on a calculator. For applications that really require impredictible randomness, you can monitor user interaction or input some timers as a seed.

**Comment by Ecco** [comment]
The culprit seems to be `s_roundPackToF64.c` from softfloat. Depending on which toolchain you build it with, `random()` always returns zero.

**Comment by jacobly0** [comment]
My gcc 6.3.1 download also has random() always returning zero.

**Comment by jbgodn** [comment]
And the random() function of the python random module works fine... A workaround for students and teachers

**Comment by jbgodn** [comment]
Many thanks @EmilieNumworks and @Ecco. It works perfect now !
The famous float versus double in c ;-)
