### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by toml12953** [numworks/epsilon#354]
Whenever I try to compile the source code, I get the following error:

`I18N    apps/i18n.cpp
Traceback (most recent call last):
  File "apps/i18n.py", line 7, in <module>
    from sets import Set
ModuleNotFoundError: No module named 'sets'
make: *** [apps/Makefile:68: apps/i18n.cpp] Error 1
`
Is there a workaround?

**Comment by Ecco** [comment]
Duplicates #197
