### ISSUE TITLE
Assertion Failed When Trying to use Python

### ISSUE THREAD

**Issue by toml12953** [numworks/epsilon#357]
Whenever I try to do anything at all with Python, I get the following message:

`Assertion failed!
Program:
D:\cygwin64\home\tlake\numworks\epsilon\epsilon.exe
File:python/src/py/gc.c, Line 543
Expression: VERIFY_PTR(ptr)`

I'm using Windows 10 with MSYS2 MinGW 64-bit.

**Comment by Ecco** [comment]
Duplicate #242
