### ISSUE TITLE
Licensing issues : the CC-BY-NC-ND license shouldn't be used

### ISSUE THREAD

**Issue by utybo** [numworks/epsilon#365]
As per the Creative Commons website, it is not recommended to use CC licenses for software

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

Moreover, the NoDerivates clause would technically prevent pull requests from being made (as you are explicitely not allowing others to modify epsilon), and I am not sure whether the distribution inside the Numworks calculator is considered to be commercial distribution, which is also explicitly forbidden in the license (NonCommercial clause).

I would suggest changing the license to another open source software license.

Note : I am not a lawyer.

**Comment by rhaamo** [comment]
duplicate of #38

**Comment by utybo** [comment]
Oops, didn't see that
