### ISSUE TITLE
Support for boolean algebra/logic calculations

### ISSUE THREAD

**Issue by adriweb** [numworks/epsilon#37]
**Feature idea**: support, right in the Calculation app, for boolean algebra/logic, or at the very least of boolean values.
Thus we could say `1+1=3` and it'd return `false`. And then, manipulate such boolean values with operators like `xor`, etc.

**Comment by mateoconlechuga** [comment]
I second this feature. It could also be interesting to introduce support for greater than, less than, and other variants as well.

**Comment by adriweb** [comment]
Looks like the bitwise sibling features of the logical operations I listed above are requested too: https://github.com/numworks/epsilon/issues/144

**Comment by UDXS** [comment]
I support having boolean calculations in the same way TI does it where 0 = false and anything non-zero = true. The following operators are needed:
- and
- or
- not
- xor
- <
- >
- =
- !=
- >=
- <=

**Comment by artaxxx** [comment]
Fixed in version 20
