### ISSUE TITLE
Result approximation is cut off and should be on new line

### ISSUE THREAD

**Issue by ejohn54** [numworks/epsilon#374]
When the result is long and contains the exact and approximate result, the approximate is cut off or scrolled off the screen.

The approximate answer should be on a new line below the exact.

For example in the Calculator enter 
30!

The result is 
265252859812191058636308480000000 ≈ 2.6525285981219E32

It is cut off in the middle and you have to scroll to see the approximate result.

It should show this as the result:
265252859812191058636308480000000 
         ≈ 2.6525285981219E32

Where the approximate result is on a second line and not cut off.

**Comment by agucova** [comment]
Can replicate, it has happened to me a lot of the time.

**Comment by artaxxx** [comment]
This is fixed in version 16
