### ISSUE TITLE
windows emulator : Python Shell -> Assertion failed

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#381]
I compiled last version of emulator on windows.

When using python and selecting "Python shell", Il have an error as on this capture :

![image](https://user-images.githubusercontent.com/11474581/38139724-feebb714-3430-11e8-9684-bf8d20505c43.png)

**Comment by UDXS** [comment]
I can confirm that this error happens on Windows, but not on Linux.

**Comment by medjahe** [comment]
there is a solution on Windows ?
thank you

y-a-t-il une solution pour que python fonctionne sur l'émulateur windows ?
merci

**Comment by ljoets** [comment]
Bonjour,
Il me semble que les versions suivantes n'avaient plus ce souci.

**Comment by Ecco** [comment]
I looks like this bug is no longer present. Please reopen if it is.
