### ISSUE TITLE
abscissas display in proba app 

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#397]
![2018-04-13 08_41_21-online graphing calculator numworks](https://user-images.githubusercontent.com/3930757/38717486-3fb6f228-3ef8-11e8-876b-ba4a36cb3e21.png)

it should be 12 instead of 2 on the lower right

**Comment by Ecco** [comment]
Good catch! Thanks @AlainBusser

**Comment by EmilieNumworks** [comment]
Thanks! The bug only appears on the emulator.

**Comment by matheod** [comment]
Fixed ?
