### ISSUE TITLE
Division Remainder issue

### ISSUE THREAD

**Issue by OLaurent-Maths** [numworks/epsilon#40]
Try to compute
rem(100000000000, 10)   -> returns undef

Maybe in division_remainder.cpp : 
replace  if (isnan(f1) || isnan(f2) || f1 != (int)f1 || f2 != (int)f2)
with   if (isnan(f1) || isnan(f2) || f1 != (int64_t)f1 || f2 != (int64_t)f2)  ?

Same goes for the quotient

**Comment by artaxxx** [comment]
Fixed in the new version 1.2.0
