### ISSUE TITLE
Font size in Python editor too large

### ISSUE THREAD

**Issue by tvillingett** [numworks/epsilon#400]
Is it possible to consider either a smaller font, or have a way to choose a smaller font in the settings, so you could get a better overview of the edited text?

**Comment by Ecco** [comment]
You can give it a try by either:
 * Changing the [default font size](https://github.com/numworks/epsilon/blob/c934eab947c594910cf4f7b2b5a4f3384d8896bb/escher/include/escher/text_area.h#L11) for TextArea
* Pass `KDText::FontSize::Small` when [creating the editor](https://github.com/numworks/epsilon/blob/c934eab947c594910cf4f7b2b5a4f3384d8896bb/apps/code/editor_controller.cpp#L13) in the Code app

**Comment by RedGl0w** [comment]
This issue can be closed since https://github.com/numworks/epsilon/commit/b3d45833d0a0ebd04def5dc126cabd935926a565

**Comment by Ecco** [comment]
Indeed. Thanks!
