### ISSUE TITLE
Request: dialog boxes and toolbar on numWorks

### ISSUE THREAD

**Issue by compsystems** [numworks/epsilon#406]
Sorry for my bad English

Suggestion for the developer team of the numWorks calculator.

One of the features that users appreciated in the ti68k calculators (ti92, ti89, ti-voyage200) were the dialog boxes and toolbar. Please numWorks team incorporate these functions in Python as a extra library. The purpose is to create easy data entry programs, instead of black boxes of functions f(a,b,c, ...) where the user does not know what parameters to enter, unless they read an instruction manual. A toolbar instruction is also important in order to organize topics and for the user to explore the content.

The next screenshot is an animation program for a cube, a program that I could not replicate in the ti-nspire because they (Texas Instruments) eliminated the dialog boxes and the toolbar of ti-basic.  :'( 

![screenshot of ti](http://eonicasys.com.co/public/math/CAS/hp_prime/toolBar/images/toolBar_hp_prime_image00.png)

Other math programs such as Xcas and hp-prime have a limited set of dialog box instructions, but no instructions to create a menu bar with submenus  

![screenshot of xcas](http://eonicasys.com.co/public/math/CAS/xCAS/files/dialogBoxes/images/dialogBoxes_Xcas_image01.png)

in the following tutorial of the hp-prime I show [the list of instructions](http://eonicasys.com.co/public/math/CAS/hp_prime/libraries/dialogBoxes/tutorial_dialogBoxes_hp_prime.pdf) of dialog boxes of the hp-prime

Thanks

**Comment by Ecco** [comment]
This is not something we plan to add to Python in the near future. But you can completely use our whole UI toolkit in your custom C++ app!
