### ISSUE TITLE
boxplot quartile stats different

### ISSUE THREAD

**Issue by tvillingett** [numworks/epsilon#412]
Hi when I do a box-plot with the following
13,19,23,31,45,46,47,51,53
(size = 1 on all)

Then on the HP Prime https://www.youtube.com/watch?v=XaS94tjE2WA
and on http://www.alcula.com/calculators/statistics/box-plot/
It shows 21 and 49 as first quart and third quart, but numworks shows 23 and 47
Is it not defined in the same way or is there a rounding error?

**Comment by artaxxx** [comment]
The definition used is not the same: here, the quartile is a value from the data list. There is a discussion on this here: https://github.com/numworks/epsilon/issues/158.
