### ISSUE TITLE
[Python] enumerate built-in function is not defined

### ISSUE THREAD

**Issue by bisam69** [numworks/epsilon#415]
The 'enumerate' function which is part of Python since version 2.3 and also part of Micropython 1.9.3 as shown [here](http://docs.micropython.org/en/latest/wipy/library/builtins.html#enumerate) seems to have been forgotten on calc.

**Comment by Ecco** [comment]
That's a good catch. Thanks @bisam69 !

**Comment by adriweb** [comment]
@Ecco after #521 can this be done?

**Comment by Ecco** [comment]
It's all good 😄
