### ISSUE TITLE
[Regression] Add more equation forms

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#418]
So, while testing the regression app, I noticed that it only supports linear. I assumed it supported other forms automatically as it had an equation field in the table. Does it not? or have I done something wrong? If it doesn't, I believe that it should. As a high schooler, regression is a fairly important feature for a calculator. I'd at least like to be able to set the form I'd like but automatic would be very nice.

**Comment by lastfuture** [comment]
I've noticed that more regression types have been added, as well as attempts to detect automatically, so I assume this can be closed, right?

**Comment by Ecco** [comment]
Indeed, good catch @lastfuture !
