### ISSUE TITLE
Add inequality graphing

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#419]
Like my previous issue (#418), this came about while I was experimenting with the simulator and evaluating if this calculator would be good for me. One feature that I think would make it even more high school-friendly would be the addition of inequality graphing. Being able to draw either the full line (>= or <=) or the dotted line (> or <) as well as shade the inequality in the right section would be good. This can be expanded into union and intersection features which would let one see the solutions for the inputted inequalities and see where the lines intersect. Also allowing one to plug in coordinates and have it checked to see if it is a solution would be good too.

**Comment by artaxxx** [comment]
It's now in version 17
