### ISSUE TITLE
Stop parsing numbers with multiple decimal dots?

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#423]
At the moment, we decided to be as forgiving as possible and parse `1.2.3` as `1.2 implicit-multiplication .3`, which yields `1.2 x 0.3 = 0.36`.

Should we keep it that way, or is that be misleading?

**Comment by boricj** [comment]
It's misleading and just feels wrong. Also, while Python accepts `.1` as a number, it does not accept `1.2.3` so the behavior of the calculator is inconsistent between the Calculation app and the Python app.

**Comment by adriweb** [comment]
Voting for misleading/to-change as well

**Comment by adriweb** [comment]
Yeah - my answer was in general :)
(Based on experience with the rest, mostly - for instance on the TI-83PCE, `1.2.3` will be a syntax error on the second dot)

**Comment by UDXS** [comment]
I think it is misleading and should instead error out. If one wants to multiply two decimals like that, they should do `1.2(.3)`. That's the way it is taught in most textbooks as well.

**Comment by artaxxx** [comment]
Numbers with multiple decimal dots are no longer parsed in 1.9.0
