### ISSUE TITLE
Give exact results in function tables

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#434]
Some users have asked for exact results in the table.

**Comment by Ecco** [comment]
One of the problem with this approach is that it would yield a very inconsistent table layout. I wonder if it wouldn't fix the issue to allow users to evaluate functions in the Calculation app.

**Comment by matheod** [comment]
Maybe allowing to press Ok key while hovering a result cell to see the exact value.

**Comment by Ecco** [comment]
That's actually an interesting idea. Thanks!

**Comment by HelloEdit** [comment]
it would be really convenient to have this feature for all tables, I'm thinking in particular of the suites.

**Comment by artaxxx** [comment]
Fixed in version 20
