### ISSUE TITLE
Thick curves

### ISSUE THREAD

**Issue by AlainBusser** [numworks/epsilon#436]
Hi, 

in the functions and probability apps, the curves are a little too thick so that it is difficult to see the space between the curve and the asymptote. For example, if the probability that a gaussian variable be between two values approaches one, one has difficulties looking at the small non colored parts below the bell shaped curve. So two questions:

1. Would a lot of people agree with me to just draw finer curves?
2. Would it be possible to choose the thickness of the curves in the settings?

**Comment by RedGl0w** [comment]
This is a bit related to https://github.com/numworks/epsilon/issues/1247

**Comment by artaxxx** [comment]
We don't plan to change the thickness of the curves in the future or support different thicknesses. This is something we tried at the beginning of epsilon and we weren't satisfied by the visual aspect. So I'll close this issue
