### ISSUE TITLE
graph a recursive sequence

### ISSUE THREAD

**Issue by erwanh1** [numworks/epsilon#437]
Sometimes teachers ask to graph a sequence (u_{n+1}=f(u_n)) thanks to the line whose equation is y=x and the graph of the function f.
It could be useful for students to have this kind of graph with the calculator.

**Comment by AlainBusser** [comment]
Is it what is called «[cobweb diagram](https://en.wikipedia.org/wiki/Cobweb_plot)» ?

**Comment by XanderLeaDaren** [comment]
Here’s what is actually feasible on TI calculators, and some documentation here:
http://tibasicdev.wikidot.com/web

![ekrano-kopio 2019-06-06 à 09 50 22](https://user-images.githubusercontent.com/28948599/59015981-89a3ab00-8840-11e9-8657-5807a87b5695.jpg)

The Casio calc do it, too.

**Comment by artaxxx** [comment]
Fixed in version 20
