### ISSUE TITLE
Calculator is a tiny bit slower after flashing the firmware

### ISSUE THREAD

**Issue by zardam** [numworks/epsilon#439]
After flashing the calculator with dfu-util and the new DFU implementation (the one used for the Python script) and pressing "back", the calculator runs slower than expected.

Hard resetting the calculator with the button on the back restores proper performance.

**Comment by Ecco** [comment]
Interesting! Would you mind sharing a benchmark? I just ran a quick test and didn't seem to reproduce the issue. Here's what I tried:

* Plug a device, press RESET
* Flash latest version `92b9fc5` using `make epsilon_flash`
* Press `Back` to leave the "Calculator is connected" screen
* Compute `100!` which takes roughly 1 sec
* Unplug the USB cable and plug it back on
* Re-run `make epsilon_flash`
* Press `Back` to leave the "Calculator is connected" step
* Compute `100!` again. This seemed to take the exact same time as before.

**Comment by zardam** [comment]
I'm running `make epsilon_flash` when the calculator is on the "Calculator is connected" screen (much faster to flash than the ST DFU).

For the benchmark, I'm using `mandelbrot(10)` using the stock Python script.

**Comment by Ecco** [comment]
That's indeed how it's done in ST's HAL library. Thanks for pointing this out! See fix in above commit.
