### ISSUE TITLE
Add a Python REPL

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#44]
It would be pretty useful to have a Python shell where you can input a Python snippet and have it executed straight away.

**Comment by titimoby** [comment]
The repl code files (.c and .h) are still here, so what's the main difficulty to have working repl ?
USB/Serial management?
Just trying to figure out the job to be done.

**Comment by Ecco** [comment]
Oh, we weren't thinking about a tethered REPL (which could be useful as well, just apparently a less requested feature).

What I was referring to was an on-device REPL (using the screen as output and the keyboard as input).

**Comment by titimoby** [comment]
a REPL is definitively a good idea, whatever the form.
I'll figure out a formulation around a USB enhancement request (either for a REPL, to transmit python script or just to have USB keyboard ;) )

**Comment by adriweb** [comment]
Apparently the OTG pin of the USB isn't soldered, so it's going to be hard working with that (calc can't be the host to a keyboard, from what I've heard)

**Comment by titimoby** [comment]
i didn't found precise info on what to do to activate OTG on this chip.
I just found mention that the ID pin (4th) need to be grounded.
But that sound weird.

**Comment by artaxxx** [comment]
Fixed in the last version 1.2.0
