### ISSUE TITLE
Change the toolbox icon on keyboard

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#45]
[This icon](https://puu.sh/xnXXx.jpg) is supposed to be a toolbox. However it also looks like a printer icon, which is what I and jacobly0 thought it was (and probably many others).

If you want to keep the toolbox, angling the edges like [this](http://puu.sh/xnY1T.jpg) should be enough to not mistake the handle for a sheed of paper.

However, since you've mentioned you base your design on smartphones, why not use [the menu icon from android](https://i.stack.imgur.com/Fw96Z.png)? It would be more recognizable.

**Comment by Ecco** [comment]
Good suggestion, wrong repository 😄 See https://github.com/numworks/dieter

**Comment by Zezombye** [comment]
Opened it here, thanks :)
