### ISSUE TITLE
Open up the Wiki

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#450]
Please open up the wiki for this project. It would be a great way to host and crowdsource documentation.

**Comment by Ecco** [comment]
That would be yet another thing to maintain. We already have a user manual and a forum, so we don't think this is necessary.

**Comment by adriweb** [comment]
> We already have an extensive user manual, a website with a lots of doc on the inner workings of the device

I agree with what you said, but a repo for those would definitely be nice, I'm sure some people would help adding details and whatnot :)

**Comment by UDXS** [comment]
This is more for developers but this thing would be 90% community maintained. Also, I can't reopen this.
