### ISSUE TITLE
simple calculation results in undef after several seconds with latest firmware

### ISSUE THREAD

**Issue by istvano** [numworks/epsilon#455]
Following basic calculation fails to produce result

STEP BY STEP
- 0.08/12
- ans +1
- ans ^60
this results in a UNDEF after a good few seconds.

Background information:

I was about to do a compounded interest calculation
A(t)=P(1+r/n)^nt

v: 1.4.1
(1+0.08/12)^60
This can be executed and the result is -> 1.489846

**Comment by bisam69** [comment]
More precisely, I tested that :
1.0066666666667^23 gives correct result
1.0066666666666^24 gives correct result
1.0066666666667^24 leads to undef

1.0000000000007^25 is correct
1.0000000000007^26 returns undef

I hope it will help finding the bug (probably an error while handling last digit rounding).

**Comment by Ecco** [comment]
The bug has already been fixed actually :) See #458

**Comment by istvano** [comment]
great. so I am closing this.
