### ISSUE TITLE
Add a random() function

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#47]
The feature is very useful in high school to give an interactive feeling of randomness to students.

On the technical side, the MCU features an actual RNG, we may as well use it.

**Comment by mateoconlechuga** [comment]
Do we want functions such as `randInt()`, `randNorm()`, randBin()`, along with a way to seed random numbers using a `rand` style variable? It would help match other calculator variants.

**Comment by Ecco** [comment]
> a way to seed random numbers using a rand style variable

This could actually be a great opportunity to teach students the difference between pseudo-randomness and actual randomness. These two concepts have long been improperly mixed up :-) We could do both and give them appropriate names (e.g. random() and pseudoRandom() would seem like a great start).

**Comment by Grahack** [comment]
Hi,
Now that the Python app has the glorious `>>>` wouldn't it be easier and perhaps more useful to have the `random` module. Or did you want to have `random()` in the `calculation` app?

**Comment by maxBzh** [comment]
Hi,
I also want this for my students, when introducing simple statistics.
So I have compiled epsilon with support of Python library urandom (the random library of Micro Python). Works like a charm. I have the following random functions : 
- seed(int)
- random() : float between 0 and 1
- randInt(int start,int stop) : integer between start and stop
- randrange(int stop, int start, int step) : integer between start and stop, search with step (start and stop not mandatory)
- choice([a,b,c,...]) : choose item randomly in array [a,b,c,...]

Do I make a pull request for this ?

**Comment by Grahack** [comment]
@maxBzh Release early, release often! I'm interested, and I may not be the only one.

**Comment by maxBzh** [comment]
@Grahack Here you go https://github.com/numworks/epsilon/pull/295

**Comment by Ecco** [comment]
Thank you @maxBzh ! Definitely something we wanted to do so your PR is very much appreciated! Thank you very much!

**Comment by artaxxx** [comment]
Fixed by #295 and #316
