### ISSUE TITLE
Issue with matrix transposition

### ISSUE THREAD

**Issue by OLaurent-Maths** [numworks/epsilon#48]
Create a 1x2 matrix : [[1,2]]
Transpose this matrix -> result is a 1x2 matrix instead of a 2x1 matrix
![image](https://user-images.githubusercontent.com/22173255/29930540-e7b3f84e-8e6e-11e7-82b2-ebb51cc2bf5e.png)

**Comment by jacobly0** [comment]
Given any non-square matrix, the values are swapped but not the dimensions.

**Comment by jacobly0** [comment]
Similarly, multiplying matrices transposes the dimensions of the result.

**Comment by jacobly0** [comment]
I imagine a lot of this can be traced to ExpressionMatrix and ComplexMatrix taking dimensions in a different order.
