### ISSUE TITLE
Misc build issues on Ubuntu

### ISSUE THREAD

**Issue by OLaurent-Maths** [numworks/epsilon#5]
Hello,

Just sharing build issues that I encountered on Ubuntu 16.04: 
- Had to add missing dependencies (not specified in https://www.numworks.com/resources/engineering/software/sdk/other/ ) : clang (not by default in build-essentials) and gdb-arm-none-eabi
- Had to add the namespace std in a bunch of cpp files : isnan and isinf were generating errors.

Besides this, everything went fine and the emulator is working fine.

**Comment by rhaamo** [comment]
Which clang version ? (output of ```clang --version```) With a ```4.0.0-1ubuntu1``` on Ubuntu 17.04 it didn't caused any issues for building about std namespaces.

**Comment by OLaurent-Maths** [comment]
For clang I installed the default one (3.8): 
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

I'll try to update to version 4

**Comment by OLaurent-Maths** [comment]
I switched to clang 4 and gcc 6 and it works like a charm !
