### ISSUE TITLE
Fuzzing (Poincare especially?)

### ISSUE THREAD

**Issue by adriweb** [numworks/epsilon#50]
I (and others) believe it would be interesting to launch some fuzzer instances (probably [afl-fuzz](http://lcamtuf.coredump.cx/afl/)) on the different modules, but probably Poincare especially.
The goal would be to reveal bugs/crashes in an automated way for things like unexpected inputs yielding unhandled cases.

I have _some_ experience in that, so I'll try to see what I can do but if anyone wants to join in and help/give ideas, please do :)

In any case, this issue could be useful to keep track of the status of that, and possibly to report bad cases found by the instances, if they aren't worth having their own github issue or PR.

**Comment by debrouxl** [comment]
afl-fuzz and honggfuzz would do the job; libfuzzer, which has dictionary support as well (see 
https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md ) would be more efficient because it doesn't fork(), beating e.g. afl deferred mode.

**Comment by Ecco** [comment]
This is something we've been doing already. Look at the "blackbox" target (`make PLATFORM=blackbox`). The whole OS has been fuzzed already.

That being said, yes, we could even target poincare more specifically, but I don't know if it would be more efficient.

**Comment by adriweb** [comment]
Ah, I only quickly looked at that part, didn't really notice it was for fuzzing purposes - nice :)

**Comment by Ecco** [comment]
I'm going to close this one for now, because it's something we've somewhat already done.
