### ISSUE TITLE
SD-Card

### ISSUE THREAD

**Issue by alsacchi** [numworks/epsilon#509]
If I compile the Firmware with SD_card support to 1 and if I solder a sdcard reader and put a sdcard in. 
Will work?

**Comment by boricj** [comment]
It won't do much. There's a couple of functions in the HAL, but the firmware doesn't know how to read sectors, parse filesystems, show data to the user or pretty much do _anything_ with it.

**Comment by Ecco** [comment]
Indeed, @boricj 's answer is spot on. We did place a uSD-card footprint on the PCB in case hackers want to put one, but since it doesn't ship on standard device we haven't written the relevant code just yet.

**Comment by chocol4te** [comment]
Do any other components need to be populated? I can see in the schematic it looks like R15, Q4 and SB1 are needed?

**Comment by Ecco** [comment]
Yes, those are required to power the SD-Card on and off.

**Comment by chocol4te** [comment]
Ah, thanks! :D

**Comment by Zml99** [comment]
When do you plan to program that SD card reader? I'm a programmer but I have no idea how to do this and I'm interested in doing this. @Ecco

**Comment by boricj** [comment]
I very much doubt the NumWorks team itself will implement support for SD cards anytime soon as they have no business case for doing so. However, you can to try to implement it and submit a pull request if you want to, but you should first familiarize yourself with the firmware, hardware, toolchain and development process (https://www.numworks.com/resources/engineering/) with smaller-scale modifications before attempting this.

**Comment by UnknownAMD** [comment]
this issue needs to be reopened imo
