### ISSUE TITLE
Add Italian language

### ISSUE THREAD

**Issue by Andreabont** [numworks/epsilon#520]
Hi, the Italian language is missing in the firmware. 
I can add it, if there aren't problems, but I need some advice :-)

Thank you

Bye

**Comment by boricj** [comment]
There are several new translations inside pull requests right now, you can check out #438 for an example.

You'll need to be able to compile at least the simulator to check your work, so you'll need to read at the very least https://www.numworks.com/resources/engineering/software/sdk/ to set up your development environment.

To build epsilon with a custom set of languages, set the `EPSILON_I18N` environment variable before building, like so: `EPSILON_I18N='fr en' PLATFORM=simulator make -j 8`. Building will fail if any translation are missing.

**Comment by Andreabont** [comment]
Hi, i fork this repository for make some test:
https://github.com/Andreabont/epsilon/commit/1ce92a1e2a2bc8ddf78f25b191982e02e1c02d09

**Comment by LeaNumworks** [comment]
We just released the Italian translation with version-14 :)
