### ISSUE TITLE
Boxplot top and bottom border missing

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#527]
In boxplot (boite à moustache / diagramme en boite), the figure is strange because it lack top and bottom border.

![image](https://user-images.githubusercontent.com/339611/40738237-4d496b1c-6443-11e8-8cd5-464e9b411bf5.png)

It shoudl have a top and bottom border like below : 

![image](https://user-images.githubusercontent.com/339611/40738253-59f249b0-6443-11e8-8af1-1d5fdd2c09f5.png)

The strange things is that this border sometime appear, for exemple on one of numworks video, there is the bottom border : 

![image](https://user-images.githubusercontent.com/339611/40738285-6e2be2f6-6443-11e8-8f64-c3b08edb4cbf.png)

**Comment by artaxxx** [comment]
As the designed of the boxplot changed with the last version (1.6.0), I close this issue

**Comment by matheod** [comment]
Isn't it better like below ?

![image](https://user-images.githubusercontent.com/339611/42458316-f5dee8e0-8399-11e8-8c64-ba1a29aacda3.png)

I will create the PR.
