### ISSUE TITLE
Consider adding functions to compute normal/binomial probabilities

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#531]
This way we could compute said probabilities everywhere and not only in the Probabilities app.

**Comment by OlivierV78** [comment]
It would be usefull to get a table of probability ....

**Comment by matheod** [comment]
I think the table of probability should be in the probability section. Having to manually do it from function would be less handy (moins pratique, pas sûr de la traduction :D).

**Comment by OlivierV78** [comment]
You are right.
Ok for a probability table in the table in the probability section !

But why not offer somme fonctions (like the TI ...) for other (old ...) teacher who would like to do so or for studend who would like to calculate in text mode and not in graphical mode because text is sometime faster (I have some ...) ?
This shouhd not be very difficult to do ...

Thank you.

**Comment by jenskuespert** [comment]
"not difficult" as in "we'll throw it in the next release"? :-)

If not: Is poincare the right point to attempt an implementation? What operation would be a fitting template for this new function?

**Comment by OlivierV78** [comment]
I would say : if you have a fonction to make the table of probability in graphical mode in the next release, then it should not be very difficult to give an access to this function in text mode too

**Comment by OlivierV78** [comment]
The 4 fonctions I mean are the "normalFdP","normalFRep", "binomFRep" and "binomFdp" from the TI calculator. I don't know how they are implemented.

**Comment by boricj** [comment]
@jenskuespert Adding a function is not hard, but there are a couple of extra steps:
* Adding the function's implementation to Poincare,
* Adding the function to the lexer/parser,
* Adding test cases to the test suite,
* (Technically optional) Adding the function to the toolbox with all translations.

I don't have a simple, straightforward example on hand, but there's #163 and #316 you can take a look at.

@OlivierV78 The probability law implementations are inside the probability app, they are not part of Poincare and they are actually subtypes of `CurveViewRange`. Those are not usable inside an expression so adding them to the Calculation app is not trivial (but it shouldn't be too difficult either).

**Comment by OlivierV78** [comment]
Thank you for your answer.

**Comment by LeaNumworks** [comment]
Hi, I am closing since this was done with commits 3a03132c6 to c47bcb5bd.
