### ISSUE TITLE
3rd Party App Loop?

### ISSUE THREAD

**Issue by chocol4te** [numworks/epsilon#532]
Hello!

I'd like my app to work around a `while (true) {}`, but I can't quite understand how I would structure it. I am writing to the display ""manually"" using Ion instead of Escher in said loop, but I would like a menu view when the app is first opened and the top menu item being to start the program loop. How do I do this? I've tried implementing what's done in other apps but without much luck.

Will the back or home key interrupt the loop or do I need to write that myself? If they do interrupt, is there any way to modify that behaviour (EG, use back key as input in my app and write my own interrupt routine)?

Thanks!

**Comment by Ecco** [comment]
Hi! This is not really an issue, I suggest you use our [Reddit](https://reddit.com/r/numworks/) for this 😄
