### ISSUE TITLE
(x+2)² return 4+2·x+x² ≈ undef

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#535]
→ write (x+2)^2
→ the calculator show ``4+2·x+x² ≈ undef``

- [x] It shouldn't show the ``≈ undef``

- [x] It would be better if it was in this order :  ``x²+2·x+4``

- [ ] And maybe also remove the ``·`` ?

**Comment by matheod** [comment]
Seems fixed with the next version ?

**Comment by artaxxx** [comment]
It is! But it would be much better to write: x²+2·x+4.
So let's keep this open :)

**Comment by LeaNumworks** [comment]
Closing since this was done: `(pi+2)²` returns  `pi²+4pi+4`
