### ISSUE TITLE
Zeroes in front of numbers count as significant

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#541]
For example, if the calculator is set to display 4 significant numbers, if you enter
`0.00123456789`
it will display
`0.001`
; whereas it should display
`0.001234`

Present as of 1.5.0 release

**Comment by EmilieNumworks** [comment]
Indeed, it has bother me for a while. This should be resolved by #445 but it still need some improvements.

**Comment by artaxxx** [comment]
It is now fixed in 1.8.1
