### ISSUE TITLE
[Functions] Reach the advanced options using the Toolbox key

### ISSUE THREAD

**Issue by kauderni35** [numworks/epsilon#544]
The "toolbox" key is very often used for advanced functions. But in the Functions and Sequences apps, one need to use the OK button to perform computations on a curve. Shouldn't the Toolbox key be used?

For reference, original French version below
> Bonjour
> le touche " tools" est utilisée régulièrement pour accéder aux outils :-)
> mais pour les fonctions et les suites, il faut utiliser la touche ok ??  
> je ne trouve pas ça très logique...
> Sébastien

**Comment by Ecco** [comment]
Hi @kauderni35, thanks for your suggestion! We're welcoming a community of contributors who don't necessarily speak french, so I translated your original suggestion to english.

**Comment by Ecco** [comment]
My first feeling reading this suggestion: maybe both OK and Toolbox could open the menu?

**Comment by matheod** [comment]
Why not. What was your motive for using Ok key instead of Toolbox if there was one ? I am curious about that.

**Comment by artaxxx** [comment]
Toolbox is supposed to provide edition shortcuts. The output is always a text that you can use in an expression. OK is used to navigate through the UI: you want some options in your statistical data, go on the title of the column and press OK, you'll reach the options menu. In the same way, if you want to get the option menu for a particular curve in your graph, press OK and you'll be able to move the cursor to a particular abscissa, calculate a minimum, etc.

**Comment by matheod** [comment]
Hum, yea I think we can officialy use the Ok button (so still show Ok on screen) but also unofficialy allow the use of the toolbox button but without mentionning it.

**Comment by artaxxx** [comment]
It's done in version 16
