### ISSUE TITLE
letter as summation variable

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#546]
Currently, the n variable is used : 
![image](https://user-images.githubusercontent.com/339611/41092960-6a42d0b6-6a4a-11e8-9998-5889453e411c.png)

I think we should use an other letter (k maybe ?) as n is most of the time used as maximum of summation.

It can also confuse student dealing with sequence.

**Comment by Ecco** [comment]
The reason we picked `n` is because it allows for quick typing using the `x,n,t` key.

**Comment by matheod** [comment]
Oh, didn't think about that. That make sense. I think we should keep it like that then.

By curiosity, where the t variable is used ? Maybe it should have been x,n,k (but it's too late now) ?

**Comment by Ecco** [comment]
Great, thanks! The `t` variable isn't used anywhere for now. But it will when we'll do parametric plots 😄
