### ISSUE TITLE
Is this possible (or planned) to download a compiled version of the emulator?

### ISSUE THREAD

**Issue by paternal** [numworks/epsilon#547]
I would like to have it installed on the computers of my highschool (where the Internet is sometimes broken), but I think my sysadmin would not like to have to compile it himself.

Thanks for your work!

**Comment by Ecco** [comment]
Yes, it is planned. Note that we currently are able to build two versions of the simulator:
* One as a native executable (.exe for windows, for example)
* One as a web page (.html / .js file).

We're using the native version internally (useful to attach a debugger for example), but at the moment we don't plan to distribute it. Indeed, the HTML version is better on pretty much every single aspect:
* It doesn't require code signing to run
* It doesn't require admin rights to run
* It doesn't need to be installed : just open the .html page from wherever you want (including an USB key).
* Same build works everywhere (Windows,  Linux, macOS, Android, iOS, etc…)

The "downloadable" version will be very close to what you can find at https://www.numworks.com/simulator , except you'll be able to download it, save it to an USB key and use it wherever you want without needing network access.

**Comment by Ecco** [comment]
I'm going to close this issue as it's actually already available in Epsilon's code. We just need to make it more easily accessible for everyone though.

Meanwhile, here's what you'll need to do to build your own version:
* Install emscripten
* Load emscripten in your terminal (`source ~/emsdk_portable/emsdk_env.sh`)
* `make PLATFORM=emscripten simulator.zip`
