### ISSUE TITLE
Make the calculator work as a USB key

### ISSUE THREAD

**Issue by paternal** [numworks/epsilon#548]
It would be nice if, to transfer python files between the calculator and the computer, to:
- plug the calculator (which would be recognized as a USB key);
- move files using the OS file manager.

**Comment by Ecco** [comment]
We decided against this feature for several reasons:
* You need to "unmount" your calculator after plugging in, which is annoying
* You need to use a FAT filesystem which may raise some patenting issues
* You need to take care of whatever temp file the OS will dump on the device (.Thumbsdb, .ds_store, etc…)

That being said, if you want to use your OS file manager, you could quite easily write a FUSE driver for the NumWorks calculator. Given Epsilon's code is available and that we're doing file transfer using a standard protocol (DFU), it should be quite straightforward to write :)

**Comment by boricj** [comment]
@Ecco I don't think closing this issue is warranted just yet. While the USB MSD class is a rather poor fit for this usecase, the MTP class could be a suitable candidate.

**Comment by Ecco** [comment]
@boricj Well, depending on the OS, MTP wouldn't let you browse your calculator from the built-in file manager. Also, it's not how most (all?) USB keys work, and that was the title of the original issue :)

That being said, we have no plan to support MTP either 😄 The protocol might indeed be a better fit than MSD, but so far (ab)using DFU seems to be a rather efficient solution and we can't see any compelling reason to move to something else.
