### ISSUE TITLE
ft2build.h error

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#549]
I used to be able to compile to test on my PC, but using the lastest version I can't anymore due to this bug:
![screenshot](https://i.imgur.com/wHunOcP.png)

**Comment by Moddingear** [comment]
Actually I have this error on a fresh install of windows 10 with MSYS2 completely up to date and all of the dependencies installed following this tutorial : [https://en.wikibooks.org/wiki/Unofficial_Guide_To_Expanding_Your_Numworks/Getting_your_development_environment_set_up](url)
`pkg-config` is present but not under bin/sh and not in the right version when following your tutorial and the one above.
What needs to be added is `pacman -S mingw-w64-x86_64-pkg-config`
Now consider this closed

**Comment by adriweb** [comment]
You should edit that wiki page to mention this :)

**Comment by Moddingear** [comment]
> You should edit that wiki page to mention this :)
Yes
And also `dfu-util` seems to be missing.

**Comment by Moddingear** [comment]
And now i really need help because I can't figure how to install it.

**Comment by adriweb** [comment]
If you just want to "test on your PC", you don't need dfu-util. that's for flashing a binary on real hardware.

Why don't you first try `make PLATFORM=simulator` first. (you may need to do `make PLATFORM=simulator clean` beforehand, now...)
Note that you can add ` -j4` for instance, with whatever number of cores you have/want to use (and in which, case, sometimes you may need to launch that command several times)

**Comment by Moddingear** [comment]
I've tried the simulator and it works, but I want to flash my calculator so that I can test it more extensively while in class. And the new features are sweet.

**Comment by adriweb** [comment]
You can use web-dfu if you cannot get dfu-util to work: https://devanlai.github.io/webdfu/dfu-util/

**Comment by adriweb** [comment]
You can use web-dfu if you cannot get dfu-util to work: https://devanlai.github.io/webdfu/dfu-util/

Note that on Windows, there's probably a dfu driver to install. Previously, the one hosted by Numworks worked fine, IIRC, but the link doesn't work anymore (maybe @Ecco 
 still has it?)
Anyway, look at the links here: https://github.com/devanlai/webdfu#host-side-implementation

**Comment by Moddingear** [comment]
I did not manage to get it to work using web-dfu, but using the link given in the Numworks website, I was able to get it to work with the regular dfu-util : 

- Download [the lastest dfu-util binary](http://dfu-util.sourceforge.net/releases/) in zip format

- Copy all of the contents of the zipped folder you downloaded to `\mingw64\bin`

**Comment by Ecco** [comment]
> Previously, the one hosted by Numworks worked fine, IIRC, but the link doesn't work anymore (maybe @Ecco still has it?)

Just go to https://workshop.numworks.com and perform a regular update. It will prompt you to install the driver if needed. As a side effect, this will allow you to use `dfu-util` afterwards 😄

**Comment by matheod** [comment]
Got the same issue, `pacman -S mingw-w64-x86_64-pkg-config` need to be added.
