### ISSUE TITLE
Compilation error on windows

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#554]
Hello,

I tried to compile simulator platform on windows.
With an up-to-date Git folder, it doesn't works :-(

```
admin@admin-PC MINGW64 ~/epsilon
$ make PLATFORM=simulator
I18N    apps/i18n.cpp
HOSTCC  escher/image/inliner
HOSTCC  kandinsky/fonts/rasterizer
/bin/sh: pkg-config : commande introuvable
/bin/sh: pkg-config : commande introuvable
kandinsky/fonts/rasterizer.c:15:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [kandinsky/Makefile:57: kandinsky/fonts/rasterizer] Error 1
```

**Comment by adriweb** [comment]
Duplicate, see here: https://github.com/numworks/epsilon/issues/549 for the same issue and how it was solved.
Basically, you have to install `mingw-w64-x86_64-pkg-config` (pacman -S ...)

**Comment by ljoets** [comment]
Thanks, that solved my problem. Sorry for duplicate :-\
