### ISSUE TITLE
Exact output for complex numbers and converting to re^i(theta)

### ISSUE THREAD

**Issue by Moddingear** [numworks/epsilon#555]
Currently, the calculator doesn't display the exact output of theta as a fraction on pi when displaying as re^i(theta).
Also, i'd like it if there was a way to have the fractions for any r as non-natural number, because right now, for example, inputting `2.5e^(i*pi/4)` gives `2.5e^0.785398i` which is useless, instead of the expected `(2.5sqrt(2)*(1+i))/2 = 2.5e^(i*pi/4)`
Also, a way to force the re^i(theta) or a+bi notation in the calculation app would be very appreciated.

**Comment by artaxxx** [comment]
Added in 10.0.0

**Comment by obi1666** [comment]
Is there a way to perform the rect<->polar coordinate change in 'Calculation' without changing settings?
I understand there are functions abs, arg, re, im, but this is quite frustrating to need to input two separate lines for each conversion when desiring the other coordinate system.
