### ISSUE TITLE
Incorrect syntaxic coloration in Python app

### ISSUE THREAD

**Issue by claire-savinas** [numworks/epsilon#559]
There are some problems with the syntaxic coloration in the Python app, check the end of the first lines :
![telechargement 9](https://user-images.githubusercontent.com/32409683/41333016-63ef3746-6ee0-11e8-9ade-0918db64ba5d.png)
![telechargement 8](https://user-images.githubusercontent.com/32409683/41333018-640b143e-6ee0-11e8-85d1-c9d8a4731396.png)
![telechargement 7](https://user-images.githubusercontent.com/32409683/41333019-6424d66c-6ee0-11e8-9991-8b9c72a8ecf1.png)

**Comment by Ecco** [comment]
Indeed, good catch. Thanks @claire-savinas !

**Comment by sagessylu** [comment]
On 11.2.0 version,
there are also problems with "\n" and "\t" when they are between quotes : 

![screenshot-2](https://user-images.githubusercontent.com/49091098/67139611-6c510580-f252-11e9-8563-dc9bf8f10234.png)

The second quote is grey when it's at the end of the line, else it is invisible.

**Comment by LeaNumworks** [comment]
This has been fixed by 0f52335
