### ISSUE TITLE
[Suggestion] / [WIP] Color Mode

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#565]
It would be nice to have an optional dark mode for darker classrooms and less eye strain.
![screen shot 2018-06-14 at 6 39 23 pm](https://user-images.githubusercontent.com/29680628/41443434-730cc130-7002-11e8-939e-350ee1014bea.png) ![screen shot 2018-06-14 at 6 39 37 pm](https://user-images.githubusercontent.com/29680628/41443435-74b39fea-7002-11e8-92a2-eb48a412d609.png)
I didn't have much time, but this is what I have so far. If anybody wants to add this before I get around to it, please feel free to do so.

**Comment by adriweb** [comment]
That could be pretty cool indeed.
Normally a well-designed drak mode [is not](https://developer.apple.com/videos/play/wwdc2018/210/) just color-inversion but I'm just wondering what that would look like, at least...

Should be trivial to implement if the LCD has such a mode, otherwise it's some good old `0xFF-value` on the RGB components :P

**Comment by 0b101** [comment]
I started work on an alternate dark palette and it will start to look better as I spend more time working on this. 
![screen shot 2018-06-15 at 7 50 47 am](https://user-images.githubusercontent.com/29680628/41468922-2331e59a-7071-11e8-951c-114107dbee1a.png)

**Comment by 0b101** [comment]
All of my changes are currently located at [https://github.com/0b101/epsilon/tree/darkMode](https://github.com/0b101/epsilon/tree/darkMode). Please feel free to contribute.

**Comment by 0b101** [comment]
![screen shot 2018-06-15 at 2 04 27 pm](https://user-images.githubusercontent.com/29680628/41485161-0fefc054-70a5-11e8-914b-aed86b543910.png)
Should I use a Yellow or Gray header?

**Comment by 0b101** [comment]
Here is an example of what I currently have
![darkmodeexample](https://user-images.githubusercontent.com/29680628/41539141-a2a6091a-72d2-11e8-9eae-ab938bfbee04.gif)

**Comment by 0b101** [comment]
The Calculation app is looking better already...
![darkmodeexample2](https://user-images.githubusercontent.com/29680628/41566675-231d4316-7322-11e8-8766-fcab9fa1a9a5.gif)

**Comment by 0b101** [comment]
![image](https://user-images.githubusercontent.com/29680628/41810498-46734602-76c5-11e8-83f1-3c21c8e9ba8c.png) vs ![image](https://user-images.githubusercontent.com/29680628/41810520-8b948a48-76c5-11e8-9b59-e6063f8377b8.png)
(XD mock up)

**Comment by LeSeulArtichaut** [comment]
@0b101 Is this "project" of doing a dark theme maintained ? I would really appreciate to take the opportunity to have this kind of appearance, and to give a helping hand (if I can 😄)  !

**Comment by 0b101** [comment]
@LeSeulArtichaut I could use some help with creating a way to live switch palette files. I had to take a short (3 month) break, but I recently resumed my work. I should be re-uploading my code to GitHub when I get a little farther along.

**Comment by LeSeulArtichaut** [comment]
@0b101 Is it possible to get your dark theme ? I can’t find any commit about it on the dark branch of your fork, is it normal ?

**Comment by Ecco** [comment]
Hi! I'm going to close this, as at the moment we have no plan to merge and maintain multiple different look'n'feel 😄
