### ISSUE TITLE
[minor] When editing subscript in uₙ the n doesn't look like the same

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#571]
![image](https://user-images.githubusercontent.com/339611/41512645-dca07ad8-728c-11e8-8773-b009ca37ec64.png)

Step : Add the uₙ with toolbox, if you try to edit the subscript by adding an other n, it look bigger.

**Comment by LeaNumworks** [comment]
Thank you for spotting this! We made all subscripts bigger in #615
