### ISSUE TITLE
[Sequences] Allow re-using a given term as a start value

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#572]
![b4b5dcbf4600496f308dd378a63548b1](https://user-images.githubusercontent.com/55989/41524301-4f25ae66-72dd-11e8-97d0-80e2248ff263.png)

* Create `U(n)`
* Create `V(n)` and try re-using `U(0)` somewhere

Originally found on [Reddit](https://www.reddit.com/r/numworks/comments/8rrzs9/bug_suites_imbriquées/).

**Comment by artaxxx** [comment]
Fixed in 15.0.0
