### ISSUE TITLE
Add transparency to icons

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#575]
In my attempt to add a dark mode in #565, I discovered that the transparency in the icons do not carry over to the calculator. I included an image of my dark mode progress with modified png icons to have transparency on the corners, but the transparency is displayed as white in the build.   
![image](https://user-images.githubusercontent.com/29680628/41567400-aa8574e2-7325-11e8-8959-93f91e2f954e.png)

**Comment by boricj** [comment]
`kandinsky` does not handle RGBA images (but does handle RGB images as well as grayscale for alpha blending) and the inliner will ignore the alpha channel when processing the PNG files.

While changing image format from RGB to RGBA is possible, this will negatively impact blitting performance and increase flash consumption unless optimizations are made.

**Comment by eried** [comment]
Maybe square icons make everything look sleeker and do not add issues with the transparency?

**Comment by adriweb** [comment]
> Maybe square icons make everything look sleeker and do not add issues with the transparency?

naww, in fact I'm hoping they will make the name label background a round rect instead of a plain one which is rather... "ugly" when seeing everything else :)

**Comment by boricj** [comment]
There are ways to mitigate enabling icon transparency on the home screen (1-bit alpha, palettized images, RLE compression, blitting optimizations...). I'm just saying that an overly naive implementation that unreasonably burns through CPU and flash is unlikely to be accepted by the NumWorks team.

**Comment by Ecco** [comment]
>  is unlikely to be accepted by the NumWorks team

As is this whole PR, actually, since we've had virtually zero feedback from end-users saying the UI needed a customizable dark mode. Of course we're very happy to let hackers customize their own device though 😄

As a general rule, we'll happily merge "extra" features as long as they have zero impact for "regular" end-users. In that case, I think we could merge a **compile**-time dark mode, but most likely not a **runtime** one.

**Comment by 0b101** [comment]
> we've had virtually zero feedback from end-users saying the UI needed a customizable dark mode 

I can't remember where, but I have seen a couple people complain about how the color scheme on the display makes it hard to focus.  I was thinking that a dark mode might make it a little easier to stare at the screen during late night studying and tests without as much eye strain.

> As a general rule, we'll happily merge "extra" features as long as they have zero impact for "regular" end-users. 

From what I've seen from other platforms (macOS for example) people are generally fans of a dark mode option and use it heavily.

> I think we could merge a compile-time dark mode, but most likely not a runtime one.

I am willing to remove the setting and make the addition compile-time, but the only space saved would be with the removal of the setting. 

> Maybe square icons make everything look sleeker and do not add issues with the transparency?

I don't think that would look as good as the rounded icons.

**Comment by Ecco** [comment]
I'm going to close this issue because we have no plan to maintain multiple themes at the moment.
