### ISSUE TITLE
LED connection documentation flaw

### ISSUE THREAD

**Issue by Mecrisp** [numworks/epsilon#576]
Dear Numworks team,

while trying to get PA11/PA12 working as GPIO lines instead of USB, I found irregularities regarding the LED connection:

In the top-left corner of the schematic, a note says LED_RED = PA6.
But at the drawn microcontroller, LED_RED is on PC7.

In epsilon-1.6.0/ion/src/device/device.h
```
 *  PA6 | LED red           | Alternate Function XX | TIM3_CH1
 *  PA7 | LED green         | Alternate Function XX | TIM3_CH2
```
In epsilon-1.6.0/ion/src/device/led.cpp:
```
  /* RED_LED(PC7), GREEN_LED(PB1), and BLUE_LED(PB0) are driven using a timer,
   * which is an alternate function. More precisely, we will use AF2, which maps
   * PB0 to TIM3_CH2, PB1 to TIM3_CH4, and PC7 to TIM3_CH2. */
```
Probably you rewired the beautiful calculator during design, but missed to change the comments.

Best wishes,
Matthias

**Comment by Ecco** [comment]
Hi @Mecrisp 

Indeed, good catch. We split the documentation from `device.h` into multiple files (`display.h`, `led.h`) and forgot to remove it from `device.h`. Thanks for pointing this out!
