### ISSUE TITLE
Suggestion: Light single language firmware

### ISSUE THREAD

**Issue by eried** [numworks/epsilon#577]
Since the calculator has a very limited memory for python programs, it would be nice if from https://workshop.numworks.com the users were able to choose a light version of the fw only containing one language, no?

**Comment by Ecco** [comment]
Note that all Python scripts currently live in the RAM, and that we artificially limited the size available for Python script out of caution. Changing the firmware size will have zero impact on the number of Python scripts you can store.

**Comment by Ecco** [comment]
That being said, the feature is here already: just pass a custom value of `EPSILON_I18N` when building. For example, `make EPSILON_I18N=en` 😄
