### ISSUE TITLE
[Calculation] Keep the current input when leaving the app

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#583]
1. Enter something in the input field, say `1+1`
2. Press the Home key
3. Enter the Calculation app again

The previous input, `1+1` has been discarded.

**Comment by matheod** [comment]
@Martin56700 Didn't understand what you said

**Comment by Martin56700** [comment]
1. Go up in the history (if exist)
2. Press Home key
3. Enter the Calculation app again
You lose the position in the history

**Comment by Ecco** [comment]
@Martin56700 Thanks for the clarification. That's not the same issue though, and it's not as annoying as this one.

**Comment by artaxxx** [comment]
Fixed in 15.0.0
