### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by Salamandar** [numworks/epsilon#587]
Autocompletion would be great in Calculs/Python. I guess MicroPython provides such feature.

Maybe by a double-click on the right arrow ?

**Comment by matheod** [comment]
Or an autocompletion menu in the toolbox ?

**Comment by 0b101** [comment]
It would be great for parentheses ( )

**Comment by Salamandar** [comment]
> Or an autocompletion menu in the toolbox ?

That may be too "hidden" but that's an idea. Or maybe a long-click on the toolbox button to show the autocompletion list ? :)

**Comment by UDXS** [comment]
Simply placing ')' when '(' is typed and then placing it between them would make programming faster. This should be done with '{', '[', and quotations.

**Comment by Salamandar** [comment]
> Simply placing ')' when '(' is typed and then placing it between them would make programming faster. This should be done with '{', '[', and quotations.

That's not what I meant by autocompletion but that's a great start yeah ;)

**Comment by XanderLeaDaren** [comment]
I support autocompletion, also for functions’ and variables’ names!

**Comment by artaxxx** [comment]
Fixed in 14.4.0
