### ISSUE TITLE
Circular list

### ISSUE THREAD

**Issue by Salamandar** [numworks/epsilon#588]
When inside a list (toolbox, scripts list, …), an expected behaviour is to go from the top to the bottom of the list by clicking the "up arrow" (and the other way around of course).

**Comment by 0b101** [comment]
#39

**Comment by Ecco** [comment]
Indeed, that's a duplicate of #39. Closing 😄

**Comment by Salamandar** [comment]
Woops, I didn't have the correct keywords when searching for duplicate.
