### ISSUE TITLE
Notes app

### ISSUE THREAD

**Issue by nickatamas** [numworks/epsilon#590]
Guys, would be awesome to have something like Notes app, to store formulas, and other reference information.

**Comment by boricj** [comment]
There's already the Python app for that, just stash your notes inside a heredoc in a Python script.

**Comment by UDXS** [comment]
While a notes app would be cool, it would raise some eyebrows with teachers, unfortunately.

**Comment by nickatamas** [comment]
I am a techer myself, so do not  see any problems. By enabling Exam mode
students could be restricted or completely unable to use the app.

**Comment by UDXS** [comment]
That is a good way to restrict it. I wonder what CollegeBoard would think of it though.

**Comment by nickatamas** [comment]
They pretty much ok with TI and its notes programs.

**Comment by UDXS** [comment]
TI has notes programs? I didn't know that.

**Comment by 0b101** [comment]
The Ti-Nspire CX and CX CAS both have a notes app.

**Comment by UDXS** [comment]
That would explain why I haven't seen it.

**Comment by adriweb** [comment]
All the Nspires have it.
But it’s way more than just a “notes” app. In fact, the French name (which translates to “mathematical editor”) is closer to what it is: a full rich text editor with support for 2D math (and chemistry) expressions/formulas, which are dynamic (variables and expressions can be evaluated at will depending on the current file’s variables values). Even embedding images are supported in fact.

**Comment by UDXS** [comment]
So it's a bit like Mathematica? If Numworks added that, it would set it apart, especially if you could also evaluate python with it.

**Comment by adriweb** [comment]
Not really as it’s not a sequence of things but rather allows to have nice rich text documents (useful for classroom activities for instance) with evaluate-able math expressions.

**Comment by UDXS** [comment]
I've looked at a demo and it looks both interesting and doable. I think adding the ability to show graphs would make it better, especially for classrooms.

**Comment by nickatamas** [comment]
Guys is it possible to have something like that on numworks? I’m complete dumb at programming (;

**Comment by artaxxx** [comment]
We decided not to add a Notes application to the software. So I'm going to close this issue.
