### ISSUE TITLE
TI-style copy & paste

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#591]
I see that there are cut/copy/paste buttons that do nothing at least in the Python editor. I think copy & paste by line would be a good way to do it. However, unlike TI's implementation, one should be able to take a line and paste it on the current line, rather than make a new line.

**Comment by 0b101** [comment]
What about holding shift while moving the cursor to select certain areas of text to copy? Then pasting either at the cursor's location or pasting and replacing a selected area of text?

**Comment by boricj** [comment]
@0b101 That'd require a couple of new events at the `ion` layer and minor changes to differentiate between a shift being active (ie. pressing and releasing the shift key as usual) and holding down the shift key and then pressing up/down/left or right. If I'm not mistaken the keyboard matrix on the device can handle this, so overall it should be fairly easy to do.

**Comment by UDXS** [comment]
That is another way to do it. I would suggest a hybrid where, if you have nothing selected, it copies/cuts the whole line but will only copy parts with a selection.

**Comment by RedGl0w** [comment]
This issue can be closed since 5de65e0

**Comment by LeaNumworks** [comment]
As @RedGl0w said, this issue was fixed :)
