### ISSUE TITLE
[Popup] Hard to know selected button

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#597]
Little game, which button is selected ?

![image](https://user-images.githubusercontent.com/339611/42178305-218d6b84-7e30-11e8-8fb0-7890f217e649.png)

I would say Valider but in fact it is cancel.

**Comment by boricj** [comment]
May I suggest taking inspiration from the venerable Atari ST?

![](http://atariage.com/forums/uploads/monthly_04_2018/post-31554-0-97389400-1524761686.png)

Jokes aside, the NumWorks team uses a flat design UI so adding a border to the focused button will most likely not be accepted. I'd say the focused button needs to have a more visible hue ("warmth") to differentiate itself from light, desaturated and unselected ("cold") buttons.

By the way, has the NumWorks team conducted usability tests with color blindness or other visual deficiencies? If there are issues with accessibility, that could justify implementing #565 with standard, night and high-contrast color modes built-in.

**Comment by matheod** [comment]
Is underlining text allowed in flat design ?

**Comment by boricj** [comment]
It's not so much about what's allowed or not in flat design (Windows 10 buttons do have colored borders and variable thickness), but rather blending in with NumWorks's existing design.

The UI is almost completely borderless and thickless and relies mostly on contrast between flat-shaded rectangles to distinguish widgets. Lines overall are uncommon, so underlining text is probably not an option either. The best option is probably to make the selected button orange, as it is the hue used to highlight something (like the selected app on the main screen) when it's not done with a variation of lightness.

**Comment by 0b101** [comment]
![screen shot 2018-07-05 at 10 07 23 am](https://user-images.githubusercontent.com/29680628/42331562-521f4486-803b-11e8-8b0b-7c89d751b89a.png)
