### ISSUE TITLE
[Minor] Serial number on calc is not in the same format as on the workshop

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#598]
On calc : letters + numbers

On workshop : only number

Would be better if worshop also used letters + numbers.

I didn't found what was the function to transform from one to the other.

**Comment by Ecco** [comment]
Indeed. Serial number on the workshop are currently displayed as hexadecimal values. On the device, they are shown as Base64. It's the same underlying number though. We need to fix this on the workshop.

**Comment by matheod** [comment]
Are you sure, I have only digit (no letter) on the workshop. And why I try to base64 decode, I get strange character ?

(the goal of this is to be able to find which of my student is the owner in case they ever mix up their calculator :D)

**Comment by adriweb** [comment]
You probably want to decode the base64 to hex, not text/ascii :)

**Comment by matheod** [comment]
> You probably want to decode the base64 to hex, not text/ascii :)

Oh you are right. And I was confused because my hex number only contain 0 - 9 digits :D

**Comment by Ecco** [comment]
Solved 😄
