### ISSUE TITLE
Wrong median : Q3 before median (web version)

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#606]
edit : you can ignore list 1 and list 2. Only list 3 matter but the bug also happen if I put value of list 3 in list 1 or 2.

![image](https://user-images.githubusercontent.com/339611/42453487-3393a80e-838d-11e8-9aaf-bbe289358648.png)

![image](https://user-images.githubusercontent.com/339611/42453504-3df80042-838d-11e8-82a5-3aceb9280973.png)

(pressing right arrow go from min, Q1, median, Q3, max)

![image](https://user-images.githubusercontent.com/339611/42453548-5e53e298-838d-11e8-95bf-90fe7193509e.png)

![image](https://user-images.githubusercontent.com/339611/42453557-668ee5e8-838d-11e8-9f08-b21f1b1bbbb5.png)

![image](https://user-images.githubusercontent.com/339611/42453574-763df1fa-838d-11e8-9820-5b58a2d32e87.png)

![image](https://user-images.githubusercontent.com/339611/42453583-7d6b2498-838d-11e8-8563-7618beb520b5.png)

![image](https://user-images.githubusercontent.com/339611/42453594-85bfc8c4-838d-11e8-8edc-668b40dc8fee.png)

**Comment by matheod** [comment]
I will try to fix this even if I never programmed in C++ because the code about it look easy to understand. But I promise nothing :D

**Comment by LeaNumworks** [comment]
Hi @matheod, thanks a lot for catching this bug! I have nearly finished correcting it, so you do not have to bother working on it :)

**Comment by matheod** [comment]
oh okay then :)

**Comment by LeaNumworks** [comment]
sortedElementAfter returned the first element greater than 3 (thus 4), but what we needed instead is the first element of cumulated frequency greater than 1/2 :)

**Comment by LeaNumworks** [comment]
Fixed by #608
