### ISSUE TITLE
washed out colors / gamma correction / color correction

### ISSUE THREAD

**Issue by tvillingett** [numworks/epsilon#609]
Hi, as several others have commented the display seems to be a bit washed out. I think it could be a bit better with some gamma correction, and I think to do it directly in the LCD driver chip would be the best to avoid losing colors. I have looked through the data sheet of the controller, and it seems quite a lot to setup, and maybe to use code from other linux could help:
https://github.com/torvalds/linux/blob/63f04777162181798399a2c4e5436d0d0c16291b/drivers/staging/fbtft/fb_st7789v.c#L172

**Comment by boricj** [comment]
Reusing GPL-licensed is not an option here. Reimplementing is the way to go (and it really doesn't look bad at all, it's just populating a set of registers with values).

**Comment by tvillingett** [comment]
yes, sure that could be done, the other isssue is how to interpret the gamma curve from the numbers. I cannot see the logic in the numbers, it almost follow a line/curve except for 48, 33, 53 which looks like the top of a cowboyhat...
[gammacurve_original.pdf](https://github.com/numworks/epsilon/files/2190258/gammacurve_original.pdf)

**Comment by claire-savinas** [comment]
To understand the values, you have to look in the [datasheet](https://www.numworks.com/shared/binary/datasheets/st7789v-lcd-controller-73f8bc3e.pdf) of the display controller, page 287. Some values are "packed" (8th parameter, for example) and not in the right order.

Once done, you have to look at page 139 to have the relation between the values and the voltage applied to the LCD.

I'm asking myself if the datasheet is correct. According to it, VP7 to VP12 are equals (and also VP51 to VP56). This seems strange...

I have put together a [cell sheet](https://github.com/numworks/epsilon/files/2316479/gamma_numworks.zip) with the interpreted formulas, if you are interested, and also tested some values, but I don't know if the result is really better than the default ones. If you want to try : fe3a7bf

**Comment by tvillingett** [comment]
Sorry for my late response, but I finally got a chance to compile and test your suggested change, and for me it really made a difference. The orange is much more saturated for example, more like the simulator on a computer screen, and the light blue in the background in the calculator screen really shows. It is hard to make a photo, but I will try. So the only adjustments I would like to try, is to reduce the blue a bit to get more neutral white/grey and perhaps put back the "gamma" correction you made a notch... Thanks a lot! I will look into making the adjustments.

**Comment by tvillingett** [comment]
It seems like the values in VP7..VP12 should follow another percentage from J0P and J1P, it looks much better now, I updated the cell sheet: 
[gamma_numworks2.xlsx](https://github.com/numworks/epsilon/files/2563900/gamma_numworks2.xlsx)

**Comment by claire-savinas** [comment]
Very good catch ! 

I tried your settings and they are looking really good. It's very noticeable with two calculators side by side. I tried to take a photo but I did not manage to have a good one...

**Comment by tvillingett** [comment]
You can try this to compare:
`from kandinsky import *
from random import *
def dith8_6(n):
  return max(0,(min(255, n + randint(-2,2))))
def dith8_5(n):
  return max(0,(min(255, n + randint(-4,4))))

#grey
for x in range(255):
  for y in range(20):
    r = dith8_5(x)
    g = dith8_6(x)
    b = dith8_5(x)
    col = color(r,g,b)
    set_pixel(x,y,col)
#grey gamma
col1 = color( 255, 255, 255)
col2 = color( 0, 0, 0)
for x in range(255):
  for y in range(20):
    if (x%2) == 0:
      col = col1
    else:
      col = col2
    set_pixel(x,y+20,col)
    
# red
for x in range(255):
  for y in range(20):
    col = color( dith8_5(x), 0, 0)
    set_pixel(x,y + 40,col)
#red gamma
col1 = color( 255, 0, 0)
col2 = color( 0, 0, 0)
for x in range(255):
  for y in range(20):
    if (x%2) == 0:
      col = col1
    else:
      col = col2
    set_pixel(x,y+60,col)

# green
for x in range(255):
  for y in range(20):
    col = color( 0, dith8_6(x), 0)
    set_pixel(x,y + 80,col)
#green gamma
col1 = color( 0, 255, 0)
col2 = color( 0, 0, 0)
for x in range(255):
  for y in range(20):
    if (x%2) == 0:
      col = col1
    else:
      col = col2
    set_pixel(x,y+100,col)

# blue
for x in range(255):
  for y in range(20):
    col = color( 0, 0, dith8_5(x))
    set_pixel(x,y + 120,col)
#blue gamma
col1 = color( 0, 0, 255)
col2 = color( 0, 0, 0)
for x in range(255):
  for y in range(20):
    if (x%2) == 0:
      col = col1
    else:
      col = col2
    set_pixel(x,y+140,col)`

**Comment by Ecco** [comment]
Hi! That feature is indeed a great idea, but FYI I gave #756 a try and it's not very convincing so far 😄

**Comment by Ecco** [comment]
We've added this for N0110 😄 We kinda liked the default calibration on N0100, but feel free to tweak it on your device.
