### ISSUE TITLE
[web emulator] [css] Add user-select: none on .calculator on web emulator page

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#610]

**Comment by Ecco** [comment]
Well, that's not an issue, that's a potential solution 😄 

What's the actual problem you're trying to solve?

**Comment by matheod** [comment]
- On pc : avoid the forbidden drag icon that might sometime happen when we accidently drag by clicking too quick, 

But the realy reason, and I think user-select would fix it but I can't test, is that on mobile selection handle sometime happen when clicking on button.

**Comment by matheod** [comment]
I tested again and I no longer have text selection issue.

This issue can be closed.
