### ISSUE TITLE
[Manual] Rounding error + link error + function name error

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#611]
https://www.numworks.com/fr/ressources/manuel/book.pdf

- p 3

> Sous forme exponentielle, le calcul de mènera au résultat : exp(1.570797∗i)

it should be

> exp(1.57079**6**∗i)

- Also all link point on local file, for exemple `file:///var/folders/bx/_72rztp95qqdj81bsjstj4nh0000gn/T/%=%20p(%22ressources/manuel/parametres%22)%20%`

- p 15, its writen `ln2` and `ln10` instead of `log2` and `log10`.

- > Affiche le texte textaux coordonnées x,y

Missing space after text

> Génère un nombre entier aléatoire compris entrea et b

missing space before a 

- In english manual, there is a lots of formula whith align issue (ex last page).

**Comment by LeaNumworks** [comment]
Hi, thanks for the issue.
As of today, all problems are solved apart from formula alignment.
I did not really understand where the link problem happens.

**Comment by matheod** [comment]
For exemple, on page 19, "Rubrique" point to : `https://www.numworks.com/fr/ressources/manuel/%=%20p(%22ressources/python%22)%20%.pdf#[0,{%22name%22:%22Fit%22}]`

**Comment by artaxxx** [comment]
Fixed
