### ISSUE TITLE
trig function errors

### ISSUE THREAD

**Issue by cleemesser** [numworks/epsilon#612]
sin(2*pi) gives result of ~ 0.1094426069063

expected result: 0 
( or something very close it, for example in python 3.6)
```python
>>> from math import *
>>> sin(2*pi)
-2.4492935982947064e-16
```

NUMWORKS  Software version 1.6.0

For comparison, TI 84 ce gives zero

**Comment by matheod** [comment]
You are probably in degree and not in radian.

**Comment by cleemesser** [comment]
You are totally right. I did not think of that

changing settings to radians

sin(2 * pi) = 0   < correct

**Comment by matheod** [comment]
By the way, maybe the numworks could detect when the user might have misconfigured his calculator :  

If the calculator is in degree and the user write pi in his formula, warn the user that the calculator is in degree mode.
If the calculator is in radian and the user doesn't write pi in his formula, warn the user that the calculator is in radian mode.

The warning could only be shown once by session.
