### ISSUE TITLE
Python Interpreter : function bin

### ISSUE THREAD

**Issue by LeJoW** [numworks/epsilon#613]
In the Epsilon 1.6 Python Interpreter, the function `bin` does not work.
To get this issue, I tried : 
`````
>>> bin(x)
`````
and Python output : 
`````
'_brace_open__colon__hash_b_brace_close_'
`````
when the title of the `bin` function is *Convert integer to binary*.

This happens on all devices.

I hope this error would help the Numworks Community.

**Comment by Ecco** [comment]
Hi @LeJoW ! Thanks for reporting this! It had already been fixed by #573 though 😄
