### ISSUE TITLE
Feature : Middle school interface

### ISSUE THREAD

**Issue by yeKcim** [numworks/epsilon#63]
please add a way to switch between classic epsilon and light interface for middle school students. With this feature, students will be accustomed to numworks earlier and will learn to use it step by step.

**Comment by mateoconlechuga** [comment]
What do you mean by a "light interface" exactly?

**Comment by yeKcim** [comment]
Hide all functions useless for middle school student. I think that epsilon is really really intuitive but I'm not middle school student anymore (since a long time). I've a camera with normal/easy mode, it's really useful for kids.

**Comment by mateoconlechuga** [comment]
I agree. Also half of the fun is discovering what the calculator has to offer, at least that is what got me into calculators in the first place.
