### ISSUE TITLE
Make an apk app ?

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#643]
Hi,
A wonderful feature could be to compile an apk and share it on https://f-droid.org/ .
It there a way to obtain it from the git ?

**Comment by boricj** [comment]
There's currently no support for building and packaging epsilon as an APK. It is likely to be doable, but since epsilon is not FLOSS it won't be accepted into F-Droid.

**Comment by Ecco** [comment]
We have no plan to support binary versions of the simulator at the moment. We have an FLTK one for debugging purposes, but we only ship the JavaScript version.

That version works really well on Android, as you can see by browser https://www.numworks.com/simulator/ from and Android device.

**Comment by RedGl0w** [comment]
This issue could be reopened / reclosed for the f-droid part.
