### ISSUE TITLE
Extra icon display

### ISSUE THREAD

**Issue by Axenntio** [numworks/epsilon#645]
In the firmware, when you add an icon and scroll down , you will get the last row middle icon duplicate and unselectionnable.

<img width="452" alt="screen shot 2018-09-07 at 17 20 55" src="https://user-images.githubusercontent.com/18538043/45228099-8637bf00-b2c2-11e8-8939-28acb4b2b649.png">

**Comment by boricj** [comment]
It's not really a duplicate icon, but in fact a dirty screen where the previous icon at this location wasn't erased. Still, a graphical glitch to correct indeed.

**Comment by 0b101** [comment]
While this is being fixed you can try to create a new application with a white icon and no label to clear that "ghost" icon.
