### ISSUE TITLE
Crash when manipulating 9x9 matrixes with big decimal numbers

### ISSUE THREAD

**Issue by TheElectronWill** [numworks/epsilon#650]
I was working on multiple linear regression and I accidentally calculated a 9x9 matrix instead of a scalar. A few operations later, my calculator crashed and rebooted (at least it made me notice my mistake :smile:)

Here are the steps to reproduce a similar crash:
```
[[1,2,3,4,5,6,7,8,9]] -> M0
transpose(M0)M0 -> M1
M1 + π·100000 -> M2
M2 - 123456.789
```
The online simulator doesn't seem to be affected, maybe it's a memory issue?

**Comment by adriweb** [comment]
Couldn't make it crash on the desktop simulator, despite strict flags and ASAN, so yeah maybe hardware specific

**Comment by EmilieNumworks** [comment]
Thanks for reporting this issue. The crash was due to a dynamic allocation failure, the heap seemed to be full. We just changed the way we store mathematical expressions and memory exhaustion now triggers a pop-up. However, we might want to increase the memory provided...

**Comment by RubenNumworks** [comment]
> Thanks for reporting this issue. The crash was due to a dynamic allocation failure, the heap seemed to be full. We just changed the way we store mathematical expressions and memory exhaustion now triggers a pop-up. However, we might want to increase the memory provided...

Fixed
