### ISSUE TITLE
Epsilon Retro

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#653]
![1](https://user-images.githubusercontent.com/29680628/45599810-f1b31800-b9b7-11e8-8e7c-40ceab762d28.PNG) ![2](https://user-images.githubusercontent.com/29680628/45599811-f1b31800-b9b7-11e8-87d5-31d2a682af04.PNG) ![3](https://user-images.githubusercontent.com/29680628/45599812-f1b31800-b9b7-11e8-983a-6d0277b43b5b.PNG) ![4](https://user-images.githubusercontent.com/29680628/45599813-f1b31800-b9b7-11e8-9b26-811fe5817eeb.PNG)

GitHub repository: https://github.com/0b101/epsilon/tree/retro 

*info coming soon*

**Comment by Ecco** [comment]
Nice 😄Does it come with AAA batteries too?

**Comment by 0b101** [comment]
Here is the link if anyone wants to try it out: https://github.com/0b101/epsilon/tree/retro
There are a couple icons in probability that I forgot to change.

**Comment by tarapitha** [comment]
Cool! Althought it is not an issue and increments unnessecarily the number of open issues :(

**Comment by LeSeulArtichaut** [comment]
@0b101 The current Python editor style style basically don't match the retro style. I've done a commit wich I wanted to propose you but I cannot directly push it into your repo (I'm not very familiar with GitHub so I've perhaps missed something)

**Comment by parrotgeek1** [comment]
This style would work extremely well for a hypothetical port to the classic ti-nspire

**Comment by Ecco** [comment]
I'm going to close this issue. It's a fun theme, but we currently have no plan to maintain any other look'n'feel 😄
