### ISSUE TITLE
Long lines in Python editor

### ISSUE THREAD

**Issue by jmg-74** [numworks/epsilon#655]
Hi, it would be nice to see directly whole (long) lines in Python editor. 
Yet it is hidden on right part, not so easy to read on calculator. A dedicated arrow on the left to indicate that it is not a new line but the end of the least one could be nice to use ? E.g. \u21b3 ↳

[Quite related with [#400 issue](https://github.com/numworks/epsilon/issues/400), for more or less the same reason]

Thanks

**Comment by artaxxx** [comment]
Fixed in version 20
