### ISSUE TITLE
Computing log(100) doesn't yield an exact 2

### ISSUE THREAD

**Issue by Ecco** [numworks/epsilon#656]
Computing `log(100)` yields `2*log(2)+2*log(5)` instead of an exact `2`. While not an error _per se_, it's obviously not the best simplification we could do.

It also has an annoying side-effect: the numerical result, 2, is said to be an approximation (`≈2`) instead of an exact one.

![screenshot](https://user-images.githubusercontent.com/55989/45806989-ae5fee80-bcc2-11e8-8548-21e1ba2aa097.png)

**Comment by olaure01** [comment]
In ```log(x,a)```, factorization of ```x``` by ```a``` should certainly be used before prime decomposition of ```x``` for rational arguments.

**Comment by LeaNumworks** [comment]
Fixed by 1577063ad2eb1423db81f54140c82dd1731d632a.
When the base a of the logarithm is an integer, we now divide x by a as many times as we can before using prime decomposition.
