### ISSUE TITLE
Allow the user not to close parens, quotes etc.

### ISSUE THREAD

**Issue by adriweb** [numworks/epsilon#66]
**Set up**:
In the calculation app, a user types `2` `*` `(` `3` `+` `5` then presses [EXE].

**Current situation:**
The calculator tells the user that there is a syntax error.

**Proposed situation:**
The calculator ignores the missing closing _X_ character (in this case, _X_ being a parenthesis) and computes what the user intended: `2*(3+5)`, resulting in less time wasted.
To be clearer to the user, as soon as an open-_X_ character is typed, the OS would append the matching closing one to the current input, in a lighter color for instance.
  
**Comments**:
- This could work for characters like parens (for expressions), quotes (for strings), brackets (both curly and square, for lists and matrices).
- Support for nested characters would have to be done.
- ... and support for characters being deleted, too, where the inserted matching closed one would go away as well.
- Note: this is the way things work on some TI calculators (ignoring only on the z80/ez80, "grey draw" on the Nspire), and possibly others.

**Example**:
![grey draw example](https://i.imgur.com/uwBfJpA.gif)

**Comment by Zezombye** [comment]
Also maybe add autocompletion support for commas. For example, if I select "sum" from the toolbox, it gives me `sum(|,,)`, and if I type '6' then ',', it should override the present comma instead of adding another.

The Casio calculators also support missing closing brackets btw.

**Comment by yeKcim** [comment]
A pretty solution, could be colored brackets.

If there is only one brackets level, stay black. Each sublevel has its own color. If a bracket is open and not closed (or closed and not opened) it's red. Colors have to be used each time it's helpful…

A mockup (I thought "1st level stay black" after drawing)
![capture du 2017-10-10 18-00-16](https://user-images.githubusercontent.com/10558744/31397423-4700de0c-ade6-11e7-9a25-cc70bcf8d95b.png)

**Comment by matheod** [comment]
I think it is better if student are forced to close bracket.
We already have too many student typing 1+x/2 instead of (1+x)/2 ...

If this sort of thing get ever added, I think it should be an option disabled by defaut.

But some coloring of bracket could be good (for exemple cooloring the "cursor touched" bracked couple).

**Comment by RubenNumworks** [comment]
Related to #587

**Comment by RedGl0w** [comment]
Indeed, other application of this would be useful :
When you want to have an expression at numerator, but you didn't opened any parentheses at the beginning, just pressing a closing parenthese and then division would be nice (so allowing student not to open parenthese too)

**Comment by artaxxx** [comment]
Fixed in version 20
