### ISSUE TITLE
Function Orthonormal preadjustment loses normality in Zoom

### ISSUE THREAD

**Issue by tarapitha** [numworks/epsilon#665]
Here are two views with orthonormal preadjustment of two functions { sqrt(1-x^2); -sqrt(1-x^2) } :
![orthonormal](https://user-images.githubusercontent.com/8431237/45926463-e49fa700-bf2a-11e8-9dd8-e1d28fc85788.png)
![orthonormalzoom](https://user-images.githubusercontent.com/8431237/45926464-e49fa700-bf2a-11e8-9ce3-c017b05531e0.png)
While the first looks almost orthonormal, it loses normality as soon as the Zoom function is activated. This presumably happens due to Zoom helper menu at the bottom of the screen. I think it would be better to not rescale graph to make place for menu, but just add the menu on bottom of the screen and by overlapping part of the graph?

**Comment by matheod** [comment]
Or remove the zoom title bar at the top ?

**Comment by artaxxx** [comment]
Fixed in 10.0.0
