### ISSUE TITLE
[Statistics/Regression] Additional functionality (e.g. more useful stats, copying cols, etc.)

### ISSUE THREAD

**Issue by tjhorner** [numworks/epsilon#690]
In my AP Statistics class, there are lots of functions of Epsilon that would be super helpful as well as some that should be fixed. I've gathered them here for consideration:

## Feature Proposals

The first is the ability to **copy/save lists of data**. In class, we often re-use the same context but for different concepts, so at the beginning of class it's super tedious to re-enter all the data. Instead, it would be easier to save data in separate named variables (like how TI calculators do it). This way, it would be as simple as just selecting "Load data" on a column.

This brings me to my next suggestion: **more lists!** We use upwards of 6 lists at once in my class, but the Statistics app only has 3. (I have been working around this by using the X and Y lists in the Regression app to have a total of 6 lists, lol.)

**The ability to reference a list from anywhere** would be very nice as well. You can already reference other lists when filling a column with a formula (e.g. `V1 - 2` would iterate over each value in list V1, subtract 2 and fill the corresponding index w/ the result), but you cannot reference lists from other apps (e.g. can't reference V1 from the Regression app), and you can't reference lists _at all_ in the Calculation app.

**More complex functions that can be applied to lists** such as `sum` would be extremely helpful. This ties in with the above - `sum(V1)` (return a sum of all values in the list) would require the list to be able to be referenced in the Calculation app.

**SORTING LISTS**. This is a must. I've been working around this in several ways, but it seems we deal with sorted lists a lot.

## "Fix" Proposals

In the AP Statistics curriculum, percentiles do not necessarily need to be a part of the set (or, at least according to my teacher). As an example, if we had the data set `1, 3, 5, 9, 11, 13, 14, 18, 19` and we wanted to find the first quartile, logically it would be `5` since the index of the 25th percentile is `2.25`. But in AP Statistics, since the index is not a whole number, we are supposed to choose the number between them, so: `4`, even though it's not a part of our data. _Yes, this is really weird, but it's what the College Board wants._ Being able to switch between the two calculation modes would be a good addition.

Adding sample standard deviation `s` in the regression statistics column as well as the residual standard deviation would be very useful. We use these quite a lot (we do not use `σ` for std. dev. in these cases), so having them on-hand would speed up problem solving a bit. (I have already implemented these in my fork: see [here](https://github.com/tjhorner/epsilon/blob/stats-fixes/apps/regression/store.cpp#L277-L289), [here](https://github.com/tjhorner/epsilon/blob/stats-fixes/apps/regression/store.cpp#L303-L315), and [here](https://github.com/tjhorner/epsilon/blob/stats-fixes/apps/regression/calculation_controller.cpp#L183-L195))

---- 

I understand that a few of these are pretty specific to my needs with AP Stats, but I feel that a lot of them (especially relating to the lists) would be extremely useful for the majority of students taking any type of statistics course. I am happy to help wherever I can with these, if the NumWorks team decides to implement them.

Thank you for making such an awesome calculator, team!

**Comment by adriweb** [comment]
> In the AP Statistics curriculum, percentiles do not necessarily need to be a part of the set (or, at least according to my teacher). As an example, if we had the data set `1, 3, 5, 9, 11, 13, 14, 18, 19` and we wanted to find the first quartile, logically it would be `5` since the index of the 25th percentile is `2.25`. But in AP Statistics, since the index is not a whole number, we are supposed to choose the number between them, so: `4`, even though it's not a part of our data. _Yes, this is really weird, but it's what the College Board wants._ Being able to switch between the two calculation modes would be a good addition.

Yep this is different from France where the definition (and as such, what is expected in exams etc) is the other way around - TI and Casio calcs (not sure about HP, probably as well), for instance, have long had the US definition, and only recently had a way to use the french definition (enabled by default for french models).

**Comment by matheod** [comment]
The french way is absolutly stupid :/

I don't know who choose it, and why he choose it.

**Comment by tjhorner** [comment]
Is this one of those cases where the US is special and the rest of the world uses the other definition? 😛

**Comment by matheod** [comment]
The US definition is actually more smart than the french ones because it is symetrical.

**Comment by tjhorner** [comment]
@boricj 

>The Statistics app would by default work on V0, but the user could choose to work on any other vector. Similarly, the Regressions app would use V0/V1 for X/Y values, V2/V3 for another set of data and so on. We could use matrices and M{0,9} instead, but the various ways to represent data would most likely be too tricky to expose and implement properly.

I like the idea of shared vectors between the stats and regression apps. Would make things a lot easier to work with.

>I think it was rebutted at the time because mobile apps on smartphones are walled off from each other and students would expect the same behavior, but math topics are inherently interconnected.

Yeah, and even on smartphones there are share sheets, a global clipboard, among other things that let apps communicate directly with each other.

**Comment by artaxxx** [comment]
Fixed in 19.0.0, if some details are missing, please feel free to open a new issue
