### ISSUE TITLE
python shell and kandinsky show special characters as garbage

### ISSUE THREAD

**Issue by alinanorakari** [numworks/epsilon#698]
These special characters should be either displayed correctly (pretty sure they're in the source code) or not at all.

<img width="731" alt="screenshot 2018-10-05 at 01 42 23" src="https://user-images.githubusercontent.com/4239297/46508935-37893080-c840-11e8-801f-3c59ec9e671d.png">

**Comment by lastfuture** [comment]
I would suggest to implement some kind of filter than that will at least prevent garbage from being printed when using UTF-8.
Out of curiosity, how can I use the proprietary characters?

**Comment by boricj** [comment]
The proprietary characters are defined in https://github.com/numworks/epsilon/blob/master/ion/include/ion/charset.h. I haven't checked if they are usable inside Python though.

**Comment by lastfuture** [comment]
I have checked today and they totally are, if you use them via `chr()`, e.g. `chr(150)` for `≈`, both in the shell and using kandinsky.

This should be documented somewhere!

**Comment by RedGl0w** [comment]
This is now patch, by using utf-8, and when the character isn't in the font, showing the "buggy" character

**Comment by LeaNumworks** [comment]
Closing because it's been fixed.
