### ISSUE TITLE
[apps/graphing] Find an intersection point between 2 functions?

### ISSUE THREAD

**Issue by tjhorner** [numworks/epsilon#70]
Some popular calculators (such as Ti-84 Plus) have a "find intersection" ability that finds the point of intersection between 2 or more functions. Is this possible with Epsilon? I've noticed some strings (`Intersection`, `SelectLowerBound`, `SelectUpperBound`) in the i18n file, but they don't seem to be used. Is this a planned feature? It would be very useful in my Algebra 2 class.

**Comment by artaxxx** [comment]
Fixed by #317
