### ISSUE TITLE
random numbers behave strangely in sequence containing random()

### ISSUE THREAD

**Issue by lastfuture** [numworks/epsilon#702]
in a sequence `u(n)=random()` the random values seem to be recalculated too often. The values constantly change both when scrolling the Table and when interacting with the Graph. The latter results in graphical artefacts because only the part where the cursor moved is being redrawn.

I suggest that as soon as editing the sequence is done a random seed will be determined (randomly?) that will stay fixed until the sequence is edited again.

**Comment by Ecco** [comment]
Well, random is… random, isn't it? I do get your point about the graphic glitch, but I'm going to close this anyway because to be honest plotting/browsing "random()" quite doesn't make any sense anyway. Thanks for your report though 😄

**Comment by lastfuture** [comment]
Plotting a bunch of `randint(1,6)` makes sense though, e.g. to visualize the difference of distribution between throwing one dice and many. But I suppose you're right, it's not much of an issue

**Comment by matheod** [comment]
Couldn't we set the seed when submitting the sequence formula ?

**Comment by boricj** [comment]
On the device the hardware RNG is used directly, it can hardly be seeded. Besides, trying to plot the random() function itself is meaningless without sampling it first, shouldn't the calculator just display TV static noise instead?

**Comment by lastfuture** [comment]
use your imagination

![screenshot-3](https://user-images.githubusercontent.com/4239297/46560452-1bdf6200-c8f4-11e8-9ace-cb60ef850ae0.png)
