### ISSUE TITLE
ability to copy table data

### ISSUE THREAD

**Issue by lastfuture** [numworks/epsilon#707]
I would love if we could copy or transfer data from tables between apps, e.g. a result from Sequences to Statistics, or an input from Statistics into Regression. As far as I can tell that's not possible right now.

I could imagine one of the following methods:
* with the ability to select and copy the entire table, e.g. via a thin extra header row that spans two columns
* via text labels "copy data"/"paste data" where we also have "set the interval"
* via "sto->" and/or an option in the var menu that saves it as a matrix

**Comment by boricj** [comment]
This is a recurring issue with epsilon (#690 and too many other posts to count) and a step back from TI calculators. It goes beyond Statistics/Regression too: I would expect functions defined inside Functions to be usable inside Calculations and variables defined inside Calculations to affect functions when they have variables in them. Copy-pasting is inconvenient when we could just use global variables and vectors instead...

**Comment by lastfuture** [comment]
I'd much rather work with copies of data, perhaps stored in matrices in order to migrate it from one app to the other, but never used as a direct reference, but as a means for pasting into the target app as a copy of the matrix, essentially using the matrix like a clipboard.

I believe copying data is a concept well understood by the target audience of NumWorks as I understand it. It would also work much better considering I'm including result tables in my suggestion.

Consider the following: I've generated 500 simulated dice rolls with four six-sided dice using the Sequences app and the formula `randint(1,6)+randint(1,6)+…`. I'd like to use this data in the Statistics app to visualize the distribution of results. I would want a copy of that data as to not destroy it the next time I need to tweak, delete or change the sequence I've used.

Now throw into the mix that I could manipulate my matrix in the Calculation app between copying from Sequences and pasting to Statistics, and I could easily store the result in a second matrix to retain my original data.

I think for all of these cases the concept of copy and paste works much better and it retains state within the respective apps and removes a factor that can seem like a black box to the uninitiated

**Comment by lastfuture** [comment]
replace "copy" and "paste" in my comment with "sto->" and "the variables menu" as you see fit, since I was talking about matrices as a sort of clipboard. The concepts are essentially the same though

**Comment by lastfuture** [comment]
Here's my proposal for an interface for this functionality

<img width="1021" alt="screenshot 2018-10-06 at 16 34 48" src="https://user-images.githubusercontent.com/4239297/46572430-d2d7ee00-c985-11e8-8cb4-ea988f5ce7a2.png">

**Comment by LeJoW** [comment]
Other possibility : use copy/paste button via the row header button.

**Comment by artaxxx** [comment]
Fixed in 19.0.0
