### ISSUE TITLE
[Python] Problem on real calculator with compiled sources of 1.7.0 from 2018-10-05

### ISSUE THREAD

**Issue by tarapitha** [numworks/epsilon#708]
This should be easy to sort off. On the development version of firmware with real calculator, the python script is overwritten with empty or other scripts when its "Auto import in shell" is deactivated.

How to repeat:
1) Reset the calculator by reset button and pick language
2) Go to Python app
3) Deactivate "Auto import in shell" for factorial.py
4) Open factorial.py
5) Wonder, where the program went :)

**Comment by EmilieNumworks** [comment]
Thank you for catching this! #710 should fix it. I'll close this pull request as soon as the fix is merged.
