### ISSUE TITLE
Some calculations show a precise result, some only the decimal

### ISSUE THREAD

**Issue by lastfuture** [numworks/epsilon#713]
I get the precise fraction output `17/2000 = 0.0085` when typing the following calculations into Calculation:

* `85*10^(-4)`
* `85/10000`

however in the following cases none of the calculations triggers the precise output. For all of the following, the result is `0.0085` (only decimal without the fraction):

* `85*0.0001`
* `0.0170/2`
* `0.0085`
* `0.0084+0.0001`

Is there a reason that only some types of calculation trigger the precise output? I'd love if it would work with more of the above terms, and I can't see a clear rule when it works and when it doesn't.

**Comment by lastfuture** [comment]
I think I found the rule: Calculations containing values with decimal places don't trigger precise results, right? That would be a shame, because I would expect `0.5/1` to be turned into `1/2 = 0.5`

**Comment by FrnchFrgg** [comment]
This issue (of which #887 seems a duplicate) seems to already be a duplicate of #294. Maybe consolidate all these issues into one ?

**Comment by RubenNumworks** [comment]
> I think I found the rule: Calculations containing values with decimal places don't trigger precise results, right? That would be a shame, because I would expect `0.5/1` to be turned into `1/2 = 0.5`

You are right and that rule still holds. Since version 11 of Epsilon, selecting the (approximate) result makes the exact fractional result appear.

Thank you for your feedback.
