### ISSUE TITLE
Numbers with more than 31 decimal places become undefined

### ISSUE THREAD

**Issue by lastfuture** [numworks/epsilon#715]
If a number has more than 31 decimal places it becomes `undef`
![oct-08-2018 21-07-43](https://user-images.githubusercontent.com/4239297/46628662-90a5dc80-cb3e-11e8-84c4-940627b4258a.gif)

I wish the calculator handled this more gracefully

**Comment by artaxxx** [comment]
The bug is fixed in the device but still present in the simulator

**Comment by Ecco** [comment]
I think this has been fixed. I cannot reproduce it on current master.
