### ISSUE TITLE
matrix issue with the 10/09 1.7.0  release 

### ISSUE THREAD

**Issue by gnah33** [numworks/epsilon#716]
Minus signs just disappear when storing a matrix in memory.
try : [4 -1 2] sto M0
After that, M0 is [4 1 2].
Minus signs disappear whatever the matrix size.

Same problem on the 6/7th of Oct. version.
arm cpp compiler version is 7.3.1 (20180622)  if it helps.

**Comment by LeaNumworks** [comment]
Hello! Good catch, thank you! This issue should be fixed by #718.
