### ISSUE TITLE
sum() function doesn't work

### ISSUE THREAD

**Issue by Zezombye** [numworks/epsilon#72]
Doing `sum(3,4,6)` will return undef instead of 9. I tried some other variations but they still return undef.

**Comment by Zezombye** [comment]
Apparently that's fixed, the simulator is not up to date.

**Comment by artaxxx** [comment]
I reopen this issue because that's a very good one. Actually when computing a sum, it should display "n" when I press "x,n,t" key. I get an "x" instead.

**Comment by Ecco** [comment]
This is in fact another issue (xnt vs sum computation). Closing.
