### ISSUE TITLE
Function Graph do not follow Ymin and ymax value

### ISSUE THREAD

**Issue by matheod** [numworks/epsilon#722]
![image](https://user-images.githubusercontent.com/339611/46813460-06948880-cd77-11e8-8481-4e204de9ff68.png)
![image](https://user-images.githubusercontent.com/339611/46813507-1dd37600-cd77-11e8-82c1-9e9fcdec2b19.png)
![image](https://user-images.githubusercontent.com/339611/46813546-3348a000-cd77-11e8-8b02-2ade7aa1a443.png)

On the last image you see that y axis do not follow choosen values.

If you go back on axis value changed :

![image](https://user-images.githubusercontent.com/339611/46813597-4c515100-cd77-11e8-9c27-b57cddb90bd8.png)

Bug : in calculator and emulator

**Comment by artaxxx** [comment]
Fixed in 10.0.0
