### ISSUE TITLE
python the round function does not round in some cases

### ISSUE THREAD

**Issue by ptitjoz** [numworks/epsilon#724]
Hello
in python the round function does not round in some cases
example:
`round(25/(1-(pow(1.0025,-180))),2)` gives an unrounded number.
we get  69.06000000000001 
the expected result is 69.06

**Comment by RubenNumworks** [comment]
With the input `69.06`, you get `69.06000000000001`. That is due to the way floating-point numbers are stored by micropython. It is not directly related to Epsilon.
