### ISSUE TITLE
Regression in displaying integral operation in Calculation app.

### ISSUE THREAD

**Issue by tarapitha** [numworks/epsilon#732]
When using 1.8.0 from Oct 17 git commit, the 'dx' is positioned incorrectly. It is correct on 1.7.0 stable software. The 'dx' should be vertically centered. Screenshot from compiled emulator:
![numworks_int](https://user-images.githubusercontent.com/8431237/47107502-28e44580-d252-11e8-838a-af7a23f711ec.png)

**Comment by LeaNumworks** [comment]
Hello, thank you for spotting this! It will be fixed by #733.
