### ISSUE TITLE
[Calculation] CAS outputs 

### ISSUE THREAD

**Issue by UDXS** [numworks/epsilon#738]
![Calculation](https://user-images.githubusercontent.com/10068612/47202404-44983a80-d37d-11e8-8d6d-96966fc971a5.png)

The expected output is "x^4 + x^2" not just because it was originally written in that order but because that is the standard way to write exponents, with the higher exponents first.

**Comment by agucova** [comment]
I've always thought the same, why is this so? When I see a polynomial I always expect it to be ordered from the higger exponent to the lowest.

**Comment by matheod** [comment]
Duplicate of #535

**Comment by joshuachris2001** [comment]
I feel dumb for asking, but how do you get epsilon to display the equation for output?

**Comment by RedGl0w** [comment]
He's in a previous version, because until 11.0.0 the symbolic calculation has been disabled

**Comment by joshuachris2001** [comment]
And I guess there is no way to re-enable that feature

**Comment by RedGl0w** [comment]
Of course there's : it's just a boolean to change
I don't remember well where it is, but on oméga it was changed, and maybe by looking in the commit history you can find it :)

**Comment by LeaNumworks** [comment]
Hi,
I am closing since this was solved -> you can check that by calculating `pi^4+pi^2`, which returns `pi^4+pi^2`
