### ISSUE TITLE
Simulator not working on macOS Mojave (10.14)

### ISSUE THREAD

**Issue by Axenntio** [numworks/epsilon#743]
Compiling and running the simulator on macOS Mojave leave a blank window (In light and dark mode)

<img width="452" alt="screenshot 2018-10-24 at 09 41 19" src="https://user-images.githubusercontent.com/18538043/47414359-121d8180-d771-11e8-92c6-818394cb0ed0.png">

**Comment by Ecco** [comment]
Hi @Axenntio ! Thank you for reporting this 😄 It's already been reported though as #688 , and the solution is "FLTK should be fixed". Thanks though!

**Comment by Axenntio** [comment]
Oops ! Sorry, thank for the reply !
