### ISSUE TITLE
Idea ::::::: New App -:- Graph Network

### ISSUE THREAD

**Issue by chezsick** [numworks/epsilon#749]
I Good Idea, To Added A App For Graph Network, Is A Map, The Node Represente A Node (Pointe) And Edge Represente A Link (Line), Node To Node, Three Graph Type Network ::::
1. Directed ::: The Edge Is A Arrow
2. Undirected :::: The Edge Is No Arrow
3. Bipartite ::::: The Node Letter A Are Liked To B, Never A To A And B To B

I Hope This Idea Is Possible, Sick

**Comment by Ecco** [comment]
What? Do you mean something ala [Graphviz](https://www.graphviz.org/)?

**Comment by chezsick** [comment]
Yes

**Comment by Ecco** [comment]
Hi! Sorry for the delay 😄 Writing such an app is certainly possible, but at the moment it's not one of our priorities, so I'm going to close this issue. Note that even though Epsilon is still a moving target, that's definitely something you can develop on the side 😄
