### ISSUE TITLE
[approximation] Bug with `floor` function

### ISSUE THREAD

**Issue by LeJoW** [numworks/epsilon#758]
## Software: 
Epsilon v1.7.1

## Bug:
The `floor` function gives some results with a sign ≈ when its result is always an integer.

## Example:
![screenshot](https://user-images.githubusercontent.com/33910128/48363620-a27f2000-e6a6-11e8-8cd6-ec78e8c7dfb1.png)

**Comment by nsajko** [comment]
This is fixed in current master.

**Comment by Ecco** [comment]
Indeed. Thanks!
