### ISSUE TITLE
Roots of negative numbers only returning imaginary values

### ISSUE THREAD

**Issue by techtideapps** [numworks/epsilon#759]
If I do a root of a negative number, say the third root of -8, rather than saying -2 it says the positive imaginary root. Although this is still a correct answer this is not always super practical. In addition to this, graphing a higher root will not show the negative side even though it still should since it still has real numbers as solutions.

**Comment by UDXS** [comment]
Any odd root should have an answer instead of an imaginary. This behavior is similar to that in TI-OS.

**Comment by artaxxx** [comment]
Fixed in 10.0.0
