### ISSUE TITLE
License might not allow contributions.

### ISSUE THREAD

**Issue by RobertZenz** [numworks/epsilon#76]
>  Disclaimer: I'm not a lawyer, and this is assembled from my own, humble, legal knowledge. Correct me if I'm wrong.

The README states:

 > We welcome contributions. For smaller changes just open a pull request straight away.

However, the whole code is licensed under [CC-BY-NC-ND](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode), which does not allow derivative works. Setting a side that CC licenses are not designed with software in mind, a "derivative work" is not defined by the CC-BY-NC-ND, but states the following conditions in section 2.a.1:

 > 1. Subject to the terms and conditions of this Public License, the Licensor hereby grants You a worldwide, royalty-free, non-sublicensable, non-exclusive, irrevocable license to exercise the Licensed Rights in the Licensed Material to:
 > 
 >  A. reproduce and Share the Licensed Material, in whole or in part, for NonCommercial purposes only; and
 >  B. produce and reproduce, **but not Share, Adapted Material** for NonCommercial purposes only.

Emphasis are mine. Which can be interpreted that a fork with modifications is in violation of the license, because the material has been "adapted" and/or "modified" (therefor, a derivative work has been created) and is being actively distributed. Contributing by patches seems therefor impossible.

Various possible solutions come to mind (in no particular order):

 * Remove the suggestion to contribute and state clearly that modifications are not allowed under the license.
 * Extend the license to explicitly allow forks and patches (note that this might require the consent of all contributors).
 * Drop the ND requirement (note that his will require the consent of all contributors).
 * Change to a software license, like the GPL (note that his will require the consent of all contributors).

**Comment by adriweb** [comment]
There’s already an issue about that here : https://github.com/numworks/epsilon/issues/38 , where NumWorks has replied with ideas on how they’ll probably change the license.

**Comment by RobertZenz** [comment]
Sorry, I did check already existing tickets, but managed to miss that.
