### ISSUE TITLE
[function] Uncorrect display of some function

### ISSUE THREAD

**Issue by LopsemPyier** [numworks/epsilon#774]
Hi, for some functions the graph isn't correctly plot. 
e.g. : for function 

> sin(x)²+cos(x)²

 which normaly always is 1 the graph has Ymax = Ymin = 1 so the graphe has not a linear line.
Or for the function : 

> diff(sqrt(1+2x²), x)

 for x ~= 100 the graph is not linear and has some points not on th line.

Version system : 1.7.0

**Comment by Ecco** [comment]
Great catch @LopsemPyier ! The first case definitely comes from a rounding error assorted with a bad auto-zooming decision.

**Comment by artaxxx** [comment]
Fixed in 10.0.0
