### ISSUE TITLE
[Rounding error] Matrix issue, wrong inverse

### ISSUE THREAD

**Issue by gnah33** [numworks/epsilon#777]
The bug described in #757  remains in the 1.8.1 release.
Inverse of
(16 -4 1)
(1 1 1) 
(16 4 1)
gives a22 = -1.11E-16 instead of zero.
That does not occur with the 1.7.1 version nor with the last commits simulators but weirdly, only with the last commits device firmwares including the official 1.8.1 release so it happens only with the real device !

**Comment by Ecco** [comment]
Hi @gnah33 ! This is most likely a rounding error, thanks for the bug report! We'll most likely fix this by calculating exact inverses.

By the way, in the future, please open one GitHub issue per, well, issue 😄 We missed your report in #757 because we assumed it was all about compiler warnings.

**Comment by gnah33** [comment]
Thank you Ecco, you were right about my indadequate titles.
I'm really happy to learn you're about to fix this by calculating exact inverses :smiley: 
It's gonna make most of my colleagues speechless.

**Comment by RubenNumworks** [comment]
Exact computations on matrices has been added on the master branch. Those rounding errors should not happen anymore.
