### ISSUE TITLE
[python] Error in the display of special characters squence

### ISSUE THREAD

**Issue by LopsemPyier** [numworks/epsilon#795]
Hi,
In python when you type a string with special characters as _\n_ or _\t_, the end quote become white or transparent.
Also when you put a _b_ before the quote for encode the string, all the string become white or transparent.

A last thing, if in a input statement you put a _\n_ the result printed is all the lines in the same like if you execute
```Python
input('One\nTwo')
```
It will display the _One_ and the _Two_ one the same line but on just the bottom and the other just the top.

Version system : 1.8.1

**Comment by LeaNumworks** [comment]
Hi,
Thanks for the issue!
I am closing since this was solved by 0f52335 and 177373c5a.
