### ISSUE TITLE
[Feature request] Warn users before updating operating system.

### ISSUE THREAD

**Issue by jlachniet** [numworks/epsilon#804]
Right now, it is very unintuitive that updating the calculator's operating system deletes its files. It does not mention this anywhere on the website, or on the calculator.

It would probably be a good idea for the user to confirm that they are about to reset their calculator before doing it, or at the very least, mention it before deleting all of their files without warning.

**Comment by matheod** [comment]
We could save files just before update and add them after update.

**Comment by XanderLeaDaren** [comment]
Same wanted feature as #128

**Comment by LeaNumworks** [comment]
Hi, I am closing since as @XanderLeaDaren said, this is the same issue as #128.
