### ISSUE TITLE
Unit conversions

### ISSUE THREAD

**Issue by jlachniet** [numworks/epsilon#805]
Having the ability to do basic unit conversions quickly on the calculator would be very helpful. It shouldn't be necessary to have to download or write a program to do basic conversions.

**Comment by WOKNz** [comment]
Please make trigonometric functions understand DMS or at least option to convert them.

**Comment by PiGuy2** [comment]
If the units start with a prefix (I have been thinking of using and underscore), it should be easy to parse the units as a separate token (See https://github.com/PiGuy2/epsilon/commit/cfa8f3cbbc57f44312a70671120c4ecf1b63f9c8). However, processing this token is proving to be more difficult. If anyone has any tips or suggestions, let me know, but I am planning on attempting to implement something that will support at least basic functions (probably addition, subtraction, multiplication, division, and exponentiation). As for which units and constants to use, I was thinking of using the SI base units, and later adding a small list of derived units and all of the US equivalents.

**Comment by ericflores** [comment]
> 
> 
> If the units start with a prefix (I have been thinking of using and underscore), it should be easy to parse the units as a separate token (See [PiGuy2@cfa8f3c](https://github.com/PiGuy2/epsilon/commit/cfa8f3cbbc57f44312a70671120c4ecf1b63f9c8)).

This is exactly how they are managed in the HP48 series of calculators. For example:

    6000_m/1_s * 1_km/1000_m = 6_km/1_s

or 

    1_hp converts to 745.69987182_W 

The units parts are always to the number part. Never alone. Well, it is not a units conversion system; it is a unit of measure algebraic system that includes conversions natively. I think that no unit of measure is just another unit of measure (null), from the algebraic point of view.

**Comment by RedGl0w** [comment]
This issue can be closed since https://github.com/numworks/epsilon/commit/92d17145b28beb81139b480ae2682e7366f2d639

**Comment by Ecco** [comment]
Indeed. Thanks!
