### ISSUE TITLE
sum function render

### ISSUE THREAD

**Issue by LeJoW** [numworks/epsilon#810]
Hi ! I think it would be usefull to can choose the variable name of the `sum` function (`"n"` here) to avoid this case (the result of this expression is not very obvious) :

![screenshot](https://user-images.githubusercontent.com/33910128/49788077-abf0bc00-fd28-11e8-86d3-dc6020ea31c7.png)

````
Software v1.8.1 (Simulator)
````

**Comment by Ecco** [comment]
This has been fixed by 31a5caff602e0b608683f855c827b3024bcdbb2b 😄
