### ISSUE TITLE
Significant figures

### ISSUE THREAD

**Issue by LeJoW** [numworks/epsilon#813]
It may be usefull to add a support for an automatic rounding engine based on the number of `significant figures` from the user input.
Here the result would be `0.5` because of the two significant figures number `1.4`.

![screenshot](https://user-images.githubusercontent.com/33910128/49859866-e033ad80-fdf8-11e8-9ecf-5a43404deb95.png)

A button `Automatic rounding` can be added in the `Settings` app, turning off the `Significant figures` field.

Thank you for your job !

**Comment by matheod** [comment]
But how do you know which number used in the formula are exact and which one are approximate ?

**Comment by LeJoW** [comment]
> But how do you know which number used in the formula are exact and which one are approximate ?

A result cannot be more exact than the input numbers. It is not required to know if a number is approximate, just know how many significant digits it has. The number of significant digits in the result is the lowest of the input numbers.

**Comment by LeJoW** [comment]
> `5.07±0.02`. It forces the student to actually _think_ what they're typing instead of blindly assuming

Excuse me, but I really do not understand this notation `5.07±0.02` !

**Comment by boricj** [comment]
It's the uncertainty of measurement in engineering and physics. `5.07±0.02 m` means that the physical value is between `5.05` and `5.09` meters. An example with two significant digits would be `5.0±0.05 cm` on a common ruler, which means that the thing measured is between `4.95` and `5.05` centimeters in length.

**Comment by LeJoW** [comment]
Nice ! But I think we can add the two options 😀 can't we ?

**Comment by INailedIt** [comment]
In all honesty, I don't think that there's much value in adding an automatic rounding feature, especially given that in a lot of questions you need to go at least 1.s.f higher than the given value (for the sake of proof) and that 3.s.f is considered standard. The uncertainty notation would be useful however.

**Comment by artaxxx** [comment]
We thought about this one and we decided not to include this feature. The main problem is the one that @matheod raised: you can't know what number is exact and what number is a measure and adding a system to indicate it would be counter productive (if we want to simplify the calculations in physics this is not by adding complexity in the input)
