### ISSUE TITLE
[Idea] Keyboard shortcuts

### ISSUE THREAD

**Issue by LeJoW** [numworks/epsilon#818]
Hi ! Is it possible to add some customisable keyboard shortcuts for exemple to switch between `Auto` and `Scientific` result format (ex. : `shift+0` / `shift+1`, …) ?

**Comment by varszegimarcell** [comment]
It is a good idea, but the calculators keyboard is limited to 2KRO. (2 registered key presses guaranteed.)  It works just like common rubber dome keyboards. It's not a big deal trough, and basic two/three key shortcuts are possible.  (Just make sure, the matrix can handle that. )

**Comment by artaxxx** [comment]
We don't plan to do it for now. We added some textual shortcuts (for math input) in version 20
