### ISSUE TITLE
Just a bunch of 'needed improvements'.

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#825]
So I've been using the N100 for about a month now and it's great. (far better than my friend's TI84 Plus CE and substantially more usable than my other friend's Casio FX-CG50)

That being said, there are some things that I'd like to suggest are added. So in order of priority:
- Calculating the normal of a curve as well as the tangent
- Add option to display coefficients in natural form as well as decimal
- Being able to integrate and differentiate in the regression app
- Scientific constants and unit conversions in the toolbox
- Use equals sign instead of approximate when the value is definite.
`diff(2x+1,2) ≈ 2` instead of `diff(2x+1,2) = 2`
- Conversion between different bases
- An easier way to make apps ourselves

Nice to haves (but not necessary by any means)
- Geometry app
- Finance app
- Periodic table app (eventually)

Anyway, keep up the great work!

**Comment by boricj** [comment]
I've done a couple of third-party native apps (https://github.com/topics/numworks), I am aware of a couple others by @zardam and that's about it. The lack of documentation on that subject and on how escher works makes for a very steep learning curve, the lack of stability of the internal APIs tend to make these apps bitrot every couple of months and putting these apps in the hands of nontechnical users is challenging to say the least...

The Functions app can display the numerical derivative at the currently selected abscissa, but displaying a full-length tangent will create a lot of flickering and slowdowns when moving the cursor. I'm not sure how long the tangent can be drawn without incurring these issues.

**Comment by INailedIt** [comment]
The calculate can already calculate the tangent to a line and draw it in the functions app. Which is why it's slightly annoying that the normal can't be drawn as well. Also, regarding you point surrounding the learning curve, it'd be nice if there were some kind of IDE for the calculator.

**Comment by boricj** [comment]
I didn't know the calculator could draw tangents, good to know. I've located where it happens in the source code if you want to give it a try, simply adding a new `drawCurve` call should do the trick: https://github.com/numworks/epsilon/blob/master/apps/graph/graph/graph_view.cpp#L46

I could write a fair amount of documentation regarding third-party apps and escher, but there's no good place to put them online and have it visible to the rest of the community. Ideally https://www.numworks.com/resources/engineering/software/ would be open to contributions in some way, but I can't predict what solution would suit the NumWorks team in that area.

**Comment by INailedIt** [comment]
Thanks very much for the help regarding adding a normal. Also, would it be possible for you to do a blog post and put your documentation there. It'd be a massive help for anybody new who wants to develop for epsilon.

**Comment by Ecco** [comment]
> Ideally https://www.numworks.com/resources/engineering/software/ would be open to contributions in some way, but I can't predict what solution would suit the NumWorks team in that area.

That's actually a very good suggestion. Definitely something we need to set up.

**Comment by Ecco** [comment]
Hi @INailedIt ! Thank you for the kind words and extensive feedback.

The way we use GitHub issues is by having one issue per specific topic: this allows for easier triaging. I'll try to split this issue into smaller ones when I have time.

**Comment by INailedIt** [comment]
Ah, sorry about the inconvenience. I didn't realise.

Should I just just split each point into a separate issue then?

**Comment by metawops** [comment]
> I could write a fair amount of documentation regarding third-party apps and escher, but there's no good place to put them online and have it visible to the rest of the community. Ideally https://www.numworks.com/resources/engineering/software/ would be open to contributions in some way, but I can't predict what solution would suit the NumWorks team in that area.

What about 
https://en.wikibooks.org/wiki/Unofficial_Guide_To_Expanding_Your_Numworks for a start?

Some place official would be better, of course.

**Comment by boricj** [comment]
That Wikibook is hopelessly out of date, the information it contains was relevant for epsilon 1.2.0. It requires a complete rewrite. At this point, starting from https://github.com/boricj/numworks-hello-world to add a new app for a beginner would be far less confusing than trying to use the guide, despite the fact that my Hello World sample is barely documented.

**Comment by artaxxx** [comment]
Some of these issues are fixed. I will close the main issue, feel free to separate your bullet points into different issues if you wish
