### ISSUE TITLE
Sum of sequences with a step less than 0 (sum seq on Ti calculators)

### ISSUE THREAD

**Issue by techtideapps** [numworks/epsilon#829]
I've written a python script that does this, but it would be nice to have the option to do a sum of a sequence and change the step to something less than 1. You can change the step in the sequences application so it is greater than 1, but it doesn't let you change it to less than one. So either add a function for it to the calculation app or change the sequences app so the step can be set to less than one so either way it works out. This would be especially helpful for calculus students that may need to use this to find Riemann sums.

**Comment by techtideapps** [comment]
> I've written a python script that does this, but it would be nice to have the option to do a sum of a sequence and change the step to something less than 1. You can change the step in the sequences application so it is greater than 1, but it doesn't let you change it to less than one. So either add a function for it to the calculation app or change the sequences app so the step can be set to less than one so either way it works out. This would be especially helpful for calculus students that may need to use this to find Riemann sums.

**Comment by whattheflukz** [comment]
was this solved outside of writing your own script?

**Comment by techtideapps** [comment]
Not solved as of 11.2.0 - I ended up writing a python script and it works,
although I now realize that it doesn't entirely make sense to have steps
smaller than one in a sequence, although I'm not sure where else it would
fit in.
