### ISSUE TITLE
Explain how to put the device in DFU mode when building app_flash

### ISSUE THREAD

**Issue by thertp** [numworks/epsilon#83]
While trying to flash my device from Linux, I had hard time figuring out how
to put the device in dfu mode. Maybe this should be documented somewhere ?

Of course, if it's already documented, please give me the information, then
close and forget this issue.

**Comment by Ecco** [comment]
It **is** indeed already documented on the (main website)[https://www.numworks.com/resources/engineering/software/sdk/] (which is linked from the Readme).

That being said, we definitely could make use of better instruction (in the Makefile) on the app_flash target.

**Comment by Ecco** [comment]
Fixed in #94
