### ISSUE TITLE
Choose between fractions and decimals

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#835]
Is it possible to be able to select whether the output is a decimal or a fraction. Enables higher levels of precision in pure mathematics and suitable rounding in applied.

**Comment by INailedIt** [comment]
For example, pressing shift when highlighting the answer to see it's exact form.
2.236... would be `sqrt(5)` after pressing shift.

**Comment by FrnchFrgg** [comment]
I think this is solved in current version by outputting both at the same time. This issue can probably be closed.

**Comment by Ecco** [comment]
Indeed. Thanks 😄
