### ISSUE TITLE
[Functions app] Auto resize when central point out of screen

### ISSUE THREAD

**Issue by olaure01** [numworks/epsilon#840]
If axes values are modified but f((Xmax + Xmin)/2) is not in [Ymin,Ymax], the values of Ymin and Ymax are automatically modified.
For example: f(x) = x, Xmin = 0, Xmax = 4, Ymin = -1, Ymax = 1, automatically resizes to Ymin = 0.1800001 and Ymax = 2.18
Is there a way to avoid this behavior which is not appropriate when one wants to fix precise values for axes?

**Comment by artaxxx** [comment]
This is fixed in 10.0.0
