### ISSUE TITLE
How to customize Icons

### ISSUE THREAD

**Issue by sajjaadf** [numworks/epsilon#846]
I tried to customize the icons, but while compiling it said RGBA png only, what does that mean?

**Comment by Lesquivemeau** [comment]
It means that you have to save your image with an alpha layer (transparency
layer)

Le mar. 8 janv. 2019 à 04:30, Sajjaad Farzad <notifications@github.com> a
écrit :

**Comment by sajjaadf** [comment]
I fixed it thanks!
