### ISSUE TITLE
number formats get mixed up when using ans

### ISSUE THREAD

**Issue by DSchndr** [numworks/epsilon#848]
When you calculate something which is going to end up being an floating point number (eg. 10.2/15.6) and then for example use root/sin/cos/... with ans the displayed number in the root is not the number that was calculated before. (well it is, but it is in scientific format)

![bildschirmfoto vom 2019-01-09 05-37-32](https://user-images.githubusercontent.com/19175445/50877176-fa998080-13d0-11e9-9c5f-61282dadcc43.png)

**Comment by Ecco** [comment]
Isn't that *by design*? Ans is short for answer, so it makes sense for it to be replaced by the calls the previous *answer*?

**Comment by DSchndr** [comment]
It would be less confusing if there was the answer from before (0.65... instead of 6.53...e-1) **in the root**.
Some people, who do not know how the calculator is doing its magic, might think that the calc is doing something wrong when they first see this.
