### ISSUE TITLE
Running ./epsilon.elf on Linux

### ISSUE THREAD

**Issue by Sbgodin** [numworks/epsilon#850]
Under linux, I installed the SDK, compiled and updated the device. I also could build the simulator. But the executable _epsilon.elf_ won't run

``
$ ./epsilon.elf 
bash: ./epsilon.elf : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
``

This french message says _"impossible to execute the binary file: Format error for exec()"_
The file seems to be for ARM. I run under amd64.

How can I compile for my infrastructure? Perhaps I missed something.

**Comment by boricj** [comment]
By default the build system will target the calculator, the resulting executable cannot be run on a Linux system. Change the target by setting the environment variable `PLATFORM=simulator` (don't forget to also clear out all build artifacts _before_ rebuilding too).

**Comment by Sbgodin** [comment]
Okay. My bad. How do I say in english « Je suis un boulet » ?

I used a somewhat french PLAT**E**FORM instead of the english PLATFORM…

It works now. @boricj Thanks for the time you spent.
