### ISSUE TITLE
Support literal vars in matrix

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#852]
It’s really cool that it now doesn’t always return “undef”, when using undefined vars. That could be extended to matrix as well
![6e7edbd8-1a91-4136-b7ea-1d73d5992cbd](https://user-images.githubusercontent.com/10530980/51086441-50f71e00-1747-11e9-9101-dbbee6be9ddc.jpeg)

**Comment by sajjaadf** [comment]
Are you related to Harry Potter? Is he your brother?

**Comment by LeaNumworks** [comment]
Hi, I am closing this since matrices are now handled exactly, so undef would not appear if we allowed symbolic computation
