### ISSUE TITLE
[enhancement] Deny illegal script’s name

### ISSUE THREAD

**Issue by gpotter2** [numworks/epsilon#853]
It might be worth adding an error message when trying to rename a script to an illegal name. Some students weren’t aware o that restriction
![4efb3eff-5753-4e0f-a689-4c2b46ddf8f0](https://user-images.githubusercontent.com/10530980/51086507-f611f680-1747-11e9-9653-344de1ad4fab.jpeg)
![729a17db-9fb5-428b-abe1-27044ccff0d3](https://user-images.githubusercontent.com/10530980/51086508-f611f680-1747-11e9-8c75-6d85c05d650e.jpeg)

**Comment by LeaNumworks** [comment]
Thank you! This should be fixed by #854.
