### ISSUE TITLE
Handling of negative numbers isn't normal in new update

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#861]
Presently if you type `sqrt(4^2-3^2)` the result is `sqrt(7)` as opposed to 5. I think this is because the calculator is handling this as `sqrt((4^2)-(3^2))` instead of `sqrt((4^2)+((-3)^2))`. Can there be a patch for this please, because it makes many calculations require more typing than necessary and wasn't an issue in v1.8.1. Thanks.

**Comment by adriweb** [comment]
`sqrt(4^2-3^2)` is definitely the same as `sqrt((4^2)-(3^2))` and should not be interpreted any differently. Looks like it was a bug _before_ if that was the case.
Try it on any other calc, or even google or wolfram alpha, and they will give you 2.6457... which in indeed sqrt(7).

**Comment by INailedIt** [comment]
Yep, turns out you're right. I presume this is the reason some calculators have a negative symbol separate from the minus sign then. Well then, I best get used to writing this the correct way. Thanks.

**Comment by INailedIt** [comment]
Right, so I just went to this calculation with the correct parenthesis, `sqrt((4^2)+(-3^2)) and the result was still `sqrt(7)` as opposed to 5. I'll accept that I was originally incorrect in my notation, however this seems to not just be limited to that.

**Comment by FramboisePi** [comment]
Not exactly. I think the result is correct. 
-3^2=(-3^2)=-3*3=-9
(-3)^2=(-3)*(-3)=9

**Comment by adriweb** [comment]
You could write `sqrt(4^2+(-3)^2)` I guess.

**Comment by INailedIt** [comment]
From my point of view the most practical thing would be to write `sqrt(4^2+-3^2)`. The fact that there is a plus before the minus should make it obvious that the 3 is negative.

**Comment by INailedIt** [comment]
The problem is that the calculator draws the exponent into the parenthesis as well.

**Comment by INailedIt** [comment]
Would there be a way to make the calculator recognise `x^2 + -y^2` as `x^2 + (-y)^2` or is that non standard either. I'm trying to think of a substitute for a negative symbol button.

**Comment by adriweb** [comment]
That's non-standard, yeah. Order of operations etc. Most (if not all graphing) other calcs do that too, even with a distinct negative button.

That said, regarding the shorter variant, as an example you can indeed write 2+-3 for instance, no need to write 2+(-3).

**Comment by FramboisePi** [comment]
I think it wouldn't be a good idea. 
2+-3 is interpreted as 2+(-3) but I don't think it could be something else.
-y^2 really means -(y^2) and not (-y)^2. 
It would be really confusing to have an expression you can use in exercise which means something else in the calculator. 
A polynom like -x^2+2 isn't the same as x^2+2. It would means that a student should enter -(x^2)+2 in the function app ?

In my opinion the use of an universal minus sign is an advantage of the numworks calculator. 
A symbolic computation tool like Mathematica use the same sign for the operations and the negative numbers.
