### ISSUE TITLE
Ulam / Hailstone / Collatz (3n+1) sequence

### ISSUE THREAD

**Issue by metawops** [numworks/epsilon#866]
Currently, it’s not possible to define the „hailstone numbers“ sequence where

u(n+1) = 3*u(n)+1, if u(n) is odd,
u(n+1) = u(n)/2, if u(n) is even.

Please allow for such kinds of sequences.

**Comment by boricj** [comment]
It is possible to define such a sequence, like so: `u(n+1)=(3*u_n+1)rem(u_n,2)+(u_n/2)rem(u_n+1,2)`.

However, just because we can work around epsilon's limitations through creative abuse of existing functions doesn't mean we should settle for this.

**Comment by metawops** [comment]
Hey, that's a cool hack! (You missed that +1, though, in the odd part ... 😉)

Too bad it's not possible to tell the system to stop after a loop. (This sequence always ends in the loop 4-2-1 – which is still unproven, btw.!)

**Comment by metawops** [comment]
There are no other graph styles, right? Like a bar graph or a line graph for sequences ...? 😳😞

**Comment by metawops** [comment]
> It is possible to define such a sequence, like so: `u(n+1)=(3*u_n)rem(u_n,2)+(u_n/2)rem(u_n+1,2)`.
> 
> However, just because we can work around epsilon's limitations through creative abuse of existing functions doesn't mean we should settle for this.

True, especially because this hack only works for this special kind of sequence where the two parts of the definition correspond to odd and even numbers which can be simulated via the rem(p,q) function. However, generic multi-part-definitions with arbitrary conditions won't always be possible by means of such a hack. 😉

**Comment by metawops** [comment]
Also, what's the maximum value in a given interval would be an interesting fact to know.
And how many steps were neccessary to reach a certain sequence value or loop (like 4-2-1) would be nice to know ... 😉

**Comment by AlainBusser** [comment]
You can program this sequence in Python. I did it for a slightly simpler variant : https://workshop.numworks.com/python/alain-busser/collatz
By the way Ulam did not discover this sequence, the idea came to Collatz in the 1930s while he was working on his PhD. Hasse made the sequence known to american mathematicians at Syracuse University during the 1950s.

**Comment by artaxxx** [comment]
Fixed in version 20

**Comment by metawops** [comment]
> Fixed in version 20

After a long time of thinking about this I finally decided to spend money on a 2nd Numworks calculator and today I got my N0120 model that can run firmwares >19 (other than my good old N0100 model).

@artaxxx Can you explain how we can enter "piecewise defined" sequences like the Collatz/Hailstone sequence above?
