### ISSUE TITLE
Numpy and Scipy

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#868]
Is there any chance of the Numpy and Scipy modules being added to the python app? It'd massively increase the number of uses for the python app.

**Comment by boricj** [comment]
There's no way they'll fit within the current NumWorks hardware, the calculator does not have enough Flash nor RAM to pull it off.

**Comment by INailedIt** [comment]
Shame. Out of interest would this be possible if one were to do the hardware mod and add more storage to the device?

**Comment by INailedIt** [comment]
Aww... That sucks.

**Comment by Oreig403** [comment]
There is a software called upsilon based on omega that contains scipy and numpy

**Comment by loretoparisi** [comment]
> There is a software called upsilon based on omega that contains scipy and numpy

Thanks,
specifically Upsilon added Ulab which contains SciPy and NumPy.

https://getupsilon.web.app/
