### ISSUE TITLE
Conversion between degrees and radians

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#885]
Is there any possibility of having a method of converting between degrees and radians?

**Comment by INailedIt** [comment]
Also, represent radians in terms of Pi as opposed to merely spitting out the decimal?

**Comment by artaxxx** [comment]
You can use the shell in the Python app for now

**Comment by artaxxx** [comment]
What do you mean by "represent radians in terms of Pi". The calculator already does it, right?

![screenshot - 2019-03-28T164836 632](https://user-images.githubusercontent.com/20040032/55171830-5a562b00-5179-11e9-9cee-e26a89d32cee.png)

**Comment by FraH90** [comment]
I need this functionality too.
It's quite absurd that an advanced calculator like the Numworks doesn't have ANY way of converting degree to radians and viceversa, besides from using the python app.

**Comment by Yaya-Cout** [comment]
If you want to convert degrees to radians, you can use `x÷360×pi` or `x÷pi×360` to convert radians to degrees, but a native implementation would be great.

**Comment by artaxxx** [comment]
Fixed in version 20
