### ISSUE TITLE
Parametric Graphing

### ISSUE THREAD

**Issue by IonImpulse** [numworks/epsilon#891]
One major feature that I feel is holding this calculator back is the lack of parametric graphing. I do believe that there is a python script that does this, but having the ability to do it natively (with an automatic table) would help a lot for my precalculus class. Is there any plan to add this in the future?

**Comment by Ecco** [comment]
This has been fixed in the current master :tada:

**Comment by NicoloZorzetto** [comment]
> This has been fixed in the current master 🎉

hi there, has it? I tried the online simulation, but it does not seem to work in the functions app

**Comment by Ecco** [comment]
It as. Select a function's name and press OK to change its type to parametric.
