### ISSUE TITLE
support for inf in sums and integrals

### ISSUE THREAD

**Issue by AlexPMLikesNumWorks** [numworks/epsilon#893]
Looks like epsilon currently (9.2.0) does not attempt to approximate or to look for a limit when inf is used as a bound for sum() or int(). Would be nice to handle it gracefully though, as it would provide a convenient way to express useful mathematical expressions.

**Comment by RubenNumworks** [comment]
Related to #258, #987, #1198 as for the integrals

**Comment by artaxxx** [comment]
Fixed in version 20
