### ISSUE TITLE
Increase the number of brightness levels. 

### ISSUE THREAD

**Issue by varszegimarcell** [numworks/epsilon#902]
Hi 

I have a suggestion, for brightness customization. 

When you open the settings app,  you can choose five brightness levels. In my experience, this isn't precise enough, as some settings in the middle (2/5 or 3/5) can become too bright in darker environments, as well as too dark in lamplight etc. 

This problem can be easily solved, by increasing the values of brightness levels, allowing more precise backlighting settings. 

You just have to change one constant in the apps/global_preferences.h header file. 

`23: constexpr static int NumberOfBrightnessStates = 5; // original code`

My suggestion is, to change this value to 20.

`23: constexpr static int NumberOfBrightnessStates = 20; // my recommendation `

I've tested this "mod" on my calculator, works perfectly fine. 

Thanks for your amazing work on this great piece of tech, this calculator made my math studies much easier. 

Best regards.
Marcell Varszegi

**Comment by INailedIt** [comment]
Have you tried committing your mod?

**Comment by INailedIt** [comment]
I phrased that horribly.

**Comment by varszegimarcell** [comment]
Can I commit to this project? Do I have the rights for this?

**Comment by adriweb** [comment]
You can commit to your fork of this project. From which you can make a PR, that is, a suggested change to be merged here :)

**Comment by Ecco** [comment]
Note that the hardware can only do 16 levels of brightness. Anything higher than that won't have any effect.

**Comment by varszegimarcell** [comment]
> Note that the hardware can only do 16 levels of brightness. Anything higher than that won't have any effect.

Oh I see. I missed that some of the brightness levels doesn't change anything if the constant is setted to 20.

> You can commit to your fork of this project. From which you can make a PR, that is, a suggested change to be merged here :)

Thanks, now I know how the git system works. I'm studying computer science engineering, and we learned about software development teamwork in this semester. Hopefully, I will became a good software engineer one day... :D

As this feature already added to the project, I close this issue thread.
