### ISSUE TITLE
randomize the serial number and fcc id in simulator build mode

### ISSUE THREAD

**Issue by chezsick** [numworks/epsilon#906]
hello, is possible to random the fcc id and serial number for the simulator and emscripten build mode, show always 12 zero in serial number, and "NA" in FCC ID, so why not to generate the both in "about" randomly.

Sick.

**Comment by DSchndr** [comment]
It is possible, but why would you want that feature?
I think, that it's pointless to implement it because there is no real need and reason for it.

**Comment by chezsick** [comment]
because it's to see an example and to believe that it's real.

**Comment by DSchndr** [comment]
Well the placeholders should be enough of an example to see how it looks on the real devices.
The Serial Number & FCC ID is only for real produced devices which the simulator isn't.

**Comment by Ecco** [comment]
The serial number and FCC id serve no purpose on the simulator. So we picked the easiest route: just return NA / zero. I don't think generating a fake serial number would serve any real purpose, so I'm going to close this issue for now. Feel free to re-open if you disagree 😄
