### ISSUE TITLE
[simulator] Dodgy keyboard shortcuts commit

### ISSUE THREAD

**Issue by ian-abbott** [numworks/epsilon#907]
Commit 15c87dc0b3635f3fa001e8994901eb097f02d94b ("[simulator] Comment 3 keyboard events") commented out 7 lines of code in `FltkKbd::initOtherShortcuts()`. However, 2 lines of code are needed for each shortcut, so this leaves the shortcut for `FL_ALT | ')'` set without a callback.

**Comment by Ecco** [comment]
We've moved away from FLTK, so I think it's safe to assume this doesn't apply anymore.
