### ISSUE TITLE
Python Data Persistence

### ISSUE THREAD

**Issue by Gerzer** [numworks/epsilon#908]
Is there any way to store data in Python in a way that survives reboots? I’ve tried using the `open()` top-level function to create a text file, but it always returns `None` instead of a file-like object.

**Comment by Ecco** [comment]
Hi @Gerzer ! No there is not, by design. What do you call reboots though? Do you mean a hard reset or leaving and entering the Python app again?

**Comment by boricj** [comment]
@Gerzer If you mean the Python interpreter state, it's destroyed whenever you exit the Python app. If you mean the Python scripts, they are stored in RAM and will be lost upon reset.

The NumWorks calculator doesn't have a general-purpose global datastore like the TI-83's VAT to store variables. It does have a global `poincare` context to store math things and a tiny "filesystem" to store Python scripts, but both are currently inaccessible from the Python interpreter.

**Comment by Gerzer** [comment]
> Hi @Gerzer ! No there is not, by design. What do you call reboots though? Do you mean a hard reset or leaving and entering the Python app again?

@Ecco, I was referring to the act of pressing the power button twice to turn off the screen and to turn it back on again.

You said that this functionality is absent "by design". What do you mean? Why? This is definitely a feature that I would love to have.

To both you and @boricj, thanks for such a quick response, by the way! I just purchased the calculator a few days ago, and, overall, I'm impressed.

**Comment by Ecco** [comment]
> I was referring to the act of pressing the power button twice to turn off the screen and to turn it back on again.

Oh then, it's virtually transparent! Pressing the power button simply puts the device to sleep, and it resumes execution just where it left it.

So to keep Python data between power-button presses, just put it in a script or variable. Problem solved 😄
