### ISSUE TITLE
Storing values in every app.

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#911]
This is fairly self explanatory, but it'd be useful to be able to store values in apps like sequences and functions.

**Comment by Ecco** [comment]
Hi! I'm not sure I understand your question. Would you mind elaborating a little bit? Thanks!

**Comment by INailedIt** [comment]
An example would be being able to store roots in the equation app as variables. As for the method, I'd suggest pressing store causes a window to appear through which you can store variables.

This would be useful when working between apps.

**Comment by RubenNumworks** [comment]
Related to #570

**Comment by artaxxx** [comment]
Fixed in version 20
