### ISSUE TITLE
Support exact answer in matrix

### ISSUE THREAD

**Issue by FramboisePi** [numworks/epsilon#919]
It would be really useful to support operations with exact results.

For exemple when we enter `2*[1/5;1/2]` the result is `[0,4;1]` and not `[2/5;1]`
Or the numworks can do a product of fraction like `2*1/5`

With this exemple it is not a big issue but when we need a long calculation it is not practical. Like the inverse of a big matrix.

I don’t know if it would be difficult to implement it but it would be useful for student.

An other exemple with a matrix of size 3:
![screenshot(1)](https://user-images.githubusercontent.com/25133304/54224934-d9512f80-44fa-11e9-999f-145c137615c6.png)

**Comment by boricj** [comment]
If I recall correctly, the calculator won't compute exact answer on matrices because it's both memory and CPU intensive, especially for large matrices. The layout engine also has trouble rendering large equations in a timely manner, probably because the framebuffer isn't memory-mapped.

**Comment by FramboisePi** [comment]
Thank you for your answer. 
I didn’t know, it was not possible because of hardware limitations. 

The `enhancement` label let me think the idea will not be totally abandoned and I hope there could be a solution in the future.

Would it be possible, for example, to test if the Numworks can calculate an exact result in a reasonable time by looking at the characteristics of the operation?
- Constant times *nxn* matrix is equivalent to *n* operation.
- *2x2* times *2x2* matrix need 4 operations `sum of two products`.
<img width="376" alt="Capture d’écran 2019-03-15 à 21 14 27" src="https://user-images.githubusercontent.com/25133304/54459599-64366200-4767-11e9-90d5-5cade328e1dd.png">

- *3x3* times *3x3* matrix need 9 operations `sum of three products`.


We could could says that if there is less than 5 or 10 operations the Numworks can find the exact result.

An other solution could be to let the user specify if he wants an exact result and calculate an approximate result otherwise.
I don’t know what would be the best solution to specify "We want an exact result", in Wolfram Language we can add `//N` at the end of the line in order to get an approximate result. A similar form could be a solution.

**Comment by LeaNumworks** [comment]
Hi, thanks for the issue!
We added exact computations on matrices (with these commits for instance: f017a8d03, 248521b52, a8d8e72fb), so I am closing this.
