### ISSUE TITLE
In the simulator at least, sqrt(-1) fails yet i*i = -1

### ISSUE THREAD

**Issue by ngvrnd** [numworks/epsilon#92]
If you support imaginary numbers, I would expect sqrt(-1) to evaluate to i.  You have an i key and i*i = -1, so...

**Comment by jacobly0** [comment]
This was already fixed by 55513781097729b1e0a0d17f9a24e52e521b9a81.

**Comment by Ecco** [comment]
@ngvrnd Hi, thanks for reporting that bug. It's been fixed already, we simply haven't pushed the fix on the simulator just yet.
