### ISSUE TITLE
Provide instruction on how to install arm-none-eabi-gcc on Windows

### ISSUE THREAD

**Issue by z00kus** [numworks/epsilon#922]
#### Describe the bug
Can't compile most recent version.  

#### To Reproduce
1. Follow directions and install everything needed for making a build on Windows.
2.  Type "make clean"
3. Type "make"
4. Results in the following:

Zook@DESKTOP MSYS /c/Users/Zook/OneDrive/Desktop/epsilon
$ make clean
CLEAN

Zook@DESKTOP MSYS /c/Users/Zook/OneDrive/Desktop/epsilon
$ make
I18N    apps/i18n.cpp
QSTRDAT python/port/genhdr/qstrdefs.generated.h
CXX     apps/main.o
/bin/sh: arm-none-eabi-gcc: command not found
make: *** [Makefile:107: build/device/apps/main.o] Error 127

#### Expected behavior
Updated build.

**Comment by Ecco** [comment]
Yes, you need to install the [GNU ARM Embedded toolchain](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm) on your device, and add its path to your MSYS installation.

The second part is the one that's a bit more complicated, let me know if you figured things out 😄

**Comment by RubenNumworks** [comment]
Fixed by #1084
