### ISSUE TITLE
Logs with exponents expand incorrectly

### ISSUE THREAD

**Issue by MixedMatched** [numworks/epsilon#924]
Logs with exponents outside the parenthesis expand incorrectly. For example `log base 5 ((3^5)/11)^4` should expand to `20 * log base 5 (3) - 4 * log base 5 (11)`, but actually expands to `625 log base 5 (3)^4 - 500 log base 5 (3)^3 * log base 5 (11)..` .

I'm guessing this has to do with the order of operations and how I'm typing the log, but I'm not really sure where to start. This happened on the physical version of the calculator.

**Comment by Ecco** [comment]
Would you mind specifying a version of Epsilon as well as a screenshot, as per our issue template? You can use https://www.numworks.com/simulator/ for the screenshot. Thanks!

**Comment by MixedMatched** [comment]
![screenshot](https://user-images.githubusercontent.com/30960626/54627178-460f8100-4a49-11e9-904a-1bf983190293.png)
This is a screenshot from the online simulator.

**Comment by EmilieNumworks** [comment]
Hi! When you write `log(3^5/11,5)^4`, it is equivalent to `(log(3^5/11,5))^4`. This gives `(5*log(3,5) - log(11,5))^4` when you use log rules. And then you can expand the expression with the binomial theorem which gives `log(11,5)^4 - 4*5*log(3,5)*log(11,5)^3+6*5^2*log(3,5)^2*log(11,5)^2-4*5^3*log(3,5)^3*log(11,5)+5^4*log(3,5)^4` which hopefully gives the result of the screenshot.
To get `20 * log base 5 (3) - 4 * log base 5 (11)` you should type `log((3^5/11)^4)` (see screenshot).

![screenshot](https://user-images.githubusercontent.com/31415152/54671068-639a2480-4af5-11e9-8f47-a7b1585ff932.png)
