### ISSUE TITLE
Settings lost on app exit

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#930]
#### Describe the bug
On the iOS Numworks app, the settings are only remembered while the app is opened and/or still stored in ram. This means that the user has to change their settings every time they open up the app. This issue could be solved by either having a separate app specific settings page, or by saving the contents of the simulator's/calculator's ram whenever the app is closed (applicationDidEnterBackground & applicationWillTerminate in Xcode). 

#### To Reproduce
1. Go to the Settings app
2. Change any setting
3. Swipe up to the app switcher
4. Swipe up on the Numworks app to quit it
5. Open up the Numworks app again
6. Go to the Settings app
7. See that the settings have been reset back to their defaults

#### Expected behavior
The settings are the same as before the app was quit.

#### Environment
iOS 12.2 on iPhone XR

**Comment by boricj** [comment]
It's more than just settings, all variables and scripts are lost upon exit. The apps don't persist any state.

**Comment by LudovicRousseau** [comment]
The iOS app is just a demonstrator. The product is the real hardware.
The iOS app must not be too attractive.

I guess this feature/limitation is on purpose and will not be fixed.
