### ISSUE TITLE
Compilation fails on Windows because the argument list is too long

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#932]
#### Describe the bug
Whenever I try to build epsilon in MSYS2 on Windows I get the error below.

```
LD      epsilon.elf
make: execvp: arm-none-eabi-gcc: Argument list too long
make: *** [Makefile:127: build/device/epsilon.elf] Error 127
```

I am also getting a similar error on my Mac running MacOS 10.13.

#### To Reproduce
1. Open MSYS2
2. Set path to arm-none-eabi
3. Type `make -j5` to build epsilon
4. Wait until make is almost finished
5. See error

#### Expected behavior
epsilon.elf should compile without any errors.

#### Environment
MSYS2 on Windows 10 1809

##### Edit: 
I'm getting the same error using the 2018 q4, 2018 q2, and the 2017 q4 arm-none-eabi updates.

**Comment by Ecco** [comment]
Duplicate #922

**Comment by Ecco** [comment]
Ooops, my bad, it has nothing to do with #922.

This issue comes from a Windows limitation which can't handle long command lines.

See [this comment](https://github.com/numworks/epsilon/blob/c84216d918d4d822605e6a9b24bb9bbded311014/scripts/toolchain.mingw.mak#L9) for an explanation.

This hack should be applied to other targets when building from Windows.

**Comment by 0b101** [comment]
I don't know if I did this right, but when I attempt to build epsilon using `make TOOLCHAIN=MINGW` I get this error: 
`/bin/sh: build/device/ion/src/device/usb/dfu.exe.objs: No such file or directory
make: *** [scripts/toolchain.MINGW.mak:15: build/device/ion/src/device/usb/dfu.exe] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by ThomasFrenchDeveloper** [comment]
I have the the exact same issue did anyone find a solution ?

**Comment by Ecco** [comment]
This has been fixed by the PR above.
