### ISSUE TITLE
Display more calculations on screen

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#935]
#### Problem you'd like to fix
Currently, there can be only 3 calculations display on screen.

#### Screenshots
Here is what currently happens: 
![SingleLine0](https://user-images.githubusercontent.com/29680628/54956447-f126ab80-4f1d-11e9-8fcc-7ff152da042d.PNG)

This is what the Ti-Nspire CX and HP Prime do:
![SingleLine](https://user-images.githubusercontent.com/29680628/54956492-08659900-4f1e-11e9-9846-4ec49dc31725.PNG) ![SingleLine2](https://user-images.githubusercontent.com/29680628/54956491-07346c00-4f1e-11e9-9178-d09beb9ac648.PNG)

#### Describe the solution you'd like
Calculations + answers that can fit on a single line should be displayed on a single line while longer calculations + answers should be displayed on two lines (like how all calculations + answers are currently displayed). I don't think this could be too complicated to implement.

#### Describe alternatives you've considered
There could also be a font size option (small - medium - large) #937?

**Comment by PiGuy2** [comment]
How does this look, other than the space below each calculation?
![Example](https://user-images.githubusercontent.com/20521763/55193425-50cec200-517d-11e9-81bf-45320d4c5bd3.PNG)

**Comment by 0b101** [comment]
That looks pretty good 👍

**Comment by PiGuy2** [comment]
@0b101 I made some progress, but I can't figure out what is laying out the `HistoryViewCell`s. Do you have any idea? I got the actual cells to be smaller, but I need to change their position relative to the other cells by the same amount.
![Capture](https://user-images.githubusercontent.com/20521763/55206325-6d362300-51ac-11e9-9a0c-42355d1fc240.PNG)
As you can see, the white bands are the proper height, but they are still the same distance from the other calculations.

**Comment by 0b101** [comment]
There might be something in the Escher folder. Maybe in one of the even_odd files?

**Comment by 0b101** [comment]
Left/top is after I removed the + statement from m_height, right/bottom is without the edited m_height
![moff](https://user-images.githubusercontent.com/29680628/55254910-2b968e00-5227-11e9-9c10-f094af284e76.PNG)![moffz](https://user-images.githubusercontent.com/29680628/55254911-2c2f2480-5227-11e9-91f2-b5ac892767ba.PNG)

**Comment by PiGuy2** [comment]
The code for the background size probably should be put back, but the reason there are still spaces is that the calculations can still be moved closer together. I'm going to move them at least a little closer before I submit this as a PR.

I'm going to try to make them like this, but so far this only works for exact _or_ approximate, but not both.
![Capture](https://user-images.githubusercontent.com/20521763/55269256-9c5d9a80-5267-11e9-9453-55bda57502c8.PNG)

**Comment by PiGuy2** [comment]
@0b101 I still am fixing the last couple screen tearing issues, but thanks for the help!

**Comment by 0b101** [comment]
@PiGuy2 I probably should have thought about this earlier, but it might also be a good idea to add `2 * Metric::CommonSmallMargin` and `4 * Metric::CommonSmallMargin` into their own variables and then add those onto the height instead of those directly.

**Comment by 0b101** [comment]
The screen tearing issues are now fixed.
![hh](https://user-images.githubusercontent.com/29680628/55410540-a0b8da80-5529-11e9-865e-249ef4b02618.PNG)

**Comment by PiGuy2** [comment]
This still has rendering issues. For example `11^9`:
![Capture](https://user-images.githubusercontent.com/20521763/55991379-277f5d00-5c78-11e9-9aff-9154a4a7c650.PNG)
This makes #954 not really ready to merge.

The best fix I can come up with now is to fill that space, so it looks like this:
![Capture](https://user-images.githubusercontent.com/20521763/55992368-67dfda80-5c7a-11e9-846b-ae500dfccdb2.PNG)

**Comment by 0b101** [comment]
Try changing the `- 70` in apps/calculation/calculation.cpp. It might fix the issue.

**Comment by 0b101** [comment]
@PiGuy2 I fixed the odd space, my latest pull request fixes (most of) the issues.
