### ISSUE TITLE
Incorrect division in natural mode

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#941]
#### Describe the bug
When in natural writing mode, the calculator gives the wrong answer. For example, when I type in `5/4/3/2` the calculator says that the answer is `15/8 = 1.875` when the answer should really be `5/24 = 0.2083333`. If I type in `5/4/3/2` in natural mode, then I switch to linear mode it says that it's really calculating `(5)/((4)/((3)/(2)))` instead of `((5 / 4) / 3) / 2`

#### Screenshots
Left/top is natural mode, right/bottom is linear mode
![wrong](https://user-images.githubusercontent.com/29680628/55167014-2d385700-513e-11e9-9778-3b3e08993cce.PNG)![right](https://user-images.githubusercontent.com/29680628/55167015-2e698400-513e-11e9-96f5-0b32e02374ff.PNG)

#### To Reproduce
1. Go to the Calculation app
2. Type `5/4/3/2`
3. See incorrect answer
4. Switch to linear display mode
5. Type `5/4/3/2`
6. See correct answer

#### Expected behavior
The calculator should correctly follow the order of operations in both writing modes and display `5/4/3/2 = 5/24 = 0.2083333`

#### Environment
 - Epsilon version 10.1.0
 - Simulator and device

**Comment by artaxxx** [comment]
Well I don't feel that there is a bug here. It's inherent to the use of natural writing. 

In natural writing, when you type "2/3" then "/4", it does "2/(3/4)". If you want to input "(2/3)/4" just press the right arrow key after "2/3" : 

![screenshot - 2019-03-28T160027 258](https://user-images.githubusercontent.com/20040032/55168174-a487de00-5172-11e9-888a-7c0b2b63665d.png)

or

![screenshot - 2019-03-28T160102 516](https://user-images.githubusercontent.com/20040032/55168219-b79aae00-5172-11e9-8f30-c0cc940d60f3.png)
![screenshot - 2019-03-28T160124 220](https://user-images.githubusercontent.com/20040032/55168239-c1241600-5172-11e9-986b-f77396bcaf9a.png)

The priority is represented by the length of the fraction bar. 

Do you agree?

**Comment by 0b101** [comment]
I guess I'll have to agree, but it might be confusing for some students who are expecting one answer, but get another.

**Comment by artaxxx** [comment]
Sure! I've just tried with other calculators and https://www.geogebra.org/graphing and it's the same behavior.

But the 2D natural display makes things clear, right?

**Comment by 0b101** [comment]
Yes, I believe so.

**Comment by Ecco** [comment]
Definitely not a bug. Works the same way on other platforms, and there is no ambiguity on the display. 😄

**Comment by artaxxx** [comment]
Could you please give me an example of what you're looking for?

**Comment by 0b101** [comment]
It would be nice if typing in `30/16` could result in `15/8 = 1 7/8 = 1.875`

**Comment by artaxxx** [comment]
Ok! I wasn't familiar with this writing. You should open a new issue about this
