### ISSUE TITLE
Matrix inverse crashes calculator

### ISSUE THREAD

**Issue by VictorLequin** [numworks/epsilon#943]
The calculation of the inverse of a particular matrix makes the calculator crash, and reset. The mobile android app just returns `undef` to the calculation of this inverse, while the online emulator actually crashes the page (see screenshots below). The problematic matrix is the following:
 1 0 -1  0
 0 1  1  0
 0 2  0  1
 1 0  0  1

Here is a screenshot from the online emulator, which simply froze at the lauch of the computation:
![image](https://user-images.githubusercontent.com/31135175/55185808-6bad3080-5195-11e9-8c75-e9eee1aa111a.png)
It may or may not help, but here is also a screenshot of the Firefox debugger after the crash of the emulator :
![image](https://user-images.githubusercontent.com/31135175/55185949-c34b9c00-5195-11e9-9724-50342a191c5b.png)

Reproducing the problem is very easy, just go to the calculation app and enter the matrix, with a -1 exponent. Just hit EXE or OK and the calculator will crash.

The expected inverse is:
2/3 2/3 -1/3 1/3
1/3 1/3 1/3 -1/3
-1/3 2/3 -1/3 1/3
-2/3 -2/3 1/3 2/3
A friend of mine suggested that the problem might be linked to the calculator 'hesitating' to put the exact 1/3 value inside the matrix or an approximation such as 1.333... The problem happens both in decimal and scientific modes. Computing the inverse of 1/3 times the original matrix does not cause any problem, as it logically removes all fractional expressions in the resulting inverse matrix. Strangely, it also works if you try to compute the inverse of 1/2 times the original matrix, for instance. Finally, doing the process backwards (computing the inverse of the inverse matrix) works fine (it gives the original matrix as expected).

My calculator is running on the latest version up to that day, 10.1.0 ( 48c088e ), and the problem happens on all platforms: the actual calculator, the online emulator and the android app (which, again, does not crash but outputs `undef`).

**Comment by RemyDCF** [comment]
The crash seems to occurs due to this assertion failure (according to the macOS crash report):
https://github.com/numworks/epsilon/blob/c84216d918d4d822605e6a9b24bb9bbded311014/poincare/src/tree_handle.cpp#L21

**Comment by LeaNumworks** [comment]
Hello! Thank you very much for spotting and reporting this bug!

The problem actually comes from the fact that we store the approximate result as a text, but the text of this inverse matrix is too big for the buffer where we store it. When trying to read the text and transform it into an expression, we forgot to take that into account.

This bug should be fixed by #944 (the computation result will be "undef"), and the size of the problematic buffer is going to increase in one of the next updates, so you will be able to compute this inverse.

Thanks again!
