### ISSUE TITLE
Turning off symbolic manipulation

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#949]
#### Problem you'd like to fix
In the calculators current state it isn't legal in UK A Level exams. Due to it's ability to do symbolic manipulation

#### Describe the solution you'd like
Add an option in settings to turn off symbolic manipulation entirely. When on, if an input is made in the calculation app instead of trying to interpret it the calculator just returns the input as inputted. 

#### Describe alternatives you've considered
Alternatively, put the option in the exam mode settings, so that it only applies in exam mode.

**Comment by INailedIt** [comment]
On second thought, it might be better to have a system-wide toggle and an exam mode toggle. In cases, where you're allowed symbolic algebra manipulation but you want to practice without and vice versa.

**Comment by boricj** [comment]
I don't quite see the value of a system-wide toggle, at least once we preserve Python scripts when entering exam mode. What would be required would be both the ability to select what stays enabled when entering exam mode as well as being able to see what was disabled once it is engaged. Standard mode (memory wipe/lock out accepted in France and others) and custom modes should have different LED patterns too.

Is an exam mode without symbolic features an recognized way of complying with UK regulations? There are countries out there that disregard exam modes when evaluating acceptable calculator models.

**Comment by 0b101** [comment]
First off, it's amazing to see the differences in calculator's test/exam requirements. In the US requirements are created mostly by the districts, state, and test companies (ex: College Board and ACT). We (for the most part) don't even have to enter test/exam mode on our calculators or even delete our custom programs/documents during tests (including the SAT). Secondly, I agree with boricj that the exam mode should have different options that enable/disable certain features (like symbolic manipulation, python, etc). Thirdly, if UK regulation don't allow symbolic manipulation in any form (including an exam mode/system-wide disable), the NumWorks team could probably use some sort of php country check and have the website flash a symbolic manipulation free version of epsilon to UK customers.

**Comment by INailedIt** [comment]
Regarding boricj's question: It's safer to assume no. The longer answer is that whilst most exam centres are schools and the head of examinations can be spoken to in advance, exam centres that are not school based (in some cases candidates haven't been to said centre before) can't be shown in advance and it falls down to the invigilators decision. Which in most cases, to be safe, is to offer a replacement for the exam. I say this because (based on how my school did it for GCSE) they check the calculator before going into exam mode/clearing memory. Also, from an invigilators stand point, if they get to actively toggle what's on and off then there's no way the candidate can be cheating and there's less suspicion (I can imagine an invigilator standing behind a candidate, in case they're cheating and the stress it could bring).

Regarding 0b101's suggestion of doing a php check, I think that adds more complication to the whole update procedure. Since you have to produce multiple versions of the OS. That being said, it does save on storage space.

As for UK regulations I'm going to put a link here, you're looking for section 10; aptly named 'Using calculators':
https://www.jcq.org.uk/Download/exams-office/ice---instructions-for-conducting-examinations/instructions-for-conducting-examinations-2018-2019

**Comment by INailedIt** [comment]
For reference, the way I interpreted Boricj's question is that the exam mode has symbolic manipulation without a toggle. Just to avoid confusion.

**Comment by MixedMatched** [comment]
According to the guidelines, you also can't have retrievable formulas. The equations app would have to be patched so it makes only empty equations.

**Comment by INailedIt** [comment]
Thanks for pointing that out, I didn't notice that.

**Comment by INailedIt** [comment]
Closing since symbolic manipulation has been since removed.

**Comment by jneb** [comment]
Come on guys, you just lost a whole lot of fans. There must be a better way than just blandly removing symbolic calculation.
The users should have the freedom to use the calculator the way they want.
My guess is that the best way ahead is to have multiple exam modes with different LED colors and/or patterns.

**Comment by RedGl0w** [comment]
> My guess is that the best way ahead is to have multiple exam modes with different LED colors and/or patterns.

Hmmm.... Currently, there's already multiple exam modes with different LED colors (for Dutch one especially, which has an orange color).
And you're speaking of loosing fans because of the literal calculation disabled on 11.2.0, but you haven't seen the new `diff` function, which allows to derivate for all x
