### ISSUE TITLE
polar <-> rectangular

### ISSUE THREAD

**Issue by obi1666** [numworks/epsilon#953]
Thanks for a great calculator!

In 'Calculation' it would be extremely useful to display complex number results in either polar or rectangular coordinates, thus temporarily ignoring the display setting. Something like

`rect(re^(it)) --> a+ib`

and

`pol( a+ib ) --> re^(it)`

Presently it is quite frustrating using abs, arg, re, im in a two step process to change coordinates.
![absarg](https://user-images.githubusercontent.com/49063053/55675508-0ed51700-5907-11e9-8c93-0a5183ed203d.png)
![reim](https://user-images.githubusercontent.com/49063053/55675510-15638e80-5907-11e9-826c-b92c812f5ac3.png)

It is easy to write a small function (in the Function app, accessible from Calculation) to perform the conversion, but the setting controlling representation of complex numbers overrides the output

![fn](https://user-images.githubusercontent.com/49063053/55675485-aa19bc80-5906-11e9-83bb-28334eb6b53a.png)
![calc](https://user-images.githubusercontent.com/49063053/55675486-ac7c1680-5906-11e9-87cd-ced4e3932095.png)

**Comment by boricj** [comment]
My issue with the proposed syntax is that they're not really mathematical functions, rather output formatting specifiers. I think it should look something like `re^(it)▶rect --> a+ib` and `a+ib▶polar --> re^(it)` instead.

**Comment by obi1666** [comment]
I concur.

**Comment by INailedIt** [comment]
#857

**Comment by RubenNumworks** [comment]
See https://github.com/numworks/epsilon/issues/857#issuecomment-596452400

**Comment by bmuessig** [comment]
This would be great to have!

**Comment by artaxxx** [comment]
Now handled in additional results in version 22
