### ISSUE TITLE
Statistical hypothesis Testing

### ISSUE THREAD

**Issue by streydog** [numworks/epsilon#958]
#### Problem you'd like to fix
The Numworks calculator lacks a way to do hypothesis testing, such as a z test, t test, chi^2 test, chi^2 goodness of fit test, etc. 

#### Describe the solution you'd like
The solution for this problem requires input from the community, as it would be a major addition, and quite complicated.

#### Describe alternatives you've considered
One of the solutions I have considered is expanding the statistics app to have options for hypothesis testing. However, the value/frequency tables that are in the statistics app are not useful for all tests, such as chi^2, and so would need to be changed. The problem is that some hypothesis tests require value/frequency tables, some require expected/observed table, and others do not use data at all, just statistics, which would require even more additions to the statistics app if it was decided to put there. One other possible way to add hypothesis testing would be to create an entirely new app specifically for hypothesis testing, but I do not have a concrete idea for how this app could be organized and laid out.

**Comment by Will-of-R-Learn** [comment]
+1

**Comment by Will-of-R-Learn** [comment]
Change to enhancement

**Comment by marcuhroni** [comment]
+100

**Comment by Clickative** [comment]
Really need this.

**Comment by artaxxx** [comment]
It's now in version 17
