### ISSUE TITLE
Make simulator with fr as default language

### ISSUE THREAD

**Issue by ljoets** [numworks/epsilon#963]
Hi,
Is there a way or a parameter to use to make the simulator start with fr as predefined language ?
Thanks

**Comment by Ecco** [comment]
Sure, just start it with `epsilon.exe --language fr`. See https://github.com/numworks/epsilon/blob/60cbc57a0782336ac7b0fa255ca1a166dd7894de/apps/main.cpp#L17

**Comment by ljoets** [comment]
It's not working on my fresh up-to-date elf file on Debian Stretch.
./epsilon.elf --language fr runs a english language calculator :-(
