### ISSUE TITLE
Typo on update page

### ISSUE THREAD

**Issue by INailedIt** [numworks/epsilon#965]
#### Describe the bug
The word whether is spelt like wether.

#### Screenshots
![image](https://user-images.githubusercontent.com/25847138/56852137-02911800-690f-11e9-846e-149a9c01cfce.png)

**Comment by INailedIt** [comment]
Unless you actually meant 'wether', in which case... okay??

**Comment by 0b101** [comment]
I’m guessing that you don’t need a ram or goat to update your calculator, so “whether” would be the correct spelling.

**Comment by INailedIt** [comment]
Indeed.

**Comment by EmilieNumworks** [comment]
This has been fixed, thank you!
