### ISSUE TITLE
Add addition trigonometric functions

### ISSUE THREAD

**Issue by 0b101** [numworks/epsilon#966]
#### Problem you'd like to fix
There are no cosecant (csc), secant (sec), or cotangent (cot) commands.

#### Describe the solution you'd like
Add the cosecant (csc), secant (sec), and cotangent (cot) commands to the toolbox.

**Comment by INailedIt** [comment]
The problem with these is that they're inverse functions. Inverse functions require a dedicated CAS.

**Comment by 0b101** [comment]
> Inverse functions require a dedicated CAS.

The Nspire CX (non-cas) has this feature. Isn't it just `scs(x) = 1/sin(x)`?

**Comment by XanderLeaDaren** [comment]
@0b101 is right: I think there is not much work to do, except creating a dedicated menu in the Toolbox and defining these three new functions as inverse of there counterparts. Just look at what is already feasible with the current version of Epsilon:

![ekrano-kopio 2019-06-06 à 13 11 40](https://user-images.githubusercontent.com/28948599/59028809-c8dff500-885c-11e9-9f3b-5e0575147d12.jpg)
![ekrano-kopio 2019-06-06 à 13 11 50](https://user-images.githubusercontent.com/28948599/59028814-cb424f00-885c-11e9-9bd6-bbfe5fdcb2d9.jpg)

**Comment by pjhenning** [comment]
Is anyone able to weigh in on whether a PR for this would be accepted?

**Comment by Nawor3565** [comment]
Any updates on this? I might be able to take a crack at a pull request if there are no objections. Not sure who to ask, @Ecco?
