### ISSUE TITLE
Major bug in exponential regression

### ISSUE THREAD

**Issue by Chazmath** [numworks/epsilon#969]
#### Describe the bug
Very incorrect exponential regression.  As a quick example, create:
X1={0, 1, 2, 3}
Y1= create the formula 3000 exp(.1 X1)

This produces roughly Y1={3000, 3315, 3664, 4049}

Running exponential regression on this produces:
y=a exp(b x)  with a=3000 (good) and b = -390.6436  (VERY not good)

Similar things happen with logistic regression.

#screenshots
![screenshot-1](https://user-images.githubusercontent.com/50642664/57738334-de01a380-7663-11e9-8209-2460a1993b96.png)

![screenshot-2](https://user-images.githubusercontent.com/50642664/57738481-83b51280-7664-11e9-9dc7-49ef513617e2.png)

![screenshot-3](https://user-images.githubusercontent.com/50642664/57738362-f96cae80-7663-11e9-96aa-7f609d7831a5.png)

#### Expected behavior
It should produce the exact function 3000 exp(.1 x), with b=0.1 not a value of b=-390.6

#### Environment
 - Epsilon version (Settings > About > Software version).
version 10.1.0

 - The platform(s) on which the problem happens: online simulator, actual device, etc...
on both the physical calculator and the simulator.

Thanks.

**Comment by rkfritzsch** [comment]
Bug was also mentioned here, with another, real-life example:

https://www.reddit.com/r/numworks/comments/bopbe6/exponential_regression_error/

**Comment by Ecco** [comment]
Thank you very much @Chazmath and @rkfritzsch ! You'll find an explanation of the root cause and the solution we found in the comments of #983 😄 

Thanks again!
