### ISSUE TITLE
Input parsing bug

### ISSUE THREAD

**Issue by rkfritzsch** [numworks/epsilon#970]
If one inputs 0.999999999999994 (after the decimal dot, 14 times a 9, followed by a 4), the input gets simplified to 9.9999999999999E-1, thus 1-0.999999999999994 simplifies to 1E-14. That's OK.

But if one inputs 0.999999999999995 (after the decimal dot, 14 times a 9, followed by a 5), the input gets simplified to 0.1, thus  1-0.999999999999995 simplifies to 0.9 - that's far from OK!

**Comment by Ecco** [comment]
Indeed, you're right. This has been fixed by #972 . Thanks for reporting this!
