### ISSUE TITLE
Better device designation for manual flash with dfu-util

### ISSUE THREAD

**Issue by Louson** [numworks/epsilon#974]
#### Problem you'd like to fix

The build target %_flash uses only the word "Flash". This can be dangerous if I have another device which has "Flash" in its name. Same for the interface. The target uses the interface 0, which is possibly not.

https://github.com/numworks/epsilon/blob/4dd7d1d792522645c306bac7e1a1820cf233c0cc/scripts/targets.device.mak#L41-L43

#### Describe the solution you'd like

Maybe use the `<vendorID>:<deviceID>` and eventually the serial number ?
`$ dfu-util -d 0483:a291 -S BwAjAAhRNjE4NzU3 -s 0x08000000:leave -D $<`

**Comment by Louson** [comment]
Wouldn't it be more secure to also use the DFU suffix ?

https://www.usb.org/sites/default/files/DFU_1.1.pdf at annex B. DFU File Suffix.

At flash, dfu-util says the suffix will be mandatory in future versions.

**Comment by Ecco** [comment]
We don't use `dfu-util` anymore 😄
