### ISSUE TITLE
Miscalculation in integration

### ISSUE THREAD

**Issue by matescb** [numworks/epsilon#976]
I believe bug is clear enough from screenshots. Version 10.1.0

**From simulator**
![image](https://user-images.githubusercontent.com/3594800/58014324-e0974980-7af8-11e9-9f34-209128712cfe.png)

**From wolframalpha**
![image](https://user-images.githubusercontent.com/3594800/58014438-1d634080-7af9-11e9-9bb4-21365481b371.png)

**Comment by adriweb** [comment]
`Deg` vs `Rad` ?

**Comment by matescb** [comment]
Yes
Thanks
So embarrassing

**Comment by Ecco** [comment]
That's allright, we've all been there 😄
