### ISSUE TITLE
Epsilon changelog

### ISSUE THREAD

**Issue by adriweb** [numworks/epsilon#98]
It would be very nice to have, perhaps on the NumWorks blog, a changelog on each new version release (with a link from the workshop).

And in this particular context of having an open-source software, mentioning the external contributors that participated in this version would encourage even more contributions :)

For a more technical changelog, I suppose a `git log` will be enough... Although there are some [fancy tools](https://skywinder.github.io/github-changelog-generator/) to make it look nice.

**Comment by Ecco** [comment]
> And in this particular context of having an open-source software, mentioning the external contributors that participated in this version would encourage even more contributions :)

Definitely something we've overlooked. We'll correct that.

**Comment by yeKcim** [comment]
1.1.3 is out, no changelog :-(

**Comment by adriweb** [comment]
The changelog is actually available on the workshop: http://workshop.numworks.com/ You need a device though, for now (or use a relatively private URL).

But since TI-Planet has news about it you can see it there too: https://tiplanet.org/forum/viewtopic.php?p=222446#p222446

**Comment by matm** [comment]
Any chance to get a technical ChangeLog in the repository? What about seeing all the changes between versions when browsing the "Releases" page?

**Comment by EmilieNumworks** [comment]
You can access one [here](https://www.numworks.com/calculator/update/)!

**Comment by matm** [comment]
> You can access one [here](https://www.numworks.com/calculator/update/)!

Thank you @EmilieNumworks. However this is a product ChangeLog. I was more talking about a technical one, for the developers, like [this one](https://github.com/go-gitea/gitea/blob/main/CHANGELOG.md).
