### ISSUE TITLE
Installing SDK fails

### ISSUE THREAD

**Issue by ovular** [numworks/epsilon#984]
I'm trying to install the SDK on my Mac.
Using https://www.numworks.com/resources/engineering/software/sdk/macos/
It fails at:
`brew cask reinstall gcc-arm-embedded`
with:
`Error: Cask 'gcc-arm-embedded' is unavailable: No Cask with this name exists.`

It seems, that the cask doesn't exist anymore. What can I do?

**Comment by RemyDCF** [comment]
gcc-arm-embedded was removed from Homebrew (see issue Homebrew/homebrew-cask#56802). 

However, if you still want to install gcc-arm-embedded, please use `brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask/b88346667547cc85f8f2cacb3dfe7b754c8afc8a/Casks/gcc-arm-embedded.rb`

**Comment by ovular** [comment]
Ok thanks! I thought I need it, do I?

**Comment by RemyDCF** [comment]
Well, yes, this is necessary to compile the project

**Comment by ovular** [comment]
Yes, I had to install libpng seperately. Ok I think it's working so far. But as beginner I have also some further problems... :)

Tank you!

**Comment by RemyDCF** [comment]
You're welcome! But as the documentation is not yet correct, I suggest you to let this issue open until then.

**Comment by CarloMara** [comment]
Hi there, 

to add on @RemyDCF last post, this [docs link](https://www.numworks.com/resources/engineering/software/sdk/other/) has still the wrong package listed.

Cheers,
Carlo

**Comment by daffyb** [comment]
I use this command to install on my Mac the packages :
`brew install armmbed/formulae/arm-none-eabi-gcc`

**Comment by Ecco** [comment]
We have updated [instructions](https://www.numworks.com/resources/engineering/software/build/). All you need to do now on macOS is `brew install numworks/tap/epsilon-sdk`

**Comment by joecrop** [comment]
The instructions didn't work for me today. Not sure if it is a fluke on my machine, but I needed to install arm-none-eabi-gcc separately. These are the commands I had to run:

`brew install numworks/tap/epsilon-sdk
brew install armmbed/formulae/arm-none-eabi-gcc`

**Comment by Ecco** [comment]
Thanks for the info. It's weird because our CI pipeline uses that very brew tap. Would you by any chance know what happened with our gcc formulae?

**Comment by joecrop** [comment]
gcc seemed to work (but maybe it is coming from Xcode)... Now that I think of it, in order to compile the web simulator I had to manually install many other misc. tools that were missing too.
