### ISSUE TITLE
Integration bug

### ISSUE THREAD

**Issue by Chazmath** [numworks/epsilon#987]
Seems my original comment wasn't saved.  I discovered a bug in the integration of x^(1/3).  Integrating x^(1/3) from 0 to b, where b<=17 returns a result;  b>17 returns nothing.  Why would this be?
CM

**Comment by RubenNumworks** [comment]
Thank you for reporting this issue. Here is a quick pull request that allows to compute such integrals on larger (but still limited) intervals. We will try to fix this issue more generally soon.
