### ISSUE TITLE
Exact calculation and natural calculation

### ISSUE THREAD

**Issue by Tugdualworks** [numworks/epsilon#99]
It would be nice, to be able to have the right answers for example sqrt(8)=2sqrt(2) and not a approximative answer. Moreover, being able to write number such as 5/3 and have the result by 5/3 and not 1.666 would be nice too! it is more easy!

**Comment by adriweb** [comment]
Yes, that's what an "exact math engine" is all about, without going into a full CAS engine.
Definitely something worth working on, as it's been pretty popular on other calcs that have one.

**Comment by Tugdualworks** [comment]
and it is pretty useful in Maths (in every classes!) With that, the Numworks calc would be better as Ti 82 advanced and nearly as good as the CASIO graph 35+E and maybe Ti 83 Premium CE! 

P.S : thx adriweb to be everywhere (thee, Ti-Planet) and always answer the questions!!

**Comment by coconido** [comment]
This would be very useful, can't wait for integration of fraction answers. The calculator is not very useful to me until it gives answers as a fraction.

**Comment by artaxxx** [comment]
Fixed in the last version 1.2.0
