### ISSUE TITLE
Finding all visible pre-images on a graph

### ISSUE THREAD

**Issue by XanderLeaDaren** [numworks/epsilon#991]
#### Problem you'd like to fix
After plotting a function, it’s possible to go to any _x_-value and display the image of that value. A nice addition to that would be to specify any _y_-value and display the pre-image(s) of that value.

#### Screenshots
Mock-up of a possible rendering for _f_(_x_) = cos(_x_), showing the pre-images of −0.5:
![ekrano-kopio 2019-06-03 à 16 28 53_propono](https://user-images.githubusercontent.com/28948599/58810349-0b67be80-861e-11e9-8f67-18b6bd52de45.jpg)

#### Describe the solution you'd like
After specifying the desired _y_-value, the left and right arrows allow the user to navigate between all visible pre-images on the graph (this behaviour in available e.g. on Casio calculators)

#### Describe alternatives you've considered

1. For the previous example, drawing _g_(_x_) = −0.5 and asking to Epsilon for the intersection between both curves gives all visible pre-images of −0.5.
2. Also, drawing _g_(_x_) = cos(_x_) + 0.5 and asking to Epsilon for the zeros of _g_ gives all visible pre-images of −0.5 for cos(_x_) in the desired behaviour.

The suggested proposal allows the user to have a quicker access to them without drawing another function (1st alternative) nor changing the expression (2nd alternative).

#### Additional context
This feature may be available in one of these menus:
1. Go to… and then add a new field to specify _x_ **or _y_**
![ekrano-kopio 2019-06-03 à 16 37 12](https://user-images.githubusercontent.com/28948599/58810636-9d6fc700-861e-11e9-9c3c-b30836bb0cd6.jpg)
![ekrano-kopio 2019-06-03 à 16 37 22](https://user-images.githubusercontent.com/28948599/58810661-ab254c80-861e-11e9-8bde-4ba6be6d6664.jpg)

2. Calculate… and add a new  **“pre-image” option** in the existing list of options currently including intersection, max, min, zero and so on:
![ekrano-kopio 2019-06-03 à 16 30 38](https://user-images.githubusercontent.com/28948599/58810772-e3c52600-861e-11e9-8543-2b9f38333909.jpg)
![ekrano-kopio 2019-06-03 à 16 31 00](https://user-images.githubusercontent.com/28948599/58810776-e6278000-861e-11e9-931a-898df91e1c2b.jpg)

**Comment by RubenNumworks** [comment]
Thank you for suggesting this feature, which was actually added recently: see commits
* 201900060163ea5a73194d16eb22998f1f670f25
* 439474b23b0f0bb034d65702aa603bf0056a09e3
* 938c7a1a45cafe54870e7e763a6a5498266131b6
* 682fa3f294ec248bc923bd20796c8e88344bfb03
* 04675f1a5b242a628484fc2f61b52d131b7e8617

It is available in the master branch. Feel free to use and test it and suggest any other improvements.

**Comment by XanderLeaDaren** [comment]
Thanks a lot, it’s nice to see enthusiasm and involvement in the developpement of Epsilon!
